# Generated by Django 4.2.16 on 2026-07-10 17:04
# FIXED: Changed RenameIndex to conditional RunSQL to handle missing indexes

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_rename_dashboard_user_active_idx_dashboard_u_user_id_c45649_idx_and_more'),
    ]

    operations = [
        # Conditionally rename indexes only if they exist (prevents production errors)
        migrations.RunSQL(
            sql="""
                DO $$ BEGIN
                    IF EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'dashboard_user_active_idx') THEN
                        ALTER INDEX dashboard_user_active_idx RENAME TO dashboard_u_user_id_c45649_idx;
                    END IF;
                END $$;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="""
                DO $$ BEGIN
                    IF EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'dashboard_user_expires_idx') THEN
                        ALTER INDEX dashboard_user_expires_idx RENAME TO dashboard_u_user_id_2f4ce5_idx;
                    END IF;
                END $$;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
