# Generated by Django 5.0 on 2026-08-05 07:58
# SOFT-CODED FIX: migrations 0002/0003 already renamed these indexes via
# guarded RunSQL (IF EXISTS ... RENAME). On a fresh DB, by the time this
# migration runs the indexes are already at their new names, so the plain
# RenameIndex operations below crashed with "relation ... does not exist".
# Wrapping in SeparateDatabaseAndState makes this a state-only update
# (matches Django's migration history) without re-touching the DB schema.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_rename_dashboard_user_active_idx_dashboard_u_user_id_c45649_idx_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RenameIndex(
                    model_name='userdashboardinsight',
                    new_name='dashboard_u_user_id_c45649_idx',
                    old_name='dashboard_user_active_idx',
                ),
                migrations.RenameIndex(
                    model_name='userdashboardinsight',
                    new_name='dashboard_u_user_id_2f4ce5_idx',
                    old_name='dashboard_user_expires_idx',
                ),
            ],
            database_operations=[],
        ),
    ]
