# Generated by Django 5.0 on 2026-08-05 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_rename_dashboard_user_active_idx_dashboard_u_user_id_c45649_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='userdashboardinsight',
            new_name='dashboard_u_user_id_c45649_idx',
            old_name='dashboard_user_active_idx',
        ),
        migrations.RenameIndex(
            model_name='userdashboardinsight',
            new_name='dashboard_u_user_id_2f4ce5_idx',
            old_name='dashboard_user_expires_idx',
        ),
    ]
