# Generated by Django 4.2.16 on 2026-07-15 07:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_core_enquir_created_idx_core_enquir_created_8e0bcb_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project_control', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanningPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('package_code', models.CharField(help_text='Unique package identifier (e.g., PP-001, PKG-FEED-01)', max_length=64)),
                ('name', models.CharField(help_text='Package name/title', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed description of package scope')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('completed', 'Completed'), ('on_hold', 'On Hold'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, help_text='Allocated budget for this package', max_digits=14, null=True)),
                ('currency', models.CharField(default='AED', max_length=8)),
                ('actual_cost', models.DecimalField(decimal_places=2, default=0, help_text='Actual cost spent to date', max_digits=14)),
                ('planned_start', models.DateField(blank=True, help_text='Planned start date', null=True)),
                ('planned_end', models.DateField(blank=True, help_text='Planned completion date', null=True)),
                ('actual_start', models.DateField(blank=True, help_text='Actual start date', null=True)),
                ('actual_end', models.DateField(blank=True, help_text='Actual completion date', null=True)),
                ('progress_percentage', models.DecimalField(decimal_places=2, default=0, help_text='Completion percentage (0-100)', max_digits=5)),
                ('deliverables', models.TextField(blank=True, help_text='Key deliverables (one per line or JSON)')),
                ('notes', models.TextField(blank=True, help_text='Additional notes, risks, assumptions')),
                ('package_manager', models.ForeignKey(blank=True, help_text='User responsible for this package', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_planning_packages', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(help_text='Parent project this package belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='planning_packages', to='core.project')),
                ('wbs_node', models.ForeignKey(blank=True, help_text='Optional link to WBS structure', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planning_packages', to='project_control.wbsnode')),
            ],
            options={
                'ordering': ['project', 'package_code'],
                'indexes': [models.Index(fields=['project', 'status'], name='project_con_project_f46036_idx'), models.Index(fields=['project', 'priority'], name='project_con_project_14aaf9_idx'), models.Index(fields=['project', '-created_at'], name='project_con_project_68c216_idx'), models.Index(fields=['package_manager'], name='project_con_package_2a8aaa_idx')],
                'unique_together': {('project', 'package_code')},
            },
        ),
    ]
