import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('procurement', '0036_projectrelationshipresolution'),
        ('project_control', '0002_planningpackage'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, max_length=64)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency', models.CharField(default='AED', max_length=8)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('closed', 'Closed')], db_index=True, default='draft', max_length=12)),
                ('notes', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_control_budgets_approved', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='control_budget_allocations', to='core.project')),
                ('source_budget', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='control_allocations', to='procurement.budget')),
                ('wbs_node', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budget_allocations', to='project_control.wbsnode')),
            ],
            options={'ordering': ['project', 'wbs_node__sort_order', 'code']},
        ),
        migrations.CreateModel(
            name='CostAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('source_type', models.CharField(choices=[('purchase_requisition', 'Purchase Requisition'), ('purchase_order', 'Purchase Order'), ('invoice_allocation', 'Verified Invoice Allocation'), ('manual', 'Manual')], db_index=True, max_length=30)),
                ('source_id', models.CharField(db_index=True, max_length=64)),
                ('source_reference', models.CharField(blank=True, max_length=120)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency', models.CharField(default='AED', max_length=8)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('closed', 'Closed')], db_index=True, default='draft', max_length=12)),
                ('notes', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('allocated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_cost_allocations_created', to=settings.AUTH_USER_MODEL)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_cost_allocations_approved', to=settings.AUTH_USER_MODEL)),
                ('budget_allocation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_allocations', to='project_control.budgetallocation')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_allocations', to='core.project')),
                ('wbs_node', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cost_allocations', to='project_control.wbsnode')),
            ],
            options={'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='CostLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('entry_key', models.CharField(max_length=255, unique=True)),
                ('entry_type', models.CharField(choices=[('budget', 'Budget'), ('commitment', 'Commitment'), ('actual', 'Actual Cost'), ('adjustment', 'Adjustment')], db_index=True, max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency', models.CharField(default='AED', max_length=8)),
                ('source_type', models.CharField(blank=True, db_index=True, max_length=30)),
                ('source_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('source_reference', models.CharField(blank=True, max_length=120)),
                ('entry_date', models.DateField()),
                ('status', models.CharField(choices=[('posted', 'Posted'), ('reversed', 'Reversed')], db_index=True, default='posted', max_length=12)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('budget_allocation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='project_control.budgetallocation')),
                ('cost_allocation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='project_control.costallocation')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_cost_ledger_entries_created', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_ledger_entries', to='core.project')),
                ('wbs_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='project_control.wbsnode')),
            ],
            options={'ordering': ['-entry_date', '-created_at']},
        ),
        migrations.AddConstraint(model_name='budgetallocation', constraint=models.UniqueConstraint(fields=('project', 'code'), name='pc_budget_project_code_uniq')),
        migrations.AddConstraint(model_name='budgetallocation', constraint=models.CheckConstraint(check=models.Q(amount__gt=0), name='pc_budget_amount_positive')),
        migrations.AddIndex(model_name='budgetallocation', index=models.Index(fields=['project', 'status'], name='pc_budget_proj_status_idx')),
        migrations.AddConstraint(model_name='costallocation', constraint=models.UniqueConstraint(condition=models.Q(is_deleted=False), fields=('source_type', 'source_id', 'project', 'wbs_node'), name='pc_cost_source_wbs_uniq')),
        migrations.AddConstraint(model_name='costallocation', constraint=models.CheckConstraint(check=models.Q(amount__gt=0), name='pc_cost_amount_positive')),
        migrations.AddIndex(model_name='costallocation', index=models.Index(fields=['project', 'status'], name='pc_cost_proj_status_idx')),
        migrations.AddIndex(model_name='costallocation', index=models.Index(fields=['source_type', 'source_id', 'status'], name='pc_cost_source_status_idx')),
        migrations.AddConstraint(model_name='costledgerentry', constraint=models.CheckConstraint(check=models.Q(amount__gte=0), name='pc_ledger_amount_nonnegative')),
        migrations.AddIndex(model_name='costledgerentry', index=models.Index(fields=['project', 'entry_type', 'status'], name='pc_ledger_proj_type_idx')),
        migrations.AddIndex(model_name='costledgerentry', index=models.Index(fields=['project', 'wbs_node', 'status'], name='pc_ledger_proj_wbs_idx')),
    ]
