# Generated by Django 5.0 on 2026-09-08 09:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_enquiryattachment'),
        ('project_control', '0005_control_accounts_reporting_periods'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovedHourEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('employee_code', models.CharField(max_length=64)),
                ('employee_name', models.CharField(blank=True, max_length=255)),
                ('work_date', models.DateField()),
                ('hours', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hourly_cost_rate', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('labor_actual_cost', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('currency', models.CharField(default='AED', max_length=8)),
                ('source_type', models.CharField(default='manual', max_length=24)),
                ('source_reference', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted for approval'), ('approved', 'Approved'), ('reversed', 'Reversed')], db_index=True, default='draft', max_length=12)),
                ('notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('reversed_at', models.DateTimeField(blank=True, null=True)),
                ('reversal_reason', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-work_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IntegratedReportingSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField()),
                ('data_date', models.DateField()),
                ('currency', models.CharField(default='AED', max_length=8)),
                ('budget_at_completion', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('planned_value', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('earned_value', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('actual_cost', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('commitments', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('approved_hours', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('labor_actual_cost', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('finance_actual_cost', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('progress_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('planned_progress_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('cost_variance', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('schedule_variance', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('cpi', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('spi', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('estimate_at_completion', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('estimate_to_complete', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('variance_at_completion', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('source_manifest', models.JSONField(blank=True, default=dict)),
                ('calculation_payload', models.JSONField(blank=True, default=dict)),
                ('checksum', models.CharField(max_length=64)),
                ('sealed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-data_date', '-version'],
            },
        ),
        migrations.CreateModel(
            name='ReconciliationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('run_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('exceptions', 'Exceptions')], max_length=16)),
                ('approved_hours', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('labor_actual_cost', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('finance_actual_cost', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('ledger_actual_cost', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('exception_count', models.PositiveIntegerField(default=0)),
                ('exceptions', models.JSONField(blank=True, default=list)),
                ('source_manifest', models.JSONField(blank=True, default=dict)),
                ('checksum', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='costledgerentry',
            name='control_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='project_control.controlaccount'),
        ),
        migrations.AddField(
            model_name='costledgerentry',
            name='reporting_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='project_control.reportingperiod'),
        ),
        migrations.AddIndex(
            model_name='costledgerentry',
            index=models.Index(fields=['reporting_period', 'entry_type', 'status'], name='pc_ledger_period_type_idx'),
        ),
        migrations.AddField(
            model_name='approvedhourentry',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_hours_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='approvedhourentry',
            name='control_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approved_hour_entries', to='project_control.controlaccount'),
        ),
        migrations.AddField(
            model_name='approvedhourentry',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_hours_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='approvedhourentry',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approved_hour_entries', to='core.project'),
        ),
        migrations.AddField(
            model_name='approvedhourentry',
            name='reporting_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approved_hour_entries', to='project_control.reportingperiod'),
        ),
        migrations.AddField(
            model_name='approvedhourentry',
            name='reversed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_hours_reversed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='approvedhourentry',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_hours_submitted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='integratedreportingsnapshot',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='integrated_reporting_snapshots', to='core.project'),
        ),
        migrations.AddField(
            model_name='integratedreportingsnapshot',
            name='reporting_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='integrated_snapshots', to='project_control.reportingperiod'),
        ),
        migrations.AddField(
            model_name='integratedreportingsnapshot',
            name='sealed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_snapshots_sealed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reconciliationrun',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_reconciliations_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reconciliationrun',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliation_runs', to='core.project'),
        ),
        migrations.AddField(
            model_name='reconciliationrun',
            name='reporting_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliation_runs', to='project_control.reportingperiod'),
        ),
        migrations.AddField(
            model_name='integratedreportingsnapshot',
            name='reconciliation_run',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='snapshot', to='project_control.reconciliationrun'),
        ),
        migrations.AddIndex(
            model_name='approvedhourentry',
            index=models.Index(fields=['project', 'status'], name='pc_hour_project_status_idx'),
        ),
        migrations.AddIndex(
            model_name='approvedhourentry',
            index=models.Index(fields=['reporting_period', 'status'], name='pc_hour_period_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='approvedhourentry',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('project', 'source_type', 'source_reference'), name='pc_hour_source_uniq'),
        ),
        migrations.AddConstraint(
            model_name='approvedhourentry',
            constraint=models.CheckConstraint(check=models.Q(('hours__gt', 0)), name='pc_hour_hours_positive'),
        ),
        migrations.AddConstraint(
            model_name='approvedhourentry',
            constraint=models.CheckConstraint(check=models.Q(('hourly_cost_rate__gte', 0)), name='pc_hour_rate_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='reconciliationrun',
            constraint=models.UniqueConstraint(fields=('reporting_period', 'run_number'), name='pc_recon_period_run_uniq'),
        ),
        migrations.AddConstraint(
            model_name='integratedreportingsnapshot',
            constraint=models.UniqueConstraint(fields=('reporting_period', 'version'), name='pc_snapshot_period_version_uniq'),
        ),
    ]
