# Generated by Django 5.0 on 2026-09-15 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def ensure_procurement_reference_keys(apps, schema_editor):
    ensure_reference_keys(apps, schema_editor, (
        ('procurement', 'PurchaseRequisition'),
        ('procurement', 'PurchaseOrder'),
    ))


def ensure_reference_keys(apps, schema_editor, model_labels):
    """Restore PostgreSQL FK target keys without changing business identities.

    Restored databases can record migrations as applied while their ID indexes
    are absent. Repair before the calling migration's deferred foreign keys;
    adding a new predecessor would invalidate already-applied EPC histories.
    """
    connection = schema_editor.connection
    if connection.vendor != 'postgresql':
        return
    quote = schema_editor.quote_name
    with connection.cursor() as cursor:
        for app_label, name in model_labels:
            model = apps.get_model(app_label, name)
            table, column = model._meta.db_table, model._meta.pk.column
            # Retain this lock until the atomic migration finishes, so writes
            # cannot invalidate validation before the new key/FKs are created.
            cursor.execute(f'LOCK TABLE {quote(table)} IN ACCESS EXCLUSIVE MODE')
            cursor.execute('''
                SELECT EXISTS (
                    SELECT 1 FROM pg_index i
                    JOIN pg_attribute a ON a.attrelid = i.indrelid
                    WHERE i.indrelid = to_regclass(%s) AND a.attname = %s
                      AND i.indisunique AND i.indisvalid AND i.indisready
                      AND i.indimmediate AND i.indpred IS NULL
                      AND i.indexprs IS NULL AND i.indnkeyatts = 1
                      AND i.indkey[0] = a.attnum
                )
            ''', [table, column])
            if cursor.fetchone()[0]:
                continue
            cursor.execute(f'SELECT EXISTS (SELECT 1 FROM {quote(table)} WHERE {quote(column)} IS NULL)')
            if cursor.fetchone()[0]:
                raise RuntimeError(
                    f'Cannot repair {table}.{column}: null IDs exist. '
                    'Reconcile the source identities before retrying migrations; '
                    'no source rows or IDs were changed.'
                )
            cursor.execute(f'''SELECT EXISTS (
                SELECT 1 FROM {quote(table)} GROUP BY {quote(column)} HAVING COUNT(*) > 1
            )''')
            if cursor.fetchone()[0]:
                raise RuntimeError(
                    f'Cannot repair {table}.{column}: duplicate IDs exist. '
                    'Reconcile the source identities before retrying migrations; '
                    'no source rows or IDs were changed.'
                )
            cursor.execute(
                "SELECT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid = to_regclass(%s) AND contype = 'p')",
                [table],
            )
            kind = 'UNIQUE' if cursor.fetchone()[0] else 'PRIMARY KEY'
            schema_editor.execute(f'ALTER TABLE {quote(table)} ADD {kind} ({quote(column)})')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_enquiryattachment'),
        ('planning_intelligence', '0028_schedule_control_observation_revisions'),
        ('procurement', '0041_procurementreportingsnapshot_and_more'),
        ('project_control', '0006_approvedhourentry_integratedreportingsnapshot_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(ensure_procurement_reference_keys, migrations.RunPython.noop),
        migrations.CreateModel(
            name='IntegratedBaseline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('data_date', models.DateField()),
                ('currency', models.CharField(max_length=8)),
                ('budget_total', models.DecimalField(decimal_places=2, max_digits=20)),
                ('manifest', models.JSONField(default=dict)),
                ('checksum', models.CharField(max_length=64)),
                ('approved_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='integrated_baselines', to='core.project')),
                ('schedule_baseline', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='integrated_baselines', to='planning_intelligence.schedulebaseline')),
            ],
            options={
                'ordering': ['-revision', '-id'],
            },
        ),
        migrations.CreateModel(
            name='RequisitionWBSLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.CharField(max_length=500)),
                ('linked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epc_requisition_links', to='core.project')),
                ('requisition', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='enterprise_wbs_link', to='procurement.purchaserequisition')),
                ('wbs_node', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requisition_links', to='project_control.wbsnode')),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='WBSActivityLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('link_type', models.CharField(choices=[('engineering', 'Engineering'), ('procurement', 'Procurement'), ('construction', 'Construction'), ('commissioning', 'Commissioning')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('activity', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='enterprise_wbs_link', to='planning_intelligence.scheduleactivity')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epc_activity_links', to='core.project')),
                ('wbs_node', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activity_links', to='project_control.wbsnode')),
            ],
            options={
                'ordering': ['wbs_node__sort_order', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='integratedbaseline',
            constraint=models.UniqueConstraint(fields=('project', 'revision'), name='pc_epc_baseline_revision_uniq'),
        ),
        migrations.AddConstraint(
            model_name='integratedbaseline',
            constraint=models.CheckConstraint(check=models.Q(('revision__gte', 1)), name='pc_epc_revision_positive'),
        ),
        migrations.AddConstraint(
            model_name='integratedbaseline',
            constraint=models.CheckConstraint(check=models.Q(('budget_total__gt', 0)), name='pc_epc_baseline_budget_positive'),
        ),
    ]
