# Generated by Django 5.0 on 2026-09-15 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_enquiryattachment'),
        ('planning_intelligence', '0028_schedule_control_observation_revisions'),
        ('procurement', '0041_procurementreportingsnapshot_and_more'),
        ('project_control', '0006_approvedhourentry_integratedreportingsnapshot_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegratedBaseline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('data_date', models.DateField()),
                ('currency', models.CharField(max_length=8)),
                ('budget_total', models.DecimalField(decimal_places=2, max_digits=20)),
                ('manifest', models.JSONField(default=dict)),
                ('checksum', models.CharField(max_length=64)),
                ('approved_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='integrated_baselines', to='core.project')),
                ('schedule_baseline', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='integrated_baselines', to='planning_intelligence.schedulebaseline')),
            ],
            options={
                'ordering': ['-revision', '-id'],
            },
        ),
        migrations.CreateModel(
            name='RequisitionWBSLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.CharField(max_length=500)),
                ('linked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epc_requisition_links', to='core.project')),
                ('requisition', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='enterprise_wbs_link', to='procurement.purchaserequisition')),
                ('wbs_node', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requisition_links', to='project_control.wbsnode')),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='WBSActivityLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('link_type', models.CharField(choices=[('engineering', 'Engineering'), ('procurement', 'Procurement'), ('construction', 'Construction'), ('commissioning', 'Commissioning')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('activity', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='enterprise_wbs_link', to='planning_intelligence.scheduleactivity')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epc_activity_links', to='core.project')),
                ('wbs_node', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activity_links', to='project_control.wbsnode')),
            ],
            options={
                'ordering': ['wbs_node__sort_order', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='integratedbaseline',
            constraint=models.UniqueConstraint(fields=('project', 'revision'), name='pc_epc_baseline_revision_uniq'),
        ),
        migrations.AddConstraint(
            model_name='integratedbaseline',
            constraint=models.CheckConstraint(check=models.Q(('revision__gte', 1)), name='pc_epc_revision_positive'),
        ),
        migrations.AddConstraint(
            model_name='integratedbaseline',
            constraint=models.CheckConstraint(check=models.Q(('budget_total__gt', 0)), name='pc_epc_baseline_budget_positive'),
        ),
    ]
