# Generated by Django 5.0 on 2026-09-15 10:17

import django.db.models.deletion
from importlib import import_module
from django.conf import settings
from django.db import migrations, models


def ensure_execution_reference_keys(apps, schema_editor):
    """Repair existing targets before execution's deferred foreign keys run.

    A procurement-only preflight still fails on restored milestone, planning,
    or project-control tables. Use historical models and cover every existing
    target of this migration, including the documents through table's target.
    Keep requisitions for installations that applied 0007 before its preflight.
    """
    import_module('apps.project_control.migrations.0007_epc_foundation').ensure_reference_keys(
        apps, schema_editor, (
            ('procurement', 'PurchaseRequisition'),
            ('procurement', 'PurchaseOrder'),
            tuple(settings.AUTH_USER_MODEL.split('.')),
            ('core', 'Project'),
            ('core', 'ProjectMilestone'),
            ('planning_intelligence', 'ScheduleActivity'),
            ('planning_intelligence', 'ScheduleControlSnapshot'),
            ('planning_intelligence', 'ActivityProgressUpdate'),
            ('project_control', 'IntegratedBaseline'),
            ('project_control', 'ProjectDocument'),
            ('project_control', 'WBSNode'),
        ),
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_enquiryattachment'),
        ('planning_intelligence', '0028_schedule_control_observation_revisions'),
        ('procurement', '0041_procurementreportingsnapshot_and_more'),
        ('project_control', '0007_epc_foundation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(
            ensure_execution_reference_keys,
            migrations.RunPython.noop,
        ),
        migrations.CreateModel(
            name='EPCWorkItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('phase', models.CharField(choices=[('engineering', 'Engineering'), ('procurement', 'Procurement'), ('construction', 'Construction'), ('commissioning', 'Commissioning')], max_length=20)),
                ('requires_materials', models.BooleanField(default=False)),
                ('acceptance_criteria', models.JSONField(default=list)),
                ('evidence_note', models.TextField(blank=True)),
                ('data_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('reviewed', 'Reviewed'), ('accepted', 'Accepted')], default='draft', max_length=12)),
                ('submitted_at', models.DateTimeField(null=True)),
                ('reviewed_at', models.DateTimeField(null=True)),
                ('review_note', models.TextField(blank=True)),
                ('review_manifest', models.JSONField(default=dict)),
                ('accepted_at', models.DateTimeField(null=True)),
                ('acceptance_manifest', models.JSONField(default=dict)),
                ('accepted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='epc_work_accepted', to=settings.AUTH_USER_MODEL)),
                ('activity', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='epc_work_item', to='planning_intelligence.scheduleactivity')),
                ('baseline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='project_control.integratedbaseline')),
                ('control_snapshot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='planning_intelligence.schedulecontrolsnapshot')),
                ('documents', models.ManyToManyField(blank=True, related_name='epc_work_items', to='project_control.projectdocument')),
                ('milestone', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='epc_work_item', to='core.projectmilestone')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='epc_work_owned', to=settings.AUTH_USER_MODEL)),
                ('predecessors', models.ManyToManyField(blank=True, related_name='successors', to='project_control.epcworkitem')),
                ('progress_update', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='planning_intelligence.activityprogressupdate')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='epc_work_items', to='core.project')),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='procurement.purchaseorder')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='epc_work_reviews', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='epc_work_submitted', to=settings.AUTH_USER_MODEL)),
                ('wbs_node', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='project_control.wbsnode')),
            ],
            options={
                'ordering': ['code', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EPCWorkEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=20)),
                ('note', models.TextField(blank=True)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('work_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='project_control.epcworkitem')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='epcworkitem',
            constraint=models.UniqueConstraint(fields=('project', 'code'), name='pc_epc_work_code_uniq'),
        ),
    ]
