# Generated by Django 5.0 on 2026-07-23 04:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_engine', '0013_add_total_worked_days'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayslipLineItemChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted')], db_index=True, max_length=16)),
                ('old_values', models.JSONField(blank=True, default=dict, help_text='State before change (for updates/deletes)')),
                ('new_values', models.JSONField(blank=True, default=dict, help_text='State after change (for creates/updates)')),
                ('at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('note', models.TextField(blank=True, default='')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_line_item_changes', to=settings.AUTH_USER_MODEL)),
                ('line_item', models.ForeignKey(blank=True, help_text='NULL when line item is deleted.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_logs', to='payroll_engine.paysliplineitem')),
                ('payslip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_item_changes', to='payroll_engine.payslip')),
            ],
            options={
                'verbose_name': 'Payslip Line Item Change Log',
                'verbose_name_plural': 'Payslip Line Item Change Logs',
                'db_table': 'payroll_engine_line_item_change_log',
                'ordering': ('-at',),
                'indexes': [models.Index(fields=['payslip', '-at'], name='payroll_eng_payslip_1a20fa_idx'), models.Index(fields=['actor', '-at'], name='payroll_eng_actor_i_79fca3_idx'), models.Index(fields=['action', '-at'], name='payroll_eng_action_8b0ba0_idx')],
            },
        ),
    ]
