# Generated by Django 5.0 on 2026-09-03 08:43

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_engine', '0015_link_payroll_employees_to_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunSQL(
            sql='''
DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.tables
        WHERE table_schema = 'public'
          AND table_name = 'payroll_engine_run'
    )
    AND EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'payroll_engine_run'
          AND column_name = 'id'
    )
    AND NOT EXISTS (
        -- A foreign key can only target a primary key or an unconditional
        -- unique index.  Some legacy databases have a primary key on this
        -- table, but not on ``id``, so checking for any primary key is not
        -- sufficient.
        SELECT 1
        FROM pg_index i
        JOIN pg_class t ON t.oid = i.indrelid
        JOIN pg_namespace n ON n.oid = t.relnamespace
        JOIN pg_attribute a ON a.attrelid = t.oid
        WHERE n.nspname = 'public'
          AND t.relname = 'payroll_engine_run'
          AND a.attname = 'id'
          AND i.indisunique
          AND i.indpred IS NULL
          AND i.indexprs IS NULL
          AND i.indnkeyatts = 1
          AND a.attnum = ANY(i.indkey)
    ) THEN
        IF EXISTS (
            SELECT 1
            FROM pg_constraint c
            JOIN pg_class t ON c.conrelid = t.oid
            JOIN pg_namespace n ON t.relnamespace = n.oid
            WHERE n.nspname = 'public'
              AND t.relname = 'payroll_engine_run'
              AND c.contype = 'p'
        ) THEN
            ALTER TABLE public.payroll_engine_run
                ADD CONSTRAINT uq_payroll_engine_run_id UNIQUE (id);
        ELSE
            ALTER TABLE public.payroll_engine_run
                ADD CONSTRAINT payroll_engine_run_pkey PRIMARY KEY (id);
        END IF;
    END IF;
END $$;
''',
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.CreateModel(
            name='PayrollAccountingExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_system', models.CharField(choices=[('generic', 'Generic CSV'), ('dynamics', 'Microsoft Dynamics'), ('sap', 'SAP'), ('oracle', 'Oracle')], default='generic', max_length=16)),
                ('reference', models.CharField(db_index=True, max_length=50, unique=True)),
                ('status', models.CharField(choices=[('generated', 'Generated'), ('exported', 'Exported'), ('posted', 'Posted'), ('failed', 'Failed')], default='generated', max_length=16)),
                ('journal_date', models.DateField(default=django.utils.timezone.localdate)),
                ('entries', models.JSONField(default=list)),
                ('total_debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('total_credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('external_reference', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounting_exports', to='payroll_engine.payrollrun')),
            ],
            options={
                'db_table': 'payroll_engine_accounting_export',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PayrollComplianceCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('passed', 'Passed'), ('warning', 'Passed with Warnings'), ('failed', 'Failed')], db_index=True, max_length=16)),
                ('jurisdiction', models.CharField(default='AE', max_length=8)),
                ('ruleset_version', models.CharField(default='AE-2026.1', max_length=32)),
                ('findings', models.JSONField(default=list)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('warning_count', models.PositiveIntegerField(default=0)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('checked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_checks', to='payroll_engine.payrollrun')),
            ],
            options={
                'db_table': 'payroll_engine_compliance_check',
                'ordering': ['-checked_at'],
            },
        ),
        migrations.CreateModel(
            name='PayrollPaymentBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_type', models.CharField(choices=[('wps', 'UAE WPS SIF'), ('bank', 'Bank Transfer')], max_length=12)),
                ('reference', models.CharField(db_index=True, max_length=50, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('validated', 'Validated'), ('exported', 'Exported'), ('submitted', 'Submitted'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], db_index=True, default='draft', max_length=16)),
                ('record_count', models.PositiveIntegerField(default=0)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('currency', models.CharField(default='AED', max_length=3)),
                ('records', models.JSONField(default=list)),
                ('validation_errors', models.JSONField(default=list)),
                ('file_hash', models.CharField(blank=True, max_length=64)),
                ('bank_response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_batches', to='payroll_engine.payrollrun')),
            ],
            options={
                'db_table': 'payroll_engine_payment_batch',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='payrollpaymentbatch',
            constraint=models.UniqueConstraint(fields=('run', 'batch_type'), name='uq_payroll_payment_run_type'),
        ),
    ]
