# Generated by Django 5.0 on 2026-09-04 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_core', '0007_alter_employeemaster_email_alter_employeemaster_user'),
        ('payroll_engine', '0016_payrollaccountingexport_payrollcompliancecheck_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollemployee',
            name='employee',
            field=models.OneToOneField(blank=True, help_text='Canonical employee identity for this payroll-domain extension.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payroll_record', to='hr_core.employeemaster'),
        ),
    ]
