# Generated by Django 5.0 on 2026-09-09 05:47

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


def repair_missing_initial_sales_tables(apps, schema_editor):
    """Repair environments where sales.0001 was recorded but its tables were absent."""
    connection = schema_editor.connection
    model_names = ['Client', 'Contact', 'Deal', 'Quote', 'SalesActivity', 'SalesForecast']
    for model_name in model_names:
        model = apps.get_model('sales', model_name)
        existing = set(connection.introspection.table_names())
        if model._meta.db_table not in existing:
            schema_editor.create_model(model)
            continue
        for field in model._meta.local_many_to_many:
            through = field.remote_field.through
            if through._meta.auto_created and through._meta.db_table not in existing:
                schema_editor.create_model(through)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_enquiryattachment'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(repair_missing_initial_sales_tables, migrations.RunPython.noop),
        migrations.AddField(
            model_name='deal',
            name='award_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='award_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_awards_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deal',
            name='award_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='award_reference',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='deal',
            name='award_rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='award_status',
            field=models.CharField(choices=[('not_submitted', 'Not Submitted'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='not_submitted', max_length=20),
        ),
        migrations.AddField(
            model_name='deal',
            name='award_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='award_submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_awards_submitted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deal',
            name='award_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='bid_decided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='bid_decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_bid_decisions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deal',
            name='bid_decision',
            field=models.CharField(choices=[('pending', 'Pending'), ('bid', 'Bid'), ('conditional_bid', 'Conditional Bid'), ('no_bid', 'No Bid')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='deal',
            name='bid_decision_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='client_reference',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='deal',
            name='converted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='converted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_opportunities_converted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deal',
            name='converted_project',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='source_sales_opportunity', to='core.project'),
        ),
        migrations.AddField(
            model_name='deal',
            name='expected_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='handover_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='deal',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='deal',
            name='nominated_project_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_projects_nominated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deal',
            name='scope_type',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='deal',
            name='stage_entered_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='deal',
            name='submission_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='stage',
            field=models.CharField(choices=[('lead', 'Lead'), ('qualified', 'Qualified Lead'), ('proposal', 'Proposal & Estimate'), ('negotiation', 'Negotiation'), ('award_pending', 'Award Approval'), ('awarded', 'Awarded'), ('converted', 'Converted to Project'), ('no_bid', 'No Bid'), ('lost', 'Lost'), ('cancelled', 'Cancelled')], default='lead', max_length=20),
        ),
        migrations.CreateModel(
            name='OpportunityAuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(db_index=True, max_length=40)),
                ('from_stage', models.CharField(blank=True, max_length=20)),
                ('to_stage', models.CharField(blank=True, max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_opportunity_audit_events', to=settings.AUTH_USER_MODEL)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to='sales.deal')),
            ],
            options={
                'db_table': 'sales_opportunity_audit_events',
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['opportunity', '-occurred_at'], name='sales_oppor_opportu_78997b_idx')],
            },
        ),
    ]
