# Generated by Django 5.0 on 2026-09-09 06:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_enquiryattachment'),
        ('sales', '0002_deal_award_approved_at_deal_award_approved_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='commercial_risks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='client',
            name='legal_name',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='client',
            name='market_sectors',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='client',
            name='new_proposals_permitted',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='client',
            name='operating_locations',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='client',
            name='parent_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subsidiaries', to='sales.client'),
        ),
        migrations.AddField(
            model_name='client',
            name='procurement_portals',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='client',
            name='trading_name',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='client',
            name='verification_status',
            field=models.CharField(choices=[('unverified', 'Unverified'), ('verified', 'Verified'), ('review_due', 'Review Due'), ('restricted', 'Restricted')], default='unverified', max_length=20),
        ),
        migrations.AddField(
            model_name='client',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_clients_verified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deal',
            name='client_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunities', to='sales.contact'),
        ),
        migrations.AddField(
            model_name='deal',
            name='delivery_office',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='deal',
            name='disciplines',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='deal',
            name='estimated_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='next_action',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='deal',
            name='opportunity_source',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='deal',
            name='qualification_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='deal',
            name='risk_level',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='quote',
            name='approval_history',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='quote',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_proposals_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quote',
            name='assumptions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='quote',
            name='commercial_deviations',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='quote',
            name='deliverables',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='quote',
            name='disciplines',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='quote',
            name='estimated_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='quote',
            name='estimated_hours',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='quote',
            name='exclusions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='quote',
            name='expected_margin_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='expenses',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='quote',
            name='payment_terms',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='risks',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='quote',
            name='scope',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='subcontractor_costs',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='quote',
            name='submission_evidence',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='quote',
            name='submission_recipient',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='quote',
            name='submitted_version_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='salesforecast',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesforecast',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_forecasts_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesforecast',
            name='category_totals',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='salesforecast',
            name='demand_by_discipline',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='salesforecast',
            name='exchange_rate_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesforecast',
            name='exchange_rate_source',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='salesforecast',
            name='manual_adjustments',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='salesforecast',
            name='source_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='salesforecast',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('owner_review', 'Owner Review'), ('management_review', 'Management Review'), ('approved', 'Approved'), ('superseded', 'Superseded')], db_index=True, default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='quote',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('scope_development', 'Scope Development'), ('estimation', 'Estimation'), ('internal_review', 'Internal Review'), ('approval', 'Approval'), ('ready_to_submit', 'Ready to Submit'), ('submitted', 'Submitted'), ('clarification', 'Clarification'), ('negotiation', 'Negotiation'), ('won', 'Won'), ('lost', 'Lost'), ('withdrawn', 'Withdrawn'), ('cancelled', 'Cancelled'), ('sent', 'Sent to Client'), ('viewed', 'Viewed by Client'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='draft', max_length=20),
        ),
        migrations.CreateModel(
            name='FrameworkAgreement',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('framework_number', models.CharField(db_index=True, max_length=80, unique=True)),
                ('title', models.CharField(max_length=300)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('internal_review', 'Internal Review'), ('pending_signature', 'Pending Signature'), ('active', 'Active'), ('expiring', 'Expiring'), ('expired', 'Expired'), ('suspended', 'Suspended'), ('closed', 'Closed')], db_index=True, default='draft', max_length=24)),
                ('effective_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('renewal_action_date', models.DateField(blank=True, null=True)),
                ('included_services', models.JSONField(blank=True, default=list)),
                ('disciplines', models.JSONField(blank=True, default=list)),
                ('geographic_coverage', models.JSONField(blank=True, default=list)),
                ('currency', models.CharField(default='AED', max_length=10)),
                ('ceiling_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('committed_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('invoiced_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('rate_cards', models.JSONField(blank=True, default=list)),
                ('rate_escalation_method', models.TextField(blank=True)),
                ('call_off_procedure', models.TextField(blank=True)),
                ('payment_terms', models.CharField(blank=True, max_length=255)),
                ('liability_requirements', models.TextField(blank=True)),
                ('insurance_requirements', models.TextField(blank=True)),
                ('compliance_requirements', models.JSONField(blank=True, default=list)),
                ('signed_document', models.CharField(blank=True, max_length=500)),
                ('amendments', models.JSONField(blank=True, default=list)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_frameworks_approved', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='frameworks', to='sales.client')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_frameworks_owned', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sales_framework_agreements',
                'ordering': ['expiry_date', 'framework_number'],
            },
        ),
        migrations.AddField(
            model_name='deal',
            name='framework',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='opportunities', to='sales.frameworkagreement'),
        ),
        migrations.CreateModel(
            name='ProjectHandover',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('initiated', 'Handover Initiated'), ('contract_verification', 'Contract Verification'), ('delivery_preparation', 'Delivery Preparation'), ('commercial_review', 'Commercial Review'), ('meeting', 'Handover Meeting'), ('acceptance_pending', 'Acceptance Pending'), ('accepted', 'Accepted'), ('returned', 'Returned for Correction'), ('project_created', 'Project Created'), ('closed', 'Closed')], db_index=True, default='initiated', max_length=30)),
                ('signed_contract_reference', models.CharField(max_length=160)),
                ('purchase_order_reference', models.CharField(blank=True, max_length=160)),
                ('contract_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(max_length=10)),
                ('contract_start_date', models.DateField(blank=True, null=True)),
                ('contract_end_date', models.DateField(blank=True, null=True)),
                ('contract_differences', models.JSONField(blank=True, default=list)),
                ('billing_milestones', models.JSONField(blank=True, default=list)),
                ('checklist', models.JSONField(blank=True, default=dict)),
                ('delivery_data', models.JSONField(blank=True, default=dict)),
                ('meeting_at', models.DateTimeField(blank=True, null=True)),
                ('acceptance_comment', models.TextField(blank=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('returned_reason', models.TextField(blank=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_handovers_accepted', to=settings.AUTH_USER_MODEL)),
                ('opportunity', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='project_handover', to='sales.deal')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_handovers_owned', to=settings.AUTH_USER_MODEL)),
                ('project', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_handover', to='core.project')),
                ('project_manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_handovers_assigned', to=settings.AUTH_USER_MODEL)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_handovers', to='sales.quote')),
            ],
            options={
                'db_table': 'sales_project_handovers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='frameworkagreement',
            index=models.Index(fields=['client', 'status'], name='sales_frame_client__c36f63_idx'),
        ),
        migrations.AddIndex(
            model_name='frameworkagreement',
            index=models.Index(fields=['expiry_date'], name='sales_frame_expiry__ea27e1_idx'),
        ),
    ]
