# Generated by Django 5.0 on 2026-09-09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_client_commercial_risks_client_legal_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesMailboxConnection',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Sales Outlook intake', max_length=120)),
                ('tenant_id', models.CharField(max_length=100)),
                ('client_id', models.CharField(max_length=100)),
                ('mailbox_address', models.EmailField(max_length=254, unique=True)),
                ('enabled', models.BooleanField(db_index=True, default=False)),
                ('last_status', models.CharField(choices=[('not_tested', 'Not tested'), ('connected', 'Connected'), ('error', 'Connection error')], db_index=True, default='not_tested', max_length=24)),
                ('last_health_check_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('mailbox_display_name', models.CharField(blank=True, max_length=255)),
                ('total_item_count', models.PositiveIntegerField(blank=True, null=True)),
                ('unread_item_count', models.PositiveIntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sales_mailbox_connections',
                'ordering': ['name'],
            },
        ),
    ]
