# Generated by Django 5.0 on 2026-09-09 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_salesemailintake'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='salesemailintake',
            name='duplicate_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicate_intakes', to='sales.salesemailintake'),
        ),
        migrations.AddField(
            model_name='salesemailintake',
            name='resolution_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='salesemailintake',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesemailintake',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_email_intakes_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='salesemailintake',
            name='status',
            field=models.CharField(choices=[('received', 'Received'), ('under_review', 'Under review'), ('converted', 'Converted to opportunity'), ('rejected', 'Rejected'), ('duplicate', 'Duplicate')], db_index=True, default='received', max_length=24),
        ),
    ]
