# Generated by Django 5.0 on 2026-09-28 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def refuse_loss_of_captured_sources(apps, schema_editor):
    intake = apps.get_model('sales', 'SalesEmailIntake')
    if intake.objects.using(schema_editor.connection.alias).filter(mailbox_connection__isnull=False).exists():
        raise RuntimeError(
            'Cannot reverse Sales mailbox capture while captured sources exist. '
            'Keep this schema or restore a verified pre-capture backup; do not discard provenance.'
        )


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_salesemailintake_duplicate_of_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='salesemailintake',
            name='captured_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesemailintake',
            name='conversation_id',
            field=models.CharField(blank=True, db_index=True, max_length=512),
        ),
        migrations.AddField(
            model_name='salesemailintake',
            name='mailbox_connection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='email_intakes', to='sales.salesmailboxconnection'),
        ),
        migrations.AddField(
            model_name='salesemailintake',
            name='source_mailbox_address',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='salesemailintake',
            name='source_tenant_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='salesemailintake',
            name='source_message_id',
            field=models.CharField(db_index=True, max_length=512),
        ),
        migrations.AddConstraint(
            model_name='salesemailintake',
            constraint=models.UniqueConstraint(fields=('mailbox_connection', 'source_message_id'), name='sales_intake_mailbox_message_uq'),
        ),
        migrations.AddConstraint(
            model_name='salesemailintake',
            constraint=models.UniqueConstraint(condition=models.Q(('mailbox_connection__isnull', True)), fields=('source_message_id',), name='sales_intake_legacy_message_uq'),
        ),
        migrations.RunPython(migrations.RunPython.noop, refuse_loss_of_captured_sources),
    ]
