# Generated by Django 5.0 on 2026-09-28 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def refuse_loss_of_sync_progress(apps, schema_editor):
    state = apps.get_model('sales', 'SalesMailboxSyncState')
    if state.objects.using(schema_editor.connection.alias).exists():
        raise RuntimeError(
            'Cannot reverse Sales mailbox sync while sync state exists. '
            'Keep this schema or restore a verified pre-sync backup; '
            'do not discard authority, checkpoints or queued work.'
        )


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_mailbox_scoped_capture'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesMailboxSyncState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('identity', models.JSONField(default=dict)),
                ('status', models.CharField(default='paused', max_length=24)),
                ('folder_cursor', models.TextField(blank=True)),
                ('folder_discovery_completed_at', models.DateTimeField(blank=True, null=True)),
                ('folder_discovery_due_at', models.DateTimeField(blank=True, null=True)),
                ('initial_sync_completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_started_at', models.DateTimeField(blank=True, null=True)),
                ('last_successful_sync_at', models.DateTimeField(blank=True, null=True)),
                ('next_attempt_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('lease_token', models.UUIDField(blank=True, null=True)),
                ('lease_expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_code', models.CharField(blank=True, max_length=40)),
                ('consecutive_failures', models.PositiveIntegerField(default=0)),
                ('authorized_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('connection', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='sync_state', to='sales.salesmailboxconnection')),
            ],
            options={
                'db_table': 'sales_mailbox_sync_states',
            },
        ),
        migrations.CreateModel(
            name='SalesMailboxSyncItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message_id', models.CharField(max_length=512)),
                ('status', models.CharField(db_index=True, default='pending', max_length=24)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_error_code', models.CharField(blank=True, max_length=40)),
                ('intake', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='sales.salesemailintake')),
                ('sync', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.salesmailboxsyncstate')),
            ],
            options={
                'db_table': 'sales_mailbox_sync_items',
            },
        ),
        migrations.CreateModel(
            name='SalesMailboxSyncFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('folder_id', models.CharField(max_length=512)),
                ('cursor', models.TextField(blank=True)),
                ('is_removed', models.BooleanField(default=False)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('next_attempt_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_error_code', models.CharField(blank=True, max_length=40)),
                ('consecutive_failures', models.PositiveIntegerField(default=0)),
                ('sync', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='sales.salesmailboxsyncstate')),
            ],
            options={
                'db_table': 'sales_mailbox_sync_folders',
            },
        ),
        migrations.AddConstraint(
            model_name='salesmailboxsyncitem',
            constraint=models.UniqueConstraint(fields=('sync', 'message_id'), name='sales_sync_message_uq'),
        ),
        migrations.AddConstraint(
            model_name='salesmailboxsyncfolder',
            constraint=models.UniqueConstraint(fields=('sync', 'folder_id'), name='sales_sync_folder_uq'),
        ),
        # Reverse this guard before removing any table or uniqueness constraint.
        migrations.RunPython(migrations.RunPython.noop, refuse_loss_of_sync_progress),
    ]
