# Generated by Django 5.0 on 2026-10-01 13:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def preserve_preparation_evidence(apps, schema_editor):
    alias = schema_editor.connection.alias
    if apps.get_model('sales', 'BidPreparation').objects.using(alias).exists():
        raise RuntimeError('Bid preparation evidence exists. Retain this additive schema when rolling back application code.')


class Migration(migrations.Migration):

    dependencies = [
        ('planning_intelligence', '0049_resource_employee_identity'),
        ('sales', '0014_proposal_review'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BidPreparation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(max_length=1000)),
                ('source_basis', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('opportunity', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='bid_preparation', to='sales.deal')),
                ('planning_project', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='sales_bid_preparation', to='planning_intelligence.planningproject')),
            ],
        ),
        migrations.CreateModel(
            name='QuotePreparationRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revision', models.PositiveIntegerField()),
                ('source', models.JSONField(default=dict)),
                ('evidence', models.JSONField(default=dict)),
                ('source_fingerprint', models.CharField(max_length=64)),
                ('selected_fields', models.JSONField(default=list)),
                ('before_fields', models.JSONField(default=dict)),
                ('applied_fields', models.JSONField(default=dict)),
                ('reason', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('preparation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='captures', to='sales.bidpreparation')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='preparation_revisions', to='sales.quote')),
                ('technical_proposal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_preparation_revisions', to='planning_intelligence.technicalproposal')),
            ],
            options={
                'ordering': ['-revision'],
            },
        ),
        migrations.CreateModel(
            name='BidPreparationCommand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_id', models.UUIDField()),
                ('action', models.CharField(max_length=16)),
                ('request_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('preparation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commands', to='sales.bidpreparation')),
                ('capture', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='command', to='sales.quotepreparationrevision')),
            ],
        ),
        migrations.AddConstraint(
            model_name='quotepreparationrevision',
            constraint=models.UniqueConstraint(fields=('quote', 'revision'), name='sales_quote_preparation_revision_uq'),
        ),
        migrations.AddConstraint(
            model_name='bidpreparationcommand',
            constraint=models.UniqueConstraint(fields=('actor', 'request_id'), name='sales_bid_preparation_command_uq'),
        ),
        migrations.RunPython(migrations.RunPython.noop, preserve_preparation_evidence),
    ]
