# Generated by Django 5.0 on 2026-10-01 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def preserve_folder_tags(apps, schema_editor):
    if apps.get_model('sales', 'OpportunityFolderTag').objects.using(schema_editor.connection.alias).exists():
        raise RuntimeError('Opportunity folder tag evidence exists. Retain this additive schema when rolling back application code.')


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0015_bid_preparation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OpportunityFolderTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_key', models.CharField(max_length=30)),
                ('tag', models.CharField(blank=True, default='', max_length=64)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('last_request_hash', models.CharField(max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folder_tags', to='sales.deal')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='opportunityfoldertag',
            constraint=models.UniqueConstraint(fields=('opportunity', 'folder_key'), name='sales_opportunity_folder_tag_uq'),
        ),
        migrations.AddConstraint(
            model_name='opportunityfoldertag',
            constraint=models.CheckConstraint(check=models.Q(('folder_key__in', ['correspondence', 'tender', 'proposal', 'internal', 'submitted', 'award'])), name='sales_opportunity_folder_tag_key'),
        ),
        migrations.RunPython(migrations.RunPython.noop, preserve_folder_tags),
    ]
