# Generated by Django 5.0 on 2026-10-01 14:20

from django.conf import settings
from django.db import migrations, models


def preserve_storage_evidence(apps, schema_editor):
    uploads = apps.get_model('sales', 'OpportunityWorkspaceUpload').objects.using(schema_editor.connection.alias)
    if uploads.exclude(storage_encoding='identity', stored_size__isnull=True, stored_sha256='').exists():
        raise RuntimeError('Attachment storage representation evidence exists. Retain this schema and an encoding-aware reader; older application code cannot read compressed objects safely.')


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0016_opportunity_folder_tags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunityworkspaceupload',
            name='storage_encoding',
            field=models.CharField(default='identity', max_length=8),
        ),
        migrations.AddField(
            model_name='opportunityworkspaceupload',
            name='stored_sha256',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='opportunityworkspaceupload',
            name='stored_size',
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AddConstraint(
            model_name='opportunityworkspaceupload',
            constraint=models.CheckConstraint(check=models.Q(('storage_encoding__in', ['identity', 'gzip'])), name='sales_upload_storage_encoding'),
        ),
        migrations.RunPython(migrations.RunPython.noop, preserve_storage_evidence),
    ]
