# Generated by Django 5.0 on 2026-10-01 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def preserve_versions(apps, schema_editor):
    alias = schema_editor.connection.alias
    uploads = apps.get_model('sales', 'OpportunityWorkspaceUpload').objects.using(alias)
    if (apps.get_model('sales', 'OpportunityDocument').objects.using(alias).exists()
            or uploads.exclude(document__isnull=True, version_number=1, previous_upload__isnull=True,
                               revision_note='', expected_head_token='').exists()):
        raise RuntimeError('Document revision evidence exists. Retain the version-aware schema and reader; historical upload IDs must continue to resolve their original bytes.')


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0017_attachment_storage_encoding'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OpportunityDocument',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('folder_key', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=255)),
                ('normalized_name', models.CharField(max_length=400, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='opportunityworkspaceupload',
            name='sales_private_attachment_name',
        ),
        migrations.AddField(
            model_name='opportunityworkspaceupload',
            name='expected_head_token',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='opportunityworkspaceupload',
            name='previous_upload',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='sales.opportunityworkspaceupload'),
        ),
        migrations.AddField(
            model_name='opportunityworkspaceupload',
            name='revision_note',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='opportunityworkspaceupload',
            name='version_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='opportunitydocument',
            name='head_upload',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='sales.opportunityworkspaceupload'),
        ),
        migrations.AddField(
            model_name='opportunitydocument',
            name='pending_upload',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='sales.opportunityworkspaceupload'),
        ),
        migrations.AddField(
            model_name='opportunitydocument',
            name='root_upload',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='root_document', to='sales.opportunityworkspaceupload'),
        ),
        migrations.AddField(
            model_name='opportunitydocument',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='sales.opportunityworkspace'),
        ),
        migrations.AddField(
            model_name='opportunityworkspaceupload',
            name='document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='sales.opportunitydocument'),
        ),
        migrations.AddConstraint(
            model_name='opportunityworkspaceupload',
            constraint=models.UniqueConstraint(condition=models.Q(('provider', 'radai'), ('version_number', 1)), fields=('workspace', 'folder_key', 'normalized_name'), name='sales_private_attachment_name'),
        ),
        migrations.AddConstraint(
            model_name='opportunityworkspaceupload',
            constraint=models.UniqueConstraint(fields=('document', 'version_number'), name='sales_document_revision_uq'),
        ),
        migrations.AddConstraint(
            model_name='opportunityworkspaceupload',
            constraint=models.CheckConstraint(check=models.Q(('version_number__gte', 1)), name='sales_document_revision_positive'),
        ),
        migrations.AddConstraint(
            model_name='opportunitydocument',
            constraint=models.UniqueConstraint(fields=('workspace', 'folder_key', 'normalized_name'), name='sales_document_name_uq'),
        ),
        migrations.RunPython(migrations.RunPython.noop, preserve_versions),
    ]
