# Generated by Django 5.0 on 2026-10-01 16:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def preserve_classification_evidence(apps, schema_editor):
    for name in ('OpportunityDocumentClassification', 'OpportunityDocumentClassificationRun',
                 'OpportunityDocumentClassificationCommand'):
        if apps.get_model('sales', name).objects.using(schema_editor.connection.alias).exists():
            raise RuntimeError('Document classification, confirmed corrections or durable job evidence exists. Retain this schema and classification-aware application code.')


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0018_document_versions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OpportunityDocumentClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed_type', models.CharField(blank=True, max_length=40)),
                ('revision', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='classification', to='sales.opportunitydocument')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OpportunityDocumentClassificationCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.UUIDField()),
                ('request_hash', models.CharField(max_length=64)),
                ('kind', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='sales.opportunitydocument')),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='sales.opportunityworkspaceupload')),
            ],
        ),
        migrations.CreateModel(
            name='OpportunityDocumentClassificationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(db_index=True, default='queued', max_length=20)),
                ('source_sha256', models.CharField(max_length=64)),
                ('source_identity', models.CharField(max_length=64)),
                ('lease_token', models.UUIDField(null=True)),
                ('lease_until', models.DateTimeField(null=True)),
                ('next_attempt_at', models.DateTimeField(db_index=True, null=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('suggested_type', models.CharField(default='unclassified', max_length=40)),
                ('origin', models.CharField(default='unclassified', max_length=20)),
                ('evidence', models.JSONField(default=list)),
                ('error_code', models.CharField(blank=True, max_length=50)),
                ('ai_status', models.CharField(default='not_needed', max_length=20)),
                ('provider', models.CharField(blank=True, max_length=30)),
                ('model', models.CharField(blank=True, max_length=200)),
                ('extraction_code', models.CharField(blank=True, max_length=50)),
                ('engine_version', models.CharField(default='document_classification_v1', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('upload', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='classification_run', to='sales.opportunityworkspaceupload')),
            ],
        ),
        migrations.AddConstraint(
            model_name='opportunitydocumentclassificationcommand',
            constraint=models.UniqueConstraint(fields=('actor', 'request_id'), name='sales_doc_classification_request'),
        ),
        migrations.RunPython(migrations.RunPython.noop, preserve_classification_evidence),
    ]
