# Generated by Django 5.0 on 2026-10-01 16:31

from django.db import migrations, models


def preserve_custom_tags(apps, schema_editor):
    rows = apps.get_model('sales', 'OpportunityDocumentClassification').objects.using(schema_editor.connection.alias)
    if rows.exclude(custom_tag='').exists():
        raise RuntimeError('Custom document tags exist. Retain this schema and tag-aware application code; reversal must not discard user labels.')


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0019_document_classification'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunitydocumentclassification',
            name='custom_tag',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.RunPython(migrations.RunPython.noop, preserve_custom_tags),
    ]
