# Generated by Django 5.0 on 2026-10-09 14:48

import apps.sales.letter_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0028_update_letter_templates'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='salesletter',
            new_name='sales_lette_opportu_e5a425_idx',
            old_name='sales_letter_opport_1a2b3c_idx',
        ),
        migrations.RenameIndex(
            model_name='salesletter',
            new_name='sales_lette_status_9fef8d_idx',
            old_name='sales_letter_status_4d5e6f_idx',
        ),
        migrations.AlterField(
            model_name='salesletter',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to=apps.sales.letter_models.letter_pdf_upload_path),
        ),
    ]
