# Generated by Django 5.0 on 2026-01-27 05:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('period_type', models.CharField(choices=[('minute', 'Minute'), ('hour', 'Hour'), ('day', 'Day')], max_length=20)),
                ('total_activities', models.IntegerField(default=0)),
                ('user_activities', models.IntegerField(default=0)),
                ('system_activities', models.IntegerField(default=0)),
                ('api_requests', models.IntegerField(default=0)),
                ('activities_by_category', models.JSONField(default=dict)),
                ('activities_by_type', models.JSONField(default=dict)),
                ('top_users', models.JSONField(default=list)),
                ('avg_duration_ms', models.FloatField(blank=True, null=True)),
                ('success_rate', models.FloatField(default=100.0)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'activity_statistics',
                'ordering': ['-period_start'],
                'indexes': [models.Index(fields=['period_type', '-period_start'], name='activity_st_period__1d6cff_idx')],
            },
        ),
        migrations.CreateModel(
            name='SystemActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('user_login', 'User Login'), ('user_logout', 'User Logout'), ('user_created', 'User Created'), ('user_updated', 'User Updated'), ('user_deleted', 'User Deleted'), ('role_assigned', 'Role Assigned'), ('role_removed', 'Role Removed'), ('permission_granted', 'Permission Granted'), ('permission_revoked', 'Permission Revoked'), ('document_uploaded', 'Document Uploaded'), ('document_processed', 'Document Processed'), ('document_deleted', 'Document Deleted'), ('project_created', 'Project Created'), ('project_updated', 'Project Updated'), ('project_deleted', 'Project Deleted'), ('api_request', 'API Request'), ('system_error', 'System Error'), ('security_event', 'Security Event'), ('data_export', 'Data Export'), ('data_import', 'Data Import'), ('backup_created', 'Backup Created'), ('settings_changed', 'Settings Changed'), ('notification_sent', 'Notification Sent'), ('report_generated', 'Report Generated'), ('ai_analysis', 'AI Analysis Completed'), ('ml_prediction', 'ML Prediction Made'), ('database_query', 'Database Query'), ('cache_hit', 'Cache Hit'), ('cache_miss', 'Cache Miss'), ('webhook_triggered', 'Webhook Triggered')], db_index=True, max_length=50)),
                ('category', models.CharField(choices=[('authentication', 'Authentication'), ('authorization', 'Authorization'), ('data_management', 'Data Management'), ('system_operation', 'System Operation'), ('security', 'Security'), ('api', 'API'), ('ml_ai', 'ML/AI'), ('communication', 'Communication'), ('maintenance', 'Maintenance')], default='system_operation', max_length=50)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('critical', 'Critical')], default='normal', max_length=20)),
                ('user_email', models.EmailField(blank=True, max_length=254)),
                ('user_full_name', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('description', models.TextField()),
                ('details', models.JSONField(default=dict, help_text='Additional activity details')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('duration_ms', models.IntegerField(blank=True, help_text='Duration in milliseconds', null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('tags', models.JSONField(default=list, help_text='Tags for categorization')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System Activity',
                'verbose_name_plural': 'System Activities',
                'db_table': 'system_activity',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ActivityStream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_title', models.CharField(max_length=500)),
                ('display_subtitle', models.CharField(blank=True, max_length=500)),
                ('icon', models.CharField(default='info', max_length=50)),
                ('color', models.CharField(default='blue', max_length=50)),
                ('is_grouped', models.BooleanField(default=False)),
                ('group_key', models.CharField(blank=True, db_index=True, max_length=200)),
                ('group_count', models.IntegerField(default=1)),
                ('is_public', models.BooleanField(default=True)),
                ('is_pinned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stream', to='activity.systemactivity')),
            ],
            options={
                'db_table': 'activity_stream',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('device_type', models.CharField(blank=True, max_length=50)),
                ('browser', models.CharField(blank=True, max_length=100)),
                ('os', models.CharField(blank=True, max_length=100)),
                ('last_activity', models.DateTimeField(default=django.utils.timezone.now)),
                ('current_page', models.CharField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_session',
                'ordering': ['-last_activity'],
            },
        ),
        migrations.AddIndex(
            model_name='systemactivity',
            index=models.Index(fields=['-timestamp', 'activity_type'], name='system_acti_timesta_78ebc9_idx'),
        ),
        migrations.AddIndex(
            model_name='systemactivity',
            index=models.Index(fields=['user', '-timestamp'], name='system_acti_user_id_5fe3a3_idx'),
        ),
        migrations.AddIndex(
            model_name='systemactivity',
            index=models.Index(fields=['category', '-timestamp'], name='system_acti_categor_ad5264_idx'),
        ),
        migrations.AddIndex(
            model_name='systemactivity',
            index=models.Index(fields=['severity', '-timestamp'], name='system_acti_severit_89bd4f_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['user', '-last_activity'], name='user_sessio_user_id_d17407_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['is_active', '-last_activity'], name='user_sessio_is_acti_e01d0e_idx'),
        ),
    ]
