# Generated by Django 4.2.16 on 2026-01-28 04:35

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('icon', models.CharField(default='📄', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('configuration', models.JSONField(default=dict, help_text='Complete configuration including sections, fields, validations, calculations')),
                ('template_file', models.CharField(blank=True, max_length=255)),
                ('calculation_module', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('deprecated', 'Deprecated'), ('draft', 'Draft')], default='active', max_length=20)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('applicable_standards', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_equipment_types', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Equipment Type',
                'verbose_name_plural': 'Equipment Types',
                'db_table': 'process_equipment_types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProcessDatasheet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_number', models.CharField(db_index=True, max_length=100, unique=True)),
                ('contractor_document_number', models.CharField(blank=True, max_length=100)),
                ('title', models.CharField(max_length=500)),
                ('tag_number', models.CharField(db_index=True, max_length=100)),
                ('service_description', models.TextField()),
                ('location', models.CharField(blank=True, max_length=200)),
                ('project_name', models.CharField(max_length=300)),
                ('project_number', models.CharField(max_length=100)),
                ('unit_number', models.CharField(blank=True, max_length=100)),
                ('area', models.CharField(blank=True, max_length=100)),
                ('data', models.JSONField(default=dict, help_text='All datasheet field values based on equipment type configuration')),
                ('calculated_values', models.JSONField(blank=True, default=dict)),
                ('validation_status', models.CharField(default='not_validated', max_length=20)),
                ('validation_results', models.JSONField(blank=True, default=dict)),
                ('validation_score', models.FloatField(default=0.0)),
                ('extraction_metadata', models.JSONField(blank=True, default=dict, help_text='AI extraction confidence scores and sources')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ifr', 'Issued for Review'), ('ifa', 'Issued for Approval'), ('ifc', 'Issued for Construction'), ('afc', 'Approved for Construction'), ('cancelled', 'Cancelled'), ('superseded', 'Superseded')], default='draft', max_length=20)),
                ('document_class', models.CharField(choices=[('1', 'Class 1'), ('2', 'Class 2'), ('3', 'Class 3'), ('4', 'Class 4')], default='1', max_length=1)),
                ('revision', models.IntegerField(default=0)),
                ('pid_drawing_number', models.CharField(blank=True, max_length=100)),
                ('line_number', models.CharField(blank=True, max_length=100)),
                ('material_spec', models.CharField(blank=True, max_length=100)),
                ('related_documents', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, size=None)),
                ('source_files', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), blank=True, default=list, help_text='Source files (P&ID, specs, etc.) used for extraction', size=None)),
                ('generated_pdf', models.CharField(blank=True, max_length=500)),
                ('holds', models.JSONField(blank=True, default=list)),
                ('comments', models.JSONField(blank=True, default=list)),
                ('date_prepared', models.DateField(blank=True, null=True)),
                ('date_checked', models.DateField(blank=True, null=True)),
                ('date_approved', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_datasheets', to=settings.AUTH_USER_MODEL)),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_datasheets', to=settings.AUTH_USER_MODEL)),
                ('equipment_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='datasheets', to='process_datasheet.equipmenttype')),
                ('prepared_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepared_datasheets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Process Datasheet',
                'verbose_name_plural': 'Process Datasheets',
                'db_table': 'process_datasheets',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DatasheetValidationRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rule_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('condition', models.TextField(help_text='Python expression or formula')),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], default='error', max_length=20)),
                ('message', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('applies_to_projects', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, help_text='Empty = applies to all projects', size=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('equipment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_validation_rules', to='process_datasheet.equipmenttype')),
            ],
            options={
                'verbose_name': 'Validation Rule',
                'verbose_name_plural': 'Validation Rules',
                'db_table': 'process_datasheet_validation_rules',
                'ordering': ['equipment_type', 'severity', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DatasheetTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('template_data', models.JSONField(default=dict)),
                ('usage_count', models.IntegerField(default=0)),
                ('is_global', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasheet_templates', to=settings.AUTH_USER_MODEL)),
                ('equipment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='process_datasheet.equipmenttype')),
            ],
            options={
                'verbose_name': 'Datasheet Template',
                'verbose_name_plural': 'Datasheet Templates',
                'db_table': 'process_datasheet_templates',
                'ordering': ['-usage_count', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DatasheetRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revision_number', models.IntegerField()),
                ('description', models.TextField()),
                ('data_snapshot', models.JSONField(default=dict)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('pages_affected', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None)),
                ('revision_date', models.DateTimeField(auto_now_add=True)),
                ('datasheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='process_datasheet.processdatasheet')),
                ('revised_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Datasheet Revision',
                'verbose_name_plural': 'Datasheet Revisions',
                'db_table': 'process_datasheet_revisions',
                'ordering': ['-revision_number'],
            },
        ),
        migrations.CreateModel(
            name='DatasheetExtractionJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_type', models.CharField(max_length=50)),
                ('source_files', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), default=list, size=None)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('progress', models.FloatField(default=0.0)),
                ('extracted_data', models.JSONField(blank=True, default=dict)),
                ('confidence_scores', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('datasheet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extraction_jobs', to='process_datasheet.processdatasheet')),
            ],
            options={
                'verbose_name': 'Extraction Job',
                'verbose_name_plural': 'Extraction Jobs',
                'db_table': 'process_datasheet_extraction_jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='processdatasheet',
            index=models.Index(fields=['tag_number', 'equipment_type'], name='process_dat_tag_num_590d59_idx'),
        ),
        migrations.AddIndex(
            model_name='processdatasheet',
            index=models.Index(fields=['project_number', 'status'], name='process_dat_project_b23741_idx'),
        ),
        migrations.AddIndex(
            model_name='processdatasheet',
            index=models.Index(fields=['document_number', 'revision'], name='process_dat_documen_b33e74_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='datasheetrevision',
            unique_together={('datasheet', 'revision_number')},
        ),
    ]
