# Generated by Django 5.0 on 2026-01-28 08:49

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process_datasheet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasheetextractionjob',
            name='equipment_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extraction_jobs', to='process_datasheet.equipmenttype'),
        ),
        migrations.AddField(
            model_name='datasheetextractionjob',
            name='extraction_mode',
            field=models.CharField(default='hybrid', max_length=20),
        ),
        migrations.AddField(
            model_name='datasheetextractionjob',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='extraction_pdfs/'),
        ),
        migrations.AlterField(
            model_name='datasheetextractionjob',
            name='source_files',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), blank=True, default=list, size=None),
        ),
    ]
