# Generated by Django 5.0 on 2026-02-11 for Control Valve Delta P Check

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process_datasheet', '0004_discharge_pressure_calculations'),
    ]

    operations = [
        # Rename liquid_characteristics to control_valve_delta_p
        migrations.RenameField(
            model_name='pumpcalculationdata',
            old_name='liquid_characteristics',
            new_name='control_valve_delta_p',
        ),
        
        # Add Control Valve Delta P Check fields (10 fields)
        migrations.AddField(
            model_name='pumpcalculationdata',
            name='density',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Fluid density in kg/m³', max_digits=10, null=True, verbose_name='Density'),
        ),
        migrations.AddField(
            model_name='pumpcalculationdata',
            name='cv_max',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Maximum control valve coefficient', max_digits=10, null=True, verbose_name='CV Max'),
        ),
        migrations.AddField(
            model_name='pumpcalculationdata',
            name='cv_min',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Minimum control valve coefficient', max_digits=10, null=True, verbose_name='CV Min'),
        ),
        migrations.AddField(
            model_name='pumpcalculationdata',
            name='cv_ratio',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Auto-calculated ratio of maximum to minimum CV', max_digits=10, null=True, verbose_name='CVRatio (Max/Min)'),
        ),
        migrations.AddField(
            model_name='pumpcalculationdata',
            name='total_frictional_losses',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Total frictional losses at normal flow in bar', max_digits=10, null=True, verbose_name='Total Frictional Losses @ Normal Flow'),
        ),
        migrations.AddField(
            model_name='pumpcalculationdata',
            name='dynamic_losses_30_percent',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Auto-calculated 30% of total frictional losses in bar', max_digits=10, null=True, verbose_name='30% Dynamic Losses'),
        ),
        migrations.AddField(
            model_name='pumpcalculationdata',
            name='cv_pressure_drop',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Control valve pressure drop at normal flow in bar', max_digits=10, null=True, verbose_name='CV Pr. drop @ Normal Flow'),
        ),
        migrations.AddField(
            model_name='pumpcalculationdata',
            name='cv_rangeability',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Control valve rangeability factor', max_digits=10, null=True, verbose_name='CV Rangeability'),
        ),
        migrations.AddField(
            model_name='pumpcalculationdata',
            name='cv_ratio_within_range',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], help_text='Whether CV ratio is within acceptable range', max_length=10, verbose_name='A. CV Ratio Within Range'),
        ),
        migrations.AddField(
            model_name='pumpcalculationdata',
            name='cv_pressure_drop_check',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], help_text='Whether CV pressure drop exceeds 30% of frictional losses', max_length=10, verbose_name='B. CV Pr. drop@Normal Flow > 30% Fric Pr. Loss'),
        ),
    ]