# Generated by Django 5.0 on 2026-02-11 for Suction Pressure Calculations

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process_datasheet', '0006_control_valve_delta_p'),
    ]

    operations = [
        # Rename operating_conditions to suction_pressure_calculations
        migrations.RenameField(
            model_name='pumpcalculationdata',
            old_name='operating_conditions',
            new_name='suction_pressure_calculations',
        ),
        
        # Add Suction Pressure Calculation fields (8 fields)
        migrations.AddField(
            model_name='pumpcalculationdata',
            name='source_op_pressure',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Source operating pressure in bar(g)', max_digits=10, null=True, verbose_name='Source Op. Pressure'),
        ),
        migrations.AddField(
            model_name='pumpcalculationdata',
            name='suction_elm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Suction elevation in meters', max_digits=10, null=True, verbose_name='Suction ELm'),
        ),
        migrations.AddField(
            model_name='pumpcalculationdata',
            name='inline_inst_losses',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Inline instrument losses in bar', max_digits=10, null=True, verbose_name='Inline Inst. Losses'),
        ),
        migrations.AddField(
            model_name='pumpcalculationdata',
            name='line_fric_losses',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Line friction losses in bar', max_digits=10, null=True, verbose_name='Line Fric Losses'),
        ),
        migrations.AddField(
            model_name='pumpcalculationdata',
            name='control_valve_suction',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Control valve losses in suction line in bar', max_digits=10, null=True, verbose_name='Control Valve'),
        ),
        migrations.AddField(
            model_name='pumpcalculationdata',
            name='misc_items_suction',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Miscellaneous items losses in suction line in bar', max_digits=10, null=True, verbose_name='Misc Items'),
        ),
        migrations.AddField(
            model_name='pumpcalculationdata',
            name='total_suction_losses',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Auto-calculated total suction losses in bar', max_digits=10, null=True, verbose_name='Total Suction Losses'),
        ),
        migrations.AddField(
            model_name='pumpcalculationdata',
            name='total_suction_pressure',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Auto-calculated total suction pressure in bar(g)', max_digits=10, null=True, verbose_name='Total Suction Pressure'),
        ),
    ]