# Generated by Django 5.0 on 2026-02-11 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process_datasheet', '0007_suction_pressure_calculations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pumpcalculationdata',
            name='control_valve_delta_p',
            field=models.JSONField(blank=True, default=dict, help_text='Control valve delta P check calculations'),
        ),
        migrations.AlterField(
            model_name='pumpcalculationdata',
            name='suction_pressure_calculations',
            field=models.JSONField(blank=True, default=dict, help_text='Suction pressure calculations parameters'),
        ),
    ]
