# Generated by Django 5.0 on 2026-02-12 11:45
# Clean migration - only adds new fields, no index operations

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process_datasheet', '0016_add_max_discharge_pressure_options'),
    ]

    operations = [
        # Project Information Fields
        migrations.AddField(
            model_name='pumpcalculationdata',
            name='company_name',
            field=models.CharField(blank=True, help_text='Company name for the project', max_length=200, null=True, verbose_name='Company Name'),
        ),
        migrations.AddField(
            model_name='pumpcalculationdata',
            name='site',
            field=models.CharField(blank=True, help_text='Site location', max_length=200, null=True, verbose_name='Site'),
        ),
        migrations.AddField(
            model_name='pumpcalculationdata',
            name='unit',
            field=models.CharField(blank=True, help_text='Unit designation', max_length=100, null=True, verbose_name='Unit'),
        ),
        migrations.AddField(
            model_name='pumpcalculationdata',
            name='manufacturer',
            field=models.CharField(blank=True, help_text='Pump manufacturer', max_length=200, null=True, verbose_name='Manufacturer'),
        ),
        migrations.AddField(
            model_name='pumpcalculationdata',
            name='model',
            field=models.CharField(blank=True, help_text='Pump model number', max_length=200, null=True, verbose_name='Model'),
        ),
        
        # Liquid Characteristics - Max/Min Values
        migrations.AddField(
            model_name='pumpcalculationdata',
            name='liquid_type',
            field=models.CharField(blank=True, help_text='Type of liquid being pumped', max_length=200, null=True, verbose_name='Liquid Type'),
        ),
        migrations.AddField(
            model_name='pumpcalculationdata',
            name='vapor_pressure_max',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Maximum vapor pressure', max_digits=10, null=True, verbose_name='Vapor Pressure (Max)'),
        ),
        migrations.AddField(
            model_name='pumpcalculationdata',
            name='vapor_pressure_min',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Minimum vapor pressure', max_digits=10, null=True, verbose_name='Vapor Pressure (Min)'),
        ),
        migrations.AddField(
            model_name='pumpcalculationdata',
            name='density_max',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Maximum density', max_digits=10, null=True, verbose_name='Density (Max)'),
        ),
        migrations.AddField(
            model_name='pumpcalculationdata',
            name='density_min',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Minimum density', max_digits=10, null=True, verbose_name='Density (Min)'),
        ),
        migrations.AddField(
            model_name='pumpcalculationdata',
            name='viscosity_max',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Maximum viscosity', max_digits=10, null=True, verbose_name='Viscosity (Max)'),
        ),
        migrations.AddField(
            model_name='pumpcalculationdata',
            name='viscosity_min',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Minimum viscosity', max_digits=10, null=True, verbose_name='Viscosity (Min)'),
        ),
        migrations.AddField(
            model_name='pumpcalculationdata',
            name='temperature_max',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum operating temperature', max_digits=10, null=True, verbose_name='Temperature (Max)'),
        ),
        migrations.AddField(
            model_name='pumpcalculationdata',
            name='temperature_min',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum operating temperature', max_digits=10, null=True, verbose_name='Temperature (Min)'),
        ),
        
        # Operating Conditions - Max/Normal/Min Values
        migrations.AddField(
            model_name='pumpcalculationdata',
            name='flow_rate_max',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum flow rate', max_digits=10, null=True, verbose_name='Flow Rate (Max)'),
        ),
        migrations.AddField(
            model_name='pumpcalculationdata',
            name='flow_rate_normal',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Normal flow rate', max_digits=10, null=True, verbose_name='Flow Rate (Normal)'),
        ),
        migrations.AddField(
            model_name='pumpcalculationdata',
            name='flow_rate_min',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum flow rate', max_digits=10, null=True, verbose_name='Flow Rate (Min)'),
        ),
        migrations.AddField(
            model_name='pumpcalculationdata',
            name='suction_pressure_max',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Maximum suction pressure', max_digits=10, null=True, verbose_name='Suction Pressure (Max)'),
        ),
        migrations.AddField(
            model_name='pumpcalculationdata',
            name='suction_pressure_normal',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Normal suction pressure', max_digits=10, null=True, verbose_name='Suction Pressure (Normal)'),
        ),
        migrations.AddField(
            model_name='pumpcalculationdata',
            name='suction_pressure_min',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Minimum suction pressure', max_digits=10, null=True, verbose_name='Suction Pressure (Min)'),
        ),
        migrations.AddField(
            model_name='pumpcalculationdata',
            name='discharge_pressure_max',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Maximum discharge pressure', max_digits=10, null=True, verbose_name='Discharge Pressure (Max)'),
        ),
        migrations.AddField(
            model_name='pumpcalculationdata',
            name='discharge_pressure_normal',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Normal discharge pressure', max_digits=10, null=True, verbose_name='Discharge Pressure (Normal)'),
        ),
        migrations.AddField(
            model_name='pumpcalculationdata',
            name='discharge_pressure_min',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Minimum discharge pressure', max_digits=10, null=True, verbose_name='Discharge Pressure (Min)'),
        ),
        migrations.AddField(
            model_name='pumpcalculationdata',
            name='differential_pressure_max',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Maximum differential pressure', max_digits=10, null=True, verbose_name='Differential Pressure (Max)'),
        ),
        migrations.AddField(
            model_name='pumpcalculationdata',
            name='differential_pressure_normal',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Normal differential pressure', max_digits=10, null=True, verbose_name='Differential Pressure (Normal)'),
        ),
        migrations.AddField(
            model_name='pumpcalculationdata',
            name='differential_pressure_min',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Minimum differential pressure', max_digits=10, null=True, verbose_name='Differential Pressure (Min)'),
        ),
        migrations.AddField(
            model_name='pumpcalculationdata',
            name='differential_head_max',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum differential head', max_digits=10, null=True, verbose_name='Differential Head (Max)'),
        ),
        migrations.AddField(
            model_name='pumpcalculationdata',
            name='differential_head_normal',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Normal differential head', max_digits=10, null=True, verbose_name='Differential Head (Normal)'),
        ),
        migrations.AddField(
            model_name='pumpcalculationdata',
            name='differential_head_min',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum differential head', max_digits=10, null=True, verbose_name='Differential Head (Min)'),
        ),
        
        # NPSH Fields
        migrations.AddField(
            model_name='pumpcalculationdata',
            name='npsh_available_max',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum NPSH available', max_digits=10, null=True, verbose_name='NPSH Available (Max)'),
        ),
        migrations.AddField(
            model_name='pumpcalculationdata',
            name='npsh_available_min',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum NPSH available', max_digits=10, null=True, verbose_name='NPSH Available (Min)'),
        ),
        migrations.AddField(
            model_name='pumpcalculationdata',
            name='npsh_required',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='NPSH required', max_digits=10, null=True, verbose_name='NPSH Required'),
        ),
        
        # Pump Performance - Max/Normal/Min Values
        migrations.AddField(
            model_name='pumpcalculationdata',
            name='pump_efficiency_max',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum pump efficiency (%)', max_digits=10, null=True, verbose_name='Pump Efficiency (Max)'),
        ),
        migrations.AddField(
            model_name='pumpcalculationdata',
            name='pump_efficiency_normal',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Normal pump efficiency (%)', max_digits=10, null=True, verbose_name='Pump Efficiency (Normal)'),
        ),
        migrations.AddField(
            model_name='pumpcalculationdata',
            name='pump_efficiency_min',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum pump efficiency (%)', max_digits=10, null=True, verbose_name='Pump Efficiency (Min)'),
        ),
        migrations.AddField(
            model_name='pumpcalculationdata',
            name='bhp_max',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum brake horsepower', max_digits=10, null=True, verbose_name='BHP (Max)'),
        ),
        migrations.AddField(
            model_name='pumpcalculationdata',
            name='bhp_normal',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Normal brake horsepower', max_digits=10, null=True, verbose_name='BHP (Normal)'),
        ),
        migrations.AddField(
            model_name='pumpcalculationdata',
            name='bhp_min',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum brake horsepower', max_digits=10, null=True, verbose_name='BHP (Min)'),
        ),
        migrations.AddField(
            model_name='pumpcalculationdata',
            name='absorbed_power_max',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum absorbed power in kW', max_digits=10, null=True, verbose_name='Absorbed Power (Max)'),
        ),
        migrations.AddField(
            model_name='pumpcalculationdata',
            name='absorbed_power_normal',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Normal absorbed power in kW', max_digits=10, null=True, verbose_name='Absorbed Power (Normal)'),
        ),
        migrations.AddField(
            model_name='pumpcalculationdata',
            name='absorbed_power_min',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum absorbed power in kW', max_digits=10, null=True, verbose_name='Absorbed Power (Min)'),
        ),
        
        # Motor/Driver Data
        migrations.AddField(
            model_name='pumpcalculationdata',
            name='driver_type',
            field=models.CharField(blank=True, help_text='Type of driver (motor, turbine, etc.)', max_length=100, null=True, verbose_name='Driver Type'),
        ),
        migrations.AddField(
            model_name='pumpcalculationdata',
            name='motor_voltage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Motor voltage in V', max_digits=10, null=True, verbose_name='Motor Voltage'),
        ),
        migrations.AddField(
            model_name='pumpcalculationdata',
            name='motor_speed',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='Motor speed in RPM', max_digits=10, null=True, verbose_name='Motor Speed'),
        ),
        
        # Construction Materials
        migrations.AddField(
            model_name='pumpcalculationdata',
            name='casing',
            field=models.CharField(blank=True, help_text='Casing material', max_length=200, null=True, verbose_name='Casing Material'),
        ),
        migrations.AddField(
            model_name='pumpcalculationdata',
            name='impeller',
            field=models.CharField(blank=True, help_text='Impeller material', max_length=200, null=True, verbose_name='Impeller Material'),
        ),
        migrations.AddField(
            model_name='pumpcalculationdata',
            name='shaft',
            field=models.CharField(blank=True, help_text='Shaft material', max_length=200, null=True, verbose_name='Shaft Material'),
        ),
        migrations.AddField(
            model_name='pumpcalculationdata',
            name='bearings',
            field=models.CharField(blank=True, help_text='Bearings material/type', max_length=200, null=True, verbose_name='Bearings'),
        ),
        migrations.AddField(
            model_name='pumpcalculationdata',
            name='mechanical_seal',
            field=models.CharField(blank=True, help_text='Mechanical seal material/type', max_length=200, null=True, verbose_name='Mechanical Seal'),
        ),
    ]
