# Generated by Django 5.0 on 2026-02-12 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process_datasheet', '0016_add_max_discharge_pressure_options'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='pumpcalculationdata',
            name='pump_calculation_data_dest_flow_idx',
        ),
        migrations.RemoveIndex(
            model_name='pumpcalculationdata',
            name='pump_calculation_data_total_pressure_idx',
        ),
        migrations.RenameIndex(
            model_name='pumpcalculationdata',
            new_name='pump_calcul_tag_no_1ac76f_idx',
            old_name='pump_calculation_data_tag_no_project_no_idx',
        ),
        migrations.RenameIndex(
            model_name='pumpcalculationdata',
            new_name='pump_calcul_documen_2fc886_idx',
            old_name='pump_calculation_data_document_no_revision_idx',
        ),
        migrations.RenameIndex(
            model_name='pumpcalculationdata',
            new_name='pump_calcul_status_8d3b11_idx',
            old_name='pump_calculation_data_status_updated_at_idx',
        ),
        migrations.RemoveField(
            model_name='pumpcalculationdata',
            name='material_design',
        ),
        migrations.RemoveField(
            model_name='pumpcalculationdata',
            name='site_utility',
        ),
        migrations.AddField(
            model_name='pumpcalculationdata',
            name='absorbed_power_max',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum absorbed power in kW', max_digits=10, null=True, verbose_name='Absorbed Power (Max)'),
        ),
        migrations.AddField(
            model_name='pumpcalculationdata',
            name='absorbed_power_min',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum absorbed power in kW', max_digits=10, null=True, verbose_name='Absorbed Power (Min)'),
        ),
        migrations.AddField(
            model_name='pumpcalculationdata',
            name='absorbed_power_normal',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Normal absorbed power in kW', max_digits=10, null=True, verbose_name='Absorbed Power (Normal)'),
        ),
        migrations.AddField(
            model_name='pumpcalculationdata',
            name='bearings',
            field=models.CharField(blank=True, help_text='Bearing type and material specification', max_length=200, verbose_name='Bearings Type'),
        ),
        migrations.AddField(
            model_name='pumpcalculationdata',
            name='bhp_max',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum brake horsepower in HP', max_digits=10, null=True, verbose_name='BHP (Max)'),
        ),
        migrations.AddField(
            model_name='pumpcalculationdata',
            name='bhp_min',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum brake horsepower in HP', max_digits=10, null=True, verbose_name='BHP (Min)'),
        ),
        migrations.AddField(
            model_name='pumpcalculationdata',
            name='bhp_normal',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Normal brake horsepower in HP', max_digits=10, null=True, verbose_name='BHP (Normal)'),
        ),
        migrations.AddField(
            model_name='pumpcalculationdata',
            name='casing',
            field=models.CharField(blank=True, help_text='Pump casing material specification', max_length=200, verbose_name='Casing Material'),
        ),
        migrations.AddField(
            model_name='pumpcalculationdata',
            name='company_name',
            field=models.CharField(blank=True, help_text='Company or client name', max_length=200, verbose_name='Company Name'),
        ),
        migrations.AddField(
            model_name='pumpcalculationdata',
            name='density_max',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Maximum density in kg/m³', max_digits=10, null=True, verbose_name='Density (Max)'),
        ),
        migrations.AddField(
            model_name='pumpcalculationdata',
            name='density_min',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Minimum density in kg/m³', max_digits=10, null=True, verbose_name='Density (Min)'),
        ),
        migrations.AddField(
            model_name='pumpcalculationdata',
            name='differential_head_max',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum differential head in m', max_digits=10, null=True, verbose_name='Differential Head (Max)'),
        ),
        migrations.AddField(
            model_name='pumpcalculationdata',
            name='differential_head_min',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum differential head in m', max_digits=10, null=True, verbose_name='Differential Head (Min)'),
        ),
        migrations.AddField(
            model_name='pumpcalculationdata',
            name='differential_head_normal',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Normal differential head in m', max_digits=10, null=True, verbose_name='Differential Head (Normal)'),
        ),
        migrations.AddField(
            model_name='pumpcalculationdata',
            name='differential_pressure_max',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Maximum differential pressure in bar', max_digits=10, null=True, verbose_name='Differential Pressure (Max)'),
        ),
        migrations.AddField(
            model_name='pumpcalculationdata',
            name='differential_pressure_min',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Minimum differential pressure in bar', max_digits=10, null=True, verbose_name='Differential Pressure (Min)'),
        ),
        migrations.AddField(
            model_name='pumpcalculationdata',
            name='differential_pressure_normal',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Normal differential pressure in bar', max_digits=10, null=True, verbose_name='Differential Pressure (Normal)'),
        ),
        migrations.AddField(
            model_name='pumpcalculationdata',
            name='discharge_pressure_max',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Maximum discharge pressure in bar', max_digits=10, null=True, verbose_name='Discharge Pressure (Max)'),
        ),
        migrations.AddField(
            model_name='pumpcalculationdata',
            name='discharge_pressure_min',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Minimum discharge pressure in bar', max_digits=10, null=True, verbose_name='Discharge Pressure (Min)'),
        ),
        migrations.AddField(
            model_name='pumpcalculationdata',
            name='discharge_pressure_normal',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Normal discharge pressure in bar', max_digits=10, null=True, verbose_name='Discharge Pressure (Normal)'),
        ),
        migrations.AddField(
            model_name='pumpcalculationdata',
            name='driver_type',
            field=models.CharField(blank=True, help_text='Type of driver (e.g., Electric Motor, Steam Turbine)', max_length=100, verbose_name='Driver Type'),
        ),
        migrations.AddField(
            model_name='pumpcalculationdata',
            name='flow_rate_max',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Maximum flow rate in m³/h', max_digits=10, null=True, verbose_name='Flow Rate (Max)'),
        ),
        migrations.AddField(
            model_name='pumpcalculationdata',
            name='flow_rate_min',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Minimum flow rate in m³/h', max_digits=10, null=True, verbose_name='Flow Rate (Min)'),
        ),
        migrations.AddField(
            model_name='pumpcalculationdata',
            name='flow_rate_normal',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Normal flow rate in m³/h', max_digits=10, null=True, verbose_name='Flow Rate (Normal)'),
        ),
        migrations.AddField(
            model_name='pumpcalculationdata',
            name='impeller',
            field=models.CharField(blank=True, help_text='Pump impeller material specification', max_length=200, verbose_name='Impeller Material'),
        ),
        migrations.AddField(
            model_name='pumpcalculationdata',
            name='liquid_type',
            field=models.CharField(blank=True, help_text='Type of liquid being pumped', max_length=200, verbose_name='Liquid Type / Service'),
        ),
        migrations.AddField(
            model_name='pumpcalculationdata',
            name='manufacturer',
            field=models.CharField(blank=True, help_text='Pump manufacturer name', max_length=200, verbose_name='Manufacturer'),
        ),
        migrations.AddField(
            model_name='pumpcalculationdata',
            name='mechanical_seal',
            field=models.CharField(blank=True, help_text='Mechanical seal type and specification', max_length=200, verbose_name='Mechanical Seal Type'),
        ),
        migrations.AddField(
            model_name='pumpcalculationdata',
            name='model',
            field=models.CharField(blank=True, help_text='Pump model designation', max_length=200, verbose_name='Model'),
        ),
        migrations.AddField(
            model_name='pumpcalculationdata',
            name='motor_speed',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Motor speed in RPM', max_digits=10, null=True, verbose_name='Motor Speed'),
        ),
        migrations.AddField(
            model_name='pumpcalculationdata',
            name='motor_voltage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Motor voltage in V', max_digits=10, null=True, verbose_name='Motor Voltage'),
        ),
        migrations.AddField(
            model_name='pumpcalculationdata',
            name='npsh_available_max',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum NPSH available in m', max_digits=10, null=True, verbose_name='NPSH Available (Max)'),
        ),
        migrations.AddField(
            model_name='pumpcalculationdata',
            name='npsh_available_min',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum NPSH available in m', max_digits=10, null=True, verbose_name='NPSH Available (Min)'),
        ),
        migrations.AddField(
            model_name='pumpcalculationdata',
            name='npsh_required',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='NPSH required by pump in m', max_digits=10, null=True, verbose_name='NPSH Required'),
        ),
        migrations.AddField(
            model_name='pumpcalculationdata',
            name='pump_efficiency_max',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum pump efficiency in %', max_digits=5, null=True, verbose_name='Pump Efficiency (Max)'),
        ),
        migrations.AddField(
            model_name='pumpcalculationdata',
            name='pump_efficiency_min',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum pump efficiency in %', max_digits=5, null=True, verbose_name='Pump Efficiency (Min)'),
        ),
        migrations.AddField(
            model_name='pumpcalculationdata',
            name='pump_efficiency_normal',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Normal pump efficiency in %', max_digits=5, null=True, verbose_name='Pump Efficiency (Normal)'),
        ),
        migrations.AddField(
            model_name='pumpcalculationdata',
            name='shaft',
            field=models.CharField(blank=True, help_text='Pump shaft material specification', max_length=200, verbose_name='Shaft Material'),
        ),
        migrations.AddField(
            model_name='pumpcalculationdata',
            name='site',
            field=models.CharField(blank=True, help_text='Site or facility name', max_length=200, verbose_name='Site'),
        ),
        migrations.AddField(
            model_name='pumpcalculationdata',
            name='suction_pressure_max',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Maximum suction pressure in bar', max_digits=10, null=True, verbose_name='Suction Pressure (Max)'),
        ),
        migrations.AddField(
            model_name='pumpcalculationdata',
            name='suction_pressure_min',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Minimum suction pressure in bar', max_digits=10, null=True, verbose_name='Suction Pressure (Min)'),
        ),
        migrations.AddField(
            model_name='pumpcalculationdata',
            name='suction_pressure_normal',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Normal suction pressure in bar', max_digits=10, null=True, verbose_name='Suction Pressure (Normal)'),
        ),
        migrations.AddField(
            model_name='pumpcalculationdata',
            name='temperature_max',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum operating temperature in °C', max_digits=10, null=True, verbose_name='Temperature (Max)'),
        ),
        migrations.AddField(
            model_name='pumpcalculationdata',
            name='temperature_min',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum operating temperature in °C', max_digits=10, null=True, verbose_name='Temperature (Min)'),
        ),
        migrations.AddField(
            model_name='pumpcalculationdata',
            name='unit',
            field=models.CharField(blank=True, help_text='Unit or plant designation', max_length=100, verbose_name='Unit'),
        ),
        migrations.AddField(
            model_name='pumpcalculationdata',
            name='vapor_pressure_max',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Maximum vapor pressure in bar', max_digits=10, null=True, verbose_name='Vapor Pressure (Max)'),
        ),
        migrations.AddField(
            model_name='pumpcalculationdata',
            name='vapor_pressure_min',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Minimum vapor pressure in bar', max_digits=10, null=True, verbose_name='Vapor Pressure (Min)'),
        ),
        migrations.AddField(
            model_name='pumpcalculationdata',
            name='viscosity_max',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Maximum viscosity in cP', max_digits=10, null=True, verbose_name='Viscosity (Max)'),
        ),
        migrations.AddField(
            model_name='pumpcalculationdata',
            name='viscosity_min',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Minimum viscosity in cP', max_digits=10, null=True, verbose_name='Viscosity (Min)'),
        ),
        migrations.AlterField(
            model_name='pumpcalculationdata',
            name='destination_pressure',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Destination pressure', max_digits=10, null=True, verbose_name='Destination Pressure'),
        ),
    ]
