# Generated by Django 5.0 on 2026-03-06 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('process_datasheet', '0004_alter_material_design_nullable'),
        ('process_datasheet', '0017_add_datasheet_template_fields'),
    ]

    operations = [
    ]
