# Generated by Django 5.0 on 2026-03-10 (Conflict Resolution)
# This migration resolves the conflicting merge migrations in preprod

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('process_datasheet', '0018_merge_20260306_1236'),
    ]

    operations = [
        # No operations needed - this migration simply establishes 
        # the proper dependency chain after resolving conflicts
    ]
