# Generated by Django 4.2.16 on 2026-07-10 17:04
# FIXED: Changed RemoveIndex/RenameIndex to conditional SQL to handle missing indexes

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('process_datasheet', '0019_remove_pumpcalculationdata_pump_calculation_data_dest_flow_idx_and_more'),
    ]

    operations = [
        # Conditional DROP (safe if index already removed)
        migrations.RunSQL(
            sql="DROP INDEX IF EXISTS pump_calculation_data_dest_flow_idx;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="DROP INDEX IF EXISTS pump_calculation_data_total_pressure_idx;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        # Conditional RENAME (safe if index doesn't exist or already renamed)
        migrations.RunSQL(
            sql="""DO $$ BEGIN IF EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'pump_calculation_data_tag_no_project_no_idx') THEN ALTER INDEX pump_calculation_data_tag_no_project_no_idx RENAME TO pump_calcul_tag_no_1ac76f_idx; END IF; END $$;""",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="""DO $$ BEGIN IF EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'pump_calculation_data_document_no_revision_idx') THEN ALTER INDEX pump_calculation_data_document_no_revision_idx RENAME TO pump_calcul_documen_2fc886_idx; END IF; END $$;""",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="""DO $$ BEGIN IF EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'pump_calculation_data_status_updated_at_idx') THEN ALTER INDEX pump_calculation_data_status_updated_at_idx RENAME TO pump_calcul_status_8d3b11_idx; END IF; END $$;""",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="""DO $$ BEGIN IF EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'ph_snap_user_proj_idx') THEN ALTER INDEX ph_snap_user_proj_idx RENAME TO process_dat_user_id_bb3a97_idx; END IF; END $$;""",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="""DO $$ BEGIN IF EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'ph_snap_user_idx') THEN ALTER INDEX ph_snap_user_idx RENAME TO process_dat_user_id_4fd13a_idx; END IF; END $$;""",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
