# Generated by Django 5.0 on 2026-08-05 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('process_datasheet', '0020_remove_pumpcalculationdata_pump_calculation_data_dest_flow_idx_and_more'),
    ]

    # Migrations 0019 and 0020 already apply these index changes with
    # idempotent SQL. This final generated migration reconciles state only.
    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
        migrations.RemoveIndex(
            model_name='pumpcalculationdata',
            name='pump_calculation_data_dest_flow_idx',
        ),
        migrations.RemoveIndex(
            model_name='pumpcalculationdata',
            name='pump_calculation_data_total_pressure_idx',
        ),
        migrations.RenameIndex(
            model_name='pumpcalculationdata',
            new_name='pump_calcul_tag_no_1ac76f_idx',
            old_name='pump_calculation_data_tag_no_project_no_idx',
        ),
        migrations.RenameIndex(
            model_name='pumpcalculationdata',
            new_name='pump_calcul_documen_2fc886_idx',
            old_name='pump_calculation_data_document_no_revision_idx',
        ),
        migrations.RenameIndex(
            model_name='pumpcalculationdata',
            new_name='pump_calcul_status_8d3b11_idx',
            old_name='pump_calculation_data_status_updated_at_idx',
        ),
        migrations.RenameIndex(
            model_name='pumphydraulicsnapshot',
            new_name='process_dat_user_id_bb3a97_idx',
            old_name='ph_snap_user_proj_idx',
        ),
        migrations.RenameIndex(
            model_name='pumphydraulicsnapshot',
            new_name='process_dat_user_id_4fd13a_idx',
            old_name='ph_snap_user_idx',
        ),
            ],
        ),
    ]
