# Generated by Django 5.0 on 2026-09-03 05:43

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


def ensure_employee_master_id_is_unique(apps, schema_editor):
    """Repair legacy tables whose UUID id column lost its PK/unique constraint.

    Some long-lived environments have ``hr_employee_master`` recorded as
    migrated even though its ``id`` column was created without the primary-key
    constraint declared by 0001.  PostgreSQL cannot create the workflow foreign
    keys until that target column is unique.
    """
    EmployeeMaster = apps.get_model('hr_core', 'EmployeeMaster')
    table_name = EmployeeMaster._meta.db_table
    quoted_table = schema_editor.quote_name(table_name)
    quoted_id = schema_editor.quote_name('id')

    with schema_editor.connection.cursor() as cursor:
        constraints = schema_editor.connection.introspection.get_constraints(
            cursor, table_name
        )
        if any(
            details.get('unique') and details.get('columns') == ['id']
            for details in constraints.values()
        ):
            return

        cursor.execute(
            f'SELECT {quoted_id} FROM {quoted_table} '
            f'GROUP BY {quoted_id} HAVING COUNT(*) > 1 LIMIT 1'
        )
        duplicate = cursor.fetchone()
        cursor.execute(
            f'SELECT COUNT(*) FROM {quoted_table} WHERE {quoted_id} IS NULL'
        )
        null_count = cursor.fetchone()[0]

    if duplicate or null_count:
        raise RuntimeError(
            'Cannot repair hr_employee_master.id automatically: '
            f'duplicate id={duplicate[0] if duplicate else None!s}, '
            f'null rows={null_count}. Resolve these rows before migrating.'
        )

    constraint_name = schema_editor.quote_name(
        'hr_employee_master_id_unique_repair'
    )
    schema_editor.execute(
        f'ALTER TABLE {quoted_table} ADD CONSTRAINT {constraint_name} '
        f'UNIQUE ({quoted_id})'
    )


def seed_hr_foundation(apps, schema_editor):
    EmployeeMaster = apps.get_model('hr_core', 'EmployeeMaster')
    EmployeeIdentityAlias = apps.get_model('hr_core', 'EmployeeIdentityAlias')
    WorkflowDefinition = apps.get_model('hr_core', 'HRWorkflowDefinition')
    WorkflowStage = apps.get_model('hr_core', 'HRWorkflowStage')

    definition, _ = WorkflowDefinition.objects.update_or_create(
        code='leave_request_v1',
        version=1,
        defaults={
            'name': 'Leave request approval',
            'description': 'Reporting manager review followed by HR final approval.',
            'subject_type': 'payroll.leave_request',
            'is_active': True,
            'configuration': {'status_mapping': {'approved': 'APPROVED', 'rejected': 'REJECTED'}},
        },
    )
    WorkflowStage.objects.update_or_create(
        definition=definition,
        sequence=1,
        defaults={
            'code': 'manager_review',
            'name': 'Reporting manager review',
            'approver_type': 'employee_manager',
            'due_after_hours': 24,
            'escalate_after_hours': 48,
            'escalation_role_code': 'hr_manager',
            'require_comment_on_reject': True,
        },
    )
    WorkflowStage.objects.update_or_create(
        definition=definition,
        sequence=2,
        defaults={
            'code': 'hr_review',
            'name': 'HR final review',
            'approver_type': 'role',
            'approver_value': 'hr_manager',
            'due_after_hours': 24,
            'escalate_after_hours': 48,
            'escalation_role_code': 'hr_admin',
            'require_comment_on_reject': True,
        },
    )

    alias_rows = []
    for employee in EmployeeMaster.objects.all().iterator(chunk_size=500):
        aliases = (
            ('radai', 'uuid', str(employee.id), True),
            ('radai', 'user_id', str(employee.user_id), True),
            ('radai', 'email', employee.email, True),
            ('radai', 'employee_number', employee.employee_number, True),
            ('payroll', 'employee_code', employee.employee_code, False),
            ('timesheet', 'employee_code', employee.emp_code, False),
        )
        for source, identifier_type, value, primary in aliases:
            if not value:
                continue
            normalized = str(value).strip().casefold() if identifier_type == 'email' else ''.join(str(value).upper().split()) if identifier_type in {'employee_number', 'employee_code'} else str(value).strip()
            alias_rows.append(EmployeeIdentityAlias(
                source=source,
                identifier_type=identifier_type,
                normalized_value=normalized,
                employee_id=employee.id,
                value=str(value).strip(),
                is_primary=primary,
            ))
    EmployeeIdentityAlias.objects.bulk_create(
        alias_rows, batch_size=500, ignore_conflicts=True
    )


def remove_seeded_workflow(apps, schema_editor):
    apps.get_model('hr_core', 'HRWorkflowDefinition').objects.filter(
        code='leave_request_v1', version=1
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('hr_core', '0002_employeemaster_engineer_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(
            ensure_employee_master_id_is_unique,
            migrations.RunPython.noop,
        ),
        migrations.CreateModel(
            name='HRWorkflowDefinition',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=80)),
                ('name', models.CharField(max_length=160)),
                ('version', models.PositiveIntegerField(default=1)),
                ('description', models.TextField(blank=True)),
                ('subject_type', models.CharField(help_text='For example: payroll.leave_request', max_length=80)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('configuration', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_workflow_definitions_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hr_workflow_definition',
                'ordering': ['code', '-version'],
            },
        ),
        migrations.CreateModel(
            name='HRWorkflowInstance',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject_type', models.CharField(db_index=True, max_length=80)),
                ('subject_id', models.CharField(db_index=True, max_length=80)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='hr_core.hrworkflowdefinition')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_instances', to='hr_core.employeemaster')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_workflows_requested', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hr_workflow_instance',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HRWorkflowEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(db_index=True, max_length=50)),
                ('stage_code', models.CharField(blank=True, max_length=80)),
                ('note', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_workflow_events', to=settings.AUTH_USER_MODEL)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='hr_core.hrworkflowinstance')),
            ],
            options={
                'db_table': 'hr_workflow_event',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='HRWorkflowStage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=80)),
                ('name', models.CharField(max_length=160)),
                ('sequence', models.PositiveIntegerField()),
                ('approver_type', models.CharField(choices=[('employee_manager', 'Employee Manager'), ('role', 'RBAC Role'), ('user', 'Named User'), ('requester', 'Requester')], max_length=30)),
                ('approver_value', models.CharField(blank=True, help_text='Role code or user ID when required by approver_type.', max_length=160)),
                ('due_after_hours', models.PositiveIntegerField(default=48)),
                ('escalate_after_hours', models.PositiveIntegerField(default=72)),
                ('escalation_role_code', models.CharField(blank=True, max_length=80)),
                ('require_comment_on_reject', models.BooleanField(default=True)),
                ('configuration', models.JSONField(blank=True, default=dict)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='hr_core.hrworkflowdefinition')),
            ],
            options={
                'db_table': 'hr_workflow_stage',
                'ordering': ['definition', 'sequence'],
            },
        ),
        migrations.AddField(
            model_name='hrworkflowinstance',
            name='current_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='active_instances', to='hr_core.hrworkflowstage'),
        ),
        migrations.CreateModel(
            name='HRWorkflowTask',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assigned_role_code', models.CharField(blank=True, db_index=True, max_length=80)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('due_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('escalated_at', models.DateTimeField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_workflow_tasks', to=settings.AUTH_USER_MODEL)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_workflow_tasks_decided', to=settings.AUTH_USER_MODEL)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='hr_core.hrworkflowinstance')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='hr_core.hrworkflowstage')),
            ],
            options={
                'db_table': 'hr_workflow_task',
                'ordering': ['status', 'due_at'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeIdentityAlias',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('radai', 'RADAI'), ('rbac', 'RBAC Profile'), ('payroll', 'Payroll'), ('timesheet', 'Timesheet / Biometric'), ('onboarding', 'Onboarding'), ('external', 'External System')], db_index=True, max_length=30)),
                ('identifier_type', models.CharField(choices=[('uuid', 'Canonical UUID'), ('user_id', 'User ID'), ('email', 'Email'), ('employee_number', 'Employee Number'), ('employee_code', 'Employee Code'), ('account_name', 'Account Name')], db_index=True, max_length=30)),
                ('value', models.CharField(max_length=255)),
                ('normalized_value', models.CharField(db_index=True, max_length=255)),
                ('is_primary', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identity_aliases', to='hr_core.employeemaster')),
            ],
            options={
                'db_table': 'hr_employee_identity_alias',
                'ordering': ['source', 'identifier_type'],
                'indexes': [models.Index(fields=['identifier_type', 'normalized_value'], name='hr_identity_lookup_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='employeeidentityalias',
            constraint=models.UniqueConstraint(fields=('source', 'identifier_type', 'normalized_value'), name='hr_identity_alias_unique'),
        ),
        migrations.AddConstraint(
            model_name='hrworkflowdefinition',
            constraint=models.UniqueConstraint(fields=('code', 'version'), name='hr_workflow_code_version_unique'),
        ),
        migrations.AddConstraint(
            model_name='hrworkflowstage',
            constraint=models.UniqueConstraint(fields=('definition', 'code'), name='hr_workflow_stage_code_unique'),
        ),
        migrations.AddConstraint(
            model_name='hrworkflowstage',
            constraint=models.UniqueConstraint(fields=('definition', 'sequence'), name='hr_workflow_stage_seq_unique'),
        ),
        migrations.AddIndex(
            model_name='hrworkflowinstance',
            index=models.Index(fields=['status', 'current_stage'], name='hr_workflow_queue_idx'),
        ),
        migrations.AddConstraint(
            model_name='hrworkflowinstance',
            constraint=models.UniqueConstraint(fields=('definition', 'subject_type', 'subject_id'), name='hr_workflow_subject_unique'),
        ),
        migrations.AddConstraint(
            model_name='hrworkflowtask',
            constraint=models.UniqueConstraint(fields=('instance', 'stage'), name='hr_workflow_task_stage_unique'),
        ),
        migrations.RunPython(seed_hr_foundation, remove_seeded_workflow),
    ]
