# Generated by Django 5.0 on 2026-09-03 07:13

import django.db.models.deletion
import datetime
import uuid
from django.conf import settings
from django.db import migrations, models


def seed_talent_and_workforce_foundation(apps, schema_editor):
    Definition = apps.get_model('hr_core', 'HRWorkflowDefinition')
    Stage = apps.get_model('hr_core', 'HRWorkflowStage')
    WorkShift = apps.get_model('hr_core', 'WorkShift')

    workflow_specs = [
        (
            'overtime_request_v1', 'Overtime approval', 'hr.overtime_request',
            [
                ('manager_review', 'Reporting manager review', 'employee_manager', '', 'hr_manager', 24, 48),
                ('hr_review', 'HR final review', 'role', 'hr_manager', 'hr_admin', 24, 48),
            ],
        ),
        (
            'promotion_case_v1', 'Promotion approval', 'hr.promotion_case',
            [
                ('manager_endorsement', 'Manager endorsement', 'employee_manager', '', 'hr_manager', 72, 120),
                ('hr_approval', 'HR approval', 'role', 'hr_admin', 'super_admin', 72, 120),
            ],
        ),
    ]
    for code, name, subject_type, stages in workflow_specs:
        definition, _ = Definition.objects.update_or_create(
            code=code, version=1,
            defaults={'name': name, 'subject_type': subject_type, 'is_active': True},
        )
        for sequence, values in enumerate(stages, 1):
            stage_code, stage_name, approver_type, approver_value, escalation, due, escalate = values
            Stage.objects.update_or_create(
                definition=definition, sequence=sequence,
                defaults={
                    'code': stage_code, 'name': stage_name,
                    'approver_type': approver_type, 'approver_value': approver_value,
                    'escalation_role_code': escalation, 'due_after_hours': due,
                    'escalate_after_hours': escalate, 'require_comment_on_reject': True,
                },
            )

    shifts = [
        ('day', 'Day Shift', datetime.time(8, 0), datetime.time(17, 0), 60, False, '#2563EB'),
        ('night', 'Night Shift', datetime.time(20, 0), datetime.time(5, 0), 60, True, '#7C3AED'),
        ('flex', 'Flexible Shift', datetime.time(9, 0), datetime.time(18, 0), 60, False, '#059669'),
    ]
    for code, name, start, end, break_minutes, crosses_midnight, color in shifts:
        WorkShift.objects.update_or_create(
            code=code,
            defaults={
                'name': name, 'start_time': start, 'end_time': end,
                'break_minutes': break_minutes, 'crosses_midnight': crosses_midnight,
                'color': color, 'is_active': True,
            },
        )


def remove_unused_seeded_workflows(apps, schema_editor):
    Definition = apps.get_model('hr_core', 'HRWorkflowDefinition')
    Definition.objects.filter(
        code__in=['overtime_request_v1', 'promotion_case_v1'], version=1,
        instances__isnull=True,
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('hr_core', '0003_hrworkflowdefinition_hrworkflowinstance_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkShift',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('break_minutes', models.PositiveSmallIntegerField(default=60)),
                ('crosses_midnight', models.BooleanField(default=False)),
                ('color', models.CharField(default='#2563EB', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('configuration', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'hr_work_shift',
                'ordering': ['start_time', 'code'],
            },
        ),
        migrations.CreateModel(
            name='DevelopmentPlan',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=220)),
                ('career_aspiration', models.TextField(blank=True)),
                ('target_role', models.CharField(blank=True, max_length=160)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20)),
                ('start_date', models.DateField()),
                ('target_date', models.DateField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='development_plans', to='hr_core.employeemaster')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hr_development_plan',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='DevelopmentAction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('training', 'Training'), ('mentoring', 'Mentoring'), ('assignment', 'Stretch Assignment'), ('certification', 'Certification'), ('coaching', 'Coaching')], max_length=20)),
                ('title', models.CharField(max_length=220)),
                ('description', models.TextField(blank=True)),
                ('provider', models.CharField(blank=True, max_length=160)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', max_length=20)),
                ('completion_evidence', models.JSONField(blank=True, default=list)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='hr_core.developmentplan')),
            ],
            options={
                'db_table': 'hr_development_action',
                'ordering': ['due_date', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceCycle',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('self_review_due', models.DateField(blank=True, null=True)),
                ('manager_review_due', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('calibration', 'Calibration'), ('closed', 'Closed')], db_index=True, default='draft', max_length=20)),
                ('goal_weight', models.DecimalField(decimal_places=2, default=60, max_digits=5)),
                ('competency_weight', models.DecimalField(decimal_places=2, default=40, max_digits=5)),
                ('configuration', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hr_performance_cycle',
                'ordering': ['-start_date'],
            },
        ),
        migrations.AddField(
            model_name='developmentplan',
            name='cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='development_plans', to='hr_core.performancecycle'),
        ),
        migrations.CreateModel(
            name='PerformanceGoal',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('goal_type', models.CharField(choices=[('individual', 'Individual'), ('team', 'Team'), ('kpi', 'KPI'), ('development', 'Development')], default='individual', max_length=20)),
                ('title', models.CharField(max_length=220)),
                ('description', models.TextField(blank=True)),
                ('metric_name', models.CharField(blank=True, max_length=160)),
                ('target_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('current_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('unit', models.CharField(blank=True, max_length=40)),
                ('weight', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20)),
                ('success_criteria', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performance_goals_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performance_goals_created', to=settings.AUTH_USER_MODEL)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='hr_core.performancecycle')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_goals', to='hr_core.employeemaster')),
                ('parent_goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aligned_goals', to='hr_core.performancegoal')),
            ],
            options={
                'db_table': 'hr_performance_goal',
                'ordering': ['cycle', 'employee', 'due_date'],
            },
        ),
        migrations.CreateModel(
            name='GoalCheckIn',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('progress', models.PositiveSmallIntegerField()),
                ('current_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('note', models.TextField(blank=True)),
                ('evidence', models.JSONField(blank=True, default=list)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_ins', to='hr_core.performancegoal')),
            ],
            options={
                'db_table': 'hr_goal_check_in',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContinuousFeedback',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feedback_type', models.CharField(choices=[('recognition', 'Recognition'), ('coaching', 'Coaching'), ('general', 'General Feedback')], default='general', max_length=20)),
                ('visibility', models.CharField(choices=[('employee', 'Employee and Management'), ('management', 'Management Only'), ('private', 'Author Only')], default='employee', max_length=20)),
                ('content', models.TextField()),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_feedback_given', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='continuous_feedback', to='hr_core.employeemaster')),
                ('related_goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback', to='hr_core.performancegoal')),
            ],
            options={
                'db_table': 'hr_continuous_feedback',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceReview',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('review_type', models.CharField(choices=[('self', 'Self Assessment'), ('manager', 'Manager Review'), ('peer', 'Peer Review'), ('direct_report', 'Direct Report'), ('calibration', 'Calibration')], max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('acknowledged', 'Acknowledged'), ('reopened', 'Reopened')], db_index=True, default='draft', max_length=20)),
                ('goal_score', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('competency_score', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('overall_score', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('ratings', models.JSONField(blank=True, default=dict)),
                ('key_achievements', models.TextField(blank=True)),
                ('strengths', models.TextField(blank=True)),
                ('areas_for_improvement', models.TextField(blank=True)),
                ('goals_next_period', models.TextField(blank=True)),
                ('overall_comments', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='hr_core.performancecycle')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_reviews', to='hr_core.employeemaster')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_reviews_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hr_performance_review',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromotionCase',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_title', models.CharField(max_length=160)),
                ('proposed_title', models.CharField(max_length=160)),
                ('proposed_grade', models.CharField(blank=True, max_length=50)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('justification', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_cases', to='hr_core.employeemaster')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('workflow_instance', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotion_case', to='hr_core.hrworkflowinstance')),
            ],
            options={
                'db_table': 'hr_promotion_case',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShiftAssignment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('worked', 'Worked'), ('absent', 'Absent'), ('leave', 'Leave'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_assignments', to='hr_core.employeemaster')),
            ],
            options={
                'db_table': 'hr_shift_assignment',
                'ordering': ['date', 'shift__start_time'],
            },
        ),
        migrations.CreateModel(
            name='OvertimeRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('work_date', models.DateField(db_index=True)),
                ('requested_hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('approved_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overtime_requests', to='hr_core.employeemaster')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overtime_requests_created', to=settings.AUTH_USER_MODEL)),
                ('workflow_instance', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overtime_request', to='hr_core.hrworkflowinstance')),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overtime_requests', to='hr_core.shiftassignment')),
            ],
            options={
                'db_table': 'hr_overtime_request',
                'ordering': ['-work_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShiftRoster',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=180)),
                ('department', models.CharField(blank=True, max_length=120)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('locked', 'Locked'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hr_shift_roster',
                'ordering': ['-start_date'],
            },
        ),
        migrations.AddField(
            model_name='shiftassignment',
            name='roster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='hr_core.shiftroster'),
        ),
        migrations.CreateModel(
            name='SuccessionPlan',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role_title', models.CharField(max_length=180)),
                ('department', models.CharField(blank=True, max_length=120)),
                ('criticality', models.CharField(choices=[('standard', 'Standard'), ('critical', 'Critical')], default='standard', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('closed', 'Closed')], default='draft', max_length=20)),
                ('risk_notes', models.TextField(blank=True)),
                ('incumbent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='succession_plans_as_incumbent', to='hr_core.employeemaster')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hr_succession_plan',
                'ordering': ['department', 'role_title'],
            },
        ),
        migrations.CreateModel(
            name='SuccessionCandidate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('readiness', models.CharField(choices=[('ready_now', 'Ready Now'), ('one_year', 'Ready in 1 Year'), ('two_plus_years', 'Ready in 2+ Years'), ('not_applicable', 'Not Applicable')], max_length=30)),
                ('rank', models.PositiveSmallIntegerField(default=1)),
                ('development_gaps', models.TextField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='succession_candidates', to='hr_core.employeemaster')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='hr_core.successionplan')),
            ],
            options={
                'db_table': 'hr_succession_candidate',
                'ordering': ['rank'],
            },
        ),
        migrations.CreateModel(
            name='TalentAssessment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('performance', models.PositiveSmallIntegerField(choices=[(1, 'Low'), (2, 'Moderate'), (3, 'High')])),
                ('potential', models.PositiveSmallIntegerField(choices=[(1, 'Low'), (2, 'Moderate'), (3, 'High')])),
                ('retention_risk', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=20)),
                ('readiness', models.CharField(choices=[('ready_now', 'Ready Now'), ('one_year', 'Ready in 1 Year'), ('two_plus_years', 'Ready in 2+ Years'), ('not_applicable', 'Not Applicable')], default='not_applicable', max_length=30)),
                ('critical_role', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('assessed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talent_assessments', to='hr_core.performancecycle')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talent_assessments', to='hr_core.employeemaster')),
            ],
            options={
                'db_table': 'hr_talent_assessment',
                'ordering': ['cycle', 'employee'],
            },
        ),
        migrations.AddField(
            model_name='shiftassignment',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='hr_core.workshift'),
        ),
        migrations.AddConstraint(
            model_name='performancecycle',
            constraint=models.UniqueConstraint(fields=('name', 'start_date'), name='hr_perf_cycle_name_start_unique'),
        ),
        migrations.AddIndex(
            model_name='performancegoal',
            index=models.Index(fields=['employee', 'cycle', 'status'], name='hr_goal_employee_cycle_idx'),
        ),
        migrations.AddIndex(
            model_name='performancereview',
            index=models.Index(fields=['employee', 'cycle', 'review_type'], name='hr_review_employee_cycle_idx'),
        ),
        migrations.AddConstraint(
            model_name='performancereview',
            constraint=models.UniqueConstraint(fields=('cycle', 'employee', 'reviewer', 'review_type'), name='hr_review_rater_unique'),
        ),
        migrations.AddIndex(
            model_name='overtimerequest',
            index=models.Index(fields=['status', 'work_date'], name='hr_overtime_queue_idx'),
        ),
        migrations.AddConstraint(
            model_name='overtimerequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'approved'])), fields=('employee', 'work_date'), name='hr_overtime_active_day_unique'),
        ),
        migrations.AddConstraint(
            model_name='successioncandidate',
            constraint=models.UniqueConstraint(fields=('plan', 'employee'), name='hr_successor_plan_employee_unique'),
        ),
        migrations.AddConstraint(
            model_name='talentassessment',
            constraint=models.UniqueConstraint(fields=('cycle', 'employee'), name='hr_talent_cycle_employee_unique'),
        ),
        migrations.AddIndex(
            model_name='shiftassignment',
            index=models.Index(fields=['employee', 'date', 'status'], name='hr_shift_employee_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='shiftassignment',
            constraint=models.UniqueConstraint(fields=('employee', 'date'), name='hr_shift_employee_date_unique'),
        ),
        migrations.RunPython(seed_talent_and_workforce_foundation, remove_unused_seeded_workflows),
    ]
