# Generated by Django 5.0 on 2026-09-03 08:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def seed_service_request_workflows(apps, schema_editor):
    Definition = apps.get_model('hr_core', 'HRWorkflowDefinition')
    Stage = apps.get_model('hr_core', 'HRWorkflowStage')
    specifications = {
        'expense': [('manager_review', 'Manager review', 'employee_manager', ''), ('finance_review', 'Finance and HR review', 'role', 'hr_admin')],
        'travel': [('manager_review', 'Manager review', 'employee_manager', ''), ('travel_review', 'Travel and HR review', 'role', 'hr_admin')],
        'asset': [('manager_review', 'Manager review', 'employee_manager', ''), ('asset_fulfilment', 'Asset team review', 'role', 'hr_admin')],
        'hr_helpdesk': [('hr_triage', 'HR helpdesk triage', 'role', 'hr_admin')],
    }
    for request_type, stages in specifications.items():
        definition, _ = Definition.objects.update_or_create(
            code=f'{request_type}_request_v1', version=1,
            defaults={'name': f'{request_type.replace("_", " ").title()} request',
                      'subject_type': f'hr.{request_type}_request', 'is_active': True},
        )
        for sequence, (code, name, approver_type, approver_value) in enumerate(stages, 1):
            Stage.objects.update_or_create(
                definition=definition, sequence=sequence,
                defaults={'code': code, 'name': name, 'approver_type': approver_type,
                          'approver_value': approver_value, 'due_after_hours': 48,
                          'escalate_after_hours': 72, 'escalation_role_code': 'hr_admin',
                          'require_comment_on_reject': True},
            )


def remove_unused_service_request_workflows(apps, schema_editor):
    Definition = apps.get_model('hr_core', 'HRWorkflowDefinition')
    Definition.objects.filter(
        code__in=[f'{kind}_request_v1' for kind in ['expense', 'travel', 'asset', 'hr_helpdesk']],
        version=1, instances__isnull=True,
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('hr_core', '0004_workshift_developmentplan_developmentaction_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeServiceRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_number', models.CharField(blank=True, db_index=True, max_length=32, unique=True)),
                ('request_type', models.CharField(choices=[('expense', 'Expense Reimbursement'), ('travel', 'Business Travel'), ('asset', 'Asset Request'), ('hr_helpdesk', 'HR Helpdesk')], db_index=True, max_length=24)),
                ('title', models.CharField(max_length=220)),
                ('description', models.TextField()),
                ('category', models.CharField(blank=True, max_length=100)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=16)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('currency', models.CharField(default='AED', max_length=3)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('destination', models.CharField(blank=True, max_length=180)),
                ('cost_center', models.CharField(blank=True, max_length=80)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('in_progress', 'In Progress'), ('fulfilled', 'Fulfilled'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=24)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('resolution', models.TextField(blank=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_service_requests_assigned', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to='hr_core.employeemaster')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_service_requests', to=settings.AUTH_USER_MODEL)),
                ('workflow_instance', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_request', to='hr_core.hrworkflowinstance')),
            ],
            options={
                'db_table': 'hr_employee_service_request',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeServiceRequestComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('is_internal', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='hr_core.employeeservicerequest')),
            ],
            options={
                'db_table': 'hr_employee_service_request_comment',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='employeeservicerequest',
            index=models.Index(fields=['employee', 'request_type', 'status'], name='hr_service_employee_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeservicerequest',
            index=models.Index(fields=['status', 'priority'], name='hr_service_queue_idx'),
        ),
        migrations.RunPython(seed_service_request_workflows, remove_unused_service_request_workflows),
    ]
