# Generated by Django 5.0 on 2026-09-04 05:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_core', '0005_employeeservicerequest_employeeservicerequestcomment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HRAssistantInteraction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('citations', models.JSONField(blank=True, default=list)),
                ('model_name', models.CharField(default='extractive-grounded', max_length=80)),
                ('grounded', models.BooleanField(default=False)),
                ('refusal_reason', models.CharField(blank=True, max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant_interactions', to='hr_core.employeemaster')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_assistant_interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hr_assistant_interaction',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HRAuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(db_index=True, max_length=100)),
                ('object_type', models.CharField(blank=True, db_index=True, max_length=120)),
                ('object_id', models.CharField(blank=True, db_index=True, max_length=120)),
                ('outcome', models.CharField(db_index=True, default='success', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('previous_hash', models.CharField(blank=True, max_length=64)),
                ('event_hash', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='hr_core.employeemaster')),
            ],
            options={
                'db_table': 'hr_audit_event',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HRPolicyDocument',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=240)),
                ('category', models.CharField(db_index=True, max_length=100)),
                ('jurisdiction', models.CharField(blank=True, db_index=True, max_length=100)),
                ('version', models.CharField(default='1.0', max_length=40)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('retired', 'Retired')], db_index=True, default='draft', max_length=16)),
                ('visibility', models.CharField(choices=[('employees', 'All Employees'), ('managers', 'Managers and HR'), ('hr', 'HR Only')], db_index=True, default='employees', max_length=16)),
                ('allowed_role_codes', models.JSONField(blank=True, default=list)),
                ('content', models.TextField()),
                ('source_url', models.URLField(blank=True, max_length=1000)),
                ('sharepoint_item_id', models.CharField(blank=True, db_index=True, max_length=220)),
                ('checksum', models.CharField(blank=True, db_index=True, max_length=64)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('review_date', models.DateField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_hr_policies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hr_policy_document',
                'ordering': ['category', 'title', '-version'],
            },
        ),
        migrations.CreateModel(
            name='HRPrivacyRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_number', models.CharField(blank=True, db_index=True, max_length=32, unique=True)),
                ('request_type', models.CharField(choices=[('access', 'Access'), ('correction', 'Correction'), ('deletion', 'Deletion'), ('restriction', 'Restriction'), ('export', 'Portable Export')], max_length=20)),
                ('details', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('verified', 'Identity Verified'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('rejected', 'Rejected')], db_index=True, default='submitted', max_length=20)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('resolution', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_hr_privacy_requests', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='privacy_requests', to='hr_core.employeemaster')),
            ],
            options={
                'db_table': 'hr_privacy_request',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HRRetentionPolicy',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_category', models.CharField(max_length=100, unique=True)),
                ('legal_basis', models.CharField(max_length=240)),
                ('retention_days', models.PositiveIntegerField()),
                ('disposition_action', models.CharField(choices=[('review', 'Review'), ('anonymize', 'Anonymize'), ('delete', 'Delete')], default='review', max_length=16)),
                ('legal_hold', models.BooleanField(default=False)),
                ('enabled', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hr_retention_policy',
                'ordering': ['data_category'],
            },
        ),
        migrations.CreateModel(
            name='MicrosoftGraphConnection',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Microsoft 365', max_length=120)),
                ('tenant_id', models.CharField(max_length=100)),
                ('client_id', models.CharField(max_length=100)),
                ('enabled', models.BooleanField(db_index=True, default=False)),
                ('entra_sync_enabled', models.BooleanField(default=True)),
                ('outlook_enabled', models.BooleanField(default=False)),
                ('teams_enabled', models.BooleanField(default=False)),
                ('sharepoint_enabled', models.BooleanField(default=False)),
                ('sharepoint_site_id', models.CharField(blank=True, max_length=220)),
                ('sharepoint_drive_id', models.CharField(blank=True, max_length=220)),
                ('sharepoint_policy_folder', models.CharField(default='HR Policies', max_length=500)),
                ('teams_app_id', models.CharField(blank=True, max_length=100)),
                ('default_team_id', models.CharField(blank=True, max_length=100)),
                ('mail_sender', models.EmailField(blank=True, max_length=254)),
                ('last_health_check_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_status', models.CharField(default='not_configured', max_length=24)),
                ('last_error', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hr_microsoft_graph_connection',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MicrosoftGraphUserLink',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entra_object_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('user_principal_name', models.EmailField(blank=True, db_index=True, max_length=254)),
                ('account_enabled', models.BooleanField(default=True)),
                ('raw_profile', models.JSONField(blank=True, default=dict)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='microsoft_graph_link', to='hr_core.employeemaster')),
            ],
            options={
                'db_table': 'hr_microsoft_graph_user_link',
            },
        ),
        migrations.CreateModel(
            name='HRConsentRecord',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purpose', models.CharField(db_index=True, max_length=120)),
                ('policy_version', models.CharField(max_length=40)),
                ('status', models.CharField(choices=[('granted', 'Granted'), ('withdrawn', 'Withdrawn')], default='granted', max_length=16)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('granted_at', models.DateTimeField(blank=True, null=True)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='hr_core.employeemaster')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hr_consent_record',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['employee', 'purpose', 'status'], name='hr_consent_employee_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='hrpolicydocument',
            constraint=models.UniqueConstraint(fields=('title', 'version', 'jurisdiction'), name='hr_policy_title_version_jurisdiction_unique'),
        ),
    ]
