# Generated by Django 5.0 on 2026-09-04 05:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_core', '0006_hrassistantinteraction_hrauditevent_hrpolicydocument_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemaster',
            name='email',
            field=models.EmailField(blank=True, db_index=True, help_text='Employee email; optional for historical employees without an account', max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='employeemaster',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Optional authentication account; historical employees and contractors may not have one', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_master', to=settings.AUTH_USER_MODEL),
        ),
    ]
