# Generated by Django 5.0 on 2026-09-04 06:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_core', '0007_alter_employeemaster_email_alter_employeemaster_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegacyEmployeeArchive',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_table', models.CharField(db_index=True, max_length=120)),
                ('source_pk', models.CharField(max_length=120)),
                ('payload', models.JSONField(default=dict)),
                ('retired_at', models.DateTimeField(auto_now_add=True)),
                ('canonical_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_archives', to='hr_core.employeemaster')),
            ],
            options={
                'db_table': 'hr_legacy_employee_archive',
                'ordering': ['source_table', 'source_pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='legacyemployeearchive',
            constraint=models.UniqueConstraint(fields=('source_table', 'source_pk'), name='hr_legacy_archive_source_unique'),
        ),
    ]
