# Generated by Django 5.0 on 2026-09-10 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_core', '0012_overtimeconversion_overtimeconversionallocation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='overtimeconversion',
            name='basic_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='overtimeconversion',
            name='multiplier',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='overtimeconversion',
            name='target_month',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='overtimeconversion',
            name='target_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='overtimerequest',
            name='compensation_type',
            field=models.CharField(blank=True, choices=[('cash', 'Encashment'), ('day_off', 'Off day')], default='', max_length=12),
        ),
    ]
