# Generated by Django 5.0 on 2026-09-10 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_core', '0013_overtimeconversion_basic_salary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='overtimerequest',
            name='day_entries',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
