# Generated by Django 5.0 on 2026-07-01 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('non_teff_metadata', '0003_project_model'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='nonteffbatchitem',
            new_name='non_teff_me_batch_i_2cd8f0_idx',
            old_name='non_teff_ba_batch_i_idx',
        ),
        migrations.RenameIndex(
            model_name='nonteffproject',
            new_name='non_teff_me_status_7815c8_idx',
            old_name='ntm_proj_status_upd_idx',
        ),
        migrations.RenameIndex(
            model_name='nonteffproject',
            new_name='non_teff_me_created_06767f_idx',
            old_name='ntm_proj_creator_upd_idx',
        ),
    ]
