# Generated by Django 5.0 on 2026-08-05 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('non_teff_metadata', '0005_rename_non_teff_ba_batch_i_idx_non_teff_me_batch_i_2cd8f0_idx_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
        migrations.RenameIndex(
            model_name='nonteffbatchitem',
            new_name='non_teff_me_batch_i_2cd8f0_idx',
            old_name='non_teff_ba_batch_i_idx',
        ),
        migrations.RenameIndex(
            model_name='nonteffproject',
            new_name='non_teff_me_status_7815c8_idx',
            old_name='ntm_proj_status_upd_idx',
        ),
        migrations.RenameIndex(
            model_name='nonteffproject',
            new_name='non_teff_me_created_06767f_idx',
            old_name='ntm_proj_creator_upd_idx',
        ),
            ],
        ),
    ]
