# Generated by Django 5.0 on 2026-09-15 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_organizer', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='project',
            new_name='project_org_status_61b226_idx',
            old_name='project_org_status_98d3a1_idx',
        ),
        migrations.RenameIndex(
            model_name='project',
            new_name='project_org_created_0989bd_idx',
            old_name='project_org_created_5e1c2b_idx',
        ),
        migrations.RenameIndex(
            model_name='projectactivity',
            new_name='project_org_project_4b39f3_idx',
            old_name='project_org_project_7a4f6d_idx',
        ),
        migrations.RenameIndex(
            model_name='projectactivity',
            new_name='project_org_tool_co_c75466_idx',
            old_name='project_org_toolcod_c9b8e2_idx',
        ),
    ]
