# Generated by Django 5.0 on 2026-01-20 13:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseRequisition',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pr_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(max_length=50)),
                ('department', models.CharField(blank=True, max_length=200)),
                ('project', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('converted', 'Converted to PO')], default='draft', max_length=20)),
                ('priority', models.CharField(choices=[('urgent', 'Urgent'), ('high', 'High'), ('normal', 'Normal'), ('low', 'Low')], default='normal', max_length=20)),
                ('required_date', models.DateField(blank=True, null=True)),
                ('estimated_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('items', models.JSONField(blank=True, default=list)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prs_approved', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prs_requested', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'procurement_requisitions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('po_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent to Vendor'), ('acknowledged', 'Acknowledged by Vendor'), ('in_progress', 'In Progress'), ('partially_received', 'Partially Received'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('category', models.CharField(max_length=50)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('items', models.JSONField(blank=True, default=list)),
                ('po_date', models.DateField(auto_now_add=True)),
                ('expected_delivery', models.DateField(blank=True, null=True)),
                ('actual_delivery', models.DateField(blank=True, null=True)),
                ('terms_and_conditions', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_created', to=settings.AUTH_USER_MODEL)),
                ('pr_reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='procurement.purchaserequisition')),
            ],
            options={
                'db_table': 'procurement_orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('receipt_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('receipt_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Inspection'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('partial', 'Partially Accepted')], default='pending', max_length=20)),
                ('items_received', models.JSONField(blank=True, default=list)),
                ('quality_check_passed', models.BooleanField(default=True)),
                ('inspection_notes', models.TextField(blank=True)),
                ('delivery_note_number', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='procurement.purchaseorder')),
                ('received_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'procurement_receipts',
                'ordering': ['-receipt_date'],
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vendor_code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=300)),
                ('contact_person', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('address', models.TextField(blank=True)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('tax_id', models.CharField(blank=True, max_length=100)),
                ('payment_terms', models.CharField(blank=True, max_length=200)),
                ('credit_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending Approval'), ('blacklisted', 'Blacklisted')], default='pending', max_length=20)),
                ('rating', models.IntegerField(blank=True, choices=[(5, 'Excellent'), (4, 'Good'), (3, 'Average'), (2, 'Below Average'), (1, 'Poor')], null=True)),
                ('performance_notes', models.TextField(blank=True)),
                ('categories', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True)),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendors_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'procurement_vendors',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='procurement.vendor'),
        ),
        migrations.AddIndex(
            model_name='purchaserequisition',
            index=models.Index(fields=['pr_number'], name='procurement_pr_numb_b724b1_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaserequisition',
            index=models.Index(fields=['status', 'priority'], name='procurement_status_89e183_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaserequisition',
            index=models.Index(fields=['requested_by', 'status'], name='procurement_request_fee77a_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaserequisition',
            index=models.Index(fields=['-created_at'], name='procurement_created_a4ba8c_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['receipt_number'], name='procurement_receipt_23e677_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['purchase_order', 'status'], name='procurement_purchas_22da00_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['-receipt_date'], name='procurement_receipt_2eead0_idx'),
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['vendor_code'], name='procurement_vendor__42483d_idx'),
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['status'], name='procurement_status_ecde4f_idx'),
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['rating'], name='procurement_rating_4d65af_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['po_number'], name='procurement_po_numb_636d2a_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['vendor', 'status'], name='procurement_vendor__ccc0a9_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['status'], name='procurement_status_f9129b_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['-created_at'], name='procurement_created_ac83e9_idx'),
        ),
    ]
