# Generated by Django 5.0 on 2026-01-22 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0002_purchaseorder_applicable_standards_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='icv_certificate',
            field=models.CharField(blank=True, help_text='ICV Certificate Number', max_length=100),
        ),
        migrations.AddField(
            model_name='vendor',
            name='icv_expiry_date',
            field=models.DateField(blank=True, help_text='ICV Certificate Expiry Date', null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='icv_issuing_authority',
            field=models.CharField(blank=True, default='ADDED', help_text='ICV Issuing Authority (e.g., ADDED)', max_length=200),
        ),
        migrations.AddField(
            model_name='vendor',
            name='icv_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='In-Country Value percentage (0-100)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='is_icv_certified',
            field=models.BooleanField(default=False, help_text='ICV Certification Status'),
        ),
    ]
