# Generated by Django 5.0 on 2026-01-23 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0003_vendor_icv_certificate_vendor_icv_expiry_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequisition',
            name='requisition_type',
            field=models.CharField(choices=[('general', 'General'), ('project', 'Project')], default='general', max_length=20),
        ),
    ]
