# Generated by Django 5.0 on 2026-07-09 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0008_rename_procurement_budget_idx1_procurement_project_cf65fc_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaserequisition',
            name='description',
        ),
        migrations.AddField(
            model_name='purchaserequisition',
            name='currency',
            field=models.CharField(default='USD', help_text='Currency code (USD, AED, EUR, etc.)', max_length=3),
        ),
        migrations.AddField(
            model_name='purchaserequisition',
            name='description_reason',
            field=models.TextField(blank=True, help_text='Description and Reason for Purchase'),
        ),
        migrations.AddField(
            model_name='purchaserequisition',
            name='form_reference',
            field=models.CharField(default='RAD-OM-PRC-0001 FRM -1 Rev 0', help_text='Form template reference', max_length=100),
        ),
        migrations.AddField(
            model_name='purchaserequisition',
            name='issued_by',
            field=models.ForeignKey(help_text='Person who issued the PR', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prs_issued', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaserequisition',
            name='issued_date',
            field=models.DateField(blank=True, help_text='Date when PR was issued', null=True),
        ),
        migrations.AddField(
            model_name='purchaserequisition',
            name='net_total_excl_vat',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Net Total, excluding VAT', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='purchaserequisition',
            name='page_number',
            field=models.CharField(default='Page 1 of 1', help_text='Page number', max_length=20),
        ),
        migrations.AddField(
            model_name='purchaserequisition',
            name='pm_approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('not_approved', 'Not Approved')], default='pending', help_text='PM Approval Status', max_length=20),
        ),
        migrations.AddField(
            model_name='purchaserequisition',
            name='pm_approved_at',
            field=models.DateTimeField(blank=True, help_text='PM approval timestamp', null=True),
        ),
        migrations.AddField(
            model_name='purchaserequisition',
            name='pm_name',
            field=models.ForeignKey(blank=True, help_text='Project Manager name', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prs_pm_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaserequisition',
            name='pm_signature',
            field=models.CharField(blank=True, help_text='PM signature (base64 or S3 URL)', max_length=500),
        ),
        migrations.AddField(
            model_name='purchaserequisition',
            name='po_number_reference',
            field=models.CharField(blank=True, help_text='Related PO number (e.g., RAD-PRJ-PUR-0014_JAN2025)', max_length=100),
        ),
        migrations.AddField(
            model_name='purchaserequisition',
            name='preferred_supplier_if_any',
            field=models.CharField(blank=True, help_text='Preferred Supplier (if any)', max_length=300),
        ),
        migrations.AddField(
            model_name='purchaserequisition',
            name='price_description',
            field=models.TextField(blank=True, help_text='Item/Service description for pricing'),
        ),
        migrations.AddField(
            model_name='purchaserequisition',
            name='price_remarks',
            field=models.TextField(blank=True, help_text='Pricing remarks (e.g., Included in HSE budget)'),
        ),
        migrations.AddField(
            model_name='purchaserequisition',
            name='product_service',
            field=models.TextField(blank=True, help_text='Product or Service being purchased'),
        ),
        migrations.AddField(
            model_name='purchaserequisition',
            name='project_department',
            field=models.TextField(blank=True, help_text='Project name and department details'),
        ),
        migrations.AddField(
            model_name='purchaserequisition',
            name='special_notes',
            field=models.TextField(blank=True, help_text='Special Notes (if any)'),
        ),
        migrations.AddField(
            model_name='purchaserequisition',
            name='supplier_business_id',
            field=models.CharField(blank=True, help_text='Supplier Business ID No (e.g., CN-3362215)', max_length=100),
        ),
        migrations.AddField(
            model_name='purchaserequisition',
            name='supplier_name',
            field=models.CharField(blank=True, help_text='Preferred supplier name (e.g., Velimor Middle East Consultancy LLC)', max_length=300),
        ),
        migrations.AddField(
            model_name='purchaserequisition',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total Price (e.g., USD 4,000.00)', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='purchaserequisition',
            name='vp_op_approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('not_approved', 'Not Approved')], default='pending', help_text='VP Approval Status', max_length=20),
        ),
        migrations.AddField(
            model_name='purchaserequisition',
            name='vp_op_approved_at',
            field=models.DateTimeField(blank=True, help_text='VP approval timestamp', null=True),
        ),
        migrations.AddField(
            model_name='purchaserequisition',
            name='vp_op_name',
            field=models.ForeignKey(blank=True, help_text='VP Operations name', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prs_vp_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaserequisition',
            name='vp_op_signature',
            field=models.CharField(blank=True, help_text='VP signature (base64 or S3 URL)', max_length=500),
        ),
        migrations.AlterField(
            model_name='purchaserequisition',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prs_approved_legacy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='purchaserequisition',
            name='attachments',
            field=models.JSONField(blank=True, default=list, help_text='List of S3 file URLs'),
        ),
        migrations.AlterField(
            model_name='purchaserequisition',
            name='category',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='purchaserequisition',
            name='pr_number',
            field=models.CharField(db_index=True, help_text='Auto-generated PR No (e.g., RAD-PRJ-PR-0021_2025)', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='purchaserequisition',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prs_requested_legacy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='purchaserequisition',
            name='requisition_type',
            field=models.CharField(choices=[('general', 'General'), ('project', 'Project')], default='project', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchaserequisition',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('pm_approved', 'PM Approved'), ('vp_approved', 'VP Approved'), ('fully_approved', 'Fully Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('converted', 'Converted to PO')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchaserequisition',
            name='title',
            field=models.CharField(blank=True, help_text='Short title (auto-generated from product_service)', max_length=300),
        ),
    ]
