# Generated by Django 5.0 on 2026-07-09 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0009_add_purchase_requisition_template_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='approval_signature',
            field=models.CharField(blank=True, help_text='Digital signature (base64 or S3 URL)', max_length=500),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='approval_stamp',
            field=models.CharField(blank=True, help_text='Company stamp image (S3 URL)', max_length=500),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='approved_by_name',
            field=models.CharField(blank=True, help_text='Approver name (soft-coded string, e.g., Jarmo Suominen)', max_length=300),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='approved_by_title',
            field=models.CharField(blank=True, help_text='Approver title (e.g., Senior VP, Middle East, CEO)', max_length=300),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='approved_date',
            field=models.DateField(blank=True, help_text='Date when PO was approved', null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='buyer_reference_pe',
            field=models.CharField(blank=True, help_text='Procurement Engineer (e.g., Ms.Sukanya Ravichandran)', max_length=300),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='buyer_reference_pm',
            field=models.CharField(blank=True, help_text='Procurement Manager (e.g., Ms.Richa Thomas)', max_length=300),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='company_agreement_no',
            field=models.CharField(blank=True, help_text='Company agreement number (e.g., 4700024202)', max_length=100),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='company_fax',
            field=models.CharField(blank=True, help_text='Company fax number', max_length=50),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='confirmation_date',
            field=models.DateField(blank=True, help_text='Date vendor confirmed the order', null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='contact_persons',
            field=models.JSONField(blank=True, default=dict, help_text='Contact persons by role'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='contractor',
            field=models.CharField(blank=True, help_text='Main contractor (e.g., REJLERS INTERNATIONAL ENGINEERING SOLUTIONS AB)', max_length=300),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='end_client',
            field=models.CharField(blank=True, help_text='End client name (e.g., ADNOC Gas)', max_length=300),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='form_note',
            field=models.CharField(default='(PO no. to be used in all documents)', help_text='Form usage note', max_length=200),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='invoicing_attn',
            field=models.CharField(blank=True, help_text='Invoice recipient (e.g., Attn. Mr. Aneef Thadikkarantavida)', max_length=300),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='invoicing_emails',
            field=models.JSONField(blank=True, default=list, help_text='Email addresses for invoice submission'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='marking',
            field=models.CharField(blank=True, help_text='Shipment marking (e.g., RAD-PRJ-PUR-0014)', max_length=100),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='payment_mode',
            field=models.CharField(blank=True, default='Bank Transfer', help_text='Payment method (Bank Transfer, LC, etc.)', max_length=100),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='performance_requirements',
            field=models.TextField(blank=True, help_text='Performance of services requirements'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='quote_ref',
            field=models.CharField(blank=True, help_text='Quote reference (e.g., E-mail dt 27.12.2024)', max_length=300),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='rad_project_no',
            field=models.CharField(blank=True, help_text='RAD Project number (e.g., 5900927)', max_length=100),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='reporting_meetings',
            field=models.TextField(blank=True, help_text='Reporting and meeting requirements'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='safety_requirements',
            field=models.TextField(blank=True, help_text='HSEQ regulations and safety requirements'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='scope_of_services',
            field=models.TextField(blank=True, help_text='Detailed scope of work/services'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='seller_contact_person',
            field=models.CharField(blank=True, help_text='Seller contact person name', max_length=300),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='seller_email',
            field=models.CharField(blank=True, help_text='Seller email address', max_length=200),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='seller_fax',
            field=models.CharField(blank=True, help_text='Seller fax number', max_length=50),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='seller_license_no',
            field=models.CharField(blank=True, help_text='Seller business license/CN number (e.g., CN-3362215)', max_length=100),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='seller_phone',
            field=models.CharField(blank=True, help_text='Seller phone number', max_length=50),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='seller_reference',
            field=models.CharField(blank=True, help_text='Attn: Contact person at vendor (e.g., Mr. Abdul Muneem)', max_length=300),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='subcontractor',
            field=models.CharField(blank=True, help_text='Subcontractor name (e.g., VELIMOR MIDDLE EAST CONSULTANCY LLC)', max_length=300),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='time_schedule',
            field=models.TextField(blank=True, help_text='Time schedule and milestones'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='variations_clause',
            field=models.TextField(blank=True, help_text='Contract variation and change management terms'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='vat_percentage',
            field=models.DecimalField(decimal_places=2, default=5.0, help_text='VAT/Tax percentage (e.g., 5% for UAE)', max_digits=5),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='workshop_rates',
            field=models.JSONField(blank=True, default=dict, help_text='Workshop day rates for services'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='delivery_terms',
            field=models.CharField(blank=True, help_text='e.g., Services completed and accepted, FOB, CIF', max_length=200),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='payment_terms',
            field=models.CharField(blank=True, help_text='e.g., 45 days net for agreed payment milestones', max_length=300),
        ),
    ]
