# Generated by Django 4.2.16 on 2026-07-09 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0010_add_comprehensive_po_template_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='adnoc_approved',
            field=models.BooleanField(default=False, help_text='ADNOC Vendor Approval Status'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='trade_license_number',
            field=models.CharField(blank=True, help_text='Trade License Number', max_length=100),
        ),
        migrations.AddField(
            model_name='vendor',
            name='vat_number',
            field=models.CharField(blank=True, help_text='VAT Registration Number', max_length=100),
        ),
        migrations.AddField(
            model_name='vendor',
            name='vendor_tenure_years',
            field=models.IntegerField(blank=True, help_text='Years of business relationship with Rejlers', null=True),
        ),
    ]
