# Generated by Django 4.2.16 on 2026-07-10 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0011_add_vendor_excel_template_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='budget',
            new_name='procurement_project_cf65fc_idx',
            old_name='procurement_budget_idx1',
        ),
        migrations.RenameIndex(
            model_name='budget',
            new_name='procurement_fiscal__0de50e_idx',
            old_name='procurement_budget_idx2',
        ),
        migrations.RenameIndex(
            model_name='costcenter',
            new_name='procurement_code_f170f4_idx',
            old_name='procurement_costcenter_idx1',
        ),
        migrations.RenameIndex(
            model_name='costcenter',
            new_name='procurement_departm_ea9b87_idx',
            old_name='procurement_costcenter_idx2',
        ),
        migrations.RenameIndex(
            model_name='project',
            new_name='procurement_project_3cb8c1_idx',
            old_name='procurement_project_idx1',
        ),
        migrations.RenameIndex(
            model_name='project',
            new_name='procurement_status_5adfc7_idx',
            old_name='procurement_project_idx2',
        ),
        migrations.RenameIndex(
            model_name='project',
            new_name='procurement_client__88c69c_idx',
            old_name='procurement_project_idx3',
        ),
        migrations.RenameIndex(
            model_name='project',
            new_name='procurement_start_d_19f6a3_idx',
            old_name='procurement_project_idx4',
        ),
    ]
