# Generated by Django 4.2.16 on 2026-07-10 17:04
# FIXED: Changed RenameIndex to conditional SQL to handle missing indexes

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0011_add_vendor_excel_template_fields'),
    ]

    operations = [
        migrations.RunSQL(sql="""DO $$ BEGIN IF EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'procurement_budget_idx1') THEN ALTER INDEX procurement_budget_idx1 RENAME TO procurement_project_cf65fc_idx; END IF; END $$;""", reverse_sql=migrations.RunSQL.noop),
        migrations.RunSQL(sql="""DO $$ BEGIN IF EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'procurement_budget_idx2') THEN ALTER INDEX procurement_budget_idx2 RENAME TO procurement_fiscal__0de50e_idx; END IF; END $$;""", reverse_sql=migrations.RunSQL.noop),
        migrations.RunSQL(sql="""DO $$ BEGIN IF EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'procurement_costcenter_idx1') THEN ALTER INDEX procurement_costcenter_idx1 RENAME TO procurement_code_f170f4_idx; END IF; END $$;""", reverse_sql=migrations.RunSQL.noop),
        migrations.RunSQL(sql="""DO $$ BEGIN IF EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'procurement_costcenter_idx2') THEN ALTER INDEX procurement_costcenter_idx2 RENAME TO procurement_departm_ea9b87_idx; END IF; END $$;""", reverse_sql=migrations.RunSQL.noop),
        migrations.RunSQL(sql="""DO $$ BEGIN IF EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'procurement_project_idx1') THEN ALTER INDEX procurement_project_idx1 RENAME TO procurement_project_3cb8c1_idx; END IF; END $$;""", reverse_sql=migrations.RunSQL.noop),
        migrations.RunSQL(sql="""DO $$ BEGIN IF EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'procurement_project_idx2') THEN ALTER INDEX procurement_project_idx2 RENAME TO procurement_status_5adfc7_idx; END IF; END $$;""", reverse_sql=migrations.RunSQL.noop),
        migrations.RunSQL(sql="""DO $$ BEGIN IF EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'procurement_project_idx3') THEN ALTER INDEX procurement_project_idx3 RENAME TO procurement_client__88c69c_idx; END IF; END $$;""", reverse_sql=migrations.RunSQL.noop),
        migrations.RunSQL(sql="""DO $$ BEGIN IF EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'procurement_project_idx4') THEN ALTER INDEX procurement_project_idx4 RENAME TO procurement_start_d_19f6a3_idx; END IF; END $$;""", reverse_sql=migrations.RunSQL.noop),
    ]
