# Generated by Django 4.2.16 on 2026-07-13 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0013_enhance_pr_workflow_and_vendor_integration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserequisition',
            name='ai_vendor_recommendations',
            field=models.JSONField(blank=True, default=list, help_text='AI-generated vendor recommendations based on historical data: [{"vendor_id": "uuid", "vendor_name": "...", "score": 0.95, "reason": "High performance in similar projects", "past_orders": 15, "avg_rating": 4.8}]'),
        ),
        migrations.AlterField(
            model_name='purchaserequisition',
            name='approval_workflow_config',
            field=models.JSONField(blank=True, default=list, help_text='Dynamic approval workflow: [{"step": 1, "role": "Project Manager", "user_id": "uuid", "user_name": "John Doe", "status": "pending", "approved_at": null}]'),
        ),
        migrations.AlterField(
            model_name='purchaserequisition',
            name='price_remarks_data',
            field=models.JSONField(blank=True, default=dict, help_text='Advanced pricing data: {"budget_allocation": "HSE", "cost_center": "CC-001", "payment_terms": "Net 45", "discount_percentage": 10, "discount_amount": 400, "comparative_prices": [{"vendor": "Vendor A", "price": 4200}, ...], "price_history": [...]}'),
        ),
        migrations.AlterField(
            model_name='purchaserequisition',
            name='purchase_recommendation',
            field=models.TextField(blank=True, help_text='Purchase Recommendation (previously Special Notes)'),
        ),
        migrations.AlterField(
            model_name='purchaserequisition',
            name='vendor',
            field=models.ForeignKey(blank=True, help_text='Linked vendor from vendor master database (auto-populated from supplier_name or manual selection)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_requisitions', to='procurement.vendor'),
        ),
    ]
