# Generated by Django 5.0 on 2026-08-11 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0021_pr_feedback_workflow_fields'),
    ]

    operations = [
        # Earlier migrations already conditionally renamed these indexes in
        # the database. Reconcile Django's state without repeating the SQL.
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RenameIndex(
                    model_name='budget',
                    new_name='procurement_project_cf65fc_idx',
                    old_name='procurement_budget_idx1',
                ),
                migrations.RenameIndex(
                    model_name='budget',
                    new_name='procurement_fiscal__0de50e_idx',
                    old_name='procurement_budget_idx2',
                ),
                migrations.RenameIndex(
                    model_name='costcenter',
                    new_name='procurement_code_f170f4_idx',
                    old_name='procurement_costcenter_idx1',
                ),
                migrations.RenameIndex(
                    model_name='costcenter',
                    new_name='procurement_departm_ea9b87_idx',
                    old_name='procurement_costcenter_idx2',
                ),
                migrations.RenameIndex(
                    model_name='project',
                    new_name='procurement_project_3cb8c1_idx',
                    old_name='procurement_project_idx1',
                ),
                migrations.RenameIndex(
                    model_name='project',
                    new_name='procurement_status_5adfc7_idx',
                    old_name='procurement_project_idx2',
                ),
                migrations.RenameIndex(
                    model_name='project',
                    new_name='procurement_client__88c69c_idx',
                    old_name='procurement_project_idx3',
                ),
                migrations.RenameIndex(
                    model_name='project',
                    new_name='procurement_start_d_19f6a3_idx',
                    old_name='procurement_project_idx4',
                ),
            ],
        ),
        migrations.AlterField(
            model_name='purchaserequisition',
            name='management_approval_evidence',
            field=models.JSONField(blank=True, default=list, help_text='Evidence of management approval attachments. Format: [{"filename": "approval.pdf", "s3_url": "https://...", "uploaded_at": "..."}]'),
        ),
        migrations.AlterField(
            model_name='purchaserequisition',
            name='management_approval_remarks',
            field=models.TextField(blank=True, help_text='Remarks or notes regarding management approval'),
        ),
        migrations.AlterField(
            model_name='purchaserequisition',
            name='po_applicable',
            field=models.BooleanField(default=False, help_text='Indicates whether a Purchase Order is applicable for this requisition (Feedback: PO applicable Yes/No checkbox)'),
        ),
        migrations.AlterField(
            model_name='purchaserequisition',
            name='po_number_reference',
            field=models.CharField(blank=True, help_text='Related PO number (e.g., RAD-PRJ-PUR-0014_JAN2025). Manual entry with conflict validation.', max_length=100),
        ),
        migrations.AlterField(
            model_name='purchaserequisition',
            name='pr_number',
            field=models.CharField(db_index=True, help_text='Manually assigned PR number (system validates for duplicates). Feedback: PR Number to be Manual enter with duplicate alert', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='purchaserequisition',
            name='price_description',
            field=models.TextField(blank=True, help_text='Item/Service description for pricing (Feedback: Renamed to Purchase Description)'),
        ),
        migrations.AlterField(
            model_name='purchaserequisition',
            name='price_remarks',
            field=models.TextField(blank=True, help_text='Negotiation remarks: outcome, savings, commercial clarifications, or final terms (Feedback: Renamed from Discount %)'),
        ),
        migrations.AlterField(
            model_name='purchaserequisition',
            name='priority',
            field=models.CharField(choices=[('urgent', 'Urgent - Same Day Review'), ('high', 'High - 1 Day Review'), ('normal', 'Normal - 2 Days Review'), ('low', 'Low')], default='normal', help_text='Priority level determining review cycle: Normal=2 days, High=1 day, Urgent=same day', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchaserequisition',
            name='project_details',
            field=models.JSONField(blank=True, default=list, help_text='One or more linked project/department selections. Format: [{"project_id": "...", "project_name": "...", "department": "...", "type": "project|internal"}]'),
        ),
        migrations.AlterField(
            model_name='purchaserequisition',
            name='resolution_referral',
            field=models.JSONField(blank=True, default=dict, help_text='MoE/MoP discussion referral recorded after rejection. Format: {"referred_to": "MoE", "referred_by": "user_id", "referred_at": "...", "discussion_notes": "..."}'),
        ),
        migrations.AlterField(
            model_name='purchaserequisition',
            name='selected_vendors',
            field=models.JSONField(blank=True, default=list, help_text='Vendor shortlist captured from the vendor master, including ICV details. Format: [{"vendor_id": "uuid", "vendor_name": "...", "icv_value": 0.75, "icv_validity": "2025-12-31"}]'),
        ),
        migrations.AlterField(
            model_name='purchaserequisition',
            name='single_source_justification',
            field=models.TextField(blank=True, help_text='Required justification when only one vendor is shortlisted (Feedback: Single source justification to be provided)'),
        ),
    ]
