# Generated by Django 5.0 on 2026-09-08 11:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0040_signature_image_snapshots'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcurementReportingSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('schema_version', models.CharField(default='1.0', max_length=20)),
                ('definition_version', models.CharField(default='2026.1', max_length=20)),
                ('scope', models.JSONField(default=dict)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('reporting_currency', models.CharField(blank=True, max_length=8)),
                ('payload', models.JSONField(default=dict)),
                ('checksum', models.CharField(editable=False, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_reporting_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'procurement_reporting_snapshots',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcurementCalculationAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metric_key', models.CharField(max_length=100)),
                ('definition_version', models.CharField(default='2026.1', max_length=20)),
                ('inputs', models.JSONField(default=dict)),
                ('result', models.JSONField(default=dict)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calculations', to='procurement.procurementreportingsnapshot')),
            ],
            options={
                'db_table': 'procurement_calculation_audits',
                'ordering': ['metric_key'],
            },
        ),
        migrations.AddIndex(
            model_name='procurementreportingsnapshot',
            index=models.Index(fields=['period_end', '-created_at'], name='procurement_period__fe2ee3_idx'),
        ),
        migrations.AddConstraint(
            model_name='procurementcalculationaudit',
            constraint=models.UniqueConstraint(fields=('snapshot', 'metric_key'), name='proc_calc_snapshot_metric_uniq'),
        ),
    ]
