# Generated by Django 5.0 on 2026-09-16 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0041_procurementreportingsnapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='net_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Net after discounts, recorded when the user confirms VAT treatment.', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='vat_basis',
            field=models.CharField(choices=[('unconfirmed', 'VAT treatment not confirmed'), ('exclusive', 'Add 5% VAT to entered prices'), ('inclusive', 'Entered prices include 5% VAT'), ('none', 'No VAT applies')], default='unconfirmed', max_length=16),
        ),
        migrations.AddField(
            model_name='purchaserequisition',
            name='vat_basis',
            field=models.CharField(choices=[('unconfirmed', 'VAT treatment not confirmed'), ('exclusive', 'Add 5% VAT to entered prices'), ('inclusive', 'Entered prices include 5% VAT'), ('none', 'No VAT applies')], default='unconfirmed', max_length=16),
        ),
    ]
