# Generated by Django 5.0 on 2026-01-06 05:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_type', models.CharField(choices=[('finance', 'Finance Invoice'), ('it', 'IT Invoice'), ('project', 'Project Invoice'), ('admin', 'Admin/General Invoice')], max_length=20)),
                ('min_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('approval_chain', models.JSONField(help_text='Array of approval levels with approver details')),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0, help_text='Higher priority routes are checked first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-priority', 'invoice_type'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email_subject', models.CharField(blank=True, max_length=500, null=True)),
                ('email_from', models.EmailField(blank=True, max_length=254, null=True)),
                ('email_date', models.DateTimeField(blank=True, null=True)),
                ('invoice_number', models.CharField(db_index=True, max_length=100, unique=True)),
                ('vendor_name', models.CharField(blank=True, max_length=255, null=True)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='AED', max_length=10)),
                ('tax_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('invoice_type', models.CharField(blank=True, choices=[('finance', 'Finance Invoice'), ('it', 'IT Invoice'), ('project', 'Project Invoice'), ('admin', 'Admin/General Invoice')], max_length=20, null=True)),
                ('classification_confidence', models.FloatField(blank=True, null=True)),
                ('classification_reasoning', models.TextField(blank=True, null=True)),
                ('extracted_text', models.TextField(blank=True, null=True)),
                ('line_items', models.JSONField(blank=True, null=True)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('pending_extraction', 'Pending Extraction'), ('extraction_failed', 'Extraction Failed'), ('pending_classification', 'Pending Classification'), ('classification_failed', 'Classification Failed'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('processed', 'Processed')], default='pending_extraction', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_invoices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='finance.invoice')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approver_name', models.CharField(max_length=100)),
                ('approver_email', models.EmailField(max_length=254)),
                ('approval_level', models.IntegerField(help_text='1=Department, 2=CEO, etc.')),
                ('level_name', models.CharField(help_text='e.g., Finance Head, CEO', max_length=50)),
                ('approval_metadata', models.JSONField(blank=True, help_text='Store title, CC emails, mandatory flag', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('decision', models.CharField(blank=True, max_length=20, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('decision_date', models.DateTimeField(blank=True, null=True)),
                ('approval_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='finance.invoice')),
            ],
            options={
                'ordering': ['approval_level', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoice_number'], name='finance_inv_invoice_89da8a_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status'], name='finance_inv_status_d9b47e_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoice_type'], name='finance_inv_invoice_1ea1d8_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['created_at'], name='finance_inv_created_6e1634_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['timestamp'], name='finance_aud_timesta_948a92_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action'], name='finance_aud_action_2c4f2b_idx'),
        ),
        migrations.AddIndex(
            model_name='approval',
            index=models.Index(fields=['approval_token'], name='finance_app_approva_e7d4cb_idx'),
        ),
        migrations.AddIndex(
            model_name='approval',
            index=models.Index(fields=['status'], name='finance_app_status_4194fd_idx'),
        ),
    ]
