# Generated by Django 5.0 on 2026-01-07 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='file_path',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='original_filename',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='vendor_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
