# Generated by Django 5.0 on 2026-01-07 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_invoice_file_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='tracking_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True),
        ),
    ]
