# Generated by Django 5.0 on 2026-01-09
"""
Data migration to set up approval routes for all invoice categories.
Reads email addresses from environment variables for flexibility across environments.
"""
import os
from django.db import migrations


def create_approval_routes(apps, schema_editor):
    """
    Create approval routes for IT, Admin, Finance, and Project invoice categories.
    Uses environment variables for email addresses.
    """
    ApprovalRoute = apps.get_model('finance', 'ApprovalRoute')
    
    # Get emails from environment variables
    richa_email = os.getenv('FINANCE_RICHA_EMAIL', 'richa@rejlers.ae')
    jamal_email = os.getenv('FINANCE_JAMAL_EMAIL', 'jamal@rejlers.ae')
    rafat_email = os.getenv('FINANCE_RAFAT_EMAIL', 'rafat@rejlers.ae')
    moe_email = os.getenv('FINANCE_MOE_EMAIL', 'moe@rejlers.ae')
    jarmo_email = os.getenv('FINANCE_JARMO_EMAIL', 'jarmo@rejlers.ae')
    aneef_email = os.getenv('FINANCE_ANEEF_EMAIL', 'aneef@rejlers.ae')
    aleksi_email = os.getenv('FINANCE_ALEKSI_EMAIL', 'aleksi@rejlers.ae')
    sherwin_email = os.getenv('FINANCE_SHERWIN_EMAIL', 'sherwin@rejlers.ae')
    hr_admin_email = os.getenv('FINANCE_HR_ADMIN_EMAIL', 'hradmin@rejlers.ae')
    
    # Define approval routes for each category
    routes = [
        {
            'invoice_type': 'project',
            'name': 'Project Invoice Approval',
            'approval_chain': [
                {
                    "level": 1,
                    "name": "Richa",
                    "email": richa_email,
                    "title": "Procurement Manager"
                },
                {
                    "level": 2,
                    "name": "Project Manager",
                    "email": jamal_email,
                    "title": "Project Manager",
                    "cc": [rafat_email]  # CC Jamal & Rafat
                },
                {
                    "level": 3,
                    "name": "Mo",
                    "email": moe_email,
                    "title": "Vice President"
                },
                {
                    "level": 4,
                    "name": "Jarmo",
                    "email": jarmo_email,
                    "title": "CEO",
                    "mandatory": True
                }
            ],
            'priority': 10
        },
        {
            'invoice_type': 'admin',
            'name': 'General/Admin Invoice Approval',
            'approval_chain': [
                {
                    "level": 1,
                    "name": "Richa",
                    "email": richa_email,
                    "title": "Procurement Manager"
                },
                {
                    "level": 2,
                    "name": "HR/Admin",
                    "email": hr_admin_email,
                    "title": "HR/Admin Manager"
                },
                {
                    "level": 3,
                    "name": "Jarmo",
                    "email": jarmo_email,
                    "title": "CEO",
                    "mandatory": True
                }
            ],
            'priority': 10
        },
        {
            'invoice_type': 'finance',
            'name': 'Accounting/Finance Invoice Approval',
            'approval_chain': [
                {
                    "level": 1,
                    "name": "Richa",
                    "email": richa_email,
                    "title": "Procurement Manager"
                },
                {
                    "level": 2,
                    "name": "Aneef",
                    "email": aneef_email,
                    "title": "Finance Manager"
                },
                {
                    "level": 3,
                    "name": "Aleksi",
                    "email": aleksi_email,
                    "title": "CFO"
                },
                {
                    "level": 4,
                    "name": "Jarmo",
                    "email": jarmo_email,
                    "title": "CEO",
                    "mandatory": True
                }
            ],
            'priority': 10
        },
        {
            'invoice_type': 'it',
            'name': 'IT Invoice Approval',
            'approval_chain': [
                {
                    "level": 1,
                    "name": "Richa",
                    "email": richa_email,
                    "title": "Procurement Manager"
                },
                {
                    "level": 2,
                    "name": "Sherwin/Nijum",
                    "email": sherwin_email,
                    "title": "ICT Manager"
                },
                {
                    "level": 3,
                    "name": "Aleksi",
                    "email": aleksi_email,
                    "title": "CFO"
                },
                {
                    "level": 4,
                    "name": "Jarmo",
                    "email": jarmo_email,
                    "title": "CEO",
                    "mandatory": True
                }
            ],
            'priority': 10
        }
    ]
    
    # Create or update each route
    for route_config in routes:
        ApprovalRoute.objects.update_or_create(
            invoice_type=route_config['invoice_type'],
            defaults={
                'approval_chain': route_config['approval_chain'],
                'is_active': True,
                'priority': route_config['priority']
            }
        )
    
    print(f"✅ Successfully created/updated approval route: {route_config['name']}")


def remove_approval_routes(apps, schema_editor):
    """
    Reverse migration: Remove all approval routes created by this migration.
    """
    ApprovalRoute = apps.get_model('finance', 'ApprovalRoute')
    ApprovalRoute.objects.filter(
        invoice_type__in=['project', 'admin', 'finance', 'it']
    ).delete()
    print("✅ Removed approval routes")


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_invoice_tracking_id'),
    ]

    operations = [
        migrations.RunPython(create_approval_routes, remove_approval_routes),
    ]
