# Generated by Django 5.0 on 2026-02-10 13:03

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_setup_approval_routes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeSalaryInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employee_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('designation', models.CharField(blank=True, max_length=100)),
                ('join_date', models.DateField(blank=True, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('account_number', models.CharField(blank=True, max_length=50)),
                ('iban', models.CharField(blank=True, max_length=50)),
                ('swift_code', models.CharField(blank=True, max_length=20)),
                ('tax_id', models.CharField(blank=True, max_length=50)),
                ('tax_exemption', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(default='AED', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('termination_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_salary_infos', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salary_info', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employee Salary Information',
                'verbose_name_plural': 'Employee Salary Information',
                'db_table': 'finance_employee_salary_info',
                'ordering': ['employee_id'],
            },
        ),
        migrations.CreateModel(
            name='PayrollRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('run_code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('month', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('year', models.IntegerField()),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_employees', models.IntegerField(default=0)),
                ('processed_employees', models.IntegerField(default=0)),
                ('total_gross_salary', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('total_net_salary', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('processing_started_at', models.DateTimeField(blank=True, null=True)),
                ('processing_completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_log', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payroll_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payroll Run',
                'verbose_name_plural': 'Payroll Runs',
                'db_table': 'finance_payroll_runs',
                'ordering': ['-year', '-month'],
            },
        ),
        migrations.CreateModel(
            name='SalaryComponent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('component_type', models.CharField(choices=[('allowance', 'Allowance'), ('deduction', 'Deduction')], max_length=20)),
                ('calculation_type', models.CharField(choices=[('fixed', 'Fixed Amount'), ('percentage', 'Percentage of Basic')], max_length=20)),
                ('default_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('is_taxable', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Salary Component',
                'verbose_name_plural': 'Salary Components',
                'db_table': 'finance_salary_components',
                'ordering': ['component_type', 'display_order', 'name'],
                'indexes': [models.Index(fields=['code'], name='finance_sal_code_6e2fc1_idx'), models.Index(fields=['component_type'], name='finance_sal_compone_ebd205_idx'), models.Index(fields=['is_active'], name='finance_sal_is_acti_cf11e7_idx')],
            },
        ),
        migrations.CreateModel(
            name='EmployeeSalaryComponent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee_salary_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_components', to='finance.employeesalaryinfo')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_components', to='finance.salarycomponent')),
            ],
            options={
                'verbose_name': 'Employee Salary Component',
                'verbose_name_plural': 'Employee Salary Components',
                'db_table': 'finance_employee_salary_components',
                'ordering': ['employee_salary_info', 'component__display_order'],
            },
        ),
        migrations.CreateModel(
            name='SalarySlip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slip_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('month', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('year', models.IntegerField()),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_allowances', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('gross_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('tax_deduction', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('net_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='AED', max_length=10)),
                ('allowances_breakdown', models.JSONField(blank=True, default=dict)),
                ('deductions_breakdown', models.JSONField(blank=True, default=dict)),
                ('working_days', models.IntegerField(default=30)),
                ('present_days', models.IntegerField(default=30)),
                ('absent_days', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('generated', 'Generated'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('sent', 'Sent to Employee'), ('archived', 'Archived')], default='draft', max_length=30)),
                ('pdf_file_path', models.CharField(blank=True, max_length=500)),
                ('pdf_generated_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('remarks', models.TextField(blank=True)),
                ('internal_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_salary_slips', to=settings.AUTH_USER_MODEL)),
                ('employee_salary_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_slips', to='finance.employeesalaryinfo')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_salary_slips', to=settings.AUTH_USER_MODEL)),
                ('payroll_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_slips', to='finance.payrollrun')),
            ],
            options={
                'verbose_name': 'Salary Slip',
                'verbose_name_plural': 'Salary Slips',
                'db_table': 'finance_salary_slips',
                'ordering': ['-year', '-month', 'employee_salary_info__employee_id'],
            },
        ),
        migrations.CreateModel(
            name='SalarySlipApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('approval_level', models.IntegerField(default=1)),
                ('approval_role', models.CharField(choices=[('hr', 'HR'), ('finance', 'Finance'), ('management', 'Management')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('decision_date', models.DateTimeField(blank=True, null=True)),
                ('comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_approvals', to=settings.AUTH_USER_MODEL)),
                ('salary_slip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='finance.salaryslip')),
            ],
            options={
                'verbose_name': 'Salary Slip Approval',
                'verbose_name_plural': 'Salary Slip Approvals',
                'db_table': 'finance_salary_slip_approvals',
                'ordering': ['salary_slip', 'approval_level'],
            },
        ),
        migrations.CreateModel(
            name='SalarySlipAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('generated', 'Generated'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('sent', 'Sent to Employee'), ('downloaded', 'Downloaded'), ('archived', 'Archived'), ('deleted', 'Deleted')], max_length=20)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('old_values', models.JSONField(blank=True, null=True)),
                ('new_values', models.JSONField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_slip_actions', to=settings.AUTH_USER_MODEL)),
                ('salary_slip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='finance.salaryslip')),
            ],
            options={
                'verbose_name': 'Salary Slip Audit Log',
                'verbose_name_plural': 'Salary Slip Audit Logs',
                'db_table': 'finance_salary_slip_audit_logs',
                'ordering': ['-performed_at'],
            },
        ),
        migrations.CreateModel(
            name='SalarySlipEmail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=500)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed'), ('bounced', 'Bounced')], default='pending', max_length=20)),
                ('email_provider_id', models.CharField(blank=True, max_length=200)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('downloaded_at', models.DateTimeField(blank=True, null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('salary_slip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_deliveries', to='finance.salaryslip')),
            ],
            options={
                'verbose_name': 'Salary Slip Email',
                'verbose_name_plural': 'Salary Slip Emails',
                'db_table': 'finance_salary_slip_emails',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='employeesalaryinfo',
            index=models.Index(fields=['employee_id'], name='finance_emp_employe_47f9d1_idx'),
        ),
        migrations.AddIndex(
            model_name='employeesalaryinfo',
            index=models.Index(fields=['user'], name='finance_emp_user_id_61479d_idx'),
        ),
        migrations.AddIndex(
            model_name='employeesalaryinfo',
            index=models.Index(fields=['is_active'], name='finance_emp_is_acti_d070b3_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollrun',
            index=models.Index(fields=['run_code'], name='finance_pay_run_cod_bdc7de_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollrun',
            index=models.Index(fields=['year', 'month'], name='finance_pay_year_79aec7_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollrun',
            index=models.Index(fields=['status'], name='finance_pay_status_f7f4a0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='payrollrun',
            unique_together={('month', 'year')},
        ),
        migrations.AddIndex(
            model_name='employeesalarycomponent',
            index=models.Index(fields=['employee_salary_info'], name='finance_emp_employe_3d026d_idx'),
        ),
        migrations.AddIndex(
            model_name='employeesalarycomponent',
            index=models.Index(fields=['component'], name='finance_emp_compone_6a0e81_idx'),
        ),
        migrations.AddIndex(
            model_name='employeesalarycomponent',
            index=models.Index(fields=['is_active'], name='finance_emp_is_acti_f6b957_idx'),
        ),
        migrations.AddIndex(
            model_name='employeesalarycomponent',
            index=models.Index(fields=['effective_from', 'effective_to'], name='finance_emp_effecti_882e6d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='employeesalarycomponent',
            unique_together={('employee_salary_info', 'component', 'effective_from')},
        ),
        migrations.AddIndex(
            model_name='salaryslip',
            index=models.Index(fields=['slip_number'], name='finance_sal_slip_nu_ed7ec0_idx'),
        ),
        migrations.AddIndex(
            model_name='salaryslip',
            index=models.Index(fields=['payroll_run'], name='finance_sal_payroll_abbf2d_idx'),
        ),
        migrations.AddIndex(
            model_name='salaryslip',
            index=models.Index(fields=['employee_salary_info'], name='finance_sal_employe_d142e9_idx'),
        ),
        migrations.AddIndex(
            model_name='salaryslip',
            index=models.Index(fields=['year', 'month'], name='finance_sal_year_5d7f38_idx'),
        ),
        migrations.AddIndex(
            model_name='salaryslip',
            index=models.Index(fields=['status'], name='finance_sal_status_17f1a3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='salaryslip',
            unique_together={('employee_salary_info', 'month', 'year')},
        ),
        migrations.AddIndex(
            model_name='salaryslipapproval',
            index=models.Index(fields=['salary_slip'], name='finance_sal_salary__db999a_idx'),
        ),
        migrations.AddIndex(
            model_name='salaryslipapproval',
            index=models.Index(fields=['approver'], name='finance_sal_approve_61a35a_idx'),
        ),
        migrations.AddIndex(
            model_name='salaryslipapproval',
            index=models.Index(fields=['status'], name='finance_sal_status_906f53_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='salaryslipapproval',
            unique_together={('salary_slip', 'approval_level')},
        ),
        migrations.AddIndex(
            model_name='salaryslipauditlog',
            index=models.Index(fields=['salary_slip'], name='finance_sal_salary__3606bd_idx'),
        ),
        migrations.AddIndex(
            model_name='salaryslipauditlog',
            index=models.Index(fields=['performed_by'], name='finance_sal_perform_02bbb7_idx'),
        ),
        migrations.AddIndex(
            model_name='salaryslipauditlog',
            index=models.Index(fields=['action'], name='finance_sal_action_8edcbc_idx'),
        ),
        migrations.AddIndex(
            model_name='salaryslipauditlog',
            index=models.Index(fields=['performed_at'], name='finance_sal_perform_4b13a7_idx'),
        ),
        migrations.AddIndex(
            model_name='salaryslipemail',
            index=models.Index(fields=['salary_slip'], name='finance_sal_salary__e8cec9_idx'),
        ),
        migrations.AddIndex(
            model_name='salaryslipemail',
            index=models.Index(fields=['status'], name='finance_sal_status_afdc21_idx'),
        ),
        migrations.AddIndex(
            model_name='salaryslipemail',
            index=models.Index(fields=['recipient_email'], name='finance_sal_recipie_f7338b_idx'),
        ),
    ]
