# Generated by Django 5.0 on 2026-08-18 07:59

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_payrollworkflow_workflownotificationlog_and_more'),
        ('procurement', '0029_repair_legacy_pr_insert_defaults'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True, default='')),
                ('quantity', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('net_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('tax_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('tax_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('currency', models.CharField(blank=True, default='', max_length=10)),
                ('po_item_reference', models.CharField(blank=True, default='', max_length=100)),
                ('source_data', models.JSONField(blank=True, default=dict)),
                ('ocr_confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('manually_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['line_number', 'id'],
            },
        ),
        migrations.CreateModel(
            name='InvoicePurchaseOrderAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('allocated_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency', models.CharField(default='AED', max_length=10)),
                ('match_method', models.CharField(choices=[('automatic', 'Automatic'), ('manual', 'Manual'), ('imported', 'Imported')], default='manual', max_length=20)),
                ('match_status', models.CharField(choices=[('unmatched', 'Unmatched'), ('auto_matched', 'Automatically Matched'), ('manual_matched', 'Manually Matched'), ('exception', 'Matching Exception'), ('verified', 'Verified')], db_index=True, default='unmatched', max_length=20)),
                ('match_confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('po_amount_at_match', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('invoice_amount_at_match', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('amount_variance', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('tolerance_percentage', models.DecimalField(decimal_places=2, default=5, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('amount_within_tolerance', models.BooleanField(default=False)),
                ('vendor_matched', models.BooleanField(default=False)),
                ('currency_matched', models.BooleanField(default=False)),
                ('receipt_required', models.BooleanField(default=True)),
                ('exception_codes', models.JSONField(blank=True, default=list)),
                ('review_notes', models.TextField(blank=True, default='')),
                ('matched_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='finance_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='finance_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_reviewed_vendor_invoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice',
            name='manual_review_required',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='match_status',
            field=models.CharField(choices=[('unmatched', 'Unmatched'), ('auto_matched', 'Automatically Matched'), ('manual_matched', 'Manually Matched'), ('exception', 'Matching Exception'), ('verified', 'Verified')], db_index=True, default='unmatched', max_length=20),
        ),
        migrations.AddField(
            model_name='invoice',
            name='ocr_confidence',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='invoice',
            name='ocr_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='invoice',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_reference',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_status',
            field=models.CharField(choices=[('not_scheduled', 'Not Scheduled'), ('scheduled', 'Scheduled'), ('partial', 'Partially Paid'), ('paid', 'Paid'), ('on_hold', 'On Hold'), ('cancelled', 'Cancelled')], db_index=True, default='not_scheduled', max_length=20),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_terms',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='invoice',
            name='po_reference_text',
            field=models.CharField(blank=True, db_index=True, default='', help_text='PO reference captured from the invoice before confirmed allocation.', max_length=100),
        ),
        migrations.AddField(
            model_name='invoice',
            name='procurement_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='procurement_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_reviewed_vendor_invoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice',
            name='procurement_status',
            field=models.CharField(choices=[('ocr_review', 'OCR Review'), ('ready_for_matching', 'Ready for Matching'), ('procurement_review', 'Procurement Review'), ('finance_review', 'Finance Review'), ('approved_for_payment', 'Approved for Payment'), ('rejected', 'Rejected'), ('closed', 'Closed')], db_index=True, default='ocr_review', max_length=30),
        ),
        migrations.AddField(
            model_name='invoice',
            name='received_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='scheduled_payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='source_file_sha256',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='invoice',
            name='vat_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='vat_registration_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='invoice',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_invoices', to='procurement.vendor'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['vendor', 'procurement_status'], name='finance_inv_vendor__952ce0_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['match_status', 'payment_status'], name='finance_inv_match_s_0d7458_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['due_date', 'payment_status'], name='finance_inv_due_dat_10375c_idx'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(check=models.Q(('paid_amount__gte', 0)), name='finance_invoice_paid_amount_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(condition=models.Q(('source_file_sha256', ''), _negated=True), fields=('source_file_sha256',), name='finance_invoice_unique_source_hash'),
        ),
        migrations.AddField(
            model_name='invoicelineitem',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structured_line_items', to='finance.invoice'),
        ),
        migrations.AddField(
            model_name='invoicepurchaseorderallocation',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='po_allocations', to='finance.invoice'),
        ),
        migrations.AddField(
            model_name='invoicepurchaseorderallocation',
            name='matched_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_vendor_invoice_allocations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoicepurchaseorderallocation',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_allocations', to='procurement.purchaseorder'),
        ),
        migrations.AddField(
            model_name='invoicepurchaseorderallocation',
            name='receipts',
            field=models.ManyToManyField(blank=True, related_name='invoice_allocations', to='procurement.receipt'),
        ),
        migrations.AddField(
            model_name='invoicepurchaseorderallocation',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_vendor_invoice_allocations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='invoicelineitem',
            index=models.Index(fields=['invoice', 'line_number'], name='finance_inv_invoice_6397fc_idx'),
        ),
        migrations.AddConstraint(
            model_name='invoicelineitem',
            constraint=models.UniqueConstraint(fields=('invoice', 'line_number'), name='finance_invoice_unique_line_number'),
        ),
        migrations.AddIndex(
            model_name='invoicepurchaseorderallocation',
            index=models.Index(fields=['purchase_order', 'match_status'], name='finance_inv_purchas_97679f_idx'),
        ),
        migrations.AddIndex(
            model_name='invoicepurchaseorderallocation',
            index=models.Index(fields=['invoice', 'match_status'], name='finance_inv_invoice_342723_idx'),
        ),
        migrations.AddConstraint(
            model_name='invoicepurchaseorderallocation',
            constraint=models.UniqueConstraint(fields=('invoice', 'purchase_order'), name='finance_invoice_unique_po_allocation'),
        ),
        migrations.AddConstraint(
            model_name='invoicepurchaseorderallocation',
            constraint=models.CheckConstraint(check=models.Q(('allocated_amount__gte', 0)), name='finance_invoice_allocation_nonnegative'),
        ),
    ]
