# Generated by Django 5.0 on 2026-08-18 10:33

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


def prepare_existing_payables(apps, schema_editor):
    """Resolve legacy case-only collisions and align A/P lifecycle states."""
    Invoice = apps.get_model('finance', 'Invoice')
    Allocation = apps.get_model('finance', 'InvoicePurchaseOrderAllocation')
    seen = set()
    for invoice in Invoice.objects.order_by('id').iterator():
        key = (invoice.vendor_id, (invoice.invoice_number or '').strip().casefold())
        if key in seen:
            suffix = f'-DUP-{invoice.id}'
            invoice.invoice_number = f'{invoice.invoice_number[:100-len(suffix)]}{suffix}'
        seen.add((invoice.vendor_id, invoice.invoice_number.strip().casefold()))

        total = invoice.total_amount or 0
        paid = invoice.paid_amount or 0
        if invoice.payment_status not in ('cancelled', 'on_hold'):
            invoice.payment_status = (
                'paid' if total > 0 and paid >= total else
                'partial' if paid > 0 else
                'scheduled' if invoice.scheduled_payment_date else
                'not_scheduled'
            )
        statuses = list(Allocation.objects.filter(invoice_id=invoice.pk).values_list('match_status', flat=True))
        invoice.match_status = (
            'unmatched' if not statuses else
            'exception' if 'exception' in statuses else
            'verified' if all(value == 'verified' for value in statuses) else
            'manual_matched'
        )
        invoice.procurement_status = (
            'rejected' if invoice.status == 'rejected' else
            'closed' if invoice.payment_status == 'paid' else
            'approved_for_payment' if invoice.status in ('approved', 'processed') or invoice.procurement_status == 'approved_for_payment' else
            'finance_review' if invoice.match_status == 'verified' else
            'procurement_review' if statuses else
            'ocr_review' if invoice.manual_review_required else
            'ready_for_matching'
        )
        invoice.save(update_fields=[
            'invoice_number', 'payment_status', 'match_status', 'procurement_status',
        ])


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_procurement_vendor_invoice_foundation'),
        ('procurement', '0029_repair_legacy_pr_insert_defaults'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceOCRJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='queued', max_length=20)),
                ('original_filename', models.CharField(max_length=500)),
                ('file_path', models.CharField(max_length=1000)),
                ('source_file_sha256', models.CharField(db_index=True, max_length=64)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PayablePayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation', models.CharField(choices=[('schedule', 'Schedule'), ('payment', 'Payment'), ('hold', 'Hold'), ('release', 'Release Hold'), ('cancel', 'Cancel')], db_index=True, max_length=20)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('currency', models.CharField(default='AED', max_length=10)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('reference', models.CharField(blank=True, default='', max_length=150)),
                ('notes', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='invoicepurchaseorderallocation',
            name='line_items_matched',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoicepurchaseorderallocation',
            name='match_evidence',
            field=models.JSONField(blank=True, default=dict, help_text='Snapshot of PO, invoice-line, and receipt quantity/value checks.'),
        ),
        migrations.AddField(
            model_name='invoicepurchaseorderallocation',
            name='receipt_quantities_matched',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.RunPython(prepare_existing_payables, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('invoice_number'), models.F('vendor'), condition=models.Q(('vendor__isnull', False)), name='finance_invoice_unique_number_per_vendor_ci'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('invoice_number'), condition=models.Q(('vendor__isnull', True)), name='finance_invoice_unique_unlinked_number_ci'),
        ),
        migrations.AddField(
            model_name='invoiceocrjob',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_ocr_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payablepayment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payable_payment_operations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payablepayment',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_operations', to='finance.invoice'),
        ),
        migrations.AddIndex(
            model_name='invoiceocrjob',
            index=models.Index(fields=['requested_by', 'status', '-created_at'], name='finance_inv_request_46af35_idx'),
        ),
        migrations.AddIndex(
            model_name='payablepayment',
            index=models.Index(fields=['invoice', 'operation', '-created_at'], name='finance_pay_invoice_4b97e6_idx'),
        ),
        migrations.AddConstraint(
            model_name='payablepayment',
            constraint=models.CheckConstraint(check=models.Q(('amount__isnull', True), ('amount__gt', 0), _connector='OR'), name='finance_payable_payment_positive_amount'),
        ),
    ]
