# Generated by Django 5.0 on 2026-09-04 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_invoiceocrjob_payablepayment_and_more'),
        ('hr_core', '0007_alter_employeemaster_email_alter_employeemaster_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeesalaryinfo',
            name='canonical_employee',
            field=models.OneToOneField(blank=True, help_text='Canonical employee identity; this row contains compensation-domain data only.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='legacy_compensation_profile', to='hr_core.employeemaster'),
        ),
    ]
