# Generated by Django 5.0 on 2026-09-22 04:32

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_remove_workflownotificationlog_workflow_and_more'),
        ('users', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutiveFinancePeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='First day of the calendar reporting month.')),
                ('currency', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator('^[A-Z]{3}$')])),
                ('budget_invoiced', models.DecimalField(blank=True, decimal_places=2, help_text='Approved invoicing budget, on the same recorded invoice-amount basis as the workbook.', max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('forecast_invoiced', models.DecimalField(blank=True, decimal_places=2, help_text='Approved monthly invoicing forecast. This is not an accounting revenue forecast.', max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('recognised_revenue', models.DecimalField(blank=True, decimal_places=2, help_text='Finance-approved recognised revenue, excluding tax, for the matched cost period.', max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('operating_costs', models.DecimalField(blank=True, decimal_places=2, help_text='All matching operating costs in the same currency, scope and period as recognised revenue.', max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('actual_through', models.DateField(blank=True, help_text='The inclusive date covered by both recognised revenue and operating costs.', null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved')], default='draft', max_length=12)),
                ('source_reference', models.CharField(blank=True, help_text='Finance report, workbook version or approval reference. Whole authorised workspace scope.', max_length=500)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Executive Finance period',
                'ordering': ['month', 'currency'],
                'constraints': [models.UniqueConstraint(fields=('month', 'currency'), name='finance_exec_month_currency_unique')],
                'indexes': [],
            },
        ),
    ]
