# Generated by Django 5.0 on 2026-09-22 12:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def ensure_customer_invoice_reference_key(apps, schema_editor):
    """Restore the PostgreSQL FK target without changing invoice identities.

    A restored database can have the initial invoice migration recorded while
    its ID key is missing. Repair before this migration's deferred foreign key
    is created; a new predecessor would invalidate already-applied histories.
    """
    connection = schema_editor.connection
    if connection.vendor != 'postgresql':
        return
    invoice = apps.get_model('invoice_tracker', 'CustomerInvoice')
    table, column = invoice._meta.db_table, invoice._meta.pk.column
    quote = schema_editor.quote_name
    with connection.cursor() as cursor:
        # Keep writes out until the atomic migration has validated identities
        # and created both the reference key and its dependent foreign key.
        cursor.execute(f'LOCK TABLE {quote(table)} IN ACCESS EXCLUSIVE MODE')
        cursor.execute('''
            SELECT EXISTS (
                SELECT 1 FROM pg_index i
                JOIN pg_attribute a ON a.attrelid = i.indrelid
                WHERE i.indrelid = to_regclass(%s) AND a.attname = %s
                  AND i.indisunique AND i.indisvalid AND i.indisready
                  AND i.indimmediate AND i.indpred IS NULL
                  AND i.indexprs IS NULL AND i.indnkeyatts = 1
                  AND i.indkey[0] = a.attnum
            )
        ''', [table, column])
        if cursor.fetchone()[0]:
            return
        cursor.execute(f'SELECT EXISTS (SELECT 1 FROM {quote(table)} WHERE {quote(column)} IS NULL)')
        if cursor.fetchone()[0]:
            raise RuntimeError(
                f'Cannot repair {table}.{column}: null IDs exist. '
                'Reconcile invoice identities before retrying migrations; '
                'no invoice rows or IDs were changed.'
            )
        cursor.execute(f'''SELECT EXISTS (
            SELECT 1 FROM {quote(table)} GROUP BY {quote(column)} HAVING COUNT(*) > 1
        )''')
        if cursor.fetchone()[0]:
            raise RuntimeError(
                f'Cannot repair {table}.{column}: duplicate IDs exist. '
                'Reconcile invoice identities before retrying migrations; '
                'no invoice rows or IDs were changed.'
            )
        cursor.execute(
            "SELECT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid = to_regclass(%s) AND contype = 'p')",
            [table],
        )
        kind = 'UNIQUE' if cursor.fetchone()[0] else 'PRIMARY KEY'
        schema_editor.execute(f'ALTER TABLE {quote(table)} ADD {kind} ({quote(column)})')


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_executive_finance_period'),
        ('invoice_tracker', '0004_rename_invoice_tra_account_dab1bb_idx_invoice_tra_account_55b104_idx_and_more'),
    ]

    operations = [
        migrations.RunPython(ensure_customer_invoice_reference_key, migrations.RunPython.noop),
        migrations.CreateModel(
            name='ReceivablesSourceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sha256', models.CharField(max_length=64)),
                ('file_name', models.CharField(max_length=255)),
                ('sheet_name', models.CharField(max_length=128)),
                ('header_row', models.PositiveIntegerField(default=5)),
                ('first_row', models.PositiveIntegerField(default=6)),
                ('last_row', models.PositiveIntegerField()),
                ('row_count', models.PositiveIntegerField()),
                ('imported_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=False)),
                ('reconciliation', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['-imported_at', '-pk'],
                'constraints': [models.UniqueConstraint(fields=('sha256', 'sheet_name', 'header_row', 'first_row', 'last_row'), name='finance_ar_source_identity'), models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='finance_ar_one_active_source')],
                'indexes': [],
            },
        ),
        migrations.CreateModel(
            name='ReceivablesSourceRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='finance.receivablessourcesnapshot')),
                ('row_number', models.PositiveIntegerField()),
                ('invoice_number', models.CharField(db_index=True, max_length=128)),
                ('register_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='invoice_tracker.customerinvoice')),
                ('category', models.CharField(default='external', max_length=16)),
                ('company', models.CharField(blank=True, default='', max_length=256)),
                ('account', models.CharField(blank=True, default='', max_length=256)),
                ('pm', models.CharField(blank=True, default='', max_length=128)),
                ('project_name', models.TextField(blank=True, default='')),
                ('rad_project_no', models.CharField(blank=True, default='', max_length=128)),
                ('project_id', models.CharField(blank=True, default='', max_length=128)),
                ('payment_terms', models.CharField(blank=True, default='', max_length=128)),
                ('remarks', models.TextField(blank=True, default='')),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('invoice_sent_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, db_index=True, null=True)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('payment_status', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('raw_payment_status', models.CharField(blank=True, default='', max_length=128)),
                ('currency', models.CharField(blank=True, default='', max_length=3)),
                ('currency_status', models.CharField(default='not_recorded', max_length=20)),
                ('balance_currency', models.CharField(blank=True, default='', max_length=3)),
                ('balance_currency_status', models.CharField(default='not_recorded', max_length=20)),
                ('actual_payment_currency', models.CharField(blank=True, default='', max_length=3)),
                ('actual_payment_currency_status', models.CharField(default='not_recorded', max_length=20)),
                ('invoice_amount', models.DecimalField(blank=True, decimal_places=8, max_digits=28, null=True)),
                ('invoice_amount_aed', models.DecimalField(blank=True, decimal_places=8, max_digits=28, null=True)),
                ('balance_to_be_received', models.DecimalField(blank=True, decimal_places=8, max_digits=28, null=True)),
                ('actual_payment_received', models.DecimalField(blank=True, decimal_places=8, max_digits=28, null=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['row_number'],
                'constraints': [models.UniqueConstraint(fields=('snapshot', 'row_number'), name='finance_ar_source_row_unique')],
                'indexes': [],
            },
        ),
    ]
