# Generated by Django 5.0 on 2026-09-22 12:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_executive_finance_period'),
        ('invoice_tracker', '0004_rename_invoice_tra_account_dab1bb_idx_invoice_tra_account_55b104_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceivablesSourceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sha256', models.CharField(max_length=64)),
                ('file_name', models.CharField(max_length=255)),
                ('sheet_name', models.CharField(max_length=128)),
                ('header_row', models.PositiveIntegerField(default=5)),
                ('first_row', models.PositiveIntegerField(default=6)),
                ('last_row', models.PositiveIntegerField()),
                ('row_count', models.PositiveIntegerField()),
                ('imported_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=False)),
                ('reconciliation', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['-imported_at', '-pk'],
                'constraints': [models.UniqueConstraint(fields=('sha256', 'sheet_name', 'header_row', 'first_row', 'last_row'), name='finance_ar_source_identity'), models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='finance_ar_one_active_source')],
                'indexes': [],
            },
        ),
        migrations.CreateModel(
            name='ReceivablesSourceRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='finance.receivablessourcesnapshot')),
                ('row_number', models.PositiveIntegerField()),
                ('invoice_number', models.CharField(db_index=True, max_length=128)),
                # Snapshot facts are independent of operational invoice IDs.
                # 0014 detaches the old FK where this migration already ran.
                ('register_invoice_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('category', models.CharField(default='external', max_length=16)),
                ('company', models.CharField(blank=True, default='', max_length=256)),
                ('account', models.CharField(blank=True, default='', max_length=256)),
                ('pm', models.CharField(blank=True, default='', max_length=128)),
                ('project_name', models.TextField(blank=True, default='')),
                ('rad_project_no', models.CharField(blank=True, default='', max_length=128)),
                ('project_id', models.CharField(blank=True, default='', max_length=128)),
                ('payment_terms', models.CharField(blank=True, default='', max_length=128)),
                ('remarks', models.TextField(blank=True, default='')),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('invoice_sent_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, db_index=True, null=True)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('payment_status', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('raw_payment_status', models.CharField(blank=True, default='', max_length=128)),
                ('currency', models.CharField(blank=True, default='', max_length=3)),
                ('currency_status', models.CharField(default='not_recorded', max_length=20)),
                ('balance_currency', models.CharField(blank=True, default='', max_length=3)),
                ('balance_currency_status', models.CharField(default='not_recorded', max_length=20)),
                ('actual_payment_currency', models.CharField(blank=True, default='', max_length=3)),
                ('actual_payment_currency_status', models.CharField(default='not_recorded', max_length=20)),
                ('invoice_amount', models.DecimalField(blank=True, decimal_places=8, max_digits=28, null=True)),
                ('invoice_amount_aed', models.DecimalField(blank=True, decimal_places=8, max_digits=28, null=True)),
                ('balance_to_be_received', models.DecimalField(blank=True, decimal_places=8, max_digits=28, null=True)),
                ('actual_payment_received', models.DecimalField(blank=True, decimal_places=8, max_digits=28, null=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['row_number'],
                'constraints': [models.UniqueConstraint(fields=('snapshot', 'row_number'), name='finance_ar_source_row_unique')],
                'indexes': [],
            },
        ),
    ]
