# Generated by Django 5.0 on 2026-09-30 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0014_detach_receivables_invoice_reference'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceivablesSyncState',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('generation', models.PositiveBigIntegerField(default=0)),
                ('sync_token', models.UUIDField(blank=True, null=True)),
                ('sync_expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, default='', max_length=500)),
                ('remote_identity', models.CharField(blank=True, default='', max_length=64)),
                ('etag', models.CharField(blank=True, default='', max_length=512)),
                ('remote_snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='finance.receivablessourcesnapshot')),
            ],
        ),
        migrations.AddConstraint(
            model_name='receivablessyncstate',
            constraint=models.CheckConstraint(check=models.Q(('id', 1)), name='finance_ar_sync_singleton'),
        ),
    ]
