# Generated by Django 5.0 on 2025-12-18 13:01

from django.db import migrations, models


def check_and_add_column(apps, schema_editor):
    """
    SOFT-CODED IDEMPOTENT COLUMN ADDITION
    Only add column if it doesn't already exist
    """
    from django.db import connection
    
    table_name = 'pid_analysis_pidissue'
    column_name = 'location_on_drawing'
    
    with connection.cursor() as cursor:
        # Check if column exists
        cursor.execute("""
            SELECT EXISTS (
                SELECT FROM information_schema.columns 
                WHERE table_schema = 'public' 
                AND table_name = %s 
                AND column_name = %s
            )
        """, [table_name, column_name])
        
        column_exists = cursor.fetchone()[0]
        
        if not column_exists:
            # Add column using raw SQL
            cursor.execute("""
                ALTER TABLE pid_analysis_pidissue 
                ADD COLUMN location_on_drawing JSONB NULL
            """)
            print(f"✅ Added column '{column_name}' to '{table_name}'")
        else:
            print(f"ℹ️  Column '{column_name}' already exists in '{table_name}' - skipping")


def reverse_column(apps, schema_editor):
    """Remove column if migration is reversed"""
    from django.db import connection
    
    with connection.cursor() as cursor:
        cursor.execute("""
            ALTER TABLE pid_analysis_pidissue 
            DROP COLUMN IF EXISTS location_on_drawing
        """)


class Migration(migrations.Migration):
    # Mark as non-initial to enable smart checking
    initial = False

    dependencies = [
        ('pid_analysis', '0003_referencedocument'),
    ]

    operations = [
        # Use RunPython for idempotent column addition
        migrations.RunPython(
            check_and_add_column,
            reverse_column
        ),
    ]
