# Generated by Django 4.2.16 on 2026-02-10 05:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pid_analysis', '0005_piddrawing_area_piddrawing_doc_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PIDProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(editable=False, help_text='Auto-generated unique project ID', max_length=50, unique=True)),
                ('project_name', models.CharField(help_text='User-defined project name', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Optional project description', null=True)),
                ('organization', models.CharField(blank=True, help_text='Organization name for RBAC S3 path', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pid_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pid_projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='piddrawing',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Associated P&ID project', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pid_drawings', to='pid_analysis.pidproject'),
        ),
        migrations.AddIndex(
            model_name='pidproject',
            index=models.Index(fields=['project_id'], name='pid_project_project_209c56_idx'),
        ),
        migrations.AddIndex(
            model_name='pidproject',
            index=models.Index(fields=['created_by', '-created_at'], name='pid_project_created_09046f_idx'),
        ),
        migrations.AddIndex(
            model_name='pidproject',
            index=models.Index(fields=['organization'], name='pid_project_organiz_a8e179_idx'),
        ),
    ]
