# Generated by Django 5.0 on 2026-03-27 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pid_analysis', '0006_pidproject_piddrawing_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pidissue',
            name='evidence',
            field=models.TextField(blank=True, default='', help_text='AI justification: VISUAL → GAP → STANDARD evidence chain'),
        ),
    ]
