# Generated by Django 5.0 on 2026-08-05 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pid_analysis', '0009_pidproject_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
        migrations.RenameIndex(
            model_name='pidequipmentitem',
            new_name='pid_equipme_drawing_897b8a_idx',
            old_name='pid_equip_item_drw_tag_idx',
        ),
        migrations.RenameIndex(
            model_name='pidequipmentitem',
            new_name='pid_equipme_upload__6df543_idx',
            old_name='pid_equip_item_upload_idx',
        ),
            ],
        ),
    ]
