# Generated by Django 5.0 on 2026-10-07 07:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def refuse_reverse_with_equipment_evidence(apps, schema_editor):
    """Do not silently destroy issued engineering evidence during rollback."""
    EquipmentRegister = apps.get_model('pid_analysis', 'EquipmentRegister')
    if EquipmentRegister.objects.exists():
        raise RuntimeError(
            'Cannot reverse Equipment Register persistence while register data exists. '
            'Archive or export the evidence and remove it through an approved recovery procedure first.'
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_shared_record_identity'),
        ('pid_analysis', '0010_rename_pid_equip_item_drw_tag_idx_pid_equipme_drawing_897b8a_idx_and_more'),
        ('project_organizer', '0003_enterprise_project_identity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentRegister',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('register_number', models.CharField(max_length=64)),
                ('name', models.CharField(default='Equipment List', max_length=255)),
                ('discipline', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_equipment_registers', to=settings.AUTH_USER_MODEL)),
                ('enterprise_project', models.ForeignKey(blank=True, db_constraint=False, help_text='Reviewed canonical project identity copied from the organizer workspace.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipment_registers', to='core.project')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment_registers', to='project_organizer.project')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_equipment_registers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pid_equipment_registers',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('superseded', 'Superseded')], default='draft', max_length=20)),
                ('is_immutable', models.BooleanField(default=False)),
                ('version', models.PositiveIntegerField(default=1)),
                ('source_upload_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('source_files', models.JSONField(blank=True, default=list)),
                ('extraction_run', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_equipment_revisions', to=settings.AUTH_USER_MODEL)),
                ('register', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='pid_analysis.equipmentregister')),
            ],
            options={
                'db_table': 'pid_equipment_revisions',
                'ordering': ['-number'],
            },
        ),
        migrations.AddField(
            model_name='equipmentregister',
            name='current_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='pid_analysis.equipmentrevision'),
        ),
        migrations.CreateModel(
            name='EquipmentItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('tag', models.CharField(db_index=True, max_length=64)),
                ('revision_label', models.CharField(blank=True, default='', max_length=32)),
                ('description', models.CharField(blank=True, default='', max_length=300)),
                ('equipment_type', models.CharField(blank=True, default='', max_length=120)),
                ('design_flowrate', models.CharField(blank=True, default='', max_length=100)),
                ('oper_pressure', models.CharField(blank=True, default='', max_length=64)),
                ('oper_temperature', models.CharField(blank=True, default='', max_length=64)),
                ('design_pressure_min', models.CharField(blank=True, default='', max_length=64)),
                ('design_pressure_max', models.CharField(blank=True, default='', max_length=64)),
                ('design_temp_min', models.CharField(blank=True, default='', max_length=64)),
                ('design_temp_max', models.CharField(blank=True, default='', max_length=64)),
                ('moc', models.CharField(blank=True, default='', max_length=120)),
                ('insulation', models.CharField(blank=True, default='', max_length=64)),
                ('dimension_length', models.CharField(blank=True, default='', max_length=64)),
                ('dimension_diameter', models.CharField(blank=True, default='', max_length=64)),
                ('motor_rating', models.CharField(blank=True, default='', max_length=64)),
                ('pid_no', models.CharField(blank=True, default='', max_length=300)),
                ('quality_required', models.CharField(blank=True, default='', max_length=64)),
                ('phase', models.CharField(blank=True, default='', max_length=64)),
                ('remarks', models.CharField(blank=True, default='', max_length=500)),
                ('source_locator', models.JSONField(blank=True, default=dict)),
                ('confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('review_state', models.CharField(choices=[('unreviewed', 'Unreviewed'), ('reviewed', 'Reviewed'), ('discrepancy', 'Discrepancy')], default='unreviewed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='pid_analysis.equipmentrevision')),
            ],
            options={
                'db_table': 'pid_equipment_register_items',
                'ordering': ['sort_order', 'tag'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentItemChange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field', models.CharField(max_length=64)),
                ('old_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('source', models.CharField(choices=[('ai', 'AI extraction'), ('manual', 'Manual edit'), ('import', 'Import')], max_length=20)),
                ('reason', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment_item_changes', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='changes', to='pid_analysis.equipmentitem')),
            ],
            options={
                'db_table': 'pid_equipment_item_changes',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['item', 'created_at'], name='pid_equipme_item_id_f5412c_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='equipmentrevision',
            index=models.Index(fields=['register', '-number'], name='pid_equipme_registe_8de8cc_idx'),
        ),
        migrations.AddConstraint(
            model_name='equipmentrevision',
            constraint=models.UniqueConstraint(fields=('register', 'number'), name='uniq_equipment_revision_number'),
        ),
        migrations.AddIndex(
            model_name='equipmentregister',
            index=models.Index(fields=['project', 'is_active', '-updated_at'], name='pid_equipme_project_a3148d_idx'),
        ),
        migrations.AddConstraint(
            model_name='equipmentregister',
            constraint=models.UniqueConstraint(fields=('project', 'register_number'), name='uniq_equipment_register_number_per_project'),
        ),
        migrations.AddIndex(
            model_name='equipmentitem',
            index=models.Index(fields=['revision', 'tag'], name='pid_equipme_revisio_0fc07d_idx'),
        ),
        migrations.AddConstraint(
            model_name='equipmentitem',
            constraint=models.UniqueConstraint(fields=('revision', 'tag'), name='uniq_equipment_item_tag_per_revision'),
        ),
        migrations.RunPython(
            migrations.RunPython.noop,
            reverse_code=refuse_reverse_with_equipment_evidence,
        ),
    ]
