# Generated by Django 5.0 on 2026-10-07 10:19

from django.db import migrations, models


MISSING_FIELDS = [
    'Manufacturer', 'Vendor', 'Equipment Weight', 'Dry Weight',
    'Operating Weight', 'Motor Rating', 'Insulation Type', 'Painting System',
    'Purchase Order', 'Delivery Status', 'Equipment Cost',
]
RECOMMENDED_SOURCES = [
    'Equipment Datasheet', 'Vendor Package', 'Mechanical Datasheet',
    'Procurement Documents',
]


def project_existing_item_metadata(apps, schema_editor):
    EquipmentItem = apps.get_model('pid_analysis', 'EquipmentItem')
    for item in EquipmentItem.objects.filter(metadata={}).iterator(chunk_size=500):
        equipment_type = item.equipment_type or ''
        item.metadata = {
            'pid_information': {
                'drawing_no': item.pid_no or '', 'title': '',
                'equipment_tag': item.tag, 'equipment_name': item.description or '',
                'revision': item.revision_label or '', 'project': '', 'location': '',
            },
            'equipment_record': {
                'tag_number': item.tag, 'description': item.description or '',
                'type': equipment_type, 'discipline': 'Process / Mechanical',
                'area': '', 'status': 'Extracted', 'source_pid': item.pid_no or '',
                'revision': item.revision_label or '',
            },
            'engineering_specifications': {
                'design_pressure': ' / '.join(filter(None, [item.design_pressure_max, item.design_pressure_min])),
                'operating_pressure': item.oper_pressure or '',
                'design_temperature': ' / '.join(filter(None, [item.design_temp_max, item.design_temp_min])),
                'operating_temperature': item.oper_temperature or '',
                'diameter': item.dimension_diameter or '',
                'length': item.dimension_length or '',
                'material_of_construction': item.moc or '',
                'capacity': item.design_flowrate or '',
            },
            'connected_safety_equipment': {
                'pressure_safety_valves': [], 'shutdown_valves': [],
            },
            'main_process_instruments': {
                'pressure_instruments': [], 'level_instruments': [],
                'flow_instruments': [], 'temperature_instruments': [],
            },
            'connected_lines': [],
            'validation_findings': {
                'status': 'Partial Data Extracted',
                'missing_fields': MISSING_FIELDS,
                'recommended_sources': RECOMMENDED_SOURCES,
            },
            'confidence': {
                'overall': str(item.confidence) if item.confidence is not None else None,
                'fields': {},
            },
            'field_evidence': {},
        }
        item.save(update_fields=['metadata'])


def refuse_reverse_with_metadata(apps, schema_editor):
    EquipmentItem = apps.get_model('pid_analysis', 'EquipmentItem')
    if EquipmentItem.objects.exclude(metadata={}).exists():
        raise RuntimeError(
            'Cannot remove Equipment Item metadata while source-backed metadata exists. '
            'Export and remove it through an approved recovery procedure first.'
        )


class Migration(migrations.Migration):

    dependencies = [
        ('pid_analysis', '0011_equipmentregister_equipmentrevision_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentitem',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Bounded source-backed P&ID, specification, relationship, and validation metadata.'),
        ),
        migrations.RunPython(
            project_existing_item_metadata,
            reverse_code=refuse_reverse_with_metadata,
        ),
    ]
