# Generated by Django 5.0 on 2026-07-01 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0004_normalize_employee_identity'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='dailyattendancesummary',
            name='ts_daily_sum_unique_code_date',
        ),
        migrations.RemoveIndex(
            model_name='timesheetevent',
            name='ts_event_emp_name_idx',
        ),
        migrations.RemoveIndex(
            model_name='timesheetevent',
            name='ts_event_emp_email_idx',
        ),
        migrations.AlterField(
            model_name='dailyattendancesummary',
            name='effective_hours',
            field=models.FloatField(db_index=True, default=0.0, help_text='Hours field consumed by payroll and attendance reports. Equals paired_hours when mode=paired, else elapsed_hours.'),
        ),
        migrations.AlterField(
            model_name='dailyattendancesummary',
            name='paired_hours',
            field=models.FloatField(default=0.0, help_text='Sum of completed IN→OUT pair durations (hours). Only changes when a matching OUT punch arrives.'),
        ),
        migrations.AlterField(
            model_name='dailyattendancesummary',
            name='paired_segments',
            field=models.PositiveSmallIntegerField(default=0, help_text='Number of matched IN→OUT pairs.'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyattendancesummary',
            unique_together={('employee_code', 'date')},
        ),
    ]
