"""
Real-time Detection and Alert Models
Advanced ML-based anomaly detection system
"""
from django.db import models
from django.conf import settings
from django.utils import timezone
import json


class DetectionConfig(models.Model):
    """Soft-coded ML detection configuration"""
    
    DETECTION_TYPES = [
        ('anomaly', 'Anomaly Detection'),
        ('threshold', 'Threshold Alert'),
        ('pattern', 'Pattern Recognition'),
        ('prediction', 'Predictive Alert'),
        ('security', 'Security Threat'),
        ('performance', 'Performance Degradation'),
    ]
    
    SEVERITY_LEVELS = [
        ('critical', 'Critical'),
        ('high', 'High'),
        ('medium', 'Medium'),
        ('low', 'Low'),
        ('info', 'Info'),
    ]
    
    name = models.CharField(max_length=200)
    detection_type = models.CharField(max_length=50, choices=DETECTION_TYPES)
    description = models.TextField()
    
    # ML Configuration (soft-coded)
    ml_config = models.JSONField(default=dict, help_text="ML model parameters")
    threshold_config = models.JSONField(default=dict, help_text="Threshold settings")
    
    # Alert Configuration
    severity = models.CharField(max_length=20, choices=SEVERITY_LEVELS, default='medium')
    auto_notify = models.BooleanField(default=True)
    notification_channels = models.JSONField(default=list, help_text="['email', 'dashboard', 'webhook']")
    
    # Feature flags
    is_active = models.BooleanField(default=True)
    is_ml_enabled = models.BooleanField(default=True)
    cooldown_period_seconds = models.IntegerField(default=300, help_text="Time between alerts")
    
    # Metadata
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, blank=True)
    
    class Meta:
        db_table = 'ml_detection_config'
        ordering = ['-created_at']
        
    def __str__(self):
        return f"{self.name} ({self.detection_type})"


class MLDetectionModel(models.Model):
    """Store trained ML models for detection"""
    
    MODEL_TYPES = [
        ('isolation_forest', 'Isolation Forest'),
        ('autoencoder', 'Autoencoder'),
        ('lstm', 'LSTM Network'),
        ('random_forest', 'Random Forest'),
        ('gradient_boost', 'Gradient Boosting'),
        ('svm', 'Support Vector Machine'),
    ]
    
    name = models.CharField(max_length=200)
    model_type = models.CharField(max_length=50, choices=MODEL_TYPES)
    version = models.CharField(max_length=50)
    
    # Model Storage
    model_file = models.FileField(upload_to='ml_models/', null=True, blank=True)
    model_params = models.JSONField(default=dict)
    
    # Training Metrics
    accuracy = models.FloatField(null=True, blank=True)
    precision = models.FloatField(null=True, blank=True)
    recall = models.FloatField(null=True, blank=True)
    f1_score = models.FloatField(null=True, blank=True)
    
    # Training Data
    training_samples = models.IntegerField(default=0)
    training_date = models.DateTimeField(null=True, blank=True)
    feature_importance = models.JSONField(default=dict)
    
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        db_table = 'ml_detection_model'
        ordering = ['-created_at']
        
    def __str__(self):
        return f"{self.name} v{self.version}"


class RealTimeAlert(models.Model):
    """Real-time alerts generated by ML detection"""
    
    ALERT_TYPES = [
        ('anomaly_detected', 'Anomaly Detected'),
        ('threshold_exceeded', 'Threshold Exceeded'),
        ('security_threat', 'Security Threat'),
        ('performance_issue', 'Performance Issue'),
        ('pattern_match', 'Pattern Match'),
        ('prediction_warning', 'Prediction Warning'),
    ]
    
    STATUS_CHOICES = [
        ('new', 'New'),
        ('acknowledged', 'Acknowledged'),
        ('investigating', 'Investigating'),
        ('resolved', 'Resolved'),
        ('false_positive', 'False Positive'),
    ]
    
    # Alert Details
    alert_type = models.CharField(max_length=50, choices=ALERT_TYPES)
    title = models.CharField(max_length=300)
    description = models.TextField()
    severity = models.CharField(max_length=20, choices=DetectionConfig.SEVERITY_LEVELS)
    
    # Detection Information
    detection_config = models.ForeignKey(DetectionConfig, on_delete=models.SET_NULL, null=True, blank=True)
    ml_model = models.ForeignKey(MLDetectionModel, on_delete=models.SET_NULL, null=True, blank=True)
    confidence_score = models.FloatField(help_text="ML confidence 0-1")
    
    # Context Data
    detected_data = models.JSONField(default=dict, help_text="Raw data that triggered alert")
    context = models.JSONField(default=dict, help_text="Additional context")
    affected_resources = models.JSONField(default=list, help_text="Resources affected")
    
    # Status & Resolution
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='new')
    acknowledged_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, blank=True, related_name='ml_acknowledged_alerts')
    acknowledged_at = models.DateTimeField(null=True, blank=True)
    resolved_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, blank=True, related_name='ml_resolved_alerts')
    resolved_at = models.DateTimeField(null=True, blank=True)
    resolution_notes = models.TextField(blank=True)
    
    # Timestamps
    detected_at = models.DateTimeField(default=timezone.now)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    class Meta:
        db_table = 'ml_realtime_alert'
        ordering = ['-detected_at']
        indexes = [
            models.Index(fields=['-detected_at', 'severity']),
            models.Index(fields=['status', '-created_at']),
        ]
        
    def __str__(self):
        return f"{self.alert_type}: {self.title} ({self.severity})"
    
    @property
    def is_critical(self):
        return self.severity == 'critical'
    
    @property
    def time_since_detection(self):
        return timezone.now() - self.detected_at


class AnomalyDetection(models.Model):
    """Store anomaly detection results"""
    
    # Anomaly Data
    timestamp = models.DateTimeField(default=timezone.now)
    feature_name = models.CharField(max_length=200)
    observed_value = models.FloatField()
    expected_value = models.FloatField()
    deviation = models.FloatField()
    
    # ML Metrics
    anomaly_score = models.FloatField(help_text="ML anomaly score")
    threshold = models.FloatField()
    is_anomaly = models.BooleanField()
    
    # Context
    detection_model = models.ForeignKey(MLDetectionModel, on_delete=models.CASCADE)
    related_alert = models.ForeignKey(RealTimeAlert, on_delete=models.SET_NULL, null=True, blank=True)
    metadata = models.JSONField(default=dict)
    
    created_at = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        db_table = 'ml_anomaly_detection'
        ordering = ['-timestamp']
        indexes = [
            models.Index(fields=['-timestamp', 'is_anomaly']),
            models.Index(fields=['feature_name', '-timestamp']),
        ]


class DetectionMetrics(models.Model):
    """Track detection system performance"""
    
    timestamp = models.DateTimeField(default=timezone.now)
    
    # Detection Stats
    total_detections = models.IntegerField(default=0)
    true_positives = models.IntegerField(default=0)
    false_positives = models.IntegerField(default=0)
    true_negatives = models.IntegerField(default=0)
    false_negatives = models.IntegerField(default=0)
    
    # Performance Metrics
    accuracy = models.FloatField(null=True, blank=True)
    precision = models.FloatField(null=True, blank=True)
    recall = models.FloatField(null=True, blank=True)
    f1_score = models.FloatField(null=True, blank=True)
    
    # System Performance
    avg_detection_time_ms = models.FloatField(null=True, blank=True)
    total_processing_time_ms = models.FloatField(null=True, blank=True)
    
    detection_config = models.ForeignKey(DetectionConfig, on_delete=models.CASCADE)
    
    class Meta:
        db_table = 'ml_detection_metrics'
        ordering = ['-timestamp']


class RealTimeDataStream(models.Model):
    """Store real-time data for analysis"""
    
    STREAM_TYPES = [
        ('user_activity', 'User Activity'),
        ('system_metrics', 'System Metrics'),
        ('api_requests', 'API Requests'),
        ('security_events', 'Security Events'),
        ('performance', 'Performance Data'),
    ]
    
    stream_type = models.CharField(max_length=50, choices=STREAM_TYPES)
    timestamp = models.DateTimeField(default=timezone.now, db_index=True)
    
    # Data
    data = models.JSONField(help_text="Streaming data point")
    features = models.JSONField(default=dict, help_text="Extracted features for ML")
    
    # Analysis
    analyzed = models.BooleanField(default=False)
    anomaly_detected = models.BooleanField(default=False)
    ml_score = models.FloatField(null=True, blank=True)
    
    class Meta:
        db_table = 'ml_realtime_data_stream'
        ordering = ['-timestamp']
        indexes = [
            models.Index(fields=['stream_type', '-timestamp']),
            models.Index(fields=['analyzed', 'anomaly_detected']),
        ]
