# Generated by Django 4.2.30 on 2026-08-26 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_no', models.CharField(help_text="e.g. '1.1', '2.8', '3.18'", max_length=8, unique=True)),
                ('family', models.SmallIntegerField(choices=[(1, 'carbon/low-alloy steel'), (2, 'stainless steel'), (3, 'nickel alloy')])),
                ('family_name', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'valve_standards_material_group',
                'ordering': ['family', 'group_no'],
            },
        ),
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="e.g. 'ASME_B16_34'", max_length=32, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('edition_year', models.PositiveSmallIntegerField()),
            ],
            options={
                'db_table': 'valve_standards_standard',
            },
        ),
        migrations.CreateModel(
            name='WallThicknessSocketweldThreaded',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nps', models.CharField(help_text="e.g. '1-1/4'", max_length=8)),
                ('class_group', models.CharField(help_text="'150_300','600','800','900','1500','2500','4500'", max_length=16)),
                ('mm', models.DecimalField(decimal_places=3, max_digits=10)),
                ('inch', models.DecimalField(decimal_places=3, max_digits=10)),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socketweld_rows', to='valve_standards.standard')),
            ],
            options={
                'db_table': 'valve_standards_wall_thickness_socketweld_threaded',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ReferenceStandardCitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citation', models.CharField(max_length=255)),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citations', to='valve_standards.standard')),
            ],
            options={
                'db_table': 'valve_standards_reference_citation',
                'ordering': ['citation'],
            },
        ),
        migrations.CreateModel(
            name='MaterialGroupSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_form', models.CharField(choices=[('forging', 'Forging'), ('casting', 'Casting'), ('plate', 'Plate'), ('bar', 'Bar'), ('tubular', 'Tubular')], max_length=16)),
                ('seq', models.SmallIntegerField()),
                ('spec_no', models.CharField(help_text="e.g. 'A 350'", max_length=32)),
                ('grade', models.CharField(blank=True, default='', max_length=32)),
                ('material_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specs', to='valve_standards.materialgroup')),
            ],
            options={
                'db_table': 'valve_standards_material_group_spec',
                'ordering': ['material_group_id', 'product_form', 'seq'],
            },
        ),
        migrations.CreateModel(
            name='MaterialGroupDesignation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.SmallIntegerField()),
                ('composition', models.CharField(help_text="e.g. 'C-Mn-Si'", max_length=64)),
                ('material_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designations', to='valve_standards.materialgroup')),
            ],
            options={
                'db_table': 'valve_standards_material_group_designation',
                'ordering': ['material_group_id', 'seq'],
            },
        ),
        migrations.AddField(
            model_name='materialgroup',
            name='standard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_groups', to='valve_standards.standard'),
        ),
        migrations.CreateModel(
            name='Group4BoltingMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.SmallIntegerField(unique=True)),
                ('spec_no', models.CharField(max_length=32)),
                ('grade', models.CharField(blank=True, default='', max_length=64)),
                ('notes', models.JSONField(blank=True, default=list, help_text='Footnote numbers, e.g. [2, 3]')),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bolting_materials', to='valve_standards.standard')),
            ],
            options={
                'db_table': 'valve_standards_group4_bolting_material',
                'ordering': ['seq'],
            },
        ),
        migrations.CreateModel(
            name='WallThicknessByDiameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(choices=[('mm', 'mm'), ('in', 'in')], max_length=2)),
                ('inside_dia_d', models.DecimalField(decimal_places=3, max_digits=10)),
                ('class_number', models.SmallIntegerField()),
                ('min_wall_thickness_tm', models.DecimalField(decimal_places=3, max_digits=10)),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wall_thickness_rows', to='valve_standards.standard')),
            ],
            options={
                'db_table': 'valve_standards_wall_thickness_by_diameter',
                'ordering': ['unit', 'inside_dia_d'],
                'indexes': [models.Index(fields=['unit', 'class_number'], name='idx_wtbd_unit_class')],
            },
        ),
        migrations.CreateModel(
            name='PressureTemperatureRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_section', models.CharField(choices=[('A', 'Standard'), ('B', 'Special')], max_length=1)),
                ('class_type', models.CharField(help_text="'Standard' or 'Special'", max_length=16)),
                ('class_number', models.SmallIntegerField(help_text='150,300,600,900,1500,2500,4500')),
                ('temp_label', models.CharField(help_text="e.g. '-29 to 38' or '500'", max_length=32)),
                ('temp_unit', models.CharField(choices=[('C', 'Celsius'), ('F', 'Fahrenheit')], max_length=1)),
                ('pressure', models.DecimalField(blank=True, decimal_places=2, help_text='NULL where the standard has no established rating at this point', max_digits=10, null=True)),
                ('pressure_unit', models.CharField(choices=[('bar', 'bar'), ('psig', 'psig')], max_length=8)),
                ('material_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='valve_standards.materialgroup')),
            ],
            options={
                'db_table': 'valve_standards_pt_rating',
                'indexes': [models.Index(fields=['material_group', 'class_number', 'class_section'], name='idx_rating_group_class_section')],
            },
        ),
        migrations.CreateModel(
            name='NpsToInsideDiameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nps', models.CharField(max_length=8)),
                ('dn', models.SmallIntegerField()),
                ('class_number', models.SmallIntegerField()),
                ('mm', models.DecimalField(decimal_places=3, max_digits=10)),
                ('inch', models.DecimalField(decimal_places=3, max_digits=10)),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nps_to_id_rows', to='valve_standards.standard')),
            ],
            options={
                'db_table': 'valve_standards_nps_to_inside_diameter',
                'ordering': ['dn'],
                'indexes': [models.Index(fields=['class_number'], name='idx_nps_id_class')],
            },
        ),
        migrations.AddConstraint(
            model_name='materialgroupspec',
            constraint=models.UniqueConstraint(fields=('material_group', 'product_form', 'seq'), name='uq_spec_group_form_seq'),
        ),
        migrations.AddConstraint(
            model_name='materialgroupdesignation',
            constraint=models.UniqueConstraint(fields=('material_group', 'seq'), name='uq_designation_group_seq'),
        ),
    ]
