# Generated by Django 5.0 on 2026-08-26 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valve_standards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CastingQualityFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, default='', help_text="e.g. 'Iron', 'Carbon Steel'", max_length=64)),
                ('spec_no', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=255)),
                ('ec', models.DecimalField(decimal_places=2, max_digits=4)),
                ('notes', models.CharField(blank=True, default='', max_length=64)),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casting_quality_factors', to='valve_standards.standard')),
            ],
            options={
                'db_table': 'valve_standards_b313_casting_quality_factor',
            },
        ),
        migrations.CreateModel(
            name='HighPressureAllowableStress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, default='', max_length=128)),
                ('composition', models.CharField(blank=True, default='', max_length=128)),
                ('product_form', models.CharField(blank=True, default='', max_length=32)),
                ('spec_no', models.CharField(max_length=32)),
                ('type_grade', models.CharField(blank=True, default='', max_length=32)),
                ('uns_no', models.CharField(blank=True, default='', max_length=16)),
                ('p_no', models.CharField(blank=True, default='', max_length=16)),
                ('notes', models.CharField(blank=True, default='', max_length=64)),
                ('tensile_ksi', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('yield_ksi', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='high_pressure_allowable_stresses', to='valve_standards.standard')),
            ],
            options={
                'db_table': 'valve_standards_b313_high_pressure_allowable_stress',
            },
        ),
        migrations.CreateModel(
            name='HighPressureAllowableStressPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_f', models.SmallIntegerField()),
                ('allowable_stress_ksi', models.DecimalField(decimal_places=2, max_digits=8)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='valve_standards.highpressureallowablestress')),
            ],
            options={
                'db_table': 'valve_standards_b313_high_pressure_allowable_stress_point',
                'ordering': ['temp_f'],
            },
        ),
        migrations.CreateModel(
            name='MaterialAllowableStress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, default='', help_text="e.g. 'Carbon Steel — Pipes and Tubes'", max_length=128)),
                ('composition', models.CharField(blank=True, default='', max_length=128)),
                ('product_form', models.CharField(blank=True, default='', help_text="e.g. 'Bolts', 'Tube', 'Forgings'", max_length=32)),
                ('spec_no', models.CharField(help_text="e.g. 'A53'", max_length=32)),
                ('type_grade', models.CharField(blank=True, default='', max_length=32)),
                ('uns_no', models.CharField(blank=True, default='', max_length=16)),
                ('class_condition', models.CharField(blank=True, default='', max_length=64)),
                ('size', models.CharField(blank=True, default='', max_length=64)),
                ('p_no', models.CharField(blank=True, default='', max_length=16)),
                ('notes', models.CharField(blank=True, default='', max_length=64)),
                ('min_temp', models.CharField(blank=True, default='', help_text='numeric °F or a lettered curve code', max_length=16)),
                ('tensile_ksi', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('yield_ksi', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_allowable_stresses', to='valve_standards.standard')),
            ],
            options={
                'db_table': 'valve_standards_b313_material_allowable_stress',
            },
        ),
        migrations.CreateModel(
            name='MaterialAllowableStressPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_f', models.SmallIntegerField()),
                ('allowable_stress_ksi', models.DecimalField(decimal_places=2, max_digits=8)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='valve_standards.materialallowablestress')),
            ],
            options={
                'db_table': 'valve_standards_b313_material_allowable_stress_point',
                'ordering': ['temp_f'],
            },
        ),
        migrations.CreateModel(
            name='ModulusOfElasticity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=128)),
                ('modulus_1e6_psi', models.JSONField(help_text="{'-425': 31.9, '70': 29.4, ...}")),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moduli_of_elasticity', to='valve_standards.standard')),
            ],
            options={
                'db_table': 'valve_standards_b313_modulus_of_elasticity',
            },
        ),
        migrations.CreateModel(
            name='ThermalExpansionCoefficient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=128)),
                ('coefficient_1e6_in_per_in_f', models.JSONField(help_text="{'-325': 5.5, '70': 6.4, ...}")),
                ('linear_expansion_in_per_100ft', models.JSONField()),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thermal_expansion_coefficients', to='valve_standards.standard')),
            ],
            options={
                'db_table': 'valve_standards_b313_thermal_expansion_coefficient',
            },
        ),
        migrations.CreateModel(
            name='WeldJointQualityFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, default='', max_length=64)),
                ('spec_no', models.CharField(max_length=32)),
                ('class_or_type', models.CharField(blank=True, default='', max_length=32)),
                ('description', models.CharField(max_length=255)),
                ('ej', models.DecimalField(decimal_places=2, max_digits=4)),
                ('notes', models.CharField(blank=True, default='', max_length=64)),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weld_joint_quality_factors', to='valve_standards.standard')),
            ],
            options={
                'db_table': 'valve_standards_b313_weld_joint_quality_factor',
            },
        ),
        migrations.AddIndex(
            model_name='highpressureallowablestress',
            index=models.Index(fields=['spec_no', 'type_grade'], name='idx_b313_hpas_spec_grade'),
        ),
        migrations.AddConstraint(
            model_name='highpressureallowablestresspoint',
            constraint=models.UniqueConstraint(fields=('material', 'temp_f'), name='uq_b313_hpas_point_temp'),
        ),
        migrations.AddIndex(
            model_name='materialallowablestress',
            index=models.Index(fields=['spec_no', 'type_grade'], name='idx_b313_mas_spec_grade'),
        ),
        migrations.AddConstraint(
            model_name='materialallowablestresspoint',
            constraint=models.UniqueConstraint(fields=('material', 'temp_f'), name='uq_b313_mas_point_temp'),
        ),
    ]
