# Generated by Django 5.0 on 2026-08-26 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valve_standards', '0002_castingqualityfactor_highpressureallowablestress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highpressureallowablestress',
            name='uns_no',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='materialallowablestress',
            name='uns_no',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
