# Generated by Django 5.0 on 2026-08-26 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valve_standards', '0003_alter_highpressureallowablestress_uns_no_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrillingTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_number', models.SmallIntegerField(help_text='150,300,400,600,900,1500,2500')),
                ('unit', models.CharField(choices=[('mm', 'mm'), ('in', 'in')], max_length=2)),
                ('nps', models.CharField(help_text="e.g. '1-1/4'", max_length=8)),
                ('outside_diameter_o', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('bolt_circle_w', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('bolt_hole_diameter', models.CharField(blank=True, default='', help_text="e.g. '5/8' (inch, printed as a fraction)", max_length=16)),
                ('num_bolts', models.SmallIntegerField(blank=True, null=True)),
                ('bolt_diameter', models.CharField(blank=True, default='', help_text="e.g. '1/2' (inch, printed as a fraction)", max_length=16)),
                ('bolt_length_1', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('bolt_length_2', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('bolt_length_3', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('note', models.CharField(blank=True, default='', help_text="e.g. referral to another class's table for this NPS", max_length=255)),
            ],
            options={
                'db_table': 'valve_standards_b165_drilling_template',
                'ordering': ['class_number', 'unit', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FlangeBoltingRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(help_text="e.g. 'Stud bolts', 'Nuts smaller than 3/4 in.'", max_length=64)),
                ('carbon_steel', models.CharField(max_length=255)),
                ('alloy_steel', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'valve_standards_b165_flange_bolting_recommendation',
            },
        ),
        migrations.CreateModel(
            name='FlangeDimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_number', models.SmallIntegerField(help_text='150,300,400,600,900,1500,2500')),
                ('unit', models.CharField(choices=[('mm', 'mm'), ('in', 'in')], max_length=2)),
                ('nps', models.CharField(help_text="e.g. '1-1/4'", max_length=8)),
                ('outside_diameter_o', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('values', models.JSONField(blank=True, help_text='Ordered raw dimension cells beyond O, as printed', null=True)),
                ('note', models.CharField(blank=True, default='', help_text="e.g. referral to another class's table for this NPS", max_length=255)),
            ],
            options={
                'db_table': 'valve_standards_b165_flange_dimension',
                'ordering': ['class_number', 'unit', 'id'],
            },
        ),
        migrations.AlterField(
            model_name='materialgroup',
            name='group_no',
            field=models.CharField(help_text="e.g. '1.1', '2.8', '3.18'", max_length=8),
        ),
        migrations.AddConstraint(
            model_name='materialgroup',
            constraint=models.UniqueConstraint(fields=('standard', 'group_no'), name='uq_material_group_standard_group_no'),
        ),
        migrations.AddField(
            model_name='drillingtemplate',
            name='standard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drilling_templates', to='valve_standards.standard'),
        ),
        migrations.AddField(
            model_name='flangeboltingrecommendation',
            name='standard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flange_bolting_recommendations', to='valve_standards.standard'),
        ),
        migrations.AddField(
            model_name='flangedimension',
            name='standard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flange_dimensions', to='valve_standards.standard'),
        ),
        migrations.AddIndex(
            model_name='drillingtemplate',
            index=models.Index(fields=['class_number', 'unit'], name='idx_b165_drilling_class_unit'),
        ),
        migrations.AddIndex(
            model_name='flangedimension',
            index=models.Index(fields=['class_number', 'unit'], name='idx_b165_flange_dim_class_unit'),
        ),
    ]
