# Generated by Django 5.0 on 2026-09-07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valve_standards', '0004_drillingtemplate_flangeboltingrecommendation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PipeClassConversationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_sheet', models.CharField(max_length=64)),
                ('source_row', models.PositiveIntegerField()),
                ('record_type', models.CharField(blank=True, default='', help_text="e.g. 'index_entry', 'sheet_row', 'branch_row'", max_length=32)),
                ('primary_key_text', models.CharField(blank=True, default='', help_text='Convenience key for quick UI filtering/search', max_length=128)),
                ('cells', models.JSONField(help_text='Ordered row cell values as strings/nulls')),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipe_class_conversation_records', to='valve_standards.standard')),
            ],
            options={
                'db_table': 'valve_standards_pipe_class_conversation_record',
                'ordering': ['source_sheet', 'source_row', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='pipeclassconversationrecord',
            index=models.Index(fields=['standard', 'source_sheet'], name='idx_vs_pcc_standard_sheet'),
        ),
        migrations.AddIndex(
            model_name='pipeclassconversationrecord',
            index=models.Index(fields=['standard', 'record_type'], name='idx_vs_pcc_standard_type'),
        ),
    ]
