# Generated by Django 5.0 on 2026-01-08 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfd_converter', '0002_pfddocument_uploaded_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pfddocument',
            name='comprehensive_analysis',
            field=models.JSONField(default=dict, help_text='Comprehensive GPT-4 Vision analysis with equipment specs, line sizes, instruments, etc.'),
        ),
    ]
