# Generated by Django 5.0 on 2026-01-09 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfd_converter', '0003_pfddocument_comprehensive_analysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='pfddocument',
            name='philosophy_file',
            field=models.FileField(blank=True, null=True, upload_to='philosophy_documents/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='pfddocument',
            name='philosophy_file_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='pfddocument',
            name='philosophy_file_size',
            field=models.BigIntegerField(blank=True, help_text='File size in bytes', null=True),
        ),
        migrations.AddField(
            model_name='pfddocument',
            name='philosophy_file_type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
