# Generated by Django 5.0 on 2026-01-09 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfd_converter', '0004_pfddocument_philosophy_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pfddocument',
            name='status',
            field=models.CharField(choices=[('uploaded', 'Uploaded'), ('analyzing', 'Analyzing'), ('analyzed', 'Analyzed'), ('processing', 'Processing'), ('processed', 'Processed'), ('converted', 'Converted'), ('failed', 'Failed'), ('approved', 'Approved')], default='uploaded', max_length=20),
        ),
    ]
