# Generated by Django 5.0 on 2026-01-10 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfd_converter', '0005_alter_pfddocument_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pfddocument',
            name='analysis_progress',
            field=models.IntegerField(default=0, help_text='Analysis progress percentage (0-100)'),
        ),
        migrations.AddField(
            model_name='pfddocument',
            name='analysis_stage',
            field=models.IntegerField(default=0, help_text='Current analysis stage (0-5)'),
        ),
        migrations.AddField(
            model_name='pfddocument',
            name='stage1_module_identification',
            field=models.JSONField(default=dict, help_text='Stage 1: Identified modules from PFD (PV, LV, A/B, etc.) with detailed specifications'),
        ),
        migrations.AddField(
            model_name='pfddocument',
            name='stage2_module_details',
            field=models.JSONField(default=dict, help_text='Stage 2: Detailed understanding of all modules including equipment, instruments, piping'),
        ),
        migrations.AddField(
            model_name='pfddocument',
            name='stage3_pid_complexity',
            field=models.JSONField(default=dict, help_text='Stage 3: Number of P&IDs required based on complexity analysis'),
        ),
        migrations.AddField(
            model_name='pfddocument',
            name='stage4_module_coverage',
            field=models.JSONField(default=dict, help_text='Stage 4: Modules covered in each P&ID drawing'),
        ),
        migrations.AddField(
            model_name='pfddocument',
            name='stage5_connectivity',
            field=models.JSONField(default=dict, help_text='Stage 5: Connectivity and relationships between modules'),
        ),
    ]
