# Generated by Django 5.0 on 2026-01-11 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfd_converter', '0006_pfddocument_analysis_progress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pfddocument',
            name='yolov8_detections',
            field=models.JSONField(default=dict, help_text='YOLOv8 detected P&ID symbols with bounding boxes and confidence scores'),
        ),
    ]
