# Generated by Django 5.0 on 2026-07-01 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_tracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='customerinvoice',
            new_name='invoice_tra_account_55b104_idx',
            old_name='invoice_tra_account_dab1bb_idx',
        ),
        migrations.RenameIndex(
            model_name='customerinvoice',
            new_name='invoice_tra_rad_pro_21a969_idx',
            old_name='invoice_tra_rad_pro_71f8b9_idx',
        ),
    ]
