# Generated by Django 4.2.16 on 2026-07-10 17:04
# FIXED: Changed RenameIndex to conditional RunSQL to handle missing indexes

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_tracker', '0002_rename_invoice_tra_account_dab1bb_idx_invoice_tra_account_55b104_idx_and_more'),
    ]

    operations = [
        # Conditionally rename indexes only if they exist (prevents production errors)
        migrations.RunSQL(
            sql="""
                DO $$ BEGIN
                    IF EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'invoice_tra_account_dab1bb_idx') THEN
                        ALTER INDEX invoice_tra_account_dab1bb_idx RENAME TO invoice_tra_account_55b104_idx;
                    END IF;
                END $$;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="""
                DO $$ BEGIN
                    IF EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'invoice_tra_rad_pro_71f8b9_idx') THEN
                        ALTER INDEX invoice_tra_rad_pro_71f8b9_idx RENAME TO invoice_tra_rad_pro_21a969_idx;
                    END IF;
                END $$;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
