# Generated by Django 4.2.16 on 2026-07-10 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_tracker', '0002_rename_invoice_tra_account_dab1bb_idx_invoice_tra_account_55b104_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='customerinvoice',
            new_name='invoice_tra_account_55b104_idx',
            old_name='invoice_tra_account_dab1bb_idx',
        ),
        migrations.RenameIndex(
            model_name='customerinvoice',
            new_name='invoice_tra_rad_pro_21a969_idx',
            old_name='invoice_tra_rad_pro_71f8b9_idx',
        ),
    ]
