# Generated by Django 5.0 on 2026-07-01 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_visits', '0001_init_site_visit_tracking'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='clientsite',
            new_name='site_visit__client__eb6632_idx',
            old_name='site_visit__client__8d4e85_idx',
        ),
        migrations.RenameIndex(
            model_name='clientsite',
            new_name='site_visit__is_acti_685e85_idx',
            old_name='site_visit__is_acti_8a90f0_idx',
        ),
        migrations.RenameIndex(
            model_name='sitevisitcheckin',
            new_name='site_visit__employe_a42731_idx',
            old_name='site_visit__employe_7a9e3b_idx',
        ),
        migrations.RenameIndex(
            model_name='sitevisitcheckin',
            new_name='site_visit__site_id_1bc7ef_idx',
            old_name='site_visit__site_id_2c7f4a_idx',
        ),
        migrations.RenameIndex(
            model_name='sitevisitcheckin',
            new_name='site_visit__check_i_b3b837_idx',
            old_name='site_visit__check_i_5e8b9c_idx',
        ),
        migrations.RenameIndex(
            model_name='sitevisitrequest',
            new_name='site_visit__employe_9398a8_idx',
            old_name='site_visit__employe_9e4e8c_idx',
        ),
        migrations.RenameIndex(
            model_name='sitevisitrequest',
            new_name='site_visit__status_ff8f81_idx',
            old_name='site_visit__status_4c1e9f_idx',
        ),
        migrations.RenameIndex(
            model_name='sitevisitrequest',
            new_name='site_visit__site_id_c1fcf0_idx',
            old_name='site_visit__site_id_3f8e1d_idx',
        ),
    ]
