# Generated by Django 5.0 on 2026-07-01 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pid_verification', '0006_pidv_instrument_symbol'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='pidvdocument',
            new_name='pidv_docume_documen_c78616_idx',
            old_name='pidv_docs_doc_id_idx',
        ),
        migrations.RenameIndex(
            model_name='pidvdocument',
            new_name='pidv_docume_file_ha_5f2bf8_idx',
            old_name='pidv_docs_hash_idx',
        ),
        migrations.RenameIndex(
            model_name='pidvdocument',
            new_name='pidv_docume_status_0f5f23_idx',
            old_name='pidv_docs_status_idx',
        ),
        migrations.RenameIndex(
            model_name='pidvdocument',
            new_name='pidv_docume_uploade_af901c_idx',
            old_name='pidv_docs_user_idx',
        ),
        migrations.RenameIndex(
            model_name='pidvinstrumentsymbol',
            new_name='pidv_instru_project_a9b6c6_idx',
            old_name='pidv_is_proj_cat_idx',
        ),
        migrations.RenameIndex(
            model_name='pidvinstrumentsymbol',
            new_name='pidv_instru_symbol__b23512_idx',
            old_name='pidv_is_symbol_id_idx',
        ),
        migrations.RenameIndex(
            model_name='pidvinstrumentsymbol',
            new_name='pidv_instru_symbol__896db2_idx',
            old_name='pidv_is_code_idx',
        ),
        migrations.RenameIndex(
            model_name='pidvlegendsheet',
            new_name='pidv_legend_legend__4142c4_idx',
            old_name='pidv_ls_legend_id_idx',
        ),
        migrations.RenameIndex(
            model_name='pidvlegendsheet',
            new_name='pidv_legend_project_e3c8e5_idx',
            old_name='pidv_ls_proj_status_idx',
        ),
        migrations.RenameIndex(
            model_name='pidvproject',
            new_name='pidv_projec_project_5ecddd_idx',
            old_name='pidv_project_id_idx',
        ),
        migrations.AlterField(
            model_name='pidvdocument',
            name='status',
            field=models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('legend_pending', 'Waiting for Legend')], default='uploaded', max_length=20),
        ),
        migrations.AlterField(
            model_name='pidvinstrumentsymbol',
            name='attributes',
            field=models.JSONField(blank=True, default=dict, help_text='Flexible per-category attributes (see docstring for schema)'),
        ),
        migrations.AlterField(
            model_name='pidvlegendsheet',
            name='extracted_data',
            field=models.JSONField(blank=True, help_text='Structured legend data extracted by AI (see docstring for schema)', null=True),
        ),
        migrations.AddIndex(
            model_name='pidvdrawing',
            index=models.Index(fields=['document', 'drawing_id'], name='pidv_drawin_documen_eb66be_idx'),
        ),
        migrations.AddIndex(
            model_name='pidvfinding',
            index=models.Index(fields=['drawing', 'sl_no'], name='pidv_findin_drawing_db8fef_idx'),
        ),
        migrations.AddIndex(
            model_name='pidvfinding',
            index=models.Index(fields=['severity'], name='pidv_findin_severit_227df6_idx'),
        ),
        migrations.AddIndex(
            model_name='pidvfinding',
            index=models.Index(fields=['category'], name='pidv_findin_categor_bd5212_idx'),
        ),
    ]
