# Generated by Django 4.2.16 on 2026-07-10 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pid_verification', '0007_rename_pidv_docs_doc_id_idx_pidv_docume_documen_c78616_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='pidvdocument',
            new_name='pidv_docume_documen_c78616_idx',
            old_name='pidv_docs_doc_id_idx',
        ),
        migrations.RenameIndex(
            model_name='pidvdocument',
            new_name='pidv_docume_file_ha_5f2bf8_idx',
            old_name='pidv_docs_hash_idx',
        ),
        migrations.RenameIndex(
            model_name='pidvdocument',
            new_name='pidv_docume_status_0f5f23_idx',
            old_name='pidv_docs_status_idx',
        ),
        migrations.RenameIndex(
            model_name='pidvdocument',
            new_name='pidv_docume_uploade_af901c_idx',
            old_name='pidv_docs_user_idx',
        ),
        migrations.RenameIndex(
            model_name='pidvinstrumentsymbol',
            new_name='pidv_instru_project_a9b6c6_idx',
            old_name='pidv_is_proj_cat_idx',
        ),
        migrations.RenameIndex(
            model_name='pidvinstrumentsymbol',
            new_name='pidv_instru_symbol__b23512_idx',
            old_name='pidv_is_symbol_id_idx',
        ),
        migrations.RenameIndex(
            model_name='pidvinstrumentsymbol',
            new_name='pidv_instru_symbol__896db2_idx',
            old_name='pidv_is_code_idx',
        ),
        migrations.RenameIndex(
            model_name='pidvlegendsheet',
            new_name='pidv_legend_legend__4142c4_idx',
            old_name='pidv_ls_legend_id_idx',
        ),
        migrations.RenameIndex(
            model_name='pidvlegendsheet',
            new_name='pidv_legend_project_e3c8e5_idx',
            old_name='pidv_ls_proj_status_idx',
        ),
        migrations.RenameIndex(
            model_name='pidvproject',
            new_name='pidv_projec_project_5ecddd_idx',
            old_name='pidv_project_id_idx',
        ),
    ]
