# Generated by Django 4.2.16 on 2026-07-10 17:04
# FIXED: Changed RenameIndex to conditional RunSQL to handle missing indexes

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pid_verification', '0007_rename_pidv_docs_doc_id_idx_pidv_docume_documen_c78616_idx_and_more'),
    ]

    operations = [
        migrations.RunSQL(sql="""DO $$ BEGIN IF EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'pidv_docs_doc_id_idx') THEN ALTER INDEX pidv_docs_doc_id_idx RENAME TO pidv_docume_documen_c78616_idx; END IF; END $$;""", reverse_sql=migrations.RunSQL.noop),
        migrations.RunSQL(sql="""DO $$ BEGIN IF EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'pidv_docs_hash_idx') THEN ALTER INDEX pidv_docs_hash_idx RENAME TO pidv_docume_file_ha_5f2bf8_idx; END IF; END $$;""", reverse_sql=migrations.RunSQL.noop),
        migrations.RunSQL(sql="""DO $$ BEGIN IF EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'pidv_docs_status_idx') THEN ALTER INDEX pidv_docs_status_idx RENAME TO pidv_docume_status_0f5f23_idx; END IF; END $$;""", reverse_sql=migrations.RunSQL.noop),
        migrations.RunSQL(sql="""DO $$ BEGIN IF EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'pidv_docs_user_idx') THEN ALTER INDEX pidv_docs_user_idx RENAME TO pidv_docume_uploade_af901c_idx; END IF; END $$;""", reverse_sql=migrations.RunSQL.noop),
        migrations.RunSQL(sql="""DO $$ BEGIN IF EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'pidv_is_proj_cat_idx') THEN ALTER INDEX pidv_is_proj_cat_idx RENAME TO pidv_instru_project_a9b6c6_idx; END IF; END $$;""", reverse_sql=migrations.RunSQL.noop),
        migrations.RunSQL(sql="""DO $$ BEGIN IF EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'pidv_is_symbol_id_idx') THEN ALTER INDEX pidv_is_symbol_id_idx RENAME TO pidv_instru_symbol__b23512_idx; END IF; END $$;""", reverse_sql=migrations.RunSQL.noop),
        migrations.RunSQL(sql="""DO $$ BEGIN IF EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'pidv_is_code_idx') THEN ALTER INDEX pidv_is_code_idx RENAME TO pidv_instru_symbol__896db2_idx; END IF; END $$;""", reverse_sql=migrations.RunSQL.noop),
        migrations.RunSQL(sql="""DO $$ BEGIN IF EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'pidv_ls_legend_id_idx') THEN ALTER INDEX pidv_ls_legend_id_idx RENAME TO pidv_legend_legend__4142c4_idx; END IF; END $$;""", reverse_sql=migrations.RunSQL.noop),
        migrations.RunSQL(sql="""DO $$ BEGIN IF EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'pidv_ls_proj_status_idx') THEN ALTER INDEX pidv_ls_proj_status_idx RENAME TO pidv_legend_project_e3c8e5_idx; END IF; END $$;""", reverse_sql=migrations.RunSQL.noop),
        migrations.RunSQL(sql="""DO $$ BEGIN IF EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'pidv_project_id_idx') THEN ALTER INDEX pidv_project_id_idx RENAME TO pidv_projec_project_5ecddd_idx; END IF; END $$;""", reverse_sql=migrations.RunSQL.noop),
    ]
