# Generated by Django 5.0 on 2026-07-23 08:00

import apps.pid_verification.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pid_verification', '0008_rename_pidv_docs_doc_id_idx_pidv_docume_documen_c78616_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PIDVReferenceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('data_type', models.CharField(choices=[('line_list', 'Line List'), ('equipment_list', 'Equipment List'), ('instrument_index', 'Instrument Index')], db_index=True, max_length=30)),
                ('file_name', models.CharField(max_length=512)),
                ('original_file', models.FileField(blank=True, max_length=500, null=True, upload_to=apps.pid_verification.models._reference_data_upload_path)),
                ('s3_path', models.CharField(blank=True, max_length=1024)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('parsed_data', models.JSONField(blank=True, help_text='Parsed tabular data from Excel/CSV files', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='File metadata: row_count, columns, file_size_bytes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_data', to='pid_verification.pidvproject')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pid_reference_data', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pidv_reference_data',
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(fields=['reference_id'], name='pidv_refere_referen_049cbb_idx'),
                    models.Index(fields=['project', 'data_type'], name='pidv_refere_project_fae9d6_idx'),
                ],
            },
        ),
    ]
