# Generated by Django 5.0 on 2026-08-28 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pid_verification', '0013_repair_remaining_primary_keys'),
    ]

    operations = [
        migrations.CreateModel(
            name='PIDVTagIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.PositiveSmallIntegerField(help_text='page_index of the source PIDVDrawing')),
                ('tag', models.CharField(db_index=True, help_text="normalize_tag()'d form — the matching key", max_length=255)),
                ('raw_tag', models.CharField(help_text='Original as-extracted tag text', max_length=255)),
                ('tag_type', models.CharField(choices=[('line', 'Line'), ('equipment', 'Equipment'), ('instrument', 'Instrument'), ('valve', 'Valve')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_index', to='pid_verification.pidvdocument')),
            ],
            options={
                'db_table': 'pidv_tag_index',
                'indexes': [models.Index(fields=['document', 'tag'], name='pidv_tag_in_documen_80f2fd_idx'), models.Index(fields=['document', 'page_number'], name='pidv_tag_in_documen_8ddf11_idx')],
            },
        ),
    ]
