# Generated by Django 5.0 on 2026-07-20 07:50

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spec_customization', '0004_add_component_matching_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='paperspecextractionjob',
            name='gemini_prompt_tokens',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='paperspecextractionjob',
            name='gemini_completion_tokens',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='paperspecextractionjob',
            name='openai_prompt_tokens',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='paperspecextractionjob',
            name='openai_completion_tokens',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='paperspecextractionjob',
            name='cost_usd',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=10),
        ),
    ]
