# Generated by Django 5.0 on 2026-07-20 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spec_customization', '0005_rename_spec_cust_pa_sha256__idx_spec_custom_sha256__ce399b_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paperspecextractionjob',
            name='engineer_name',
            field=models.CharField(blank=True, default='', help_text='Optional engineer attribution (e.g. site inspector name)', max_length=255),
        ),
        migrations.AddField(
            model_name='paperspecextractionjob',
            name='user_openai_api_key',
            field=models.TextField(blank=True, default='', help_text='Optional user-supplied OpenAI API key (wiped post-extraction)'),
        ),
    ]
