# Generated by Django 5.0 on 2026-08-05 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spec_customization', '0006_add_byok_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='paperspecdocument',
            new_name='spec_custom_sha256__ce399b_idx',
            old_name='spec_cust_pa_sha256__idx',
        ),
        migrations.RenameIndex(
            model_name='paperspecdocument',
            new_name='spec_custom_created_e3e559_idx',
            old_name='spec_cust_pa_created_idx',
        ),
        migrations.RenameIndex(
            model_name='paperspecextractionjob',
            new_name='spec_custom_status_cc7b14_idx',
            old_name='spec_cust_jo_status_idx',
        ),
        migrations.RenameIndex(
            model_name='paperspecextractionjob',
            new_name='spec_custom_celery__66a838_idx',
            old_name='spec_cust_jo_celery_idx',
        ),
        migrations.RenameIndex(
            model_name='pipingclass',
            new_name='spec_custom_job_id_752a66_idx',
            old_name='spec_cust_pc_job_code_idx',
        ),
        migrations.RenameIndex(
            model_name='pipingclasscomponent',
            new_name='spec_custom_piping__35b7ee_idx',
            old_name='spec_cust_pcc_pc_type_idx',
        ),
    ]
