# Generated by Django 5.0 on 2026-08-17 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spec_customization', '0007_rename_spec_cust_pa_sha256__idx_spec_custom_sha256__ce399b_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paperspecextractionjob',
            name='user_ai_model',
            field=models.CharField(blank=True, default='', help_text='Specific AI model ID (e.g. "gpt-4o", "claude-3-5-sonnet-20241022")', max_length=100),
        ),
        migrations.AddField(
            model_name='paperspecextractionjob',
            name='user_ai_provider',
            field=models.CharField(blank=True, default='', help_text='AI provider used: "openai" or "claude"', max_length=20),
        ),
        migrations.AddField(
            model_name='paperspecextractionjob',
            name='user_claude_api_key',
            field=models.TextField(blank=True, default='', help_text='Optional user-supplied Claude API key (wiped post-extraction)'),
        ),
    ]
