# Generated by Django 5.0 on 2026-09-15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spec_customization', '0008_paperspecextractionjob_user_ai_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workbookcelloverride',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workbookcelloverride',
            name='auto_value_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workbookcelloverride',
            name='edit_origin',
            field=models.CharField(choices=[('manual', 'Manual'), ('chatbot', 'Workbook chatbot')], default='manual', max_length=16),
        ),
        migrations.AddField(
            model_name='workbookcelloverride',
            name='evidence_pages',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='workbookcelloverride',
            name='source_class',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workbook_overrides', to='spec_customization.pipingclass'),
        ),
        migrations.AddField(
            model_name='workbookcelloverride',
            name='source_component',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workbook_overrides', to='spec_customization.pipingclasscomponent'),
        ),
    ]
