# Generated by Django 4.2.16 on 2026-07-10 17:04
# FIXED: Changed RenameIndex to conditional RunSQL to handle missing indexes

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_crossdisciplinerecommendation_documentrelationship_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""DO $$ BEGIN IF EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'core_enquir_created_idx') THEN ALTER INDEX core_enquir_created_idx RENAME TO core_enquir_created_8e0bcb_idx; END IF; END $$;""",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="""DO $$ BEGIN IF EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'core_enquir_status_idx') THEN ALTER INDEX core_enquir_status_idx RENAME TO core_enquir_status_2f25e5_idx; END IF; END $$;""",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
