# Generated by Django 4.2.16 on 2026-07-10 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_crossdisciplinerecommendation_documentrelationship_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='enquiry',
            new_name='core_enquir_created_8e0bcb_idx',
            old_name='core_enquir_created_idx',
        ),
        migrations.RenameIndex(
            model_name='enquiry',
            new_name='core_enquir_status_2f25e5_idx',
            old_name='core_enquir_status_idx',
        ),
    ]
