# Generated by Django 4.2.16 on 2026-07-15 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_core_enquir_created_idx_core_enquir_created_8e0bcb_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='enquiry',
            new_name='core_enquir_created_8e0bcb_idx',
            old_name='core_enquir_created_idx',
        ),
        migrations.RenameIndex(
            model_name='enquiry',
            new_name='core_enquir_status_2f25e5_idx',
            old_name='core_enquir_status_idx',
        ),
    ]
