# Generated by Django 4.2.16 on 2026-07-15 07:15
# FIXED: 0005 already performs the actual DB-level rename defensively
# (conditional RunSQL with "IF EXISTS" guards). By the time this migration
# runs, the old index names no longer exist under any circumstance (either
# already renamed by 0005, or never existed), so a plain RenameIndex here
# always fails with "relation ... does not exist" in production. This
# migration now only syncs Django's migration state to match the model
# Meta.indexes (new names) without touching the actual database schema.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_core_enquir_created_idx_core_enquir_created_8e0bcb_idx_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RenameIndex(
                    model_name='enquiry',
                    new_name='core_enquir_created_8e0bcb_idx',
                    old_name='core_enquir_created_idx',
                ),
                migrations.RenameIndex(
                    model_name='enquiry',
                    new_name='core_enquir_status_2f25e5_idx',
                    old_name='core_enquir_status_idx',
                ),
            ],
        ),
    ]
