# Generated by Django 4.2.16
# ApiUsageLog is managed=False: it maps to the pre-existing `api_usage_logs`
# table (created outside Django's migrations, no prior migration record for
# it). This migration only registers the model in Django's migration state
# so `makemigrations --check` stays clean — `migrate` issues no DDL for
# managed=False models, so the real table is never touched.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_core_enquir_created_idx_core_enquir_created_8e0bcb_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiUsageLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('endpoint', models.CharField(max_length=255)),
                ('method', models.CharField(max_length=10)),
                ('user_id', models.IntegerField()),
                ('status_code', models.IntegerField()),
                ('response_time_ms', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'db_table': 'api_usage_logs',
                'managed': False,
                'indexes': [
                    models.Index(fields=['endpoint', 'timestamp'], name='api_usage_l_endpoin_bc57dc_idx'),
                    models.Index(fields=['user_id', 'timestamp'], name='api_usage_l_user_id_786284_idx'),
                ],
            },
        ),
    ]
