# Generated by Django 5.2.15
# Document and DocumentAccessLog are managed=False: they map to the
# pre-existing `documents` / `document_access_logs` tables (created outside
# Django's migrations, no prior migration record for either). This migration
# only registers both models in Django's migration state so
# `makemigrations --check` stays clean — `migrate` issues no DDL for
# managed=False models, so the real tables are never touched.
#
# Hand-written rather than autodetector-generated: the autodetector dropped
# the `document` FK field and both models' Meta.indexes from its generated
# CreateModel operations for this specific unmanaged-forward-FK case. Field
# list, FK, and index names below were verified directly against the live
# model registry (apps.get_model('core', ...)._meta) and match the indexes
# already present on the real tables exactly.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_apiusagelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('document_type', models.CharField(max_length=50)),
                ('owner_service', models.CharField(db_index=True, max_length=100)),
                ('file', models.CharField(max_length=100)),
                ('filename', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField()),
                ('mime_type', models.CharField(max_length=100)),
                ('checksum', models.CharField(max_length=64)),
                ('metadata', models.JSONField(default=dict)),
                ('tags', models.JSONField(default=list)),
                ('current_version', models.IntegerField(default=1)),
                ('is_latest', models.BooleanField(default=True)),
                ('status', models.CharField(db_index=True, max_length=20)),
                ('created_by_user_id', models.IntegerField()),
                ('created_by_role', models.CharField(max_length=50)),
                ('is_public', models.BooleanField(default=False)),
                ('allowed_roles', models.JSONField(default=list)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'documents',
                'managed': False,
                'indexes': [
                    models.Index(fields=['status', 'is_latest'], name='documents_status_72fc1b_idx'),
                ],
            },
        ),
        migrations.CreateModel(
            name='DocumentAccessLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(db_index=True)),
                ('document', models.ForeignKey(db_column='document_id', on_delete=django.db.models.deletion.DO_NOTHING, to='core.document')),
                ('access_type', models.CharField(max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(max_length=255)),
                ('accessed_at', models.DateTimeField(db_index=True)),
            ],
            options={
                'db_table': 'document_access_logs',
                'managed': False,
                'indexes': [
                    models.Index(fields=['document', 'accessed_at'], name='document_ac_documen_b365a5_idx'),
                    models.Index(fields=['user_id', 'accessed_at'], name='document_ac_user_id_509fd5_idx'),
                ],
            },
        ),
    ]
