# Generated by Django 5.0 on 2026-08-31 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


ROUTING = {
    'general': ('Customer Service', 24), 'technical_support': ('IT / Digital', 8),
    'complaint': ('Quality Management', 12), 'suggestion': ('Corporate Services', 48),
    'partnership': ('Business Development', 24), 'legal': ('Legal', 24),
    'hr': ('Human Resources', 24), 'it_request': ('IT / Digital', 8),
    'finance_request': ('Finance', 24), 'procurement': ('Procurement', 24),
    'facility_request': ('Facilities', 12), 'other': ('Administration', 24),
}

LEGACY = {
    'password-reset': 'it_request', 'pid-analysis': 'technical_support',
    'pfd-conversion': 'technical_support', 'asset-integrity': 'technical_support',
    'engineering-consulting': 'technical_support', 'digital-twin': 'technical_support',
    'ai-ml-services': 'technical_support', 'general': 'general', 'other': 'other',
}


def seed_and_backfill_enquiries(apps, schema_editor):
    Enquiry = apps.get_model('core', 'Enquiry')
    Message = apps.get_model('core', 'EnquiryMessage')
    Activity = apps.get_model('core', 'EnquiryActivity')
    Rule = apps.get_model('core', 'EnquiryRoutingRule')
    for inquiry_type, (department, sla_hours) in ROUTING.items():
        Rule.objects.get_or_create(
            inquiry_type=inquiry_type,
            defaults={'department': department, 'sla_hours': sla_hours, 'is_active': True},
        )
    for enquiry in Enquiry.objects.all().iterator():
        inquiry_type = LEGACY.get(enquiry.service, 'general' if not enquiry.service else 'other')
        department, _ = ROUTING[inquiry_type]
        status = {'in_review': 'in_progress', 'contacted': 'responded'}.get(enquiry.status, enquiry.status)
        Enquiry.objects.filter(pk=enquiry.pk).update(
            inquiry_type=inquiry_type, department=department, status=status,
        )
        Message.objects.create(
            enquiry_id=enquiry.pk, sender_type='requester', body=enquiry.message, is_internal=False,
        )
        Activity.objects.create(
            enquiry_id=enquiry.pk, action='legacy_enquiry_migrated',
            details={'legacy_service': enquiry.service, 'department': department},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_document_documentaccesslog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiry_assignments_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_enquiries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='department',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='due_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='first_response_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='inquiry_type',
            field=models.CharField(choices=[('general', 'General Inquiry'), ('technical_support', 'Technical Support'), ('complaint', 'Complaint'), ('suggestion', 'Suggestion'), ('partnership', 'Partnership'), ('legal', 'Legal'), ('hr', 'HR'), ('it_request', 'IT Request'), ('finance_request', 'Finance Request'), ('procurement', 'Procurement'), ('facility_request', 'Facility Request'), ('other', 'Other')], db_index=True, default='general', max_length=30),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='requester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_enquiries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('waiting_user', 'Waiting for User'), ('responded', 'Responded'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('spam', 'Spam')], db_index=True, default='new', max_length=20),
        ),
        migrations.CreateModel(
            name='EnquiryActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(db_index=True, max_length=50)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiry_activities', to=settings.AUTH_USER_MODEL)),
                ('enquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='core.enquiry')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EnquiryMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sender_type', models.CharField(choices=[('requester', 'Requester'), ('representative', 'Representative'), ('system', 'System')], max_length=20)),
                ('body', models.TextField()),
                ('is_internal', models.BooleanField(db_index=True, default=False)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiry_messages', to=settings.AUTH_USER_MODEL)),
                ('enquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.enquiry')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EnquiryRoutingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inquiry_type', models.CharField(choices=[('general', 'General Inquiry'), ('technical_support', 'Technical Support'), ('complaint', 'Complaint'), ('suggestion', 'Suggestion'), ('partnership', 'Partnership'), ('legal', 'Legal'), ('hr', 'HR'), ('it_request', 'IT Request'), ('finance_request', 'Finance Request'), ('procurement', 'Procurement'), ('facility_request', 'Facility Request'), ('other', 'Other')], max_length=30, unique=True)),
                ('department', models.CharField(db_index=True, max_length=100)),
                ('sla_hours', models.PositiveIntegerField(default=24)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('representative', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiry_routing_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['inquiry_type'],
            },
        ),
        migrations.RunPython(seed_and_backfill_enquiries, migrations.RunPython.noop),
    ]
