# Generated by Django 5.0 on 2026-08-31 13:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def backfill_ticket_governance(apps, schema_editor):
    Enquiry = apps.get_model('core', 'Enquiry')
    Enquiry.objects.filter(
        urgency__in=['high', 'urgent'],
    ).exclude(status__in=['resolved', 'closed', 'spam']).update(
        approval_required=True, approval_status='pending',
    )


def populate_feedback_tokens(apps, schema_editor):
    Enquiry = apps.get_model('core', 'Enquiry')
    for enquiry in Enquiry.objects.filter(feedback_token__isnull=True).only('pk'):
        enquiry.feedback_token = uuid.uuid4()
        enquiry.save(update_fields=['feedback_token'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_enquiry_assigned_at_enquiry_assigned_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='approval_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='approval_status',
            field=models.CharField(db_index=True, default='not_required', max_length=20),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_enquiry_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='channel',
            field=models.CharField(db_index=True, default='web', max_length=20),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='escalated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='escalation_level',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='escalation_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='feedback_token',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.RunPython(populate_feedback_tokens, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='enquiry',
            name='feedback_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='resolution_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='resolution_proposed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='resolution_summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('waiting_user', 'Waiting for User'), ('responded', 'Responded'), ('escalated', 'Escalated'), ('pending_confirmation', 'Awaiting Resolution Confirmation'), ('reopened', 'Reopened'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('spam', 'Spam')], db_index=True, default='new', max_length=20),
        ),
        migrations.CreateModel(
            name='EnquiryFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.PositiveSmallIntegerField()),
                ('resolution_confirmed', models.BooleanField(default=True)),
                ('comment', models.TextField(blank=True, default='')),
                ('would_recommend', models.BooleanField(blank=True, null=True)),
                ('enquiry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='core.enquiry')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiry_feedback_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RunPython(backfill_ticket_governance, migrations.RunPython.noop),
    ]
