# Generated by Django 5.0 on 2026-07-01 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cross_recommendation', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='crossrecommendationlink',
            new_name='cross_recom_source__fedb83_idx',
            old_name='cross_recom_source__e59eca_idx',
        ),
        migrations.RenameIndex(
            model_name='crossrecommendationlink',
            new_name='cross_recom_target__4d2a9e_idx',
            old_name='cross_recom_target__7d77b4_idx',
        ),
        migrations.RenameIndex(
            model_name='crossrecommendationlink',
            new_name='cross_recom_project_ed1a64_idx',
            old_name='cross_recom_project_6d8f4f_idx',
        ),
        migrations.RenameIndex(
            model_name='crossrecommendationlink',
            new_name='cross_recom_decisio_e81fbf_idx',
            old_name='cross_recom_decisio_2e9d00_idx',
        ),
    ]
