# Generated by Django 4.2.16 on 2026-07-10 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cross_recommendation', '0002_rename_cross_recom_source__e59eca_idx_cross_recom_source__fedb83_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='crossrecommendationlink',
            new_name='cross_recom_source__fedb83_idx',
            old_name='cross_recom_source__e59eca_idx',
        ),
        migrations.RenameIndex(
            model_name='crossrecommendationlink',
            new_name='cross_recom_target__4d2a9e_idx',
            old_name='cross_recom_target__7d77b4_idx',
        ),
        migrations.RenameIndex(
            model_name='crossrecommendationlink',
            new_name='cross_recom_project_ed1a64_idx',
            old_name='cross_recom_project_6d8f4f_idx',
        ),
        migrations.RenameIndex(
            model_name='crossrecommendationlink',
            new_name='cross_recom_decisio_e81fbf_idx',
            old_name='cross_recom_decisio_2e9d00_idx',
        ),
    ]
