# Generated by Django 4.2.16 on 2026-07-10 17:04
# FIXED: Changed RenameIndex to conditional RunSQL to handle missing indexes

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cross_recommendation', '0002_rename_cross_recom_source__e59eca_idx_cross_recom_source__fedb83_idx_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""DO $$ BEGIN IF EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'cross_recom_source__e59eca_idx') THEN ALTER INDEX cross_recom_source__e59eca_idx RENAME TO cross_recom_source__fedb83_idx; END IF; END $$;""",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="""DO $$ BEGIN IF EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'cross_recom_target__7d77b4_idx') THEN ALTER INDEX cross_recom_target__7d77b4_idx RENAME TO cross_recom_target__4d2a9e_idx; END IF; END $$;""",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="""DO $$ BEGIN IF EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'cross_recom_project_6d8f4f_idx') THEN ALTER INDEX cross_recom_project_6d8f4f_idx RENAME TO cross_recom_project_ed1a64_idx; END IF; END $$;""",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="""DO $$ BEGIN IF EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'cross_recom_decisio_2e9d00_idx') THEN ALTER INDEX cross_recom_decisio_2e9d00_idx RENAME TO cross_recom_decisio_e81fbf_idx; END IF; END $$;""",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
