# Generated by Django 5.0 on 2026-03-23 07:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PFDProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(editable=False, help_text='Auto-generated unique project ID', max_length=50, unique=True)),
                ('project_name', models.CharField(help_text='User-defined project name', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Optional project description', null=True)),
                ('reference_documents', models.JSONField(default=dict, help_text="\n        Reference documents for this project:\n        {\n            'bfd': 'path/to/file',\n            'process_description': 'path/to/file',\n            'process_design_basis': 'path/to/file',\n            'operation_control_philosophy': 'path/to/file',\n            'scope_of_work': 'path/to/file',\n            'legends_symbols': 'path/to/file',\n            'equipment_datasheet': 'path/to/file',\n            'other': 'path/to/file'\n        }\n        ")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pfd_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pfd_projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PFDUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_id', models.CharField(editable=False, help_text='Auto-generated unique upload ID', max_length=50, unique=True)),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=1000)),
                ('file_size', models.BigIntegerField(help_text='File size in bytes')),
                ('drawing_number', models.CharField(blank=True, max_length=100)),
                ('drawing_revision', models.CharField(blank=True, max_length=50)),
                ('drawing_title', models.CharField(blank=True, max_length=500)),
                ('project_name_field', models.CharField(blank=True, help_text='Drawing project name', max_length=255)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='uploaded', max_length=20)),
                ('verification_results', models.JSONField(blank=True, default=dict, help_text='AI verification results')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pfd_uploads', to='pfd.pfdproject')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pfd_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pfd_uploads',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='PFDVerificationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_issues', models.IntegerField(default=0)),
                ('critical_count', models.IntegerField(default=0)),
                ('major_count', models.IntegerField(default=0)),
                ('minor_count', models.IntegerField(default=0)),
                ('observation_count', models.IntegerField(default=0)),
                ('approved_count', models.IntegerField(default=0)),
                ('ignored_count', models.IntegerField(default=0)),
                ('pending_count', models.IntegerField(default=0)),
                ('report_data', models.JSONField(default=dict, help_text='Complete AI analysis results in JSON format')),
                ('extracted_drawing_number', models.CharField(blank=True, max_length=100)),
                ('extracted_revision', models.CharField(blank=True, max_length=50)),
                ('extracted_project_name', models.CharField(blank=True, max_length=255)),
                ('extracted_client_name', models.CharField(blank=True, max_length=255)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pfd_upload', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification_report', to='pfd.pfdupload')),
            ],
            options={
                'db_table': 'pfd_verification_reports',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='PFDIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.IntegerField(help_text='Sequential issue number')),
                ('issue_found', models.TextField(help_text='Description of the issue observed')),
                ('action_required', models.TextField(help_text='Recommended corrective action')),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('major', 'Major'), ('minor', 'Minor'), ('observation', 'Observation')], default='observation', max_length=20)),
                ('category', models.CharField(choices=[('Equipment', 'Equipment'), ('Streams', 'Streams'), ('Control', 'Control'), ('Documentation', 'Documentation'), ('Safety', 'Safety'), ('Material Balance', 'Material Balance'), ('Other', 'Other')], default='Other', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('ignored', 'Ignored')], default='pending', max_length=20)),
                ('approval', models.CharField(default='Pending', help_text='Approval decision (Approved/Rejected/Pending)', max_length=50)),
                ('remark', models.TextField(blank=True, default='Pending', help_text='Engineer remarks or comments')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='pfd.pfdverificationreport')),
            ],
            options={
                'db_table': 'pfd_issues',
                'ordering': ['serial_number'],
            },
        ),
        migrations.AddIndex(
            model_name='pfdproject',
            index=models.Index(fields=['project_id'], name='pfd_project_project_3a66f8_idx'),
        ),
        migrations.AddIndex(
            model_name='pfdproject',
            index=models.Index(fields=['created_by', '-created_at'], name='pfd_project_created_428458_idx'),
        ),
        migrations.AddIndex(
            model_name='pfdupload',
            index=models.Index(fields=['project', '-uploaded_at'], name='pfd_uploads_project_5ba900_idx'),
        ),
        migrations.AddIndex(
            model_name='pfdupload',
            index=models.Index(fields=['upload_id'], name='pfd_uploads_upload__ccfddc_idx'),
        ),
        migrations.AddIndex(
            model_name='pfdupload',
            index=models.Index(fields=['status'], name='pfd_uploads_status_03fc8a_idx'),
        ),
        migrations.AddIndex(
            model_name='pfdissue',
            index=models.Index(fields=['report', 'serial_number'], name='pfd_issues_report__689229_idx'),
        ),
        migrations.AddIndex(
            model_name='pfdissue',
            index=models.Index(fields=['status'], name='pfd_issues_status_0e2513_idx'),
        ),
        migrations.AddIndex(
            model_name='pfdissue',
            index=models.Index(fields=['severity'], name='pfd_issues_severit_8b98a2_idx'),
        ),
    ]
