# Generated by Django 5.0 on 2026-03-23 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfd', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pfdissue',
            name='category',
            field=models.CharField(choices=[('Equipment', 'Equipment'), ('Streams', 'Streams'), ('Control', 'Control'), ('Documentation', 'Documentation'), ('Safety', 'Safety'), ('Material Balance', 'Material Balance'), ('Utilities', 'Utilities'), ('Process Design', 'Process Design'), ('Other', 'Other')], default='Other', max_length=50),
        ),
    ]
