# Generated by Django 5.0 on 2026-10-07 08:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectricalComparisonJob',
            fields=[
                ('job_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('status', models.CharField(default='uploaded', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('pid_file_name', models.CharField(max_length=255)),
                ('provider', models.CharField(default='claude', max_length=20)),
                ('model_used', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ElectricalComparisonResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_number', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(max_length=20)),
                ('source', models.CharField(max_length=50)),
                ('equipment_type', models.CharField(blank=True, max_length=100)),
                ('remarks', models.TextField(blank=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='electrical_comparison.electricalcomparisonjob')),
            ],
        ),
    ]
