# Generated by Django 5.0 on 2026-10-07 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electrical_comparison', '0002_electricalproject_electricalcomparisonjob_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='electricalcomparisonjob',
            name='raw_text_per_page',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
