# Generated by Django 5.0 on 2026-10-07 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electrical_comparison', '0003_electricalcomparisonjob_raw_text_per_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='electricalcomparisonjob',
            name='current_stage',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='electricalcomparisonjob',
            name='pages_done',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='electricalcomparisonjob',
            name='pages_total',
            field=models.IntegerField(default=0),
        ),
    ]
