# Generated by Django 5.0 on 2026-03-24 09:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WrenchConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_url', models.URLField(help_text='Wrench REST API base URL, e.g. https://your-org.wrenchproject.com', max_length=500)),
                ('encrypted_api_key', models.TextField(help_text='Fernet-encrypted Wrench API key – never stored in plaintext')),
                ('client_id', models.CharField(blank=True, default='', max_length=255)),
                ('organization_name', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('connection_verified', models.BooleanField(default=False)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wrench_configs_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wrench_configs_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Wrench Configuration',
                'verbose_name_plural': 'Wrench Configurations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WrenchSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('radai_to_wrench', 'RADAI → Wrench'), ('wrench_to_radai', 'Wrench → RADAI')], max_length=20)),
                ('entity_type', models.CharField(choices=[('project', 'Project'), ('document', 'Document'), ('transmittal', 'Transmittal'), ('user', 'User'), ('all', 'All')], default='all', max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('success', 'Success'), ('failed', 'Failed'), ('partial', 'Partial')], default='pending', max_length=20)),
                ('records_requested', models.IntegerField(default=0)),
                ('records_synced', models.IntegerField(default=0)),
                ('records_failed', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('sync_details', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('config', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_logs', to='wrench_integration.wrenchconfig')),
                ('triggered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wrench_sync_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Wrench Sync Log',
                'verbose_name_plural': 'Wrench Sync Logs',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['status'], name='wrench_inte_status_4f567f_idx'), models.Index(fields=['started_at'], name='wrench_inte_started_6da8ce_idx')],
            },
        ),
    ]
