# Generated by Django 5.0 on 2026-03-24 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrench_integration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wrenchconfig',
            name='encrypted_password',
            field=models.TextField(default='', help_text='Fernet-encrypted Wrench password – never stored in plaintext'),
        ),
        migrations.AddField(
            model_name='wrenchconfig',
            name='login_name',
            field=models.CharField(default='', help_text='Wrench LOGIN_NAME (username)', max_length=255),
        ),
        migrations.AddField(
            model_name='wrenchconfig',
            name='server_id',
            field=models.IntegerField(default=1, help_text='Wrench SERVER_ID – passed to /api/AccessControl/Login'),
        ),
        migrations.AddField(
            model_name='wrenchconfig',
            name='session_token',
            field=models.TextField(blank=True, default='', help_text='Current Wrench session TOKEN (refreshed on each API call)'),
        ),
        migrations.AddField(
            model_name='wrenchconfig',
            name='svc_url',
            field=models.URLField(blank=True, default='', help_text='Wrench DocumentSearch Service URL (<<SVC URL>>). Leave blank to use the same base URL. e.g. https://svc.wrenchproject.com', max_length=500),
        ),
        migrations.AddField(
            model_name='wrenchconfig',
            name='token_obtained_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wrenchconfig',
            name='base_url',
            field=models.URLField(help_text='Wrench WebAPI Server URL, e.g. https://your-org.wrenchproject.com', max_length=500),
        ),
        migrations.AlterField(
            model_name='wrenchconfig',
            name='encrypted_api_key',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='wrenchsynclog',
            name='entity_type',
            field=models.CharField(choices=[('project', 'Project'), ('document', 'Document'), ('transmittal', 'Transmittal'), ('user', 'User'), ('all', 'All'), ('doc_search', 'Document Search')], default='all', max_length=30),
        ),
    ]
