# Generated by Django 5.0 on 2026-03-24 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrench_integration', '0002_wrenchconfig_encrypted_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wrenchconfig',
            name='is_password_encrypted',
            field=models.SmallIntegerField(choices=[(0, 'Plain-text (0)'), (1, 'Pre-encrypted (1)')], default=0, help_text='Wrench IS_PASSWORD_ENCRYPTED flag: 0=plain, 1=pre-encrypted'),
        ),
        migrations.AddField(
            model_name='wrenchconfig',
            name='language',
            field=models.CharField(blank=True, default='', help_text='Wrench LANGUAGE code, e.g. en-US (leave blank for server default)', max_length=20),
        ),
        migrations.AddField(
            model_name='wrenchconfig',
            name='otp',
            field=models.CharField(blank=True, default='', help_text='One-time password for MFA (leave blank if not required)', max_length=64),
        ),
        migrations.AddField(
            model_name='wrenchconfig',
            name='time_zone_id',
            field=models.CharField(blank=True, default='', help_text='Wrench TIME_ZONE_ID (leave blank for server default)', max_length=100),
        ),
        migrations.AddField(
            model_name='wrenchconfig',
            name='workstation_name',
            field=models.CharField(blank=True, default='RADAI', help_text='WORKSTATION_NAME sent on login to identify this client', max_length=255),
        ),
    ]
