# Generated by Django 5.0 on 2026-07-21 07:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrument_io_workflow', '0002_add_iolist_document_storage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IOListProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('project_code', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(choices=[('oil_gas', 'Oil & Gas'), ('refinery', 'Refinery'), ('lng', 'LNG'), ('power', 'Power Plant'), ('water', 'Water/Wastewater'), ('other', 'Other')], default='oil_gas', max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('review', 'Under Review'), ('completed', 'Completed'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('client', models.CharField(blank=True, default='', max_length=255)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='io_list_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'I/O List Project',
                'verbose_name_plural': 'I/O List Projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='iolistdocument',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Optional project container for organizing documents', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='instrument_io_workflow.iolistproject'),
        ),
        migrations.AddIndex(
            model_name='iolistproject',
            index=models.Index(fields=['created_by', 'status'], name='instrument__created_865dbf_idx'),
        ),
        migrations.AddIndex(
            model_name='iolistproject',
            index=models.Index(fields=['category'], name='instrument__categor_ebd9a8_idx'),
        ),
        migrations.AddIndex(
            model_name='iolistproject',
            index=models.Index(fields=['-created_at'], name='instrument__created_5b6928_idx'),
        ),
    ]
