# Generated by Django 5.0 on 2026-09-01 07:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrument_io_workflow', '0004_fix_iolist_document_storage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='iolistdocument',
            name='legend_findings',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='IOListLegendSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legend_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('section', models.CharField(choices=[('io_tag_format', 'I/O Tag Format')], default='io_tag_format', max_length=32)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('definition', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='io_list_legends', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'instrument_io_workflow_legend_sheet',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['created_by', 'section', '-updated_at'], name='instrument__created_7bd015_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='iolistlegendsheet',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('created_by', 'section'), name='uniq_io_legend_active_per_user_section'),
        ),
    ]
