# Generated by Django 5.0 on 2026-09-01 09:24

import apps.instrument_io_workflow.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrument_io_workflow', '0006_copy_legends_from_pid_checker_v2'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='iolistlegendsheet',
            name='section',
            field=models.CharField(choices=[('line_list', 'Line List'), ('equipment_list', 'Equipment List'), ('instrument_index', 'Instrument Index'), ('valve', 'Valve'), ('piping', 'Piping'), ('actuator_symbols', 'Actuator Symbols'), ('flow_detector', 'Flow Detector'), ('control_valve_regulator', 'Control Valve & Regulator'), ('instrument_signal', 'Instrument Signal'), ('equipment_symbols', 'Equipment Symbols'), ('instrument_function', 'Instrument Function'), ('pipe_connection', 'Pipe Connection'), ('pipe_end', 'Pipe End'), ('special_piping', 'Special Piping'), ('scope_symbols', 'Scope Symbols'), ('miscellaneous', 'Miscellaneous'), ('limit_line', 'Limit Line'), ('other_specialties', 'Other Specialties'), ('instrument_typical_letter', 'Instrument Typical Letter'), ('drawing_cont', 'Drawing Continuations'), ('general_instrument', 'General Instrument or Function Symbols')], default='instrument_index', max_length=32),
        ),
        migrations.CreateModel(
            name='IOListLegendSymbolImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('section', models.CharField(max_length=32)),
                ('symbol_name', models.CharField(max_length=200)),
                ('image_file', models.ImageField(blank=True, max_length=500, null=True, upload_to=apps.instrument_io_workflow.models.io_legend_symbol_image_upload_path)),
                ('content_type', models.CharField(default='image/png', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='io_list_legend_symbol_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'instrument_io_workflow_legend_symbol_image',
                'ordering': ['section', 'symbol_name'],
                'unique_together': {('created_by', 'section', 'symbol_name')},
            },
        ),
    ]
