# Generated by Django 5.0 on 2026-09-01 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrument_io_workflow', '0018_seed_signal_and_cabinet_legends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iolistlegendsheet',
            name='section',
            field=models.CharField(choices=[('tag_register', 'Tag Register'), ('equipment_register', 'Equipment Register'), ('instrument_index', 'Instrument Index'), ('valve_types', 'Valve Types'), ('actuator_types', 'Actuator Types'), ('flow_instruments', 'Flow Instruments'), ('control_valves', 'Control Valves'), ('signal_line_types', 'Signal Line Types'), ('equipment_symbols', 'Equipment Symbols'), ('instrument_functions', 'Instrument Functions'), ('instrument_typical_letter', 'Instrument Typical Letter'), ('instrument_bubbles', 'Instrument Bubbles'), ('instrument_symbols', 'Instruments'), ('signal_types', 'Signal Types'), ('cabinet_locations', 'Cabinet/Panel Locations')], default='instrument_index', max_length=32),
        ),
    ]
