# Generated by Django 5.0 on 2026-09-02 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrument_io_workflow', '0032_seed_main_equipment_legend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iolistlegendsheet',
            name='section',
            field=models.CharField(choices=[('tag_register', 'Instrument Tagging'), ('equipment_register', 'Equipment Numbering'), ('instrument_index', 'Instrument Index'), ('valve_types', 'Valve Types'), ('actuator_types', 'Actuator Types'), ('flow_instruments', 'Flow Instruments'), ('control_valves', 'Control Valves'), ('signal_line_types', 'Line Representation'), ('equipment_symbols', 'Equipment Symbols'), ('instrument_functions', 'Instrument Functions'), ('instrument_typical_letter', 'Instrument Typical Letter'), ('instrument_bubbles', 'Instrument Bubbles'), ('instrument_symbols', 'Instruments'), ('signal_types', 'Signal Types'), ('cabinet_locations', 'Cabinet/Panel Locations'), ('well_instrument_tagging', 'Well Instrument Tagging'), ('well_equipment_numbering', 'Well Equipment Numbering'), ('line_numbering', 'Line Numbering'), ('main_equipment', 'Main Equipment')], default='instrument_index', max_length=32),
        ),
    ]
