# Generated by Django 5.0 on 2026-09-02 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrument_io_workflow', '0052_remove_tag_register_and_relabel_instrument_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='iolistdocument',
            name='pages_processed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='iolistdocument',
            name='pages_total',
            field=models.IntegerField(default=0),
        ),
    ]
