# Generated by Django 5.0 on 2026-09-02 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrument_io_workflow', '0054_instrument_index_full_isa_lookup'),
    ]

    operations = [
        migrations.AddField(
            model_name='iolistdocument',
            name='document_type',
            field=models.CharField(choices=[('io_list', 'IO List'), ('pid_drawing', 'P&ID Drawing')], default='io_list', max_length=20),
        ),
    ]
