# Generated by Django 5.0 on 2026-09-04 05:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrument_io_workflow', '0061_equipment_register_flexible_format'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='iolistlegendsymbolimage',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='iolistlegendsymbolimage',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='io_list_legend_symbol_images', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='iolistlegendsymbolimage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('section', 'symbol_name'), name='uniq_io_default_symbol_per_section'),
        ),
    ]
