# Generated by Django 5.0 on 2026-09-07 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrument_io_workflow', '0062_iolistlegendsymbolimage_is_default_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='iolistdocument',
            name='current_phase',
            field=models.CharField(blank=True, choices=[('', 'Not processing'), ('detecting_type', 'Detecting document type'), ('processing_pages', 'Processing pages'), ('linking_comments', 'Linking comments to tags'), ('validating_legend', 'Validating tags against legend')], default='', max_length=20),
        ),
    ]
