# Generated by Django 5.0 on 2026-09-07 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrument_io_workflow', '0063_iolistdocument_current_phase'),
    ]

    operations = [
        migrations.AddField(
            model_name='iolistdocument',
            name='extraction_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='iolistdocument',
            name='vision_calls_done',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='iolistdocument',
            name='vision_calls_total',
            field=models.IntegerField(default=0),
        ),
    ]
