# Generated by Django 5.0 on 2026-09-07 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrument_io_workflow', '0064_iolistdocument_extraction_started_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='iolistdocument',
            name='tokens_used_total',
            field=models.IntegerField(default=0),
        ),
    ]
