# Generated by Django 5.0 on 2026-09-07 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrument_io_workflow', '0065_iolistdocument_tokens_used_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='iolistdocument',
            name='provisional_comments_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='iolistdocument',
            name='provisional_rows_count',
            field=models.IntegerField(default=0),
        ),
    ]
