# Generated by Django 5.0 on 2026-07-27 06:27

import apps.planning_intelligence.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanningProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(default='Untitled Planning Project', max_length=255)),
                ('client', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('phase', models.CharField(blank=True, help_text='e.g. FEED / DEFINE', max_length=100)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('duration_months', models.PositiveIntegerField(default=10)),
                ('calendar_overrides', models.JSONField(blank=True, default=dict)),
                ('review_cycle_overrides', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planning_projects_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlanningGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('intelligence', models.JSONField(blank=True, default=dict, help_text='Extracted project intelligence')),
                ('wbs', models.JSONField(blank=True, default=list)),
                ('activities', models.JSONField(blank=True, default=list)),
                ('logic_matrix', models.JSONField(blank=True, default=list)),
                ('eddr', models.JSONField(blank=True, default=list)),
                ('milestones', models.JSONField(blank=True, default=list)),
                ('manhours', models.JSONField(blank=True, default=dict)),
                ('validation', models.JSONField(blank=True, default=list)),
                ('narrative', models.TextField(blank=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planning_generations_created', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generations', to='planning_intelligence.planningproject')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('project', 'version')},
            },
        ),
        migrations.CreateModel(
            name='PlanningFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.CharField(choices=[('sow', 'Scope of Work'), ('wbs', 'WBS Structure'), ('mdr', 'Master Deliverable Register'), ('eddr', 'Engineering Document Deliverable Register'), ('schedule_requirements', 'Schedule Requirements'), ('project_control_procedure', 'Project Control Procedure'), ('reference_schedule', 'Reference Schedule'), ('output_schedule_sample', 'Output Schedule Sample'), ('timeline', 'Timeline / Milestone File'), ('other', 'Other Attachment')], default='other', max_length=40)),
                ('file', models.FileField(max_length=512, upload_to=apps.planning_intelligence.models._planning_file_upload_path)),
                ('original_filename', models.CharField(blank=True, max_length=512)),
                ('content_type', models.CharField(blank=True, max_length=128)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('parse_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Parsed'), ('failed', 'Failed')], default='pending', max_length=12)),
                ('extracted_text', models.TextField(blank=True)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('parse_error', models.TextField(blank=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planning_files_uploaded', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='planning_intelligence.planningproject')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project', 'category'], name='planning_in_project_d23d9a_idx')],
            },
        ),
    ]
