# Generated by Django 5.0 on 2026-07-27 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning_intelligence', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planningproject',
            name='ai_settings',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
