# Generated by Django 5.0 on 2026-07-27 07:26

import apps.planning_intelligence.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning_intelligence', '0002_planningproject_ai_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planningfile',
            name='file',
            field=models.FileField(max_length=512, storage='apps.core.storage_backends.PlanningIntelligenceStorage', upload_to=apps.planning_intelligence.models._planning_file_upload_path),
        ),
    ]
