import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('planning_intelligence', '0005_phase0_foundation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(name='Schedule', fields=[
            ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)),
            ('is_deleted', models.BooleanField(default=False)), ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ('name', models.CharField(max_length=255)), ('code', models.CharField(max_length=64)),
            ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('on_hold', 'On Hold'), ('completed', 'Completed'), ('archived', 'Archived')], default='draft', max_length=16)),
            ('planned_start', models.DateField()), ('data_date', models.DateField(blank=True, null=True)),
            ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules_created', to=settings.AUTH_USER_MODEL)),
            ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='planning_intelligence.planningproject')),
        ], options={'ordering': ['-created_at']}),
        migrations.CreateModel(name='ScheduleResource', fields=[
            ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)),
            ('is_deleted', models.BooleanField(default=False)), ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ('code', models.CharField(max_length=64)), ('name', models.CharField(max_length=255)),
            ('resource_type', models.CharField(choices=[('labor', 'Labor'), ('equipment', 'Equipment'), ('material', 'Material')], default='labor', max_length=16)),
            ('role', models.CharField(blank=True, max_length=120)), ('unit', models.CharField(default='hour', max_length=32)),
            ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
            ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_resources', to='planning_intelligence.planningproject')),
        ], options={'ordering': ['code'], 'unique_together': {('project', 'code')}}),
        migrations.CreateModel(name='ScheduleVersion', fields=[
            ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)),
            ('is_deleted', models.BooleanField(default=False)), ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ('version', models.PositiveIntegerField(default=1)),
            ('status', models.CharField(choices=[('draft', 'Draft'), ('calculated', 'Calculated'), ('approved', 'Approved'), ('baselined', 'Baselined'), ('superseded', 'Superseded')], default='draft', max_length=16)),
            ('change_summary', models.CharField(blank=True, max_length=255)), ('calculated_at', models.DateTimeField(blank=True, null=True)),
            ('calculated_finish', models.DateField(blank=True, null=True)),
            ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_versions_created', to=settings.AUTH_USER_MODEL)),
            ('parent_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_versions', to='planning_intelligence.scheduleversion')),
            ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='planning_intelligence.schedule')),
            ('source_generation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_version', to='planning_intelligence.planninggeneration')),
        ], options={'ordering': ['-version'], 'unique_together': {('schedule', 'version')}}),
        migrations.CreateModel(name='ScheduleCalculationRun', fields=[
            ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)),
            ('is_deleted', models.BooleanField(default=False)), ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ('status', models.CharField(choices=[('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='running', max_length=16)),
            ('started_at', models.DateTimeField()), ('finished_at', models.DateTimeField(blank=True, null=True)),
            ('activity_count', models.PositiveIntegerField(default=0)), ('critical_activity_count', models.PositiveIntegerField(default=0)),
            ('project_finish', models.DateField(blank=True, null=True)), ('issues', models.JSONField(blank=True, default=list)),
            ('error_message', models.TextField(blank=True)),
            ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_calculations_requested', to=settings.AUTH_USER_MODEL)),
            ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculation_runs', to='planning_intelligence.scheduleversion')),
        ], options={'ordering': ['-created_at']}),
        migrations.CreateModel(name='ScheduleWBSNode', fields=[
            ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)),
            ('is_deleted', models.BooleanField(default=False)), ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ('code', models.CharField(max_length=128)), ('name', models.CharField(max_length=255)),
            ('level', models.PositiveSmallIntegerField(default=0)), ('sort_order', models.PositiveIntegerField(default=0)),
            ('discipline', models.CharField(blank=True, max_length=64)),
            ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='planning_intelligence.schedulewbsnode')),
            ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wbs_nodes', to='planning_intelligence.scheduleversion')),
        ], options={'ordering': ['sort_order', 'code'], 'unique_together': {('version', 'code')}}),
        migrations.CreateModel(name='WorkCalendar', fields=[
            ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)),
            ('is_deleted', models.BooleanField(default=False)), ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ('name', models.CharField(max_length=120)), ('working_weekdays', models.JSONField(default=list, help_text='ISO weekdays: Monday=0 through Sunday=6.')),
            ('hours_per_day', models.DecimalField(decimal_places=2, default=8, max_digits=4)),
            ('timezone', models.CharField(default='Asia/Dubai', max_length=64)), ('is_default', models.BooleanField(default=False)),
            ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_calendars', to='planning_intelligence.planningproject')),
        ], options={'ordering': ['name'], 'unique_together': {('project', 'name')}}),
        migrations.CreateModel(name='ScheduleActivity', fields=[
            ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)),
            ('is_deleted', models.BooleanField(default=False)), ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ('external_id', models.CharField(max_length=64)), ('name', models.CharField(max_length=500)),
            ('activity_type', models.CharField(choices=[('task', 'Task'), ('start_milestone', 'Start Milestone'), ('finish_milestone', 'Finish Milestone'), ('level_of_effort', 'Level of Effort')], default='task', max_length=20)),
            ('duration_days', models.DecimalField(decimal_places=2, default=1, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
            ('discipline', models.CharField(blank=True, max_length=64)), ('responsible_role', models.CharField(blank=True, max_length=120)),
            ('constraint_type', models.CharField(choices=[('none', 'None'), ('start_no_earlier', 'Start No Earlier Than'), ('start_no_later', 'Start No Later Than'), ('finish_no_later', 'Finish No Later Than'), ('must_start', 'Must Start On'), ('must_finish', 'Must Finish On')], default='none', max_length=24)),
            ('constraint_date', models.DateField(blank=True, null=True)), ('planned_start', models.DateField(blank=True, null=True)),
            ('planned_finish', models.DateField(blank=True, null=True)), ('early_start', models.DateField(blank=True, null=True)),
            ('early_finish', models.DateField(blank=True, null=True)), ('late_start', models.DateField(blank=True, null=True)),
            ('late_finish', models.DateField(blank=True, null=True)), ('total_float_days', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ('free_float_days', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ('is_critical', models.BooleanField(default=False)), ('sort_order', models.PositiveIntegerField(default=0)),
            ('metadata', models.JSONField(blank=True, default=dict)),
            ('calendar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='planning_intelligence.workcalendar')),
            ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='planning_intelligence.scheduleversion')),
            ('wbs_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='planning_intelligence.schedulewbsnode')),
        ], options={'ordering': ['sort_order', 'external_id']}),
        migrations.AddField(model_name='schedule', name='default_calendar', field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='planning_intelligence.workcalendar')),
        migrations.CreateModel(name='CalendarException', fields=[
            ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)),
            ('is_deleted', models.BooleanField(default=False)), ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ('date', models.DateField()), ('is_working', models.BooleanField(default=False)),
            ('working_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
            ('name', models.CharField(blank=True, max_length=120)),
            ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='planning_intelligence.workcalendar')),
        ], options={'ordering': ['date'], 'unique_together': {('calendar', 'date')}}),
        migrations.CreateModel(name='ActivityAssignment', fields=[
            ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)),
            ('is_deleted', models.BooleanField(default=False)), ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ('planned_units', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
            ('budgeted_hours', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
            ('budgeted_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
            ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='planning_intelligence.scheduleactivity')),
            ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='planning_intelligence.scheduleresource')),
        ], options={'unique_together': {('activity', 'resource')}}),
        migrations.CreateModel(name='ScheduleBaseline', fields=[
            ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)),
            ('is_deleted', models.BooleanField(default=False)), ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ('name', models.CharField(max_length=255)), ('data_date', models.DateField(blank=True, null=True)),
            ('snapshot', models.JSONField(blank=True, default=dict)), ('approved_at', models.DateTimeField(blank=True, null=True)),
            ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_baselines_approved', to=settings.AUTH_USER_MODEL)),
            ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baselines', to='planning_intelligence.schedule')),
            ('source_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='baselines', to='planning_intelligence.scheduleversion')),
        ], options={'ordering': ['-created_at'], 'unique_together': {('schedule', 'name')}}),
        migrations.CreateModel(name='ActivityRelationship', fields=[
            ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)),
            ('is_deleted', models.BooleanField(default=False)), ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ('relationship_type', models.CharField(choices=[('FS', 'Finish to Start'), ('SS', 'Start to Start'), ('FF', 'Finish to Finish'), ('SF', 'Start to Finish')], default='FS', max_length=2)),
            ('lag_days', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
            ('predecessor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='successor_links', to='planning_intelligence.scheduleactivity')),
            ('successor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predecessor_links', to='planning_intelligence.scheduleactivity')),
            ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to='planning_intelligence.scheduleversion')),
        ], options={'ordering': ['successor__sort_order', 'predecessor__sort_order'], 'unique_together': {('predecessor', 'successor', 'relationship_type')}}),
        migrations.AddIndex(model_name='scheduleactivity', index=models.Index(fields=['version', 'is_critical'], name='planning_in_version_be63e9_idx')),
        migrations.AlterUniqueTogether(name='scheduleactivity', unique_together={('version', 'external_id')}),
        migrations.AlterUniqueTogether(name='schedule', unique_together={('project', 'code')}),
        migrations.AlterUniqueTogether(name='calendarexception', unique_together={('calendar', 'date')}),
    ]
