# Generated by Django 5.0 on 2026-08-24 06:35

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning_intelligence', '0007_document_intelligence_evidence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityProgressUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('data_date', models.DateField()),
                ('physical_progress_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('remaining_duration_days', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('actual_start', models.DateField(blank=True, null=True)),
                ('actual_finish', models.DateField(blank=True, null=True)),
                ('forecast_finish', models.DateField(blank=True, null=True)),
                ('actual_hours', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('actual_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('notes', models.TextField(blank=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_updates', to='planning_intelligence.scheduleactivity')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_progress_reported', to=settings.AUTH_USER_MODEL)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_updates', to='planning_intelligence.scheduleversion')),
            ],
            options={
                'ordering': ['-data_date', 'activity__sort_order'],
                'indexes': [models.Index(fields=['version', '-data_date'], name='planning_in_version_5dfe19_idx')],
                'unique_together': {('activity', 'data_date')},
            },
        ),
        migrations.CreateModel(
            name='ScheduleControlSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('data_date', models.DateField()),
                ('bac', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('planned_value', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('earned_value', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('actual_cost', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('schedule_variance', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('cost_variance', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('spi', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('cpi', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('eac', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('etc', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('vac', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('progress_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('planned_progress_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('forecast_finish', models.DateField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('captured_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_control_snapshots_captured', to=settings.AUTH_USER_MODEL)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='control_snapshots', to='planning_intelligence.scheduleversion')),
            ],
            options={
                'ordering': ['-data_date', '-created_at'],
                'indexes': [models.Index(fields=['version', '-data_date'], name='planning_in_version_390187_idx')],
                'unique_together': {('version', 'data_date')},
            },
        ),
    ]
