# Generated by Django 5.0 on 2026-08-24 07:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning_intelligence', '0009_governanceitem_schedulereview_governancecomment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=120)),
                ('target_url', models.URLField(max_length=1000)),
                ('export_format', models.CharField(choices=[('json', 'JSON'), ('xer', 'Primavera XER'), ('csv', 'CSV')], default='json', max_length=12)),
                ('auth_type', models.CharField(choices=[('none', 'None'), ('bearer', 'Bearer Token'), ('hmac_sha256', 'HMAC SHA-256')], default='hmac_sha256', max_length=16)),
                ('secret_encrypted', models.TextField(blank=True)),
                ('event_types', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('timeout_seconds', models.PositiveSmallIntegerField(default=15)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_failure_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, max_length=500)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planning_integrations_created', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integration_endpoints', to='planning_intelligence.planningproject')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('project', 'name')},
            },
        ),
        migrations.CreateModel(
            name='PlanningRetentionPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('export_history_days', models.PositiveIntegerField(default=365)),
                ('delivery_history_days', models.PositiveIntegerField(default=180)),
                ('completed_job_days', models.PositiveIntegerField(default=180)),
                ('legal_hold', models.BooleanField(default=False)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='retention_policy', to='planning_intelligence.planningproject')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planning_retention_policies_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['project_id'],
            },
        ),
        migrations.CreateModel(
            name='IntegrationDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('event_type', models.CharField(default='schedule.published', max_length=64)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('delivering', 'Delivering'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], db_index=True, default='queued', max_length=16)),
                ('request_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('idempotency_key', models.CharField(max_length=255)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('payload_sha256', models.CharField(blank=True, max_length=64)),
                ('response_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('response_excerpt', models.CharField(blank=True, max_length=1000)),
                ('error_message', models.CharField(blank=True, max_length=1000)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planning_integration_deliveries_requested', to=settings.AUTH_USER_MODEL)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integration_deliveries', to='planning_intelligence.scheduleversion')),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='planning_intelligence.integrationendpoint')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['endpoint', '-created_at'], name='planning_in_endpoin_f9b68b_idx'), models.Index(fields=['status', '-created_at'], name='planning_in_status_b14e8c_idx')],
                'unique_together': {('endpoint', 'idempotency_key')},
            },
        ),
        migrations.CreateModel(
            name='ScheduleExportRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('export_format', models.CharField(choices=[('json', 'JSON'), ('csv', 'CSV'), ('xlsx', 'Excel'), ('xer', 'Primavera XER')], max_length=12)),
                ('filename', models.CharField(max_length=255)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('sha256', models.CharField(max_length=64)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_exports_requested', to=settings.AUTH_USER_MODEL)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_records', to='planning_intelligence.scheduleversion')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['version', '-created_at'], name='planning_in_version_7347a9_idx')],
            },
        ),
    ]
