# Generated by Django 5.0 on 2026-08-24 09:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning_intelligence', '0010_integrationendpoint_planningretentionpolicy_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicalProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('proposal_number', models.CharField(max_length=64)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('title', models.CharField(max_length=255)),
                ('client_name', models.CharField(blank=True, max_length=255)),
                ('opportunity_reference', models.CharField(blank=True, max_length=120)),
                ('validity_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('internal_review', 'Internal Review'), ('approved', 'Approved'), ('issued', 'Issued'), ('superseded', 'Superseded')], db_index=True, default='draft', max_length=20)),
                ('sections', models.JSONField(blank=True, default=list)),
                ('branding', models.JSONField(blank=True, default=dict)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technical_proposals_approved', to=settings.AUTH_USER_MODEL)),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technical_proposals_checked', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technical_proposals_created', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_proposals', to='planning_intelligence.planningproject')),
                ('schedule_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='technical_proposals', to='planning_intelligence.scheduleversion')),
                ('source_generation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technical_proposals', to='planning_intelligence.planninggeneration')),
            ],
            options={
                'ordering': ['-revision', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProposalExportRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('export_format', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'Microsoft Word')], max_length=8)),
                ('filename', models.CharField(max_length=255)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('sha256', models.CharField(max_length=64)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposal_exports_requested', to=settings.AUTH_USER_MODEL)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_records', to='planning_intelligence.technicalproposal')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='technicalproposal',
            index=models.Index(fields=['project', '-created_at'], name='planning_in_project_05e6ee_idx'),
        ),
        migrations.AddIndex(
            model_name='technicalproposal',
            index=models.Index(fields=['status', '-created_at'], name='planning_in_status_8160d0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='technicalproposal',
            unique_together={('project', 'proposal_number'), ('project', 'revision')},
        ),
        migrations.AddIndex(
            model_name='proposalexportrecord',
            index=models.Index(fields=['proposal', '-created_at'], name='planning_in_proposa_e9c0a6_idx'),
        ),
    ]
