# Generated by Django 5.0 on 2026-08-24 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning_intelligence', '0011_technicalproposal_proposalexportrecord_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicalproposal',
            name='bid_focal_point',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='technicalproposal',
            name='client_reference',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='technicalproposal',
            name='signatory',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='technicalproposal',
            name='submission_address',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='technicalproposal',
            name='submission_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='technicalproposal',
            name='tender_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='technicalproposal',
            name='validity_days',
            field=models.PositiveIntegerField(default=120),
        ),
    ]
