# Generated by Django 5.0 on 2026-08-25 12:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning_intelligence', '0017_recheck_legacy_id_uniqueness'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyFieldUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('report_date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='draft', max_length=16)),
                ('measurement_method', models.CharField(choices=[('manual', 'Manual percent'), ('quantity', 'Installed quantity'), ('zero_hundred', '0/100'), ('fifty_fifty', '50/50'), ('weighted_steps', 'Weighted steps')], default='manual', max_length=24)),
                ('physical_progress_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('installed_quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=16, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('planned_quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=16, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('quantity_unit', models.CharField(blank=True, max_length=32)),
                ('remaining_duration_days', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('actual_start', models.DateField(blank=True, null=True)),
                ('actual_finish', models.DateField(blank=True, null=True)),
                ('forecast_finish', models.DateField(blank=True, null=True)),
                ('actual_hours', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('actual_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('work_location', models.CharField(blank=True, max_length=255)),
                ('constraints', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('evidence', models.FileField(blank=True, null=True, upload_to='planning_field_evidence/%Y/%m/%d/')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_comment', models.TextField(blank=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_field_updates', to='planning_intelligence.scheduleactivity')),
                ('applied_progress_update', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_field_updates', to='planning_intelligence.activityprogressupdate')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_field_updates_reported', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_field_updates_reviewed', to=settings.AUTH_USER_MODEL)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_field_updates', to='planning_intelligence.scheduleversion')),
            ],
            options={
                'ordering': ['-report_date', '-created_at'],
                'indexes': [models.Index(fields=['version', '-report_date'], name='planning_in_version_82807b_idx'), models.Index(fields=['version', 'status'], name='planning_in_version_0928d1_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='dailyfieldupdate',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('activity', 'report_date'), name='unique_active_daily_field_update'),
        ),
    ]
