# Generated by Django 5.0 on 2026-08-26 10:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


WORKFLOW_FAMILIES = {
    'INSPECTION_REPORT': (
        'Inspection Report Workflow',
        [(1, 'FIELDWORK', 'Complete Inspection / Fieldwork', 5, 'task'),
         (2, 'COMPILE', 'Compile Findings', 3, 'task'),
         (3, 'TECH_REVIEW', 'Technical Review', 3, 'task'),
         (4, 'FINAL_ISSUE', 'Final Issue', 1, 'task')],
    ),
    'TECHNICAL_STUDY': (
        'Technical Study Workflow',
        [(1, 'INPUT_VALIDATION', 'Validate Inputs', 3, 'task'),
         (2, 'ANALYSIS', 'Engineering Analysis', 7, 'task'),
         (3, 'RECOMMENDATIONS', 'Develop Recommendations', 3, 'task'),
         (4, 'TECH_REVIEW', 'Technical Review', 5, 'task'),
         (5, 'FINAL_ISSUE', 'Final Issue', 1, 'task')],
    ),
    'DRAWING': (
        'Drawing Production Workflow',
        [(1, 'INPUT_FREEZE', 'Input Freeze', 0, 'start_milestone'),
         (2, 'PREPARE', 'Prepare Drawing', 8, 'task'),
         (3, 'CHECK', 'Check Drawing', 3, 'task'),
         (4, 'IDC_REVIEW', 'Interdisciplinary Review', 3, 'task'),
         (5, 'FINAL_ISSUE', 'Final Issue', 1, 'task')],
    ),
    'PLAN_PROCEDURE': (
        'Plan and Procedure Workflow',
        [(1, 'DRAFT', 'Draft', 5, 'task'), (2, 'REVIEW', 'Review', 3, 'task'),
         (3, 'APPROVAL', 'Approval', 1, 'task')],
    ),
    'RECURRING_REPORT': (
        'Recurring Report Workflow',
        [(1, 'PERIOD_CLOSE', 'Period Close', 0, 'start_milestone'),
         (2, 'PREPARE', 'Prepare Report', 2, 'task'), (3, 'SUBMIT', 'Submit', 0, 'finish_milestone')],
    ),
    'TENDER_PACKAGE': (
        'Tender Package Workflow',
        [(1, 'SCOPE_FREEZE', 'Scope Freeze', 0, 'start_milestone'),
         (2, 'PREPARE', 'Prepare Package', 8, 'task'), (3, 'REVIEW', 'Review', 5, 'task'),
         (4, 'FINAL_ISSUE', 'Final Issue', 1, 'task')],
    ),
    'FINAL_DOSSIER': (
        'Final Dossier Workflow',
        [(1, 'COMPILE', 'Compile Accepted Deliverables', 5, 'task'),
         (2, 'VERIFY', 'Completeness Verification', 3, 'task'),
         (3, 'HANDOVER', 'Handover', 0, 'finish_milestone')],
    ),
    'COST_ESTIMATE': (
        'Cost Estimate Workflow',
        [(1, 'BASIS', 'Confirm Estimate Basis', 2, 'task'),
         (2, 'ESTIMATE', 'Prepare Estimate', 5, 'task'), (3, 'REVIEW', 'Review', 3, 'task'),
         (4, 'FINAL_ISSUE', 'Final Issue', 1, 'task')],
    ),
}


def seed_workflow_families(apps, schema_editor):
    WorkflowTemplate = apps.get_model('planning_intelligence', 'WorkflowTemplate')
    WorkflowStage = apps.get_model('planning_intelligence', 'WorkflowStage')
    for code, (name, stages) in WORKFLOW_FAMILIES.items():
        template, _ = WorkflowTemplate.objects.get_or_create(
            project=None, code=code, version=1,
            defaults={
                'name': name, 'description': 'RADAI evidence-controlled workflow family.',
                'status': 'active', 'is_system': True, 'is_default': False,
            },
        )
        for sequence, stage_code, stage_name, duration, activity_type in stages:
            WorkflowStage.objects.get_or_create(
                template=template, sequence=sequence,
                defaults={
                    'code': stage_code, 'name': stage_name,
                    'activity_name_template': '{deliverable} - {stage}',
                    'duration_days': duration, 'responsible_party': '',
                    'activity_type': activity_type,
                    'relationship_to_previous': '' if sequence == 1 else 'FS',
                    'lag_days': 0, 'progress_weight': round(100 / len(stages), 4),
                    'is_release_gate': True,
                },
            )


class Migration(migrations.Migration):

    dependencies = [
        ('planning_intelligence', '0020_trustworthy_schedule_basis'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerationPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready for Approval'), ('approved', 'Approved'), ('superseded', 'Superseded')], db_index=True, default='draft', max_length=16)),
                ('readiness', models.JSONField(blank=True, default=dict)),
                ('selected_scenario', models.CharField(blank=True, max_length=64)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generation_plans_approved', to=settings.AUTH_USER_MODEL)),
                ('basis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generation_plans', to='planning_intelligence.schedulebasis')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_plans', to='planning_intelligence.planningproject')),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='GenerationPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=160)),
                ('sequence', models.PositiveSmallIntegerField()),
                ('duration_months', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('source_references', models.JSONField(blank=True, default=list)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='planning_intelligence.generationplan')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='GenerationDecisionGate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=200)),
                ('sequence', models.PositiveSmallIntegerField(default=1)),
                ('scenarios', models.JSONField(blank=True, default=list)),
                ('source_references', models.JSONField(blank=True, default=list)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decision_gates', to='planning_intelligence.generationplan')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='PlanDeliverable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('workflow_family', models.CharField(choices=[('engineering_document', 'Engineering Document'), ('inspection_report', 'Inspection Report'), ('technical_study', 'Technical Study'), ('drawing', 'Drawing'), ('plan_procedure', 'Plan / Procedure'), ('recurring_report', 'Recurring Report'), ('tender_package', 'Tender Package'), ('final_dossier', 'Final Dossier'), ('cost_estimate', 'Cost Estimate')], max_length=32)),
                ('recurrence', models.CharField(choices=[('none', 'None'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='none', max_length=16)),
                ('recurrence_count', models.PositiveSmallIntegerField(default=1)),
                ('scenario_code', models.CharField(blank=True, default='common', max_length=64)),
                ('technical_sequence', models.PositiveSmallIntegerField(default=50)),
                ('classification_reason', models.CharField(blank=True, max_length=500)),
                ('basis_deliverable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plan_entries', to='planning_intelligence.basisdeliverable')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverables', to='planning_intelligence.generationplan')),
            ],
            options={
                'ordering': ['technical_sequence', 'basis_deliverable_id'],
            },
        ),
        migrations.CreateModel(
            name='GenerationDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('relationship_type', models.CharField(choices=[('FS', 'Finish to Start'), ('SS', 'Start to Start'), ('FF', 'Finish to Finish')], default='FS', max_length=2)),
                ('lag_days', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('rationale', models.CharField(max_length=500)),
                ('source_type', models.CharField(choices=[('document', 'Document'), ('corporate_rule', 'Corporate Rule'), ('planner', 'Planner')], default='corporate_rule', max_length=20)),
                ('source_references', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], db_index=True, default='proposed', max_length=16)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generation_dependencies_reviewed', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='planning_intelligence.generationplan')),
                ('predecessor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='successor_links', to='planning_intelligence.plandeliverable')),
                ('successor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predecessor_links', to='planning_intelligence.plandeliverable')),
            ],
            options={
                'ordering': ['successor__technical_sequence', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='generationplan',
            constraint=models.UniqueConstraint(fields=('project', 'version'), name='uniq_project_generation_plan_version'),
        ),
        migrations.AddConstraint(
            model_name='generationphase',
            constraint=models.UniqueConstraint(fields=('plan', 'code'), name='uniq_generation_plan_phase'),
        ),
        migrations.AddConstraint(
            model_name='generationdecisiongate',
            constraint=models.UniqueConstraint(fields=('plan', 'code'), name='uniq_generation_decision_gate'),
        ),
        migrations.AddConstraint(
            model_name='plandeliverable',
            constraint=models.UniqueConstraint(fields=('plan', 'basis_deliverable'), name='uniq_plan_basis_deliverable'),
        ),
        migrations.AddConstraint(
            model_name='generationdependency',
            constraint=models.UniqueConstraint(fields=('plan', 'predecessor', 'successor', 'relationship_type'), name='uniq_generation_plan_dependency'),
        ),
        migrations.AddConstraint(
            model_name='generationdependency',
            constraint=models.CheckConstraint(check=models.Q(('predecessor', models.F('successor')), _negated=True), name='generation_dependency_distinct'),
        ),
        migrations.AddField(
            model_name='activityrelationship',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.RunPython(seed_workflow_families, reverse_code=migrations.RunPython.noop),
    ]
