# Generated by Django 5.0 on 2026-08-26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning_intelligence', '0021_trustworthy_generation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleresource',
            name='capacity_units_per_day',
            field=models.DecimalField(decimal_places=2, default=8, help_text='Maximum available units per working day for concurrency checks.', max_digits=12),
        ),
        migrations.CreateModel(
            name='ScheduleAssuranceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready'), ('approved', 'Approved'), ('superseded', 'Superseded')], db_index=True, default='draft', max_length=16)),
                ('network_validation', models.JSONField(blank=True, default=dict)),
                ('contract_scenarios', models.JSONField(blank=True, default=dict)),
                ('resource_validation', models.JSONField(blank=True, default=dict)),
                ('change_comparison', models.JSONField(blank=True, default=dict)),
                ('blockers', models.JSONField(blank=True, default=list)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('calculated_state_at', models.DateTimeField()),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_assurance_reviews_approved', to=settings.AUTH_USER_MODEL)),
                ('calculation_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assurance_reviews', to='planning_intelligence.schedulecalculationrun')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assurance_reviews', to='planning_intelligence.scheduleversion')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['version', 'status'], name='planning_in_version_e1d570_idx')],
            },
        ),
    ]
