# Generated by Django 5.0 on 2026-08-26 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planning_intelligence', '0022_trustworthy_scheduling'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='scheduleassurancereview',
            new_name='planning_in_version_31e87f_idx',
            old_name='planning_in_version_e1d570_idx',
        ),
    ]
