# Generated by Django 5.0 on 2026-08-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [(
        'planning_intelligence',
        '0023_rename_planning_in_version_e1d570_idx_planning_in_version_31e87f_idx',
    )]

    operations = [
        migrations.AddField(
            model_name='planninggeneration', name='input_fingerprint',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='planningjob', name='attempt_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='planningjob', name='heartbeat_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planningjob', name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='planningjob', name='progress_log',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='planningjob', name='job_type',
            field=models.CharField(choices=[('analyze', 'Analyze Documents'), ('generate', 'Generate Schedule'), ('calculate', 'Calculate CPM'), ('assurance', 'Run Schedule Assurance')], max_length=16),
        ),
        migrations.AddConstraint(
            model_name='planninggeneration',
            constraint=models.UniqueConstraint(condition=models.Q(('input_fingerprint__isnull', False)), fields=('project', 'input_fingerprint'), name='unique_generation_input_fingerprint'),
        ),
        migrations.AddConstraint(
            model_name='planningjob',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__isnull', False)), fields=('project', 'job_type', 'idempotency_key'), name='unique_planning_job_idempotency'),
        ),
    ]
