# Generated by Django 5.0 on 2026-08-27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.planning_intelligence.models
import apps.planning_intelligence.proposal_models


class Migration(migrations.Migration):

    dependencies = [
        ('planning_intelligence', '0026_workable_plan_job'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='technicalproposal',
            name='status',
            field=models.CharField(
                choices=[
                    ('draft', 'Draft'), ('internal_review', 'Internal Review'),
                    ('approval_review', 'Awaiting Approval'), ('rejected', 'Rejected'),
                    ('approved', 'Approved'), ('issued', 'Issued'),
                    ('superseded', 'Superseded'),
                ],
                db_index=True, default='draft', max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='technicalproposal', name='reviewer',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                related_name='technical_proposals_to_review', to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='technicalproposal', name='approver',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                related_name='technical_proposals_to_approve', to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(model_name='technicalproposal', name='review_due_date', field=models.DateField(blank=True, null=True)),
        migrations.AddField(model_name='technicalproposal', name='approval_due_date', field=models.DateField(blank=True, null=True)),
        migrations.AddField(model_name='technicalproposal', name='review_submitted_at', field=models.DateTimeField(blank=True, null=True)),
        migrations.AddField(model_name='technicalproposal', name='review_completed_at', field=models.DateTimeField(blank=True, null=True)),
        migrations.AddField(model_name='technicalproposal', name='approval_submitted_at', field=models.DateTimeField(blank=True, null=True)),
        migrations.AddField(model_name='technicalproposal', name='approved_at', field=models.DateTimeField(blank=True, null=True)),
        migrations.AddField(model_name='technicalproposal', name='rejected_at', field=models.DateTimeField(blank=True, null=True)),
        migrations.AddField(model_name='technicalproposal', name='review_comments', field=models.TextField(blank=True)),
        migrations.AddField(model_name='technicalproposal', name='approval_comments', field=models.TextField(blank=True)),
        migrations.AddField(
            model_name='proposalexportrecord', name='file',
            field=models.FileField(
                blank=True, max_length=512,
                storage=apps.planning_intelligence.models.get_planning_file_storage,
                upload_to=apps.planning_intelligence.proposal_models._proposal_export_upload_path,
            ),
        ),
        migrations.AddField(
            model_name='proposalexportrecord', name='is_issued_artifact',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.CreateModel(
            name='ProposalWorkflowTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('task_type', models.CharField(choices=[('review', 'Technical Review'), ('approval', 'Approval')], max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('returned', 'Returned'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=16)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('comments', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposal_workflow_tasks_assigned', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposal_workflow_tasks', to=settings.AUTH_USER_MODEL)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_tasks', to='planning_intelligence.technicalproposal')),
            ],
            options={'ordering': ['-created_at']},
        ),
        migrations.AddIndex(
            model_name='proposalworkflowtask',
            index=models.Index(fields=['assigned_to', 'status', 'due_date'], name='plan_prop_task_inbox_idx'),
        ),
        migrations.AddIndex(
            model_name='proposalworkflowtask',
            index=models.Index(fields=['proposal', '-created_at'], name='plan_prop_task_prop_idx'),
        ),
    ]
