# Generated by Django 5.0 on 2026-09-21 06:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning_intelligence', '0033_document_extraction_coverage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenceGraph',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revision', models.PositiveIntegerField(default=0)),
                ('schema_version', models.CharField(max_length=40)),
                ('rule_version', models.CharField(max_length=40)),
                ('source_fingerprint', models.CharField(blank=True, max_length=64)),
                ('source_manifest', models.JSONField(default=list)),
                ('built_at', models.DateTimeField(null=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_graph', to='planning_intelligence.planningproject')),
            ],
        ),
        migrations.CreateModel(
            name='EvidenceDocumentVersion',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=512)),
                ('storage_name', models.CharField(max_length=512)),
                ('file_sha256', models.CharField(blank=True, max_length=64)),
                ('text_sha256', models.CharField(max_length=64)),
                ('extracted_text', models.TextField(blank=True)),
                ('integrity_status', models.CharField(default='unverified', max_length=32)),
                ('extraction_method', models.CharField(blank=True, max_length=64)),
                ('extraction_run_id', models.CharField(blank=True, max_length=64)),
                ('coverage', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_file', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence_versions', to='planning_intelligence.planningfile')),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='planning_intelligence.evidencegraph')),
            ],
        ),
        migrations.CreateModel(
            name='EvidenceNode',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(db_index=True, max_length=32)),
                ('entity_id', models.CharField(db_index=True, max_length=160)),
                ('entity_name', models.CharField(blank=True, max_length=500)),
                ('property', models.CharField(blank=True, max_length=64)),
                ('value', models.JSONField(null=True)),
                ('unit', models.CharField(blank=True, max_length=40)),
                ('provenance_type', models.CharField(max_length=32)),
                ('sources', models.JSONField(default=list)),
                ('rule', models.JSONField(default=dict)),
                ('confidence', models.JSONField(default=dict)),
                ('validation', models.JSONField(default=dict)),
                ('status', models.CharField(db_index=True, default='detected', max_length=24)),
                ('current', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document_version', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nodes', to='planning_intelligence.evidencedocumentversion')),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='planning_intelligence.evidencegraph')),
            ],
        ),
        migrations.CreateModel(
            name='EvidenceEdge',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('relationship', models.CharField(max_length=32)),
                ('provenance', models.JSONField(default=dict)),
                ('current', models.BooleanField(default=True)),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges', to='planning_intelligence.evidencegraph')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_evidence_edges', to='planning_intelligence.evidencenode')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_evidence_edges', to='planning_intelligence.evidencenode')),
            ],
        ),
        migrations.CreateModel(
            name='EvidenceDecision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('graph_revision', models.PositiveIntegerField()),
                ('action', models.CharField(max_length=24)),
                ('reason', models.TextField()),
                ('value', models.JSONField(null=True)),
                ('unit', models.CharField(blank=True, max_length=40)),
                ('source_fingerprint', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decisions', to='planning_intelligence.evidencegraph')),
                ('fact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='review_decisions', to='planning_intelligence.evidencenode')),
                ('target_fact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='link_decisions', to='planning_intelligence.evidencenode')),
            ],
        ),
        migrations.AddIndex(
            model_name='evidencenode',
            index=models.Index(fields=['graph', 'current', 'entity_id', 'property'], name='evidence_entity_property_idx'),
        ),
    ]
