# Generated by Django 5.0 on 2026-09-21 09:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def protect_approved_profiles(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return
    schema_editor.execute("""
        CREATE FUNCTION radai_protect_approved_planning_profile() RETURNS trigger AS $$
        BEGIN
          IF OLD.status = 'approved' THEN
            IF TG_OP = 'DELETE' OR
              (to_jsonb(OLD) - ARRAY['updated_at']) IS DISTINCT FROM
              (to_jsonb(NEW) - ARRAY['updated_at']) THEN
              RAISE EXCEPTION 'Approved planning profiles are immutable; create a revision';
            END IF;
          END IF;
          IF TG_OP = 'DELETE' THEN RETURN OLD; END IF;
          RETURN NEW;
        END; $$ LANGUAGE plpgsql;
        CREATE TRIGGER protect_approved_planning_profile
          BEFORE UPDATE OR DELETE ON planning_intelligence_planningprofile
          FOR EACH ROW EXECUTE FUNCTION radai_protect_approved_planning_profile();
    """)


def unprotect_approved_profiles(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return
    schema_editor.execute('DROP TRIGGER IF EXISTS protect_approved_planning_profile ON planning_intelligence_planningprofile')
    schema_editor.execute('DROP FUNCTION IF EXISTS radai_protect_approved_planning_profile()')


class Migration(migrations.Migration):

    dependencies = [
        ('planning_intelligence', '0036_schedule_evidence_projection'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanningProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=160)),
                ('version', models.PositiveIntegerField()),
                ('revision', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('proposed', 'Proposed'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=16)),
                ('definition', models.JSONField(default=dict)),
                ('content_fingerprint', models.CharField(max_length=64)),
                ('approved_snapshot', models.JSONField(default=dict)),
                ('proposal_reason', models.TextField(blank=True)),
                ('decision_reason', models.TextField(blank=True)),
                ('proposed_at', models.DateTimeField(null=True)),
                ('approved_at', models.DateTimeField(null=True)),
                ('decided_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='planning_profiles_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planning_profiles_created', to=settings.AUTH_USER_MODEL)),
                ('decided_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='planning_profiles_decided', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planning_profiles', to='planning_intelligence.planningproject')),
                ('proposed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='planning_profiles_proposed', to=settings.AUTH_USER_MODEL)),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='planning_intelligence.planningprofile')),
            ],
            options={
                'ordering': ['code', '-version'],
            },
        ),
        migrations.CreateModel(
            name='ProjectPlanningProfileSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.PositiveIntegerField(default=1)),
                ('approved_snapshot', models.JSONField(default=dict)),
                ('content_fingerprint', models.CharField(max_length=64)),
                ('reason', models.TextField()),
                ('selected_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='selections', to='planning_intelligence.planningprofile')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='planning_profile_selection', to='planning_intelligence.planningproject')),
                ('selected_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planning_profile_selections', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='planningprofile',
            constraint=models.UniqueConstraint(fields=('project', 'code', 'version'), name='uniq_planning_profile_version'),
        ),
        migrations.RunPython(protect_approved_profiles, unprotect_approved_profiles),
    ]
