# Generated by Django 5.0 on 2026-09-21 10:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning_intelligence', '0040_planning_builds'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarexception',
            name='working_times',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='workcalendar',
            name='working_times',
            field=models.JSONField(blank=True, default=dict, help_text='Explicit weekday shifts; empty means not specified.'),
        ),
        migrations.AlterField(
            model_name='scheduleexportrecord',
            name='export_format',
            field=models.CharField(choices=[('json', 'JSON'), ('csv', 'CSV'), ('xlsx', 'Excel'), ('xer', 'Primavera XER'), ('mspdi', 'Microsoft Project XML'), ('mspdi_zip', 'Microsoft Project XML and provenance')], max_length=12),
        ),
        migrations.CreateModel(
            name='PlanningRiskRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_key', models.CharField(max_length=128)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('provenance', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('open', 'Open'), ('monitoring', 'Monitoring'), ('mitigated', 'Mitigated'), ('closed', 'Closed')], default='open', max_length=16)),
                ('priority', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=16, null=True)),
                ('response', models.TextField(blank=True)),
                ('resolution', models.TextField(blank=True)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planning_risks_owned', to=settings.AUTH_USER_MODEL)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planning_risks', to='planning_intelligence.scheduleversion')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='planningriskrecord',
            constraint=models.UniqueConstraint(fields=('version', 'source_key'), name='unique_planning_risk_source'),
        ),
    ]
