# Generated by Django 5.0 on 2026-09-21 10:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def protect_approved_controls(apps, schema_editor):
    if schema_editor.connection.vendor == 'postgresql':
        schema_editor.execute("""
            CREATE FUNCTION radai_protect_operational_controls() RETURNS trigger AS $$
            BEGIN
                IF OLD.status IN ('approved', 'published') THEN
                    RAISE EXCEPTION 'Approved operational controls are immutable; create a revision';
                END IF;
                IF TG_OP = 'DELETE' THEN RETURN OLD; END IF;
                RETURN NEW;
            END; $$ LANGUAGE plpgsql;
            CREATE TRIGGER protect_operational_policy BEFORE UPDATE OR DELETE
                ON planning_intelligence_operationalearningpolicy FOR EACH ROW
                EXECUTE FUNCTION radai_protect_operational_controls();
            CREATE TRIGGER protect_operational_report BEFORE UPDATE OR DELETE
                ON planning_intelligence_operationalcontrolreport FOR EACH ROW
                EXECUTE FUNCTION radai_protect_operational_controls();
        """)


def unprotect_approved_controls(apps, schema_editor):
    if schema_editor.connection.vendor == 'postgresql':
        schema_editor.execute('DROP TRIGGER IF EXISTS protect_operational_policy ON planning_intelligence_operationalearningpolicy')
        schema_editor.execute('DROP TRIGGER IF EXISTS protect_operational_report ON planning_intelligence_operationalcontrolreport')
        schema_editor.execute('DROP FUNCTION IF EXISTS radai_protect_operational_controls()')


class Migration(migrations.Migration):

    dependencies = [
        ('planning_intelligence', '0041_planning_registers_calendar_intervals'),
        ('project_control', '0010_verify_execution_reference_keys'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationalEarningPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved')], default='draft', max_length=16)),
                ('definition', models.JSONField(default=dict)),
                ('baseline_fingerprint', models.CharField(max_length=64)),
                ('approval_reason', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operational_policies_approved', to=settings.AUTH_USER_MODEL)),
                ('baseline', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='earning_policies', to='planning_intelligence.schedulebaseline')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operational_policies_created', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operational_earning_policies', to='planning_intelligence.planningproject')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='OperationalControlReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('published', 'Published')], default='draft', max_length=16)),
                ('period_snapshot', models.JSONField(default=dict)),
                ('observations', models.JSONField(default=list)),
                ('cost_coverage_confirmed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('submission_fingerprint', models.CharField(blank=True, max_length=64)),
                ('publication', models.JSONField(default=dict)),
                ('reason', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(null=True)),
                ('published_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('baseline', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operational_reports', to='planning_intelligence.schedulebaseline')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operational_reports_created', to=settings.AUTH_USER_MODEL)),
                ('edited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operational_reports_edited', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operational_control_reports', to='planning_intelligence.planningproject')),
                ('published_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operational_reports_published', to=settings.AUTH_USER_MODEL)),
                ('reporting_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operational_reports', to='project_control.reportingperiod')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operational_reports_submitted', to=settings.AUTH_USER_MODEL)),
                ('supersedes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='corrections', to='planning_intelligence.operationalcontrolreport')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='planning_intelligence.operationalearningpolicy')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='operationalcontrolreport',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['draft', 'submitted'])), fields=('baseline', 'reporting_period'), name='one_open_operational_report'),
        ),
        migrations.RunPython(protect_approved_controls, unprotect_approved_controls),
    ]
