# Generated by Django 5.0 on 2026-09-21 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def protect_delay_history(apps, schema_editor):
    if schema_editor.connection.vendor == 'postgresql':
        schema_editor.execute("""
            CREATE FUNCTION radai_protect_delay_history() RETURNS trigger AS $$
            BEGIN
                IF TG_TABLE_NAME = 'planning_intelligence_delayanalysisrun' THEN
                    RAISE EXCEPTION 'Delay calculation runs are immutable';
                END IF;
                IF TG_TABLE_NAME = 'planning_intelligence_delayanalysiscase' AND OLD.status IN ('approved', 'rejected') THEN
                    RAISE EXCEPTION 'Reviewed delay cases are immutable; create a revision';
                END IF;
                IF TG_OP = 'DELETE' THEN
                    RAISE EXCEPTION 'Delay history cannot be deleted';
                END IF;
                IF NEW.project_id != OLD.project_id OR NEW.baseline_id != OLD.baseline_id THEN
                    RAISE EXCEPTION 'Delay records cannot move between projects or baselines';
                END IF;
                IF TG_TABLE_NAME = 'planning_intelligence_delayanalysiscase' THEN
                    IF NEW.reference_report_id != OLD.reference_report_id THEN
                        RAISE EXCEPTION 'Delay cases cannot change their published reference';
                    END IF;
                END IF;
                RETURN NEW;
            END; $$ LANGUAGE plpgsql;
            CREATE TRIGGER protect_delay_run BEFORE UPDATE OR DELETE
                ON planning_intelligence_delayanalysisrun FOR EACH ROW EXECUTE FUNCTION radai_protect_delay_history();
            CREATE TRIGGER protect_delay_case BEFORE UPDATE OR DELETE
                ON planning_intelligence_delayanalysiscase FOR EACH ROW EXECUTE FUNCTION radai_protect_delay_history();
            CREATE TRIGGER protect_delay_event BEFORE UPDATE OR DELETE
                ON planning_intelligence_delayevent FOR EACH ROW EXECUTE FUNCTION radai_protect_delay_history();
        """)


def unprotect_delay_history(apps, schema_editor):
    if schema_editor.connection.vendor == 'postgresql':
        for name, table in [('run', 'delayanalysisrun'), ('case', 'delayanalysiscase'), ('event', 'delayevent')]:
            schema_editor.execute(f'DROP TRIGGER IF EXISTS protect_delay_{name} ON planning_intelligence_{table}')
        schema_editor.execute('DROP FUNCTION IF EXISTS radai_protect_delay_history()')


class Migration(migrations.Migration):

    dependencies = [
        ('planning_intelligence', '0042_operational_controls'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DelayAnalysisCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('calculated', 'Calculated'), ('submitted', 'Submitted'), ('approved', 'Reviewed'), ('rejected', 'Rejected')], default='draft', max_length=16)),
                ('event_ids', models.JSONField(default=list)),
                ('changes', models.JSONField(default=list)),
                ('scenarios', models.JSONField(default=list)),
                ('recommendation', models.JSONField(default=dict)),
                ('submission_fingerprint', models.CharField(blank=True, max_length=64)),
                ('reason', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(null=True)),
                ('reviewed_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('baseline', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delay_cases', to='planning_intelligence.schedulebaseline')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delay_cases_created', to=settings.AUTH_USER_MODEL)),
                ('edited_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delay_cases_edited', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delay_cases', to='planning_intelligence.planningproject')),
                ('reference_report', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delay_cases', to='planning_intelligence.operationalcontrolreport')),
                ('reviewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delay_cases_reviewed', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delay_cases_submitted', to=settings.AUTH_USER_MODEL)),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='planning_intelligence.delayanalysiscase')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='DelayAnalysisRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_revision', models.PositiveIntegerField()),
                ('fingerprint', models.CharField(max_length=64)),
                ('input_snapshot', models.JSONField(default=dict)),
                ('result', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='planning_intelligence.delayanalysiscase')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delay_runs_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.AddField(
            model_name='delayanalysiscase',
            name='current_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='planning_intelligence.delayanalysisrun'),
        ),
        migrations.CreateModel(
            name='DelayEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('recorded', 'Recorded'), ('closed', 'Closed')], default='recorded', max_length=16)),
                ('activity_ids', models.JSONField(default=list)),
                ('evidence', models.JSONField(default=list)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('baseline', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delay_events', to='planning_intelligence.schedulebaseline')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delay_events_created', to=settings.AUTH_USER_MODEL)),
                ('governance_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delay_events', to='planning_intelligence.governanceitem')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delay_events', to='planning_intelligence.planningproject')),
                ('risk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delay_events', to='planning_intelligence.planningriskrecord')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delay_events_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.RunPython(protect_delay_history, unprotect_delay_history),
    ]
