# Generated by Django 5.0 on 2026-09-22 09:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def protect_sources(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return
    schema_editor.execute('''
        CREATE FUNCTION planning_agreement_immutable_sources() RETURNS trigger AS $$
        BEGIN
            IF ROW(NEW.project_id, NEW.job_id, NEW.version, NEW.source_fingerprint,
                   NEW.source_manifest, NEW.candidates, NEW.analysis_metadata)
               IS DISTINCT FROM
               ROW(OLD.project_id, OLD.job_id, OLD.version, OLD.source_fingerprint,
                   OLD.source_manifest, OLD.candidates, OLD.analysis_metadata) THEN
                RAISE EXCEPTION 'Agreement source assertions are immutable; analyze a new version instead.';
            END IF;
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
        CREATE TRIGGER planning_agreement_immutable_sources
        BEFORE UPDATE ON planning_intelligence_agreementworkspace
        FOR EACH ROW EXECUTE FUNCTION planning_agreement_immutable_sources();
    ''')


def unprotect_sources(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return
    schema_editor.execute('''
        DROP TRIGGER IF EXISTS planning_agreement_immutable_sources ON planning_intelligence_agreementworkspace;
        DROP FUNCTION IF EXISTS planning_agreement_immutable_sources();
    ''')


class Migration(migrations.Migration):

    dependencies = [
        ('planning_intelligence', '0046_evidence_bulk_job'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='planningfile',
            name='category',
            field=models.CharField(choices=[('agreement', 'Agreement / Contract'), ('sow', 'Scope of Work'), ('wbs', 'WBS Structure'), ('mdr', 'Master Deliverable Register'), ('eddr', 'Engineering Document Deliverable Register'), ('schedule_requirements', 'Schedule Requirements'), ('project_control_procedure', 'Project Control Procedure'), ('reference_schedule', 'Reference Schedule'), ('output_schedule_sample', 'Output Schedule Sample'), ('timeline', 'Timeline / Milestone File'), ('other', 'Other Attachment')], default='other', max_length=40),
        ),
        migrations.AlterField(
            model_name='planningjob',
            name='job_type',
            field=models.CharField(choices=[('analyze', 'Analyze Documents'), ('preview', 'Preview Schedule'), ('generate', 'Generate Schedule'), ('build_plan', 'Build Generation Plan'), ('workable_plan', 'Build Workable Project Plan'), ('calculate', 'Calculate CPM'), ('assurance', 'Run Schedule Assurance'), ('evidence_bulk', 'Bulk Evidence Review'), ('agreement_setup', 'Analyze Agreement Workspace')], max_length=16),
        ),
        migrations.CreateModel(
            name='AgreementWorkspace',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField(default=1)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('partial', 'Partial'), ('accepted', 'Accepted')], default='draft', max_length=16)),
                ('source_fingerprint', models.CharField(max_length=64)),
                ('source_manifest', models.JSONField(default=list)),
                ('candidates', models.JSONField(default=list)),
                ('exceptions', models.JSONField(default=list)),
                ('projection', models.JSONField(default=dict)),
                ('accepted_fact_ids', models.JSONField(default=list)),
                ('materialization', models.JSONField(default=dict)),
                ('analysis_metadata', models.JSONField(default=dict)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agreement_workspaces_accepted', to=settings.AUTH_USER_MODEL)),
                ('job', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agreement_workspace', to='planning_intelligence.planningjob')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreement_workspaces', to='planning_intelligence.planningproject')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agreement_workspaces_requested', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-version', '-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='agreementworkspace',
            constraint=models.UniqueConstraint(fields=('project', 'version'), name='unique_agreement_workspace_version'),
        ),
        migrations.RunPython(protect_sources, unprotect_sources),
    ]
