# Generated by Django 4.2.16 on 2026-07-10 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userprofile_account_name_userprofile_business_area_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'managed': False, 'verbose_name': 'User Profile (Deprecated)', 'verbose_name_plural': 'User Profiles (Deprecated)'},
        ),
    ]
