# Generated by Django 5.0 on 2026-09-04 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_userprofile_options'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[migrations.DeleteModel(name='UserProfile')],
        ),
    ]
