# Generated by Django 5.0 on 2026-07-29 13:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pid_checker_v2', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PidCheckerV2Extraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extraction_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('filename', models.CharField(max_length=255)),
                ('file_size_bytes', models.BigIntegerField(default=0)),
                ('file_sha256', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('mode', models.CharField(choices=[('ocr', 'OCR'), ('vision', 'AI Vision (BYOK)')], default='ocr', max_length=16)),
                ('provider', models.CharField(blank=True, choices=[('openai', 'OpenAI'), ('claude', 'Anthropic Claude')], default='', max_length=32)),
                ('model', models.CharField(blank=True, default='', max_length=64)),
                ('force_ocr', models.BooleanField(default=False)),
                ('tag_count', models.IntegerField(default=0)),
                ('summary_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pid_checker_v2_extractions', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extractions', to='pid_checker_v2.pidcheckerv2project')),
            ],
            options={
                'db_table': 'pid_checker_v2_extraction',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PidCheckerV2LineTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=64)),
                ('size', models.CharField(blank=True, default='', max_length=64)),
                ('service', models.CharField(blank=True, default='', max_length=64)),
                ('spec', models.CharField(blank=True, default='', max_length=64)),
                ('serial', models.CharField(blank=True, default='', max_length=64)),
                ('service_group', models.CharField(blank=True, default='', max_length=64)),
                ('extraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_tags', to='pid_checker_v2.pidcheckerv2extraction')),
            ],
            options={
                'db_table': 'pid_checker_v2_line_tag',
                'ordering': ['service', 'serial', 'size'],
            },
        ),
        migrations.AddIndex(
            model_name='pidcheckerv2extraction',
            index=models.Index(fields=['created_by', '-created_at'], name='pid_checker_created_03eb94_idx'),
        ),
        migrations.AddIndex(
            model_name='pidcheckerv2linetag',
            index=models.Index(fields=['extraction', 'service'], name='pid_checker_extract_f9b403_idx'),
        ),
        migrations.AddConstraint(
            model_name='pidcheckerv2linetag',
            constraint=models.UniqueConstraint(fields=('extraction', 'tag'), name='uniq_pidv2_extraction_tag'),
        ),
    ]
