# Generated by Django 5.0 on 2026-07-29 14:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pid_checker_v2', '0002_pidcheckerv2extraction_pidcheckerv2linetag_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PidCheckerV2LegendSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legend_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('section', models.CharField(choices=[('line_list', 'Line List')], max_length=32)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('definition', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pid_checker_v2_legends', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pid_checker_v2_legend_sheet',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['created_by', 'section', '-updated_at'], name='pid_checker_created_7275ee_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='pidcheckerv2legendsheet',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('created_by', 'section'), name='uniq_pidv2_active_legend_per_user_section'),
        ),
    ]
