# Generated by Django 5.0 on 2026-07-29 14:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pid_checker_v2', '0003_pidcheckerv2legendsheet_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PidCheckerV2LineListUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_list_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('filename', models.CharField(max_length=300)),
                ('sheet_name', models.CharField(blank=True, default='', max_length=200)),
                ('title', models.CharField(blank=True, default='', max_length=500)),
                ('doc_no', models.CharField(blank=True, default='', max_length=500)),
                ('doc_date', models.CharField(blank=True, default='', max_length=64)),
                ('pid_extract_ref', models.CharField(blank=True, default='', max_length=500)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('columns', models.JSONField(default=dict)),
                ('summary', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pid_checker_v2_line_lists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pid_checker_v2_line_list_upload',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PidCheckerV2LineListRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excel_row', models.PositiveIntegerField(default=0)),
                ('tag', models.CharField(blank=True, db_index=True, default='', max_length=200)),
                ('size', models.CharField(blank=True, default='', max_length=32)),
                ('service_code', models.CharField(blank=True, default='', max_length=16)),
                ('serial', models.CharField(blank=True, default='', max_length=32)),
                ('spec', models.CharField(blank=True, default='', max_length=32)),
                ('from_ref', models.CharField(blank=True, default='', max_length=300)),
                ('to_ref', models.CharField(blank=True, default='', max_length=300)),
                ('pid_no', models.CharField(blank=True, default='', max_length=300)),
                ('fluid_service', models.CharField(blank=True, default='', max_length=200)),
                ('extras', models.JSONField(default=dict)),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='pid_checker_v2.pidcheckerv2linelistupload')),
            ],
            options={
                'db_table': 'pid_checker_v2_line_list_row',
                'ordering': ['excel_row'],
            },
        ),
        migrations.AddIndex(
            model_name='pidcheckerv2linelistupload',
            index=models.Index(fields=['created_by', '-created_at'], name='pid_checker_created_555a62_idx'),
        ),
        migrations.AddConstraint(
            model_name='pidcheckerv2linelistupload',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('created_by',), name='uniq_pidv2_active_line_list_per_user'),
        ),
        migrations.AddIndex(
            model_name='pidcheckerv2linelistrow',
            index=models.Index(fields=['upload', 'tag'], name='pid_checker_upload__e5991b_idx'),
        ),
    ]
