# Generated by Django 5.0 on 2026-07-29 15:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pid_checker_v2', '0004_line_list_upload'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PidCheckerV2EquipmentListUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_list_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('filename', models.CharField(max_length=300)),
                ('sheet_name', models.CharField(blank=True, default='', max_length=200)),
                ('title', models.CharField(blank=True, default='', max_length=500)),
                ('doc_no', models.CharField(blank=True, default='', max_length=500)),
                ('doc_date', models.CharField(blank=True, default='', max_length=64)),
                ('pid_extract_ref', models.CharField(blank=True, default='', max_length=500)),
                ('company', models.CharField(blank=True, default='', max_length=500)),
                ('project', models.CharField(blank=True, default='', max_length=500)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('columns', models.JSONField(default=dict)),
                ('summary', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pid_checker_v2_equipment_lists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pid_checker_v2_equipment_list_upload',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PidCheckerV2EquipmentListRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excel_row', models.PositiveIntegerField(default=0)),
                ('tag', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('description', models.CharField(blank=True, default='', max_length=300)),
                ('design_flow', models.CharField(blank=True, default='', max_length=100)),
                ('op_pressure', models.CharField(blank=True, default='', max_length=64)),
                ('op_temp', models.CharField(blank=True, default='', max_length=64)),
                ('design_p_min', models.CharField(blank=True, default='', max_length=32)),
                ('design_p_max', models.CharField(blank=True, default='', max_length=32)),
                ('design_t_min', models.CharField(blank=True, default='', max_length=32)),
                ('design_t_max', models.CharField(blank=True, default='', max_length=32)),
                ('moc', models.CharField(blank=True, default='', max_length=100)),
                ('insulation', models.CharField(blank=True, default='', max_length=64)),
                ('dim_length', models.CharField(blank=True, default='', max_length=32)),
                ('dim_diameter', models.CharField(blank=True, default='', max_length=32)),
                ('motor_rating', models.CharField(blank=True, default='', max_length=32)),
                ('pid_no', models.CharField(blank=True, default='', max_length=300)),
                ('qty', models.CharField(blank=True, default='', max_length=16)),
                ('phase', models.CharField(blank=True, default='', max_length=64)),
                ('remarks', models.CharField(blank=True, default='', max_length=500)),
                ('extras', models.JSONField(default=dict)),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='pid_checker_v2.pidcheckerv2equipmentlistupload')),
            ],
            options={
                'db_table': 'pid_checker_v2_equipment_list_row',
                'ordering': ['excel_row'],
            },
        ),
        migrations.AddIndex(
            model_name='pidcheckerv2equipmentlistupload',
            index=models.Index(fields=['created_by', '-created_at'], name='pid_checker_created_4c4ed4_idx'),
        ),
        migrations.AddConstraint(
            model_name='pidcheckerv2equipmentlistupload',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('created_by',), name='uniq_pidv2_active_equipment_list_per_user'),
        ),
        migrations.AddIndex(
            model_name='pidcheckerv2equipmentlistrow',
            index=models.Index(fields=['upload', 'tag'], name='pid_checker_upload__361c0e_idx'),
        ),
    ]
