# Generated by Django 5.0 on 2026-07-29 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pid_checker_v2', '0005_equipment_list_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pidcheckerv2legendsheet',
            name='section',
            field=models.CharField(choices=[('line_list', 'Line List'), ('equipment_list', 'Equipment List')], max_length=32),
        ),
    ]
