# Generated by Django 5.0 on 2026-07-29 16:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pid_checker_v2', '0006_alter_pidcheckerv2legendsheet_section'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='pidcheckerv2legendsheet',
            name='section',
            field=models.CharField(choices=[('line_list', 'Line List'), ('equipment_list', 'Equipment List'), ('instrument_index', 'Instrument Index')], max_length=32),
        ),
        migrations.CreateModel(
            name='PidCheckerV2InstrumentIndexUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument_index_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('filename', models.CharField(max_length=300)),
                ('sheet_name', models.CharField(blank=True, default='', max_length=200)),
                ('title', models.CharField(blank=True, default='', max_length=500)),
                ('doc_no', models.CharField(blank=True, default='', max_length=500)),
                ('doc_date', models.CharField(blank=True, default='', max_length=64)),
                ('pid_extract_ref', models.CharField(blank=True, default='', max_length=500)),
                ('company', models.CharField(blank=True, default='', max_length=300)),
                ('project', models.CharField(blank=True, default='', max_length=500)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('columns', models.JSONField(default=dict)),
                ('summary', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pid_checker_v2_instrument_indexes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pid_checker_v2_instrument_index_upload',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PidCheckerV2InstrumentIndexRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excel_row', models.PositiveIntegerField(default=0)),
                ('tag', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('instrument_type', models.CharField(blank=True, default='', max_length=200)),
                ('service_description', models.CharField(blank=True, default='', max_length=500)),
                ('pid_no', models.CharField(blank=True, default='', max_length=300)),
                ('line_no', models.CharField(blank=True, default='', max_length=200)),
                ('eqpt_no', models.CharField(blank=True, default='', max_length=64)),
                ('location', models.CharField(blank=True, default='', max_length=64)),
                ('ex_class', models.CharField(blank=True, default='', max_length=64)),
                ('power_supply', models.CharField(blank=True, default='', max_length=64)),
                ('range_min', models.CharField(blank=True, default='', max_length=32)),
                ('range_max', models.CharField(blank=True, default='', max_length=32)),
                ('range_unit', models.CharField(blank=True, default='', max_length=32)),
                ('cal_min', models.CharField(blank=True, default='', max_length=32)),
                ('cal_max', models.CharField(blank=True, default='', max_length=32)),
                ('cal_unit', models.CharField(blank=True, default='', max_length=32)),
                ('datasheet_no', models.CharField(blank=True, default='', max_length=200)),
                ('loop_dwg_no', models.CharField(blank=True, default='', max_length=200)),
                ('hookup_dwg_no', models.CharField(blank=True, default='', max_length=200)),
                ('location_layout_no', models.CharField(blank=True, default='', max_length=200)),
                ('manufacturer', models.CharField(blank=True, default='', max_length=200)),
                ('model', models.CharField(blank=True, default='', max_length=200)),
                ('remarks', models.CharField(blank=True, default='', max_length=500)),
                ('rev', models.CharField(blank=True, default='', max_length=16)),
                ('extras', models.JSONField(default=dict)),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='pid_checker_v2.pidcheckerv2instrumentindexupload')),
            ],
            options={
                'db_table': 'pid_checker_v2_instrument_index_row',
                'ordering': ['excel_row'],
            },
        ),
        migrations.AddIndex(
            model_name='pidcheckerv2instrumentindexupload',
            index=models.Index(fields=['created_by', '-created_at'], name='pid_checker_created_0b7aa6_idx'),
        ),
        migrations.AddConstraint(
            model_name='pidcheckerv2instrumentindexupload',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('created_by',), name='uniq_pidv2_active_instrument_index_per_user'),
        ),
        migrations.AddIndex(
            model_name='pidcheckerv2instrumentindexrow',
            index=models.Index(fields=['upload', 'tag'], name='pid_checker_upload__a107d6_idx'),
        ),
    ]
