# Generated by Django 5.0 on 2026-07-30 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pid_checker_v2', '0007_instrument_index_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='pidcheckerv2equipmentlistrow',
            name='diameter_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='pidcheckerv2equipmentlistrow',
            name='length_tt',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='pidcheckerv2equipmentlistrow',
            name='material_internal',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='pidcheckerv2equipmentlistrow',
            name='material_shell',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='pidcheckerv2equipmentlistrow',
            name='nominal_capacity',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='pidcheckerv2equipmentlistrow',
            name='trim',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
