# Generated by Django 5.0 on 2026-07-30 09:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pid_checker_v2', '0008_equipment_row_attributes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PidCheckerV2UsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('feature', models.CharField(db_index=True, max_length=64)),
                ('provider', models.CharField(blank=True, default='', max_length=32)),
                ('model_name', models.CharField(blank=True, default='', max_length=128)),
                ('call_count', models.PositiveIntegerField(default=0)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('total_tokens', models.PositiveIntegerField(default=0)),
                ('cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('related_extraction_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('related_upload_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('notes', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pid_checker_v2_usage_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pid_checker_v2_usage_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_by', '-created_at'], name='pid_checker_created_5a4345_idx'), models.Index(fields=['feature', '-created_at'], name='pid_checker_feature_9bc588_idx')],
            },
        ),
    ]
