# Generated by Django 5.2.15 on 2026-08-25 04:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pid_checker_v2', '0009_pidcheckerv2usagelog'),
        ('pid_verification', '0011_rename_pidv_ai_check_runs_run_id_idx_pidv_ai_che_run_id_bdcd91_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pidcheckerv2legendsheet',
            name='section',
            field=models.CharField(choices=[('line_list', 'Line List'), ('equipment_list', 'Equipment List'), ('instrument_index', 'Instrument Index'), ('valve', 'Valve'), ('piping', 'Piping'), ('actuator_symbols', 'Actuator Symbols'), ('flow_detector', 'Flow Detector'), ('control_valve_regulator', 'Control Valve & Regulator'), ('instrument_signal', 'Instrument Signal'), ('equipment_symbols', 'Equipment Symbols'), ('instrument_function', 'Instrument Function'), ('pipe_connection', 'Pipe Connection'), ('pipe_end', 'Pipe End'), ('special_piping', 'Special Piping'), ('scope_symbols', 'Scope Symbols'), ('miscellaneous', 'Miscellaneous'), ('limit_line', 'Limit Line'), ('other_specialties', 'Other Specialties'), ('instrument_typical_letter', 'Instrument Typical Letter')], max_length=32),
        ),
        migrations.CreateModel(
            name='LegendSymbolImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('section', models.CharField(max_length=64)),
                ('symbol_name', models.CharField(max_length=255)),
                ('image', models.BinaryField()),
                ('content_type', models.CharField(default='image/png', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('legend_sheet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='symbol_images', to='pid_verification.pidvlegendsheet')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legend_symbol_images', to='pid_verification.pidvproject')),
            ],
            options={
                'db_table': 'pid_checker_v2_legend_symbol_image',
                'ordering': ['section', 'symbol_name'],
                'indexes': [models.Index(fields=['project', 'section'], name='pid_checker_project_658e9b_idx')],
                'unique_together': {('project', 'section', 'symbol_name')},
            },
        ),
    ]
