# Generated by Django 5.2.15 on 2026-08-25 11:53

import apps.pid_checker_v2.models
import django.db.models.deletion
from django.db import migrations, models


def _copy_binary_image_to_image_file(apps, schema_editor):
    """One-time backfill: existing rows store their picture as raw bytes in
    the (soon to be removed) `image` BinaryField — copy each into the new
    `image_file` (routed through Django's storage backend, i.e. S3 in any
    environment with it configured, local disk otherwise) before the old
    field is dropped below.
    """
    from django.core.files.base import ContentFile

    LegendSymbolImage = apps.get_model('pid_checker_v2', 'LegendSymbolImage')
    ext_by_content_type = {'image/png': 'png', 'image/jpeg': 'jpg', 'image/svg+xml': 'svg'}
    for row in LegendSymbolImage.objects.all():
        data = bytes(row.image) if row.image else b''
        if not data:
            continue
        ext = ext_by_content_type.get(row.content_type, 'png')
        row.image_file.save(f'{row.image_id}.{ext}', ContentFile(data), save=True)


def _noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('pid_checker_v2', '0010_alter_pidcheckerv2legendsheet_section_and_more'),
        ('pid_verification', '0011_rename_pidv_ai_check_runs_run_id_idx_pidv_ai_che_run_id_bdcd91_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='legendsymbolimage',
            name='image_file',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=apps.pid_checker_v2.models.legend_symbol_image_upload_path),
        ),
        migrations.AddField(
            model_name='legendsymbolimage',
            name='is_default',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='legendsymbolimage',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='legend_symbol_images', to='pid_verification.pidvproject'),
        ),
        migrations.AlterField(
            model_name='pidcheckerv2legendsheet',
            name='section',
            field=models.CharField(choices=[('line_list', 'Line List'), ('equipment_list', 'Equipment List'), ('instrument_index', 'Instrument Index'), ('valve', 'Valve'), ('piping', 'Piping'), ('actuator_symbols', 'Actuator Symbols'), ('flow_detector', 'Flow Detector'), ('control_valve_regulator', 'Control Valve & Regulator'), ('instrument_signal', 'Instrument Signal'), ('equipment_symbols', 'Equipment Symbols'), ('instrument_function', 'Instrument Function'), ('pipe_connection', 'Pipe Connection'), ('pipe_end', 'Pipe End'), ('special_piping', 'Special Piping'), ('scope_symbols', 'Scope Symbols'), ('miscellaneous', 'Miscellaneous'), ('limit_line', 'Limit Line'), ('other_specialties', 'Other Specialties'), ('instrument_typical_letter', 'Instrument Typical Letter'), ('drawing_cont', 'Drawing Continuations'), ('general_instrument', 'General Instrument or Function Symbols')], max_length=32),
        ),
        migrations.RunPython(_copy_binary_image_to_image_file, _noop_reverse),
        migrations.RemoveField(
            model_name='legendsymbolimage',
            name='image',
        ),
        migrations.AddConstraint(
            model_name='legendsymbolimage',
            constraint=models.UniqueConstraint(condition=models.Q(('project__isnull', True)), fields=('section', 'symbol_name'), name='uniq_pidv2_symbolimage_default_per_symbol'),
        ),
    ]
