# Generated by Django 5.2.15 on 2026-08-25 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pid_checker_v2', '0012_legend_symbol_image_revert_db_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='pidcheckerv2linetag',
            name='confidence',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
    ]
