# Generated by Django 5.0 on 2026-09-30 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pid_checker_v2', '0014_repair_missing_primary_keys'),
        ('project_organizer', '0002_rename_project_org_status_98d3a1_idx_project_org_status_61b226_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pidcheckerv2legendsheet',
            name='uniq_pidv2_active_legend_per_user_section',
        ),
        migrations.AddField(
            model_name='pidcheckerv2legendsheet',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pid_checker_v2_legends', to='project_organizer.project'),
        ),
        migrations.AddIndex(
            model_name='pidcheckerv2legendsheet',
            index=models.Index(fields=['project', 'section'], name='pid_checker_project_8ffe38_idx'),
        ),
        migrations.AddConstraint(
            model_name='pidcheckerv2legendsheet',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('created_by', 'section', 'project'), name='uniq_pidv2_active_legend_per_user_section_project'),
        ),
    ]
