# Generated by Django 5.0 on 2026-08-28 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pid_checker_v2', '0014_repair_missing_primary_keys'),
    ]

    operations = [
        migrations.AddField(
            model_name='pidcheckerv2equipmentlistupload',
            name='owner_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipment_lists', to='pid_checker_v2.pidcheckerv2project'),
        ),
        migrations.AddField(
            model_name='pidcheckerv2instrumentindexupload',
            name='owner_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instrument_indexes', to='pid_checker_v2.pidcheckerv2project'),
        ),
        migrations.AddField(
            model_name='pidcheckerv2linelistupload',
            name='owner_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='line_lists', to='pid_checker_v2.pidcheckerv2project'),
        ),
    ]
