# Generated by Django 5.0 on 2026-08-28 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pid_checker_v2', '0015_pidcheckerv2equipmentlistupload_owner_project_and_more'),
        ('pid_verification', '0013_repair_remaining_primary_keys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pidcheckerv2equipmentlistupload',
            name='owner_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checker_v2_equipment_lists', to='pid_verification.pidvproject'),
        ),
        migrations.AlterField(
            model_name='pidcheckerv2instrumentindexupload',
            name='owner_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checker_v2_instrument_indexes', to='pid_verification.pidvproject'),
        ),
        migrations.AlterField(
            model_name='pidcheckerv2linelistupload',
            name='owner_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checker_v2_line_lists', to='pid_verification.pidvproject'),
        ),
    ]
