# Generated by Django 5.0 on 2026-08-28 09:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pid_checker_v2', '0016_alter_pidcheckerv2equipmentlistupload_owner_project_and_more'),
        ('pid_verification', '0013_repair_remaining_primary_keys'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pidcheckerv2equipmentlistupload',
            name='uniq_pidv2_active_equipment_list_per_user',
        ),
        migrations.RemoveConstraint(
            model_name='pidcheckerv2instrumentindexupload',
            name='uniq_pidv2_active_instrument_index_per_user',
        ),
        migrations.RemoveConstraint(
            model_name='pidcheckerv2linelistupload',
            name='uniq_pidv2_active_line_list_per_user',
        ),
        migrations.AddConstraint(
            model_name='pidcheckerv2equipmentlistupload',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('created_by', 'owner_project'), name='uniq_pidv2_active_equip_list_per_user_project'),
        ),
        migrations.AddConstraint(
            model_name='pidcheckerv2instrumentindexupload',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('created_by', 'owner_project'), name='uniq_pidv2_active_instr_index_per_user_project'),
        ),
        migrations.AddConstraint(
            model_name='pidcheckerv2linelistupload',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('created_by', 'owner_project'), name='uniq_pidv2_active_line_list_per_user_project'),
        ),
    ]
