# Generated by hand — isolated from unrelated pre-existing model/migration
# drift on pidcheckerv2equipmentlistupload/instrumentindexupload/
# linelistupload's owner_project field (flagged separately, not touched
# here) and pid_verification's PIDVTagIndex, which `makemigrations`
# otherwise bundles into the same migration since it diffs every app's
# models against migration state in one pass. Only the LegendSymbolImage
# default-pictures change (see models.py's own docstring) belongs here.
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pid_checker_v2', '0020_add_line_list_service_codes'),
        ('pid_verification', '0014_pidvtagindex'),
    ]

    operations = [
        migrations.AddField(
            model_name='legendsymbolimage',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='legendsymbolimage',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='legend_symbol_images', to='pid_verification.pidvproject'),
        ),
        migrations.AddConstraint(
            model_name='legendsymbolimage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('section', 'symbol_name'), name='uniq_pidv2_default_symbol_per_section'),
        ),
    ]
