# Generated by Django 5.0 on 2026-09-08 11:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pid_checker_v2', '0022_remove_pidcheckerv2equipmentlistupload_uniq_pidv2_active_equip_list_per_user_project_and_more'),
        ('pid_verification', '0014_pidvtagindex'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pidcheckerv2equipmentlistupload',
            name='uniq_pidv2_active_equipment_list_per_user',
        ),
        migrations.RemoveConstraint(
            model_name='pidcheckerv2instrumentindexupload',
            name='uniq_pidv2_active_instrument_index_per_user',
        ),
        migrations.RemoveConstraint(
            model_name='pidcheckerv2linelistupload',
            name='uniq_pidv2_active_line_list_per_user',
        ),
        migrations.AddField(
            model_name='pidcheckerv2equipmentlistupload',
            name='owner_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checker_v2_equipment_lists', to='pid_verification.pidvproject'),
        ),
        migrations.AddField(
            model_name='pidcheckerv2instrumentindexupload',
            name='owner_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checker_v2_instrument_indexes', to='pid_verification.pidvproject'),
        ),
        migrations.AddField(
            model_name='pidcheckerv2linelistupload',
            name='owner_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checker_v2_line_lists', to='pid_verification.pidvproject'),
        ),
        migrations.AddConstraint(
            model_name='pidcheckerv2equipmentlistupload',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('created_by', 'owner_project'), name='uniq_pidv2_active_equip_list_per_user_project'),
        ),
        migrations.AddConstraint(
            model_name='pidcheckerv2instrumentindexupload',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('created_by', 'owner_project'), name='uniq_pidv2_active_instr_index_per_user_project'),
        ),
        migrations.AddConstraint(
            model_name='pidcheckerv2linelistupload',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('created_by', 'owner_project'), name='uniq_pidv2_active_line_list_per_user_project'),
        ),
    ]
