# Generated by Django 5.0 on 2026-10-01 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pid_checker_v2', '0015_legend_project_scope'),
        ('pid_checker_v2', '0023_reinstate_per_project_master_lists'),
    ]

    operations = [
    ]
