# Generated by Django 5.0 on 2026-10-09 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pid_checker_v2', '0024_merge_20261001_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pidcheckerv2legendsheet',
            name='section',
            field=models.CharField(choices=[('line_list', 'Line List'), ('equipment_list', 'Equipment List'), ('instrument_index', 'Instrument Index'), ('valve', 'Valve'), ('piping', 'Piping'), ('actuator_symbols', 'Actuator Symbols'), ('flow_detector', 'Flow Detector'), ('control_valve_regulator', 'Control Valve & Regulator'), ('instrument_signal', 'Instrument Signal'), ('equipment_symbols', 'Equipment Symbols'), ('instrument_function', 'Instrument Function'), ('pipe_connection', 'Pipe Connection'), ('pipe_end', 'Pipe End'), ('special_piping', 'Special Piping'), ('scope_symbols', 'Scope Symbols'), ('miscellaneous', 'Miscellaneous'), ('limit_line', 'Limit Line'), ('other_specialties', 'Other Specialties'), ('instrument_typical_letter', 'Instrument Typical Letter'), ('drawing_cont', 'Drawing Continuations'), ('general_instrument', 'General Instrument or Function Symbols'), ('electrical', 'Electrical')], max_length=32),
        ),
    ]
