# Generated by Django 5.0 on 2026-08-12 12:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0004_alter_document_verified_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExitRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(help_text='Employee full name (cached)', max_length=255)),
                ('employee_email', models.EmailField(help_text='Employee email (cached)', max_length=254)),
                ('employee_id', models.CharField(blank=True, help_text='Employee ID (cached)', max_length=100, null=True)),
                ('position', models.CharField(help_text='Job position (cached)', max_length=255)),
                ('department', models.CharField(help_text='Department (cached)', max_length=255)),
                ('request_type', models.CharField(choices=[('resignation', 'Voluntary Resignation'), ('termination', 'Termination'), ('contract_end', 'Contract Completion'), ('retirement', 'Retirement'), ('mutual_separation', 'Mutual Separation'), ('absconding', 'Absconding')], default='resignation', help_text='Type of exit request', max_length=50)),
                ('exit_reason', models.CharField(help_text='Primary reason for exit', max_length=100)),
                ('exit_reason_detail', models.TextField(blank=True, help_text='Detailed explanation (optional)', null=True)),
                ('resignation_letter', models.CharField(blank=True, help_text='S3 path to resignation letter file', max_length=500, null=True)),
                ('resignation_letter_url', models.URLField(blank=True, help_text='Presigned URL for resignation letter', max_length=1000, null=True)),
                ('proposed_last_working_day', models.DateField(help_text="Employee's proposed last working day")),
                ('notice_period_days', models.IntegerField(help_text='Actual notice period in days (flexible)')),
                ('standard_notice_period', models.IntegerField(default=30, help_text='Standard notice period per company policy')),
                ('notice_period_buyout', models.BooleanField(default=False, help_text='Whether company is buying out notice period')),
                ('notice_period_buyout_days', models.IntegerField(default=0, help_text='Number of days being bought out')),
                ('manager_approval_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text="Manager's approval status", max_length=20)),
                ('manager_approval_date', models.DateTimeField(blank=True, help_text='When manager approved/rejected', null=True)),
                ('manager_comments', models.TextField(blank=True, help_text="Manager's comments/feedback", null=True)),
                ('hr_approval_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text="HR's approval status", max_length=20)),
                ('hr_approval_date', models.DateTimeField(blank=True, help_text='When HR approved/rejected', null=True)),
                ('hr_comments', models.TextField(blank=True, help_text="HR's comments/feedback", null=True)),
                ('final_approved_lwd', models.DateField(blank=True, help_text='Final LWD approved by HR (can differ from proposed)', null=True)),
                ('overall_status', models.CharField(choices=[('pending_manager', 'Pending Manager Approval'), ('pending_hr', 'Pending HR Approval'), ('approved', 'Approved - Exit Process Can Begin'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn by Employee'), ('processing', 'Exit Process in Progress'), ('completed', 'Exit Completed')], db_index=True, default='pending_manager', help_text='Overall request status', max_length=30)),
                ('exit_process_status', models.CharField(choices=[('not_started', 'Not Started'), ('access_revocation', 'Access Revocation in Progress'), ('equipment_return', 'Equipment Return in Progress'), ('exit_interview', 'Exit Interview Scheduled/Completed'), ('clearance', 'Department Clearances in Progress'), ('settlement', 'Final Settlement Processing'), ('completed', 'All Exit Activities Completed')], default='not_started', help_text='Status of exit process activities', max_length=30)),
                ('exit_interview_completed', models.BooleanField(default=False, help_text='Whether exit interview was completed')),
                ('exit_interview_date', models.DateTimeField(blank=True, help_text='When exit interview was conducted', null=True)),
                ('exit_interview_feedback', models.TextField(blank=True, help_text='Feedback from exit interview', null=True)),
                ('withdrawn_at', models.DateTimeField(blank=True, help_text='When request was withdrawn', null=True)),
                ('withdrawal_reason', models.TextField(blank=True, help_text='Reason for withdrawal', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exit_interview_conducted_by', models.ForeignKey(blank=True, help_text='HR person who conducted interview', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exit_interviews_conducted', to=settings.AUTH_USER_MODEL)),
                ('hr_approved_by', models.ForeignKey(blank=True, help_text='HR person who approved/rejected', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exit_requests_hr_approved', to=settings.AUTH_USER_MODEL)),
                ('manager_approved_by', models.ForeignKey(blank=True, help_text='Manager who approved/rejected', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exit_requests_manager_approved', to=settings.AUTH_USER_MODEL)),
                ('offboarding_record', models.OneToOneField(blank=True, help_text='Linked offboarding record (created when approved)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exit_request', to='onboarding.offboardingrecord')),
                ('reporting_manager', models.ForeignKey(blank=True, help_text='Direct reporting manager', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_exit_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='Employee requesting exit', on_delete=django.db.models.deletion.CASCADE, related_name='exit_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'exit_request',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExitClearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('IT', 'Information Technology'), ('HR', 'Human Resources'), ('Finance', 'Finance & Accounts'), ('Admin', 'Administration'), ('Security', 'Security'), ('Library', 'Library'), ('Facilities', 'Facilities Management'), ('Project', 'Project Department')], help_text='Department providing clearance', max_length=50)),
                ('clearance_status', models.CharField(choices=[('pending', 'Pending'), ('cleared', 'Cleared'), ('pending_action', 'Pending Employee Action')], default='pending', help_text='Current clearance status', max_length=20)),
                ('clearance_date', models.DateTimeField(blank=True, help_text='When clearance was provided', null=True)),
                ('pending_items', models.TextField(blank=True, help_text='Items pending (e.g., "Return laptop, Clear dues")', null=True)),
                ('comments', models.TextField(blank=True, help_text='Additional comments from department', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cleared_by', models.ForeignKey(blank=True, help_text='Department representative who cleared', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clearances_provided', to=settings.AUTH_USER_MODEL)),
                ('exit_request', models.ForeignKey(help_text='Related exit request', on_delete=django.db.models.deletion.CASCADE, related_name='clearances', to='onboarding.exitrequest')),
            ],
            options={
                'db_table': 'exit_clearance',
                'ordering': ['department'],
            },
        ),
        migrations.CreateModel(
            name='ExitActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('request_submitted', 'Exit Request Submitted'), ('manager_notified', 'Manager Notified'), ('manager_approved', 'Manager Approved'), ('manager_rejected', 'Manager Rejected'), ('manager_commented', 'Manager Added Comments'), ('hr_notified', 'HR Notified'), ('hr_approved', 'HR Approved'), ('hr_rejected', 'HR Rejected'), ('hr_commented', 'HR Added Comments'), ('lwd_adjusted', 'Last Working Day Adjusted'), ('process_initiated', 'Exit Process Initiated'), ('access_revoked', 'System Access Revoked'), ('equipment_returned', 'Equipment Returned'), ('exit_interview_scheduled', 'Exit Interview Scheduled'), ('exit_interview_completed', 'Exit Interview Completed'), ('clearance_completed', 'Department Clearance Completed'), ('settlement_processed', 'Final Settlement Processed'), ('request_withdrawn', 'Request Withdrawn'), ('offboarding_created', 'Offboarding Record Created'), ('status_changed', 'Status Changed'), ('document_uploaded', 'Document Uploaded'), ('email_sent', 'Email Notification Sent'), ('other', 'Other Activity')], help_text='Type of activity', max_length=50)),
                ('activity_description', models.TextField(help_text='Description of what happened')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional flexible data (e.g., old/new values, file references)')),
                ('activity_date', models.DateTimeField(auto_now_add=True, help_text='When this activity occurred')),
                ('performed_by', models.ForeignKey(blank=True, help_text='User who performed this activity', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exit_activities_performed', to=settings.AUTH_USER_MODEL)),
                ('exit_request', models.ForeignKey(help_text='Related exit request', on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='onboarding.exitrequest')),
            ],
            options={
                'db_table': 'exit_activity',
                'ordering': ['-activity_date'],
            },
        ),
        migrations.CreateModel(
            name='NoticePeriodPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation_level', models.CharField(help_text='Designation level (e.g., junior, senior, manager, director)', max_length=100)),
                ('department', models.CharField(blank=True, help_text='Department-specific policy (leave blank for company-wide)', max_length=255, null=True)),
                ('standard_notice_days', models.IntegerField(default=30, help_text='Standard notice period in days')),
                ('minimum_notice_days', models.IntegerField(default=15, help_text='Minimum acceptable notice period')),
                ('buyout_allowed', models.BooleanField(default=False, help_text='Whether company allows notice period buyout')),
                ('buyout_calculation', models.CharField(choices=[('full_salary', 'Full Salary'), ('basic_salary', 'Basic Salary Only'), ('pro_rata', 'Pro-rata Based on Days')], default='full_salary', help_text='How to calculate buyout amount', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this policy is currently active')),
                ('effective_from', models.DateField(help_text='Date from which this policy is effective')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'notice_period_policy',
                'ordering': ['-effective_from', 'designation_level'],
                'indexes': [models.Index(fields=['designation_level'], name='notice_peri_designa_e1fcbc_idx'), models.Index(fields=['department'], name='notice_peri_departm_7c0d2a_idx'), models.Index(fields=['is_active'], name='notice_peri_is_acti_f11205_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='exitrequest',
            index=models.Index(fields=['overall_status'], name='exit_reques_overall_1dbde5_idx'),
        ),
        migrations.AddIndex(
            model_name='exitrequest',
            index=models.Index(fields=['proposed_last_working_day'], name='exit_reques_propose_35d208_idx'),
        ),
        migrations.AddIndex(
            model_name='exitrequest',
            index=models.Index(fields=['user'], name='exit_reques_user_id_6cfb22_idx'),
        ),
        migrations.AddIndex(
            model_name='exitrequest',
            index=models.Index(fields=['reporting_manager'], name='exit_reques_reporti_ea4b03_idx'),
        ),
        migrations.AddIndex(
            model_name='exitrequest',
            index=models.Index(fields=['manager_approval_status'], name='exit_reques_manager_e39811_idx'),
        ),
        migrations.AddIndex(
            model_name='exitrequest',
            index=models.Index(fields=['hr_approval_status'], name='exit_reques_hr_appr_37dfed_idx'),
        ),
        migrations.AddIndex(
            model_name='exitclearance',
            index=models.Index(fields=['exit_request', 'clearance_status'], name='exit_cleara_exit_re_f9999c_idx'),
        ),
        migrations.AddIndex(
            model_name='exitclearance',
            index=models.Index(fields=['department'], name='exit_cleara_departm_e1b4b7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='exitclearance',
            unique_together={('exit_request', 'department')},
        ),
        migrations.AddIndex(
            model_name='exitactivity',
            index=models.Index(fields=['exit_request', '-activity_date'], name='exit_activi_exit_re_a7f546_idx'),
        ),
        migrations.AddIndex(
            model_name='exitactivity',
            index=models.Index(fields=['activity_type'], name='exit_activi_activit_ba2c1c_idx'),
        ),
    ]
