# Generated by Django 5.0 on 2026-09-03 04:46

import calendar
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def populate_probation_end_dates(apps, schema_editor):
    EmployeeMaster = apps.get_model('hr_core', 'EmployeeMaster')
    for employee in EmployeeMaster.objects.filter(probation_end_date__isnull=True).iterator():
        month = employee.join_date.month + 6
        year = employee.join_date.year + (month - 1) // 12
        month = (month - 1) % 12 + 1
        day = min(employee.join_date.day, calendar.monthrange(year, month)[1])
        employee.probation_end_date = employee.join_date.replace(
            year=year, month=month, day=day
        )
        employee.save(update_fields=['probation_end_date'])


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0010_add_project_fields_to_exit_approval'),
        ('hr_core', '0002_employeemaster_engineer_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProbationPerformanceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkpoint_days', models.PositiveSmallIntegerField(default=100)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted')], default='draft', max_length=20)),
                ('job_knowledge_rating', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('work_quality_rating', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('reliability_rating', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('teamwork_rating', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('achievements', models.TextField(blank=True)),
                ('strengths', models.TextField(blank=True)),
                ('improvement_areas', models.TextField(blank=True)),
                ('next_period_goals', models.TextField(blank=True)),
                ('overall_comments', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='probation_reports_created', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='probation_performance_reports', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='probation_reports_submitted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='probation_reports_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'onboarding_probation_performance_report',
                'ordering': ['-due_date', '-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='probationperformancereport',
            constraint=models.UniqueConstraint(fields=('employee', 'checkpoint_days'), name='unique_employee_probation_checkpoint'),
        ),
        migrations.RunPython(populate_probation_end_dates, migrations.RunPython.noop),
    ]
