# Generated by Django 5.0 on 2026-09-03 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0011_probationperformancereport_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='probationperformancereport',
            name='insights_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='probationperformancereport',
            name='system_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
