# Generated by Django 5.0 on 2026-09-04 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_core', '0007_alter_employeemaster_email_alter_employeemaster_user'),
        ('onboarding', '0012_probationperformancereport_insights_generated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offboardingrecord',
            name='canonical_employee',
            field=models.ForeignKey(blank=True, help_text='Canonical employee identity; duplicated fields are historical exit snapshots.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='offboarding_records', to='hr_core.employeemaster'),
        ),
        migrations.AddField(
            model_name='onboardingrecord',
            name='canonical_employee',
            field=models.OneToOneField(blank=True, help_text='Canonical employee identity; name/email/code fields are immutable workflow snapshots.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='onboarding_record', to='hr_core.employeemaster'),
        ),
        migrations.AddField(
            model_name='probationperformancereport',
            name='canonical_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='probation_performance_reports', to='hr_core.employeemaster'),
        ),
    ]
