# Generated by Django 5.0 on 2026-09-21 07:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_core', '0014_overtimerequest_day_entries'),
        ('onboarding', '0014_alter_onboardingrecord_canonical_employee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LifecycleCaseDeletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workflow', models.CharField(choices=[('onboarding', 'Onboarding'), ('offboarding', 'Offboarding')], max_length=20)),
                ('record_id', models.PositiveBigIntegerField()),
                ('employee_email', models.EmailField(blank=True, db_index=True, max_length=254)),
                ('employee_number', models.CharField(blank=True, db_index=True, max_length=100)),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
                ('canonical_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lifecycle_case_deletions', to='hr_core.employeemaster')),
                ('deleted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_lifecycle_cases', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lifecycle_case_deletions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'onboarding_lifecycle_case_deletion',
            },
        ),
        migrations.AddConstraint(
            model_name='lifecyclecasedeletion',
            constraint=models.UniqueConstraint(fields=('workflow', 'record_id'), name='unique_lifecycle_case_deletion'),
        ),
    ]
