# Generated by Django 4.2.16 on 2026-02-05 07:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectricalEquipmentType',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=10)),
                ('category', models.CharField(max_length=100)),
                ('standards', models.JSONField(default=list)),
                ('sections', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Electrical Equipment Type',
                'verbose_name_plural': 'Electrical Equipment Types',
                'db_table': 'electrical_equipment_types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ElectricalDatasheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_number', models.CharField(db_index=True, max_length=100, unique=True)),
                ('service_description', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('form_data', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('revision_required', 'Revision Required')], db_index=True, default='draft', max_length=20)),
                ('revision_number', models.IntegerField(default=1)),
                ('revision_notes', models.TextField(blank=True)),
                ('project_name', models.CharField(blank=True, max_length=200)),
                ('project_number', models.CharField(blank=True, db_index=True, max_length=100)),
                ('discipline', models.CharField(default='Electrical', max_length=50)),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='electrical_datasheets_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='electrical_datasheets_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='electrical_datasheets_deleted', to=settings.AUTH_USER_MODEL)),
                ('equipment_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='datasheets', to='electrical_datasheet.electricalequipmenttype')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='electrical_datasheets_reviewed', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='electrical_datasheets_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Electrical Datasheet',
                'verbose_name_plural': 'Electrical Datasheets',
                'db_table': 'electrical_datasheets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DatasheetRevisionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_number', models.IntegerField()),
                ('form_data', models.JSONField()),
                ('status', models.CharField(max_length=20)),
                ('revision_notes', models.TextField(blank=True)),
                ('revised_at', models.DateTimeField(auto_now_add=True)),
                ('datasheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revision_history', to='electrical_datasheet.electricaldatasheet')),
                ('revised_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Datasheet Revision',
                'verbose_name_plural': 'Datasheet Revisions',
                'db_table': 'electrical_datasheet_revisions',
                'ordering': ['-revision_number'],
            },
        ),
        migrations.CreateModel(
            name='DatasheetComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField()),
                ('field_id', models.CharField(blank=True, max_length=100)),
                ('commented_at', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('commented_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('datasheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='electrical_datasheet.electricaldatasheet')),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='electrical_datasheet.datasheetcomment')),
            ],
            options={
                'verbose_name': 'Datasheet Comment',
                'verbose_name_plural': 'Datasheet Comments',
                'db_table': 'electrical_datasheet_comments',
                'ordering': ['commented_at'],
            },
        ),
        migrations.AddIndex(
            model_name='electricaldatasheet',
            index=models.Index(fields=['equipment_type', 'status'], name='electrical__equipme_6775f1_idx'),
        ),
        migrations.AddIndex(
            model_name='electricaldatasheet',
            index=models.Index(fields=['project_number', 'status'], name='electrical__project_af2783_idx'),
        ),
        migrations.AddIndex(
            model_name='electricaldatasheet',
            index=models.Index(fields=['created_at', 'status'], name='electrical__created_474e80_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='datasheetrevisionhistory',
            unique_together={('datasheet', 'revision_number')},
        ),
    ]
