# Generated by Django 5.0 on 2026-07-16 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistExtractionJob',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('template_id', models.CharField(default='ups_battery_inspection', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('progress', models.IntegerField(default=0)),
                ('file_count', models.IntegerField(default=0)),
                ('total_pages', models.IntegerField(default=0)),
                ('fields_extracted', models.IntegerField(default=0)),
                ('signatures_found', models.IntegerField(default=0)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('extracted_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('excel_file', models.FileField(blank=True, null=True, upload_to='checklist_exports/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'electrical_checklist_jobs',
                'ordering': ['-created_at'],
            },
        ),
    ]
