# Generated by Django 5.0 on 2026-07-16 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electrical_checklist', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistProjectMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Project Owner'), ('manager', 'Project Manager'), ('engineer', 'Engineer'), ('viewer', 'Viewer')], default='viewer', max_length=20)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'electrical_checklist_project_members',
                'ordering': ['-added_at'],
            },
        ),
        migrations.RemoveField(
            model_name='checklistextractionjob',
            name='excel_file',
        ),
        migrations.AddField(
            model_name='checklistextractionjob',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checklistextractionjob',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_checklists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='checklistextractionjob',
            name='excel_file_size',
            field=models.IntegerField(default=0, help_text='Excel file size in bytes'),
        ),
        migrations.AddField(
            model_name='checklistextractionjob',
            name='excel_s3_key',
            field=models.CharField(blank=True, help_text='S3 object key for generated Excel file', max_length=500),
        ),
        migrations.AddField(
            model_name='checklistextractionjob',
            name='pdf_s3_keys',
            field=models.JSONField(default=list, help_text='List of S3 object keys for uploaded PDFs'),
        ),
        migrations.AddField(
            model_name='checklistextractionjob',
            name='requires_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ChecklistProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_code', models.CharField(editable=False, help_text='Auto-generated unique project code (e.g., ELEC-20260716-A1B2C3D4)', max_length=50, unique=True)),
                ('project_name', models.CharField(help_text='User-defined project name', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Project description and scope')),
                ('location', models.CharField(blank=True, help_text='Site location or facility name', max_length=500)),
                ('client_name', models.CharField(blank=True, help_text='Client or company name', max_length=200)),
                ('status', models.CharField(choices=[('active', 'Active'), ('on_hold', 'On Hold'), ('completed', 'Completed'), ('archived', 'Archived'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('start_date', models.DateField(blank=True, help_text='Project start date', null=True)),
                ('end_date', models.DateField(blank=True, help_text='Project end date', null=True)),
                ('template_id', models.CharField(default='ups_battery_standard', help_text='Project template identifier', max_length=100)),
                ('settings', models.JSONField(default=dict, help_text='\n        Project settings:\n        {\n            "extract_signatures": true,\n            "require_approval": true,\n            "auto_generate_excel": true,\n            "s3_storage": true,\n            "notification_enabled": true\n        }\n        ')),
                ('tags', models.JSONField(default=list, help_text="Project tags for categorization ['UPS', 'Battery', 'Commissioning']")),
                ('s3_folder', models.CharField(editable=False, help_text="S3 folder path for this project's files", max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('total_checklists', models.IntegerField(default=0)),
                ('total_fields_extracted', models.IntegerField(default=0)),
                ('total_signatures_found', models.IntegerField(default=0)),
                ('avg_confidence_score', models.FloatField(default=0.0)),
                ('created_by', models.ForeignKey(help_text='User who created the project', on_delete=django.db.models.deletion.CASCADE, related_name='created_checklist_projects', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(help_text='Project owner', on_delete=django.db.models.deletion.CASCADE, related_name='owned_checklist_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'electrical_checklist_projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='checklistextractionjob',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Parent project for this checklist', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checklist_jobs', to='electrical_checklist.checklistproject'),
        ),
        migrations.AddIndex(
            model_name='checklistextractionjob',
            index=models.Index(fields=['project', '-created_at'], name='electrical__project_34dfce_idx'),
        ),
        migrations.AddIndex(
            model_name='checklistextractionjob',
            index=models.Index(fields=['user', '-created_at'], name='electrical__user_id_dd95d9_idx'),
        ),
        migrations.AddIndex(
            model_name='checklistextractionjob',
            index=models.Index(fields=['status'], name='electrical__status_4cb4c4_idx'),
        ),
        migrations.AddField(
            model_name='checklistprojectmember',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_checklist_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='checklistprojectmember',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_members', to='electrical_checklist.checklistproject'),
        ),
        migrations.AddField(
            model_name='checklistprojectmember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='checklistproject',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='checklist_projects', through='electrical_checklist.ChecklistProjectMember', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='checklistprojectmember',
            unique_together={('project', 'user')},
        ),
        migrations.AddIndex(
            model_name='checklistproject',
            index=models.Index(fields=['project_code'], name='electrical__project_cadb23_idx'),
        ),
        migrations.AddIndex(
            model_name='checklistproject',
            index=models.Index(fields=['owner', '-created_at'], name='electrical__owner_i_653047_idx'),
        ),
        migrations.AddIndex(
            model_name='checklistproject',
            index=models.Index(fields=['status', '-created_at'], name='electrical__status_be8d8b_idx'),
        ),
    ]
