# Generated by Django 5.0 on 2026-09-30 09:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ValveMTOProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_pdf_name', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('extracting', 'Extracting'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='extracting', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valve_mto_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Valve MTO Project',
                'verbose_name_plural': 'Valve MTO Projects',
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ValveMTORow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tag_number', models.CharField(blank=True, default='', max_length=128)),
                ('valve_type', models.CharField(blank=True, default='', max_length=128)),
                ('pms_class', models.CharField(blank=True, default='', max_length=128)),
                ('rating', models.CharField(blank=True, default='', max_length=64)),
                ('size_primary', models.CharField(blank=True, default='', max_length=32)),
                ('size_secondary', models.CharField(blank=True, default='', max_length=32)),
                ('line_number', models.CharField(blank=True, default='', max_length=255)),
                ('line_list_ref', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('qty_island', models.IntegerField(blank=True, null=True)),
                ('qty_field', models.IntegerField(blank=True, null=True)),
                ('qty_combined', models.IntegerField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, default='', max_length=32)),
                ('area', models.CharField(blank=True, default='', max_length=32)),
                ('operational_status', models.CharField(blank=True, default='', max_length=64)),
                ('remarks', models.TextField(blank=True, default='')),
                ('tab', models.CharField(blank=True, default='', max_length=16)),
                ('row_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='valve_mto.valvemtoproject')),
            ],
            options={
                'verbose_name': 'Valve MTO Row',
                'verbose_name_plural': 'Valve MTO Rows',
                'ordering': ['row_order', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='valvemtoproject',
            index=models.Index(fields=['created_by', '-updated_at'], name='valve_mto_v_created_641814_idx'),
        ),
        migrations.AddIndex(
            model_name='valvemtorow',
            index=models.Index(fields=['project', 'tab', 'row_order'], name='valve_mto_v_project_55bea4_idx'),
        ),
    ]
