# Generated by Django 5.0 on 2026-09-30 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valve_mto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='valvemtorow',
            name='size_secondary_2',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
