# Generated by Django 5.0 on 2026-10-01 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valve_mto', '0002_valvemtorow_size_secondary_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='valvemtorow',
            name='facing',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='valvemtorow',
            name='pid_number',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
