# Generated by Django 5.0 on 2026-10-01 17:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valve_mto', '0003_valvemtorow_facing_valvemtorow_pid_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ValveMTOLegend',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('section', models.CharField(choices=[('valve', 'Valve'), ('piping', 'Piping'), ('line_list', 'Line List'), ('instrument_signal', 'Instrument Signal'), ('control_valve_regulator', 'Control Valve Regulator'), ('scope_symbols', 'Scope Symbols'), ('limit_line', 'Limit Line')], max_length=32)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('definition', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valve_mto_legends', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Valve MTO Legend',
                'verbose_name_plural': 'Valve MTO Legends',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['created_by', 'section', '-updated_at'], name='valve_mto_v_created_d1ebde_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='valvemtolegend',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('created_by', 'section'), name='uniq_valve_mto_active_legend_per_user_section'),
        ),
    ]
