# Generated by Django 4.2.16 on 2026-01-15 08:04

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QHSERunningProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr_no', models.IntegerField(unique=True, verbose_name='Serial Number')),
                ('project_no', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Project Number')),
                ('project_title', models.TextField(verbose_name='Project Title')),
                ('project_title_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='Project Title Key')),
                ('client', models.CharField(max_length=255, verbose_name='Client Name')),
                ('project_manager', models.CharField(max_length=255, verbose_name='Project Manager')),
                ('project_quality_eng', models.CharField(max_length=255, verbose_name='Project Quality Engineer')),
                ('project_starting_date', models.DateField(verbose_name='Project Starting Date')),
                ('project_closing_date', models.DateField(verbose_name='Project Closing Date')),
                ('project_extension', models.DateField(blank=True, null=True, verbose_name='Project Extension Date')),
                ('man_hour_for_quality', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Manhours Allocated for Quality')),
                ('manhours_used', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Manhours Used')),
                ('manhours_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Manhours Balance')),
                ('quality_billability_percent', models.CharField(default='0%', max_length=10, verbose_name='Quality Billability Percentage')),
                ('project_quality_plan_status_rev', models.CharField(blank=True, max_length=50, null=True, verbose_name='Quality Plan Status - Revision')),
                ('project_quality_plan_status_issue_date', models.DateField(blank=True, null=True, verbose_name='Quality Plan Issue Date')),
                ('project_audit_1', models.DateField(blank=True, null=True, verbose_name='Project Audit 1')),
                ('project_audit_2', models.DateField(blank=True, null=True, verbose_name='Project Audit 2')),
                ('project_audit_3', models.DateField(blank=True, null=True, verbose_name='Project Audit 3')),
                ('project_audit_4', models.DateField(blank=True, null=True, verbose_name='Project Audit 4')),
                ('client_audit_1', models.DateField(blank=True, null=True, verbose_name='Client Audit 1')),
                ('client_audit_2', models.DateField(blank=True, null=True, verbose_name='Client Audit 2')),
                ('delay_in_audits_no_days', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Delay in Audits (Days)')),
                ('cars_open', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='CARs Open')),
                ('cars_delayed_closing_no_days', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='CARs Delayed Closing (Days)')),
                ('cars_closed', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='CARs Closed')),
                ('obs_open', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Observations Open')),
                ('obs_delayed_closing_no_days', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Observations Delayed Closing (Days)')),
                ('obs_closed', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Observations Closed')),
                ('project_kpis_achieved_percent', models.CharField(default='0%', max_length=10, verbose_name='Project KPIs Achieved (%)')),
                ('project_completion_percent', models.CharField(default='0%', max_length=10, verbose_name='Project Completion (%)')),
                ('rejection_of_deliverables_percent', models.CharField(blank=True, max_length=10, null=True, verbose_name='Rejection of Deliverables (%)')),
                ('cost_of_poor_quality_aed', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cost of Poor Quality (AED)')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qhse_projects_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qhse_projects_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'QHSE Running Project',
                'verbose_name_plural': 'QHSE Running Projects',
                'db_table': 'qhse_running_projects',
                'ordering': ['sr_no'],
            },
        ),
        migrations.CreateModel(
            name='QHSEAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audit_type', models.CharField(choices=[('PROJECT', 'Project Audit'), ('CLIENT', 'Client Audit'), ('INTERNAL', 'Internal Audit'), ('EXTERNAL', 'External Audit')], max_length=50, verbose_name='Audit Type')),
                ('audit_number', models.IntegerField(verbose_name='Audit Number')),
                ('audit_date', models.DateField(verbose_name='Audit Date')),
                ('auditor', models.CharField(max_length=255, verbose_name='Auditor')),
                ('findings', models.TextField(blank=True, null=True, verbose_name='Findings')),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Completed'), ('DELAYED', 'Delayed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=50, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='qhse.qhserunningproject', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'QHSE Audit',
                'verbose_name_plural': 'QHSE Audits',
                'db_table': 'qhse_audits',
                'ordering': ['-audit_date'],
            },
        ),
        migrations.CreateModel(
            name='QHSESpotCheckRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr_no', models.IntegerField(db_index=True, verbose_name='Serial Number')),
                ('project_no', models.CharField(db_index=True, max_length=50, verbose_name='Project Number')),
                ('project_title', models.TextField(verbose_name='Project Title')),
                ('client', models.CharField(max_length=255, verbose_name='Client Name')),
                ('qhse_engineer', models.CharField(max_length=255, verbose_name='QHSE Engineer')),
                ('date_of_spot_check', models.DateField(verbose_name='Date of Spot Check')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='Time')),
                ('document_no', models.CharField(blank=True, max_length=255, null=True, verbose_name='Document Number')),
                ('document_title', models.TextField(blank=True, null=True, verbose_name='Document Title')),
                ('originator_lead', models.CharField(blank=True, max_length=255, null=True, verbose_name='Originator/Lead')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Comments')),
                ('category', models.CharField(blank=True, choices=[('OBSERVATION', 'Observation'), ('CAR', 'Corrective Action Request'), ('NCR', 'Non-Conformance Report'), ('COMPLIANT', 'Compliant'), ('MINOR', 'Minor Issue'), ('MAJOR', 'Major Issue')], max_length=50, null=True, verbose_name='Category')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='OPEN', max_length=50, verbose_name='Status')),
                ('resolution_date', models.DateField(blank=True, null=True, verbose_name='Resolution Date')),
                ('resolution_comments', models.TextField(blank=True, null=True, verbose_name='Resolution Comments')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qhse_spot_checks_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qhse_spot_checks_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'QHSE Spot Check',
                'verbose_name_plural': 'QHSE Spot Check Register',
                'db_table': 'qhse_spot_check_register',
                'ordering': ['-date_of_spot_check', 'sr_no'],
                'indexes': [models.Index(fields=['project_no'], name='qhse_spot_c_project_3d1744_idx'), models.Index(fields=['date_of_spot_check'], name='qhse_spot_c_date_of_ba8ad0_idx'), models.Index(fields=['qhse_engineer'], name='qhse_spot_c_qhse_en_8c765f_idx'), models.Index(fields=['category'], name='qhse_spot_c_categor_56addc_idx'), models.Index(fields=['status'], name='qhse_spot_c_status_480c55_idx'), models.Index(fields=['is_active'], name='qhse_spot_c_is_acti_18b9b7_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='qhserunningproject',
            index=models.Index(fields=['project_no'], name='qhse_runnin_project_edd39f_idx'),
        ),
        migrations.AddIndex(
            model_name='qhserunningproject',
            index=models.Index(fields=['client'], name='qhse_runnin_client_71c79f_idx'),
        ),
        migrations.AddIndex(
            model_name='qhserunningproject',
            index=models.Index(fields=['project_manager'], name='qhse_runnin_project_93cb87_idx'),
        ),
        migrations.AddIndex(
            model_name='qhserunningproject',
            index=models.Index(fields=['is_active'], name='qhse_runnin_is_acti_fa5569_idx'),
        ),
        migrations.AddIndex(
            model_name='qhserunningproject',
            index=models.Index(fields=['-updated_at'], name='qhse_runnin_updated_d97513_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='qhseaudit',
            unique_together={('project', 'audit_type', 'audit_number')},
        ),
    ]
