# Generated by Django 5.0 on 2026-01-15 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qhse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qhserunningproject',
            name='project_closing_date',
            field=models.DateField(blank=True, null=True, verbose_name='Project Closing Date'),
        ),
        migrations.AlterField(
            model_name='qhserunningproject',
            name='project_starting_date',
            field=models.DateField(blank=True, null=True, verbose_name='Project Starting Date'),
        ),
    ]
