# Generated by Django 5.0 on 2026-02-10 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qhse', '0002_alter_qhserunningproject_project_closing_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qhserunningproject',
            name='project_quality_eng',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Project Quality Engineer'),
        ),
    ]
