# Generated by Django 4.2.16 on 2026-01-14 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0003_userprofile_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='must_change_password',
            field=models.BooleanField(default=False, help_text='User must change password on next login'),
        ),
    ]
