# Generated by Django 4.2.16 on 2026-07-14 07:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0033_seed_ict_admin_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(help_text='Company or organization name', max_length=200)),
                ('company_logo_url', models.URLField(blank=True, help_text='URL to company logo', max_length=500)),
                ('job_title', models.CharField(help_text='Job title or position held', max_length=200)),
                ('employment_type', models.CharField(blank=True, help_text='Employment type from profile_config.EMPLOYMENT_TYPES (full_time, contract, etc.)', max_length=50)),
                ('industry', models.CharField(blank=True, help_text='Industry sector', max_length=200)),
                ('location', models.CharField(blank=True, help_text='Work location (city, country)', max_length=200)),
                ('start_date', models.DateField(help_text='Employment start date')),
                ('end_date', models.DateField(blank=True, help_text='Employment end date (null = current)', null=True)),
                ('is_current', models.BooleanField(default=False, help_text='Currently working here')),
                ('description', models.TextField(blank=True, help_text='Role description and responsibilities')),
                ('achievements_text', models.TextField(blank=True, help_text='Key achievements and accomplishments in this role')),
                ('skills_used', models.JSONField(blank=True, default=list, help_text='List of technical skills/tools used in this role')),
                ('is_public', models.BooleanField(default=True, help_text='Show on public profile')),
                ('display_order', models.IntegerField(default=0, help_text='Order for displaying experience')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experience', to='rbac.userprofile')),
            ],
            options={
                'verbose_name': 'Work Experience',
                'verbose_name_plural': 'Work Experience Entries',
                'db_table': 'rbac_work_experience',
                'ordering': ['-is_current', '-start_date'],
                'indexes': [models.Index(fields=['user_profile', '-start_date'], name='rbac_work_e_user_pr_6ba744_idx'), models.Index(fields=['user_profile', 'is_current'], name='rbac_work_e_user_pr_9dcfdb_idx'), models.Index(fields=['industry'], name='rbac_work_e_industr_76f4ae_idx')],
            },
        ),
        migrations.CreateModel(
            name='SocialMediaLink',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(help_text='Platform code from profile_config.SOCIAL_MEDIA_PLATFORMS (linkedin, github, twitter, etc.)', max_length=50)),
                ('url', models.URLField(help_text="Full URL to the user's profile on this platform", max_length=500)),
                ('username', models.CharField(blank=True, help_text='Username or handle on the platform', max_length=200)),
                ('is_verified', models.BooleanField(default=False, help_text='Link has been verified')),
                ('is_public', models.BooleanField(default=True, help_text='Show on public profile')),
                ('display_order', models.IntegerField(default=0, help_text='Order for displaying social links')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='rbac.userprofile')),
            ],
            options={
                'verbose_name': 'Social Media Link',
                'verbose_name_plural': 'Social Media Links',
                'db_table': 'rbac_social_media_links',
                'ordering': ['display_order', 'platform'],
                'indexes': [models.Index(fields=['user_profile', 'is_public'], name='rbac_social_user_pr_879009_idx'), models.Index(fields=['platform'], name='rbac_social_platfor_7c3660_idx')],
                'unique_together': {('user_profile', 'platform')},
            },
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Achievement title or award name', max_length=200)),
                ('category', models.CharField(help_text='Category code from profile_config.ACHIEVEMENT_CATEGORIES (sports, academic, professional, etc.)', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the achievement')),
                ('level', models.CharField(blank=True, help_text='Achievement level/tier', max_length=20)),
                ('achieved_date', models.DateField(blank=True, help_text='Date when achievement was earned', null=True)),
                ('location', models.CharField(blank=True, help_text='Location or event where achieved', max_length=200)),
                ('organization', models.CharField(blank=True, help_text='Issuing organization or institution', max_length=200)),
                ('certificate_url', models.URLField(blank=True, help_text='Link to certificate or evidence', max_length=500)),
                ('media_url', models.URLField(blank=True, help_text='Link to photo/video evidence', max_length=500)),
                ('is_public', models.BooleanField(default=True, help_text='Show on public profile')),
                ('is_verified', models.BooleanField(default=False, help_text='Verified by admin/system')),
                ('display_order', models.IntegerField(default=0, help_text='Order for displaying achievements')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='rbac.userprofile')),
            ],
            options={
                'verbose_name': 'User Achievement',
                'verbose_name_plural': 'User Achievements',
                'db_table': 'rbac_user_achievements',
                'ordering': ['-achieved_date', '-created_at'],
                'indexes': [models.Index(fields=['user_profile', 'category'], name='rbac_user_a_user_pr_e7152a_idx'), models.Index(fields=['user_profile', 'is_public'], name='rbac_user_a_user_pr_64dcb5_idx'), models.Index(fields=['category', '-achieved_date'], name='rbac_user_a_categor_cda1cf_idx')],
            },
        ),
    ]
