# Generated by Django 5.0 on 2026-07-14 08:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0034_enhanced_profile_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileDocument',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(help_text='Document type code from profile_config.DOCUMENT_TYPES (emirates_id, driving_license, country_id, passport, visa)', max_length=50)),
                ('document_file', models.FileField(help_text='Uploaded document file (stored in S3)', max_length=500, upload_to='profile_documents/')),
                ('document_number', models.CharField(blank=True, help_text='ID/License/Passport number', max_length=100)),
                ('issue_date', models.DateField(blank=True, help_text='Date of issue', null=True)),
                ('expiry_date', models.DateField(blank=True, help_text='Expiry date', null=True)),
                ('issuing_authority', models.CharField(blank=True, help_text='Issuing authority/country', max_length=200)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending Review'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', help_text='Document verification status', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, help_text='Verification timestamp', null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason if rejected')),
                ('notes', models.TextField(blank=True, help_text='Additional notes or comments')),
                ('is_active', models.BooleanField(default=True, help_text='Document is active (not replaced)')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='rbac.userprofile')),
                ('verified_by', models.ForeignKey(blank=True, help_text='Admin who verified this document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_documents_verified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile Document',
                'verbose_name_plural': 'Profile Documents',
                'db_table': 'rbac_profile_documents',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_profile', 'document_type', 'is_active'], name='rbac_profil_user_pr_704c87_idx'), models.Index(fields=['verification_status'], name='rbac_profil_verific_4f0b69_idx'), models.Index(fields=['expiry_date'], name='rbac_profil_expiry__f156ff_idx')],
            },
        ),
    ]
