# Generated by Django 5.0 on 2026-07-22 - Add Human Resource Role
# SOFT-CODED: Creates "Human Resource" role with all HR module access

from django.db import migrations


def create_human_resource_role(apps, schema_editor):
    """
    Create the Human Resource role with all HR modules
    """
    Role = apps.get_model('rbac', 'Role')
    Module = apps.get_model('rbac', 'Module')
    
    # SOFT-CODED configuration
    ROLE_CONFIG = {
        'code': 'human_resource',
        'name': 'Human Resource',
        'level': 3,
        'description': 'Complete access to all Human Resource features including HR Management, Payroll, Timesheet, Onboarding/Offboarding, and Employee Self-Service.',
        'is_active': True,
        'is_system_role': True,
    }
    
    HR_MODULE_CODES = [
        'hr_management',      # 4.1 Human Resources Dashboard
        'payroll',            # 4.2 Payroll Engine
        'timesheet',          # 4.3 Timesheet & Attendance
        'hr_self_service',    # 4.4 My Profile (Employee Self-Service)
        'hr_onboarding',      # 4.5 Onboarding | Offboarding
    ]
    
    print("\n" + "="*80)
    print("  CREATING HUMAN RESOURCE ROLE")
    print("="*80)
    
    # Create or update the role
    role, created = Role.objects.get_or_create(
        code=ROLE_CONFIG['code'],
        defaults=ROLE_CONFIG
    )
    
    if created:
        print(f"✓ Created new role: {role.name} (code: {role.code})")
    else:
        # Update existing role
        for key, value in ROLE_CONFIG.items():
            setattr(role, key, value)
        role.save()
        print(f"✓ Updated existing role: {role.name} (code: {role.code})")
    
    # Assign all HR modules to this role
    print(f"\n→ Assigning {len(HR_MODULE_CODES)} HR modules:")
    
    assigned_count = 0
    missing_modules = []
    
    for module_code in HR_MODULE_CODES:
        try:
            module = Module.objects.get(code=module_code)
            
            # Add module to role (M2M relationship)
            if not role.modules.filter(id=module.id).exists():
                role.modules.add(module)
                print(f"  ✓ {module.name} (code: {module_code})")
                assigned_count += 1
            else:
                print(f"  ✓ {module.name} (already assigned)")
                
        except Module.DoesNotExist:
            print(f"  ✗ Module '{module_code}' not found in database")
            missing_modules.append(module_code)
    
    print(f"\n✓ Assigned {assigned_count} modules to {role.name}")
    
    if missing_modules:
        print(f"\n⚠ Warning: {len(missing_modules)} module(s) not found:")
        for code in missing_modules:
            print(f"  - {code}")
        print("  These modules may need to be created separately.")
    
    print("\n" + "="*80)
    print("  ✓ HUMAN RESOURCE ROLE CREATED SUCCESSFULLY")
    print("="*80)
    print("\n📌 Next Steps:")
    print("  1. Go to /admin/roles page")
    print("  2. Find 'Human Resource' role in the list")
    print("  3. Click 'Assign' to give this role to any user")
    print("  4. User will have access to ALL HR features (4.1 - 4.5)")
    print("="*80 + "\n")


def reverse_migration(apps, schema_editor):
    """
    Reverse operation: Remove the Human Resource role
    """
    Role = apps.get_model('rbac', 'Role')
    
    print("\n" + "="*80)
    print("  REMOVING HUMAN RESOURCE ROLE")
    print("="*80 + "\n")
    
    try:
        role = Role.objects.get(code='human_resource')
        role_name = role.name
        
        # Clear module assignments
        role.modules.clear()
        
        # Delete the role
        role.delete()
        
        print(f"✓ Removed role: {role_name} (code: human_resource)")
        print("\n" + "="*80 + "\n")
        
    except Role.DoesNotExist:
        print("✓ Human Resource role does not exist (nothing to remove)")
        print("\n" + "="*80 + "\n")


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0035_profile_documents'),  # Latest migration
    ]

    operations = [
        migrations.RunPython(create_human_resource_role, reverse_migration),
    ]
