# Generated by Django 5.0 on 2026-08-05 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0037_seed_planning_package_module'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
        migrations.RenameIndex(
            model_name='activityevent',
            new_name='activity_ev_user_id_f3fd17_idx',
            old_name='activity_user_ts_idx',
        ),
        migrations.RenameIndex(
            model_name='activityevent',
            new_name='activity_ev_applica_be833b_idx',
            old_name='activity_app_ts_idx',
        ),
        migrations.RenameIndex(
            model_name='activityevent',
            new_name='activity_ev_feature_849538_idx',
            old_name='activity_feat_ts_idx',
        ),
        migrations.RenameIndex(
            model_name='aipricingconfig',
            new_name='ai_pricing__provide_ed408d_idx',
            old_name='ai_pricing_provider_idx',
        ),
        migrations.RenameIndex(
            model_name='aiusagelog',
            new_name='ai_usage_lo_user_id_48fed7_idx',
            old_name='ai_usage_user_ts_idx',
        ),
        migrations.RenameIndex(
            model_name='aiusagelog',
            new_name='ai_usage_lo_provide_32aae3_idx',
            old_name='ai_usage_prov_ts_idx',
        ),
        migrations.RenameIndex(
            model_name='aiusagelog',
            new_name='ai_usage_lo_applica_3a99b4_idx',
            old_name='ai_usage_app_ts_idx',
        ),
        migrations.RenameIndex(
            model_name='aiusagelog',
            new_name='ai_usage_lo_timesta_abde11_idx',
            old_name='ai_usage_ts_success_idx',
        ),
        migrations.RenameIndex(
            model_name='engineerprofile',
            new_name='rbac_engine_experti_dfb74c_idx',
            old_name='rbac_ep_expertise_idx',
        ),
        migrations.RenameIndex(
            model_name='engineerprofile',
            new_name='rbac_engine_availab_84cf7e_idx',
            old_name='rbac_ep_avail_idx',
        ),
        migrations.RenameIndex(
            model_name='monthlychampion',
            new_name='monthly_cha_period__237888_idx',
            old_name='champion_period_idx',
        ),
        migrations.RenameIndex(
            model_name='monthlychampion',
            new_name='monthly_cha_user_id_769211_idx',
            old_name='champion_user_period_idx',
        ),
            ],
        ),
    ]
