# Generated by Django 5.0 on 2026-09-04 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_core', '0007_alter_employeemaster_email_alter_employeemaster_user'),
        ('rbac', '0048_grant_default_enquiry_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='canonical_employee',
            field=models.OneToOneField(blank=True, help_text='Canonical employee identity. Null for non-employee/external accounts.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rbac_access_profile', to='hr_core.employeemaster'),
        ),
    ]
