# Generated by Django 5.0 on 2026-09-11 13:04

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0059_monthly_champion_publication'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIOutcomeEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reviewed_at', models.DateTimeField(null=True)),
                ('title', models.CharField(max_length=200)),
                ('task_reference', models.CharField(max_length=200)),
                ('evidence_url', models.URLField(max_length=1000)),
                ('comparison', models.TextField()),
                ('baseline_minutes', models.PositiveIntegerField()),
                ('ai_minutes', models.PositiveIntegerField()),
                ('review_minutes', models.PositiveIntegerField()),
                ('rework_minutes', models.PositiveIntegerField()),
                ('measurement', models.CharField(choices=[('measured', 'Measured'), ('self_reported', 'Self-reported')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('review_reason', models.TextField(blank=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rbac.module')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rbac.organization')),
                ('reviewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ai_outcomes_reviewed', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ai_outcomes_submitted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='aioutcomeevidence',
            constraint=models.UniqueConstraint(fields=('organization', 'module', 'task_reference'), name='unique_ai_outcome_task'),
        ),
    ]
