# Generated by Django 5.0 on 2026-09-11 13:15

import django.db.models.deletion
import django.utils.timezone
import uuid
from importlib import import_module
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0060_ai_outcome_evidence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(
            import_module('apps.rbac.migrations.0060_ai_outcome_evidence').ensure_ai_reference_keys,
            migrations.RunPython.noop,
        ),
        migrations.CreateModel(
            name='AIWorkforceSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('captured_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('capture_date', models.DateField()),
                ('policy_version', models.CharField(default='eligible-linked-active-v1', max_length=40)),
                ('people', models.JSONField(default=dict)),
                ('quality', models.JSONField(default=dict)),
            ],
        ),
        migrations.AddField(
            model_name='aioutcomeevidence',
            name='contribution_type',
            field=models.CharField(choices=[('task', 'Task'), ('workflow_integration', 'Workflow integration'), ('automation_creator', 'Automation creator')], default='task', max_length=32),
        ),
        migrations.AddField(
            model_name='aioutcomeevidence',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='aioutcomeevidence',
            name='value_currency',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='aiusagelog',
            name='pricing_recorded',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='aiusagelog',
            name='provenance',
            field=models.CharField(db_index=True, default='legacy', max_length=16),
        ),
        migrations.CreateModel(
            name='AIWorkflowRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('module', models.CharField(max_length=64)),
                ('operation', models.CharField(max_length=64)),
                ('deduplication_key', models.CharField(max_length=64)),
                ('session_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('started_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(null=True)),
                ('status', models.CharField(default='running', max_length=16)),
                ('source_type', models.CharField(blank=True, max_length=64)),
                ('source_id', models.CharField(blank=True, max_length=100)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('instrumentation_version', models.CharField(default='pilot-workflow-v1', max_length=32)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rbac.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at', 'id'],
            },
        ),
        migrations.AddField(
            model_name='aioutcomeevidence',
            name='workflow',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outcome', to='rbac.aiworkflowrun'),
        ),
        migrations.AddField(
            model_name='aiusagelog',
            name='workflow',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='rbac.aiworkflowrun'),
        ),
        migrations.AddConstraint(
            model_name='aiusagelog',
            constraint=models.UniqueConstraint(condition=models.Q(('provenance', 'server'), models.Q(('request_id', ''), _negated=True)), fields=('workflow', 'provider', 'request_id'), name='unique_ai_server_workflow_request'),
        ),
        migrations.AddField(
            model_name='aiworkforcesnapshot',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rbac.organization'),
        ),
        migrations.AddIndex(
            model_name='aiworkflowrun',
            index=models.Index(fields=['organization', 'module', 'started_at'], name='rbac_aiwork_organiz_37cc27_idx'),
        ),
        migrations.AddConstraint(
            model_name='aiworkflowrun',
            constraint=models.UniqueConstraint(fields=('user', 'module', 'operation', 'deduplication_key'), name='unique_ai_workflow_submission'),
        ),
        migrations.AddIndex(
            model_name='aiworkforcesnapshot',
            index=models.Index(fields=['organization', 'captured_at'], name='rbac_aiwork_organiz_89f1d7_idx'),
        ),
        migrations.AddConstraint(
            model_name='aiworkforcesnapshot',
            constraint=models.UniqueConstraint(fields=('organization', 'capture_date'), name='unique_ai_workforce_snapshot_day'),
        ),
    ]
