# Generated by Django 5.0 on 2026-07-01 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usage_tracking', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='usagelog',
            new_name='usage_log_timesta_74eff2_idx',
            old_name='usage_log_ts_disc_idx',
        ),
        migrations.RenameIndex(
            model_name='usagelog',
            new_name='usage_log_user_em_75b9a8_idx',
            old_name='usage_log_email_ts_idx',
        ),
    ]
