# Generated by Django 4.2.16 on 2026-07-10 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usage_tracking', '0002_rename_usage_log_ts_disc_idx_usage_log_timesta_74eff2_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='usagelog',
            new_name='usage_log_timesta_74eff2_idx',
            old_name='usage_log_ts_disc_idx',
        ),
        migrations.RenameIndex(
            model_name='usagelog',
            new_name='usage_log_user_em_75b9a8_idx',
            old_name='usage_log_email_ts_idx',
        ),
    ]
