# Generated by Django 4.2.30 on 2026-07-25 08:53

import apps.pid_verification_v2.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PIDVDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('file_name', models.CharField(max_length=512)),
                ('s3_path', models.CharField(blank=True, max_length=1024)),
                ('file_hash', models.CharField(db_index=True, help_text='SHA-256 of the raw file – enables deterministic caching', max_length=64)),
                ('original_file', models.FileField(blank=True, max_length=500, null=True, upload_to=apps.pid_verification_v2.models._pid_upload_path)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('legend_pending', 'Waiting for Legend')], default='uploaded', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('excel_s3_url', models.CharField(blank=True, max_length=1024)),
                ('pdf_s3_url', models.CharField(blank=True, max_length=1024)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'pidv2_documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PIDVDrawing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drawing_id', models.CharField(db_index=True, max_length=100)),
                ('title', models.CharField(blank=True, max_length=512)),
                ('page_index', models.PositiveSmallIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drawings', to='pid_verification_v2.pidvdocument')),
            ],
            options={
                'db_table': 'pidv2_drawings',
                'ordering': ['page_index'],
            },
        ),
        migrations.CreateModel(
            name='PIDVProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('project_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('legend_knowledge_data', models.JSONField(blank=True, help_text='Extracted legend prefixes specific to this project.', null=True)),
                ('legend_built_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pidv2_v_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pidv2_projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PIDVLegendSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legend_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('file_name', models.CharField(max_length=512)),
                ('original_file', models.FileField(blank=True, max_length=500, null=True, upload_to=apps.pid_verification_v2.models._legend_upload_path)),
                ('s3_path', models.CharField(blank=True, max_length=1024)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('extracted_data', models.JSONField(blank=True, help_text='Structured legend data extracted by AI (see docstring for schema)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='legend_sheets', to='pid_verification_v2.pidvproject')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pidv2_legend_sheets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pidv2_legend_sheets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PIDVInstrumentSymbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('symbol_code', models.CharField(db_index=True, help_text='e.g. HV, FIC, E-100, ZV', max_length=100)),
                ('description', models.TextField(help_text='Human-readable description from legend sheet')),
                ('category', models.CharField(choices=[('control_valve', 'Control Valves'), ('manual_valve', 'Manual Valves'), ('instrument', 'Instruments'), ('instrument_tagging', 'Instrument Tagging'), ('equipment_numbering', 'Equipment Numbering'), ('inline_equipment', 'In-Line Equipment')], db_index=True, max_length=30)),
                ('symbol_type', models.CharField(blank=True, help_text='e.g. ball_valve, diff_pressure_transmitter', max_length=100)),
                ('drawing_standard', models.CharField(blank=True, default='ISA 5.1', help_text='e.g. ISA 5.1, IEC 62424', max_length=100)),
                ('attributes', models.JSONField(blank=True, default=dict, help_text='Flexible per-category attributes (see docstring for schema)')),
                ('source', models.CharField(choices=[('ai_extraction', 'AI Extraction'), ('text_parse', 'Text Parse'), ('manual', 'Manual Entry')], default='ai_extraction', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('legend_sheet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instrument_symbols', to='pid_verification_v2.pidvlegendsheet')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instrument_symbols', to='pid_verification_v2.pidvproject')),
            ],
            options={
                'db_table': 'pidv2_instrument_symbols',
                'ordering': ['category', 'symbol_code'],
            },
        ),
        migrations.CreateModel(
            name='PIDVFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sl_no', models.PositiveIntegerField(help_text='Sequential number within the drawing')),
                ('category', models.CharField(choices=[('tag', 'Tag Issues'), ('connectivity', 'Connectivity Issues'), ('valve', 'Valve & Equipment'), ('line_size', 'Line Size'), ('notes', 'Notes & HOLDs')], max_length=20)),
                ('issue_observed', models.TextField()),
                ('action_required', models.TextField()),
                ('evidence', models.TextField(blank=True, help_text='Raw OCR text / location hint')),
                ('direction', models.CharField(blank=True, help_text='Horizontal / Vertical / N/A', max_length=100)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('major', 'Major'), ('minor', 'Minor'), ('info', 'Info')], default='major', max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('reviewed', 'Reviewed'), ('resolved', 'Resolved')], default='open', max_length=10)),
                ('rule_id', models.CharField(blank=True, help_text='Rule that triggered this finding', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('drawing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='pid_verification_v2.pidvdrawing')),
            ],
            options={
                'db_table': 'pidv2_findings',
                'ordering': ['drawing', 'sl_no'],
            },
        ),
        migrations.AddField(
            model_name='pidvdocument',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='pid_verification_v2.pidvproject'),
        ),
        migrations.AddField(
            model_name='pidvdocument',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pidv2_v_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PIDVAICheckRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('extracting', 'Extracting P&ID Elements'), ('checking', 'Running Checks'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('analysis_mode', models.CharField(default='hybrid', max_length=30)),
                ('extracted_data', models.JSONField(blank=True, help_text='All extracted P&ID elements from vision APIs', null=True)),
                ('check_results', models.JSONField(blank=True, default=list, help_text='Results of all executed checks')),
                ('summary_stats', models.JSONField(blank=True, default=dict, help_text='Summary statistics of check run')),
                ('processing_metadata', models.JSONField(blank=True, default=dict, help_text='Processing metrics and costs')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_check_runs', to='pid_verification_v2.pidvproject')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pidv2_ai_check_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pidv2_ai_check_runs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PIDVReferenceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('data_type', models.CharField(choices=[('line_list', 'Line List'), ('equipment_list', 'Equipment List'), ('instrument_index', 'Instrument Index')], db_index=True, max_length=30)),
                ('file_name', models.CharField(max_length=512)),
                ('original_file', models.FileField(blank=True, max_length=500, null=True, upload_to=apps.pid_verification_v2.models._reference_data_upload_path)),
                ('s3_path', models.CharField(blank=True, max_length=1024)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('parsed_data', models.JSONField(blank=True, help_text='Parsed tabular data from Excel/CSV files', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='File metadata: row_count, columns, file_size_bytes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_data', to='pid_verification_v2.pidvproject')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pidv2_reference_data', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pidv2_reference_data',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['reference_id'], name='pidv2_refer_referen_f39889_idx'), models.Index(fields=['project', 'data_type'], name='pidv2_refer_project_dbfd26_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='pidvproject',
            index=models.Index(fields=['project_id'], name='pidv2_proje_project_18f108_idx'),
        ),
        migrations.AddIndex(
            model_name='pidvlegendsheet',
            index=models.Index(fields=['legend_id'], name='pidv2_legen_legend__b63bc1_idx'),
        ),
        migrations.AddIndex(
            model_name='pidvlegendsheet',
            index=models.Index(fields=['project', 'status'], name='pidv2_legen_project_4991ad_idx'),
        ),
        migrations.AddIndex(
            model_name='pidvinstrumentsymbol',
            index=models.Index(fields=['project', 'category'], name='pidv2_instr_project_8b0c45_idx'),
        ),
        migrations.AddIndex(
            model_name='pidvinstrumentsymbol',
            index=models.Index(fields=['symbol_id'], name='pidv2_instr_symbol__b5212a_idx'),
        ),
        migrations.AddIndex(
            model_name='pidvinstrumentsymbol',
            index=models.Index(fields=['symbol_code'], name='pidv2_instr_symbol__8b377e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pidvinstrumentsymbol',
            unique_together={('project', 'symbol_code', 'category')},
        ),
        migrations.AddIndex(
            model_name='pidvfinding',
            index=models.Index(fields=['drawing', 'sl_no'], name='pidv2_findi_drawing_7be665_idx'),
        ),
        migrations.AddIndex(
            model_name='pidvfinding',
            index=models.Index(fields=['severity'], name='pidv2_findi_severit_70e7e1_idx'),
        ),
        migrations.AddIndex(
            model_name='pidvfinding',
            index=models.Index(fields=['category'], name='pidv2_findi_categor_aeb4d3_idx'),
        ),
        migrations.AddIndex(
            model_name='pidvdrawing',
            index=models.Index(fields=['document', 'drawing_id'], name='pidv2_drawi_documen_920de7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pidvdrawing',
            unique_together={('document', 'drawing_id')},
        ),
        migrations.AddIndex(
            model_name='pidvdocument',
            index=models.Index(fields=['document_id'], name='pidv2_docum_documen_d5c4e1_idx'),
        ),
        migrations.AddIndex(
            model_name='pidvdocument',
            index=models.Index(fields=['file_hash'], name='pidv2_docum_file_ha_83bf7b_idx'),
        ),
        migrations.AddIndex(
            model_name='pidvdocument',
            index=models.Index(fields=['status'], name='pidv2_docum_status_f861f7_idx'),
        ),
        migrations.AddIndex(
            model_name='pidvdocument',
            index=models.Index(fields=['uploaded_by', '-created_at'], name='pidv2_docum_uploade_d17492_idx'),
        ),
        migrations.AddIndex(
            model_name='pidvaicheckrun',
            index=models.Index(fields=['run_id'], name='pidv2_ai_ch_run_id_d99723_idx'),
        ),
        migrations.AddIndex(
            model_name='pidvaicheckrun',
            index=models.Index(fields=['project', 'status'], name='pidv2_ai_ch_project_c707b8_idx'),
        ),
    ]
