# Generated by Django 5.0 on 2026-07-25 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pid_verification_v2', '0001_initial'),
    ]

    operations = [
    ]
