# Generated by Django 5.0 on 2026-07-25 17:33

import apps.pid_verification_v2.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pid_verification_v2', '0002_sync_with_existing_db'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PIDVComparisonFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finding_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('finding_type', models.CharField(choices=[('tag_consistency', 'Tag Consistency'), ('line_consistency', 'Line Number Consistency'), ('symbol_legend_match', 'Symbol-Legend Match'), ('spec_material_match', 'Spec/Material Match'), ('duplicate_tag', 'Duplicate Tag'), ('missing_item', 'Missing Item'), ('format_error', 'Format Error'), ('data_quality', 'Data Quality Issue')], db_index=True, max_length=30)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], db_index=True, default='medium', max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(help_text='Detailed description of the finding')),
                ('evidence', models.JSONField(blank=True, default=dict, help_text='Supporting data: { file1: {...}, file2: {...}, comparison_data: {...} }')),
                ('ai_suggestion', models.TextField(blank=True, help_text='AI-generated correction or recommendation')),
                ('ai_confidence', models.DecimalField(decimal_places=2, default=0.0, help_text='AI confidence score (0-100)', max_digits=5)),
                ('location_info', models.JSONField(blank=True, default=dict, help_text='Where the issue was found: { file: str, page: int, bbox: [...], item: str }')),
                ('status', models.CharField(choices=[('open', 'Open'), ('reviewed', 'Reviewed'), ('resolved', 'Resolved'), ('ignored', 'Ignored')], db_index=True, default='open', max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'pidv2_comparison_findings',
                'ordering': ['-severity', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PIDVExtractionPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('page_number', models.PositiveSmallIntegerField()),
                ('layer1_data', models.JSONField(blank=True, default=dict, help_text='Layer 1 OCR results: { engine: str, text: str, confidence: float, items: [...] }')),
                ('layer2_data', models.JSONField(blank=True, default=dict, help_text='Layer 2 ML OCR fallback results (if triggered)')),
                ('layer3_data', models.JSONField(blank=True, default=dict, help_text='Layer 3 Vision AI results (if used)')),
                ('extracted_items', models.JSONField(blank=True, default=dict, help_text='Merged results: { equipment_tags: [...], line_numbers: [...], symbols: [...], notes: [...] }')),
                ('avg_confidence', models.DecimalField(decimal_places=2, default=0.0, help_text='Average OCR confidence for this page (0-100)', max_digits=5)),
                ('items_found', models.PositiveSmallIntegerField(default=0, help_text='Total items extracted on this page')),
                ('annotated_image', models.FileField(blank=True, help_text='Processed image with bounding boxes drawn', max_length=500, null=True, upload_to=apps.pid_verification_v2.models._extraction_result_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'pidv2_extraction_pages',
                'ordering': ['extraction_result', 'page_number'],
            },
        ),
        migrations.CreateModel(
            name='PIDVExtractionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extraction_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('file_type', models.CharField(help_text='pid_drawing, legend_sheet, equipment_list, line_list, pms', max_length=50)),
                ('file_name', models.CharField(max_length=512)),
                ('page_count', models.PositiveSmallIntegerField(default=1)),
                ('extraction_mode', models.CharField(choices=[('fast', 'Fast (OCR-only)'), ('balanced', 'Balanced (Smart Vision Fallback)'), ('deep', 'Deep (Full Vision Analysis)'), ('vision_only', 'Vision-Only (No OCR)')], default='balanced', max_length=20)),
                ('user_api_key_used', models.BooleanField(default=False, help_text='True if user provided BYOK API key for Layer 3')),
                ('vision_provider', models.CharField(blank=True, help_text='openai, claude, gemini', max_length=20)),
                ('extraction_data', models.JSONField(blank=True, default=dict, help_text='Complete extraction results (see docstring for schema)')),
                ('json_export_file', models.FileField(blank=True, max_length=500, null=True, upload_to=apps.pid_verification_v2.models._extraction_result_upload_path)),
                ('json_s3_url', models.CharField(blank=True, max_length=1024)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('layer1', 'Layer 1: OCR Processing'), ('layer2', 'Layer 2: ML OCR Fallback'), ('layer3', 'Layer 3: Vision AI Enhancement'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('total_cost_usd', models.DecimalField(decimal_places=4, default=0.0, help_text='Total cost of extraction (Layer 3 Vision AI only)', max_digits=10)),
                ('processing_time_seconds', models.DecimalField(decimal_places=2, default=0.0, help_text='Total processing time', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pidv2_extraction_results',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='pidvproject',
            name='pidv2_proje_project_18f108_idx',
        ),
        migrations.AddField(
            model_name='pidvcomparisonfinding',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparison_findings', to='pid_verification_v2.pidvproject'),
        ),
        migrations.AddField(
            model_name='pidvcomparisonfinding',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_pidv2_findings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pidvextractionresult',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extractions', to='pid_verification_v2.pidvdocument'),
        ),
        migrations.AddField(
            model_name='pidvextractionresult',
            name='extracted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pidv2_extractions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pidvextractionresult',
            name='legend_sheet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extractions', to='pid_verification_v2.pidvlegendsheet'),
        ),
        migrations.AddField(
            model_name='pidvextractionresult',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extraction_results', to='pid_verification_v2.pidvproject'),
        ),
        migrations.AddField(
            model_name='pidvextractionresult',
            name='reference_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extractions', to='pid_verification_v2.pidvreferencedata'),
        ),
        migrations.AddField(
            model_name='pidvextractionpage',
            name='extraction_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='pid_verification_v2.pidvextractionresult'),
        ),
        migrations.AddField(
            model_name='pidvcomparisonfinding',
            name='source_extractions',
            field=models.ManyToManyField(help_text='Extraction results involved in this finding', related_name='comparison_findings', to='pid_verification_v2.pidvextractionresult'),
        ),
        migrations.AddIndex(
            model_name='pidvextractionresult',
            index=models.Index(fields=['extraction_id'], name='pidv2_extra_extract_4e9818_idx'),
        ),
        migrations.AddIndex(
            model_name='pidvextractionresult',
            index=models.Index(fields=['project', 'file_type'], name='pidv2_extra_project_f1aeb5_idx'),
        ),
        migrations.AddIndex(
            model_name='pidvextractionresult',
            index=models.Index(fields=['status'], name='pidv2_extra_status_fa943c_idx'),
        ),
        migrations.AddIndex(
            model_name='pidvextractionresult',
            index=models.Index(fields=['extraction_mode'], name='pidv2_extra_extract_dbf1a8_idx'),
        ),
        migrations.AddIndex(
            model_name='pidvextractionpage',
            index=models.Index(fields=['extraction_result', 'page_number'], name='pidv2_extra_extract_a02f23_idx'),
        ),
        migrations.AddIndex(
            model_name='pidvextractionpage',
            index=models.Index(fields=['avg_confidence'], name='pidv2_extra_avg_con_ca3ad6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pidvextractionpage',
            unique_together={('extraction_result', 'page_number')},
        ),
        migrations.AddIndex(
            model_name='pidvcomparisonfinding',
            index=models.Index(fields=['finding_id'], name='pidv2_compa_finding_eed5c8_idx'),
        ),
        migrations.AddIndex(
            model_name='pidvcomparisonfinding',
            index=models.Index(fields=['project', 'finding_type'], name='pidv2_compa_project_cd95a5_idx'),
        ),
        migrations.AddIndex(
            model_name='pidvcomparisonfinding',
            index=models.Index(fields=['severity', 'status'], name='pidv2_compa_severit_3191d8_idx'),
        ),
        migrations.AddIndex(
            model_name='pidvcomparisonfinding',
            index=models.Index(fields=['status'], name='pidv2_compa_status_5253f9_idx'),
        ),
    ]
