# Generated by Django 5.0 on 2026-07-25 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pid_verification_v2', '0003_add_multilayer_extraction_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='pidvproject',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
