# Generated by Django 5.0 on 2026-10-01 18:19

import django.db.models.deletion
from django.db import migrations, models

from config.migration_schema import CreateModelIfMissing

class Migration(migrations.Migration):

    dependencies = [
        ('pid_verification_v2', '0005_repair_missing_primary_keys'),
    ]

    operations = [
        CreateModelIfMissing(
            name='PIDVTagIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.PositiveSmallIntegerField(help_text='page_index of the source PIDVDrawing')),
                ('tag', models.CharField(db_index=True, help_text="normalize_tag()'d form — the matching key", max_length=255)),
                ('raw_tag', models.CharField(help_text='Original as-extracted tag text', max_length=255)),
                ('tag_type', models.CharField(choices=[('line', 'Line'), ('equipment', 'Equipment'), ('instrument', 'Instrument'), ('valve', 'Valve')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_index', to='pid_verification_v2.pidvdocument')),
            ],
            options={
                'db_table': 'pidv2_tag_index',
                'indexes': [models.Index(fields=['document', 'tag'], name='pidv2_tag_i_documen_86acd5_idx'), models.Index(fields=['document', 'page_number'], name='pidv2_tag_i_documen_d1d0fd_idx')],
            },
        ),
    ]
