# Auto-generated table configuration
SYNC_TABLE_CONFIG = {
    'activity_event': {
        'description':    'Activity Event',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       100,
    },
    'activity_statistics': {
        'description':    'Activity Statistics',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       101,
    },
    'activity_stream': {
        'description':    'Activity Stream',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       102,
    },
    'admin_error_log_analytics': {
        'description':    'Admin Error Log Analytics',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       103,
    },
    'admin_feature_usage_analytics': {
        'description':    'Admin Feature Usage Analytics',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       104,
    },
    'admin_predictive_insights': {
        'description':    'Admin Predictive Insights',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       105,
    },
    'admin_security_alerts': {
        'description':    'Admin Security Alerts',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       106,
    },
    'admin_system_health_checks': {
        'description':    'Admin System Health Checks',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       107,
    },
    'admin_system_metrics': {
        'description':    'Admin System Metrics',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       108,
    },
    'admin_user_activity_analytics': {
        'description':    'Admin User Activity Analytics',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       109,
    },
    'ai_pricing_config': {
        'description':    'Ai Pricing Config',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       110,
    },
    'ai_usage_log': {
        'description':    'Ai Usage Log',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       111,
    },
    'api_usage_logs': {
        'description':    'Api Usage Logs',
        'timestamp_col':  'timestamp',
        'pk_col':         'id',
        'order_col':      'timestamp',
        'priority':       112,
    },
    'audit_logs': {
        'description':    'Audit Logs',
        'timestamp_col':  'timestamp',
        'pk_col':         'id',
        'order_col':      'timestamp',
        'priority':       113,
    },
    'auth_group': {
        'description':    'Auth Group',
        'timestamp_col':  None,
        'pk_col':         'id',
        'order_col':      'id',
        'priority':       4,  # Parent: referenced by auth_group_permissions, users_groups
    },
    'auth_group_permissions': {
        'description':    'Auth Group Permissions',
        'timestamp_col':  None,
        'pk_col':         'id',
        'order_col':      'id',
        'priority':       54,  # Child: references auth_group and auth_permission
    },
    'auth_permission': {
        'description':    'Auth Permission',
        'timestamp_col':  None,
        'pk_col':         'id',
        'order_col':      'id',
        'priority':       3,  # Parent: referenced by auth_group_permissions, users_user_permissions
    },
    'core_cross_discipline_recommendations': {
        'description':    'Core Cross Discipline Recommendations',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       117,
    },
    'core_document_relationships': {
        'description':    'Core Document Relationships',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       118,
    },
    'core_enquiry': {
        'description':    'Core Enquiry',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       119,
    },
    'core_project': {
        'description':    'Core Project',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       120,
    },
    'core_project_collections': {
        'description':    'Core Project Collections',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       121,
    },
    'core_project_disciplines': {
        'description':    'Core Project Disciplines',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       122,
    },
    'core_projectmember': {
        'description':    'Core Projectmember',
        'timestamp_col':  None,
        'pk_col':         'id',
        'order_col':      'id',
        'priority':       123,
    },
    'core_projectmilestone': {
        'description':    'Core Projectmilestone',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       124,
    },
    'core_projecttask': {
        'description':    'Core Projecttask',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       125,
    },
    'core_smart_project_documents': {
        'description':    'Core Smart Project Documents',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       126,
    },
    'cross_recommendation_links': {
        'description':    'Cross Recommendation Links',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       127,
    },
    'crs_activities': {
        'description':    'Crs Activities',
        'timestamp_col':  None,
        'pk_col':         'id',
        'order_col':      'id',
        'priority':       128,
    },
    'crs_ai_insights': {
        'description':    'Crs Ai Insights',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       129,
    },
    'crs_comment_links': {
        'description':    'Crs Comment Links',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       130,
    },
    'crs_comments': {
        'description':    'Crs Comments',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       131,
    },
    'crs_documents': {
        'description':    'Crs Documents',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       132,
    },
    'crs_documents_crsdocument': {
        'description':    'Crs Documents Crsdocument',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       133,
    },
    'crs_documents_crsdocumentversion': {
        'description':    'Crs Documents Crsdocumentversion',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       134,
    },
    'crs_google_sheet_configs': {
        'description':    'Crs Google Sheet Configs',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       135,
    },
    'crs_revision_activities': {
        'description':    'Crs Revision Activities',
        'timestamp_col':  None,
        'pk_col':         'id',
        'order_col':      'id',
        'priority':       136,
    },
    'crs_revision_chains': {
        'description':    'Crs Revision Chains',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       137,
    },
    'crs_revisions': {
        'description':    'Crs Revisions',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       138,
    },
    'dashboard_userdashboardinsight': {
        'description':    'Dashboard Userdashboardinsight',
        'timestamp_col':  None,
        'pk_col':         'id',
        'order_col':      'id',
        'priority':       139,
    },
    'data_mining_documents': {
        'description':    'Data Mining Documents',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       140,
    },
    'data_mining_projects': {
        'description':    'Data Mining Projects',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       141,
    },
    'dataset_transformations': {
        'description':    'Dataset Transformations',
        'timestamp_col':  None,
        'pk_col':         'id',
        'order_col':      'id',
        'priority':       142,
    },
    'dataset_versions': {
        'description':    'Dataset Versions',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       143,
    },
    'datasets': {
        'description':    'Datasets',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       144,
    },
    'designiq_analyses': {
        'description':    'Designiq Analyses',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       145,
    },
    'designiq_engineering_list_items': {
        'description':    'Designiq Engineering List Items',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       146,
    },
    'designiq_optimizations': {
        'description':    'Designiq Optimizations',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       147,
    },
    'designiq_pid_line_annotations': {
        'description':    'Designiq Pid Line Annotations',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       148,
    },
    'designiq_pid_source_drawings': {
        'description':    'Designiq Pid Source Drawings',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       149,
    },
    'designiq_processed_pid_outputs': {
        'description':    'Designiq Processed Pid Outputs',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       150,
    },
    'designiq_projects': {
        'description':    'Designiq Projects',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       151,
    },
    'designiq_templates': {
        'description':    'Designiq Templates',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       152,
    },
    'django_admin_log': {
        'description':    'Django Admin Log',
        'timestamp_col':  None,
        'pk_col':         'id',
        'order_col':      'id',
        'priority':       153,
    },
    'django_content_type': {
        'description':    'Django Content Type',
        'timestamp_col':  None,
        'pk_col':         'id',
        'order_col':      'id',
        'priority':       2,  # Parent: referenced by auth_permission
    },
    'django_migrations': {
        'description':    'Django Migrations',
        'timestamp_col':  None,
        'pk_col':         'id',
        'order_col':      'id',
        'priority':       155,
    },
    'django_session': {
        'description':    'Django Session',
        'timestamp_col':  None,
        'pk_col':         'session_key',
        'order_col':      'session_key',
        'priority':       156,
    },
    'document_access_logs': {
        'description':    'Document Access Logs',
        'timestamp_col':  None,
        'pk_col':         'id',
        'order_col':      'id',
        'priority':       157,
    },
    'document_versions': {
        'description':    'Document Versions',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       158,
    },
    'documents': {
        'description':    'Documents',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       159,
    },
    'electrical_checklist_jobs': {
        'description':    'Electrical Checklist Jobs',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       160,
    },
    'electrical_checklist_project_members': {
        'description':    'Electrical Checklist Project Members',
        'timestamp_col':  None,
        'pk_col':         'id',
        'order_col':      'id',
        'priority':       161,
    },
    'electrical_checklist_projects': {
        'description':    'Electrical Checklist Projects',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       162,
    },
    'electrical_datasheet_cell_edits': {
        'description':    'Electrical Datasheet Cell Edits',
        'timestamp_col':  None,
        'pk_col':         'id',
        'order_col':      'id',
        'priority':       163,
    },
    'electrical_datasheet_comments': {
        'description':    'Electrical Datasheet Comments',
        'timestamp_col':  None,
        'pk_col':         'id',
        'order_col':      'id',
        'priority':       164,
    },
    'electrical_datasheet_revisions': {
        'description':    'Electrical Datasheet Revisions',
        'timestamp_col':  None,
        'pk_col':         'id',
        'order_col':      'id',
        'priority':       165,
    },
    'electrical_datasheet_share_links': {
        'description':    'Electrical Datasheet Share Links',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       166,
    },
    'electrical_datasheets': {
        'description':    'Electrical Datasheets',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       167,
    },
    'electrical_equipment_types': {
        'description':    'Electrical Equipment Types',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       168,
    },
    'electrical_generated_datasheet_comments': {
        'description':    'Electrical Generated Datasheet Comments',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       169,
    },
    'electrical_generated_datasheet_snapshots': {
        'description':    'Electrical Generated Datasheet Snapshots',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       170,
    },
    'electrical_generated_datasheets': {
        'description':    'Electrical Generated Datasheets',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       171,
    },
    'finance_approval': {
        'description':    'Finance Approval',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       172,
    },
    'finance_approvalroute': {
        'description':    'Finance Approvalroute',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       173,
    },
    'finance_auditlog': {
        'description':    'Finance Auditlog',
        'timestamp_col':  'timestamp',
        'pk_col':         'id',
        'order_col':      'timestamp',
        'priority':       174,
    },
    'finance_employee_salary_components': {
        'description':    'Finance Employee Salary Components',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       175,
    },
    'finance_employee_salary_info': {
        'description':    'Finance Employee Salary Info',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       176,
    },
    'finance_invoice': {
        'description':    'Finance Invoice',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       177,
    },
    'finance_payroll_runs': {
        'description':    'Finance Payroll Runs',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       178,
    },
    'finance_payroll_schedule': {
        'description':    'Finance Payroll Schedule',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       179,
    },
    'finance_payroll_workflow': {
        'description':    'Finance Payroll Workflow',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       180,
    },
    'finance_salary_components': {
        'description':    'Finance Salary Components',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       181,
    },
    'finance_salary_slip_approvals': {
        'description':    'Finance Salary Slip Approvals',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       182,
    },
    'finance_salary_slip_audit_logs': {
        'description':    'Finance Salary Slip Audit Logs',
        'timestamp_col':  None,
        'pk_col':         'id',
        'order_col':      'id',
        'priority':       183,
    },
    'finance_salary_slip_emails': {
        'description':    'Finance Salary Slip Emails',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       184,
    },
    'finance_salary_slips': {
        'description':    'Finance Salary Slips',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       185,
    },
    'finance_workflow_notification_log': {
        'description':    'Finance Workflow Notification Log',
        'timestamp_col':  None,
        'pk_col':         'id',
        'order_col':      'id',
        'priority':       186,
    },
    'hr_employee_master': {
        'description':    'Hr Employee Master',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       187,
    },
    'instrument_io_workflow_iolistdocument': {
        'description':    'Instrument Io Workflow Iolistdocument',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       188,
    },
    'instrument_io_workflow_iolistextractedcomment': {
        'description':    'Instrument Io Workflow Iolistextractedcomment',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       189,
    },
    'instrument_io_workflow_iolistextractedrow': {
        'description':    'Instrument Io Workflow Iolistextractedrow',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       190,
    },
    'instrument_io_workflow_iolistproject': {
        'description':    'Instrument Io Workflow Iolistproject',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       191,
    },
    'invoice_tracker_customerinvoice': {
        'description':    'Invoice Tracker Customerinvoice',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       192,
    },
    'invoice_tracker_invoiceattachment': {
        'description':    'Invoice Tracker Invoiceattachment',
        'timestamp_col':  None,
        'pk_col':         'id',
        'order_col':      'id',
        'priority':       193,
    },
    'ml_anomaly_detection': {
        'description':    'Ml Anomaly Detection',
        'timestamp_col':  'timestamp',
        'pk_col':         'id',
        'order_col':      'timestamp',
        'priority':       194,
    },
    'ml_detection_config': {
        'description':    'Ml Detection Config',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       195,
    },
    'ml_detection_metrics': {
        'description':    'Ml Detection Metrics',
        'timestamp_col':  'timestamp',
        'pk_col':         'id',
        'order_col':      'timestamp',
        'priority':       196,
    },
    'ml_detection_model': {
        'description':    'Ml Detection Model',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       197,
    },
    'ml_realtime_alert': {
        'description':    'Ml Realtime Alert',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       198,
    },
    'ml_realtime_data_stream': {
        'description':    'Ml Realtime Data Stream',
        'timestamp_col':  'timestamp',
        'pk_col':         'id',
        'order_col':      'timestamp',
        'priority':       199,
    },
    'monthly_champion': {
        'description':    'Monthly Champion',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       200,
    },
    'non_teff_metadata_nonteffbatch': {
        'description':    'Non Teff Metadata Nonteffbatch',
        'timestamp_col':  'created_at',
        'pk_col':         'batch_id',
        'order_col':      'created_at',
        'priority':       201,
    },
    'non_teff_metadata_nonteffbatchitem': {
        'description':    'Non Teff Metadata Nonteffbatchitem',
        'timestamp_col':  'created_at',
        'pk_col':         'item_id',
        'order_col':      'created_at',
        'priority':       202,
    },
    'non_teff_metadata_nonteffextractionjob': {
        'description':    'Non Teff Metadata Nonteffextractionjob',
        'timestamp_col':  'created_at',
        'pk_col':         'job_id',
        'order_col':      'created_at',
        'priority':       203,
    },
    'non_teff_metadata_nonteffproject': {
        'description':    'Non Teff Metadata Nonteffproject',
        'timestamp_col':  'created_at',
        'pk_col':         'project_id',
        'order_col':      'created_at',
        'priority':       204,
    },
    'notification_categories': {
        'description':    'Notification Categories',
        'timestamp_col':  None,
        'pk_col':         'id',
        'order_col':      'id',
        'priority':       205,
    },
    'notification_logs': {
        'description':    'Notification Logs',
        'timestamp_col':  'timestamp',
        'pk_col':         'id',
        'order_col':      'timestamp',
        'priority':       206,
    },
    'notification_preferences': {
        'description':    'Notification Preferences',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       207,
    },
    'notifications': {
        'description':    'Notifications',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       208,
    },
    'offboarding_record': {
        'description':    'Offboarding Record',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       209,
    },
    'onboarding_access': {
        'description':    'Onboarding Access',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       210,
    },
    'onboarding_checklist': {
        'description':    'Onboarding Checklist',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       211,
    },
    'onboarding_document': {
        'description':    'Onboarding Document',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       212,
    },
    'onboarding_equipment': {
        'description':    'Onboarding Equipment',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       213,
    },
    'onboarding_record': {
        'description':    'Onboarding Record',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       214,
    },
    'payroll_ai_insight_snapshot': {
        'description':    'Payroll Ai Insight Snapshot',
        'timestamp_col':  None,
        'pk_col':         'id',
        'order_col':      'id',
        'priority':       215,
    },
    'payroll_attendance_override': {
        'description':    'Payroll Attendance Override',
        'timestamp_col':  'date',
        'pk_col':         'id',
        'order_col':      'date',
        'priority':       216,
    },
    'payroll_audit_alert': {
        'description':    'Payroll Audit Alert',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       217,
    },
    'payroll_chatbot_message': {
        'description':    'Payroll Chatbot Message',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       218,
    },
    'payroll_daily_work_log': {
        'description':    'Payroll Daily Work Log',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       219,
    },
    'payroll_employee_leave_monthly': {
        'description':    'Payroll Employee Leave Monthly',
        'timestamp_col':  None,
        'pk_col':         'id',
        'order_col':      'id',
        'priority':       220,
    },
    'payroll_employee_leave_record': {
        'description':    'Payroll Employee Leave Record',
        'timestamp_col':  None,
        'pk_col':         'id',
        'order_col':      'id',
        'priority':       221,
    },
    'payroll_engine_adjustment': {
        'description':    'Payroll Engine Adjustment',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       222,
    },
    'payroll_engine_comparison': {
        'description':    'Payroll Engine Comparison',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       223,
    },
    'payroll_engine_comparison_row': {
        'description':    'Payroll Engine Comparison Row',
        'timestamp_col':  None,
        'pk_col':         'id',
        'order_col':      'id',
        'priority':       224,
    },
    'payroll_engine_employee': {
        'description':    'Payroll Engine Employee',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       225,
    },
    'payroll_engine_line_item': {
        'description':    'Payroll Engine Line Item',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       226,
    },
    'payroll_engine_line_item_change_log': {
        'description':    'Payroll Engine Line Item Change Log',
        'timestamp_col':  None,
        'pk_col':         'id',
        'order_col':      'id',
        'priority':       227,
    },
    'payroll_engine_payslip': {
        'description':    'Payroll Engine Payslip',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       228,
    },
    'payroll_engine_run': {
        'description':    'Payroll Engine Run',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       229,
    },
    'payroll_engine_run_upload': {
        'description':    'Payroll Engine Run Upload',
        'timestamp_col':  None,
        'pk_col':         'id',
        'order_col':      'id',
        'priority':       230,
    },
    'payroll_engine_workflow_log': {
        'description':    'Payroll Engine Workflow Log',
        'timestamp_col':  None,
        'pk_col':         'id',
        'order_col':      'id',
        'priority':       231,
    },
    'payroll_leave_encashment_run': {
        'description':    'Payroll Leave Encashment Run',
        'timestamp_col':  None,
        'pk_col':         'id',
        'order_col':      'id',
        'priority':       232,
    },
    'payroll_leave_request': {
        'description':    'Payroll Leave Request',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       233,
    },
    'payroll_leave_type': {
        'description':    'Payroll Leave Type',
        'timestamp_col':  None,
        'pk_col':         'id',
        'order_col':      'id',
        'priority':       234,
    },
    'payroll_master_import': {
        'description':    'Payroll Master Import',
        'timestamp_col':  None,
        'pk_col':         'id',
        'order_col':      'id',
        'priority':       235,
    },
    'payroll_master_row': {
        'description':    'Payroll Master Row',
        'timestamp_col':  None,
        'pk_col':         'id',
        'order_col':      'id',
        'priority':       236,
    },
    'payroll_monthly_leave_accrual_log': {
        'description':    'Payroll Monthly Leave Accrual Log',
        'timestamp_col':  None,
        'pk_col':         'id',
        'order_col':      'id',
        'priority':       237,
    },
    'payroll_project_cost_allocation': {
        'description':    'Payroll Project Cost Allocation',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       238,
    },
    'payroll_public_holiday': {
        'description':    'Payroll Public Holiday',
        'timestamp_col':  'date',
        'pk_col':         'id',
        'order_col':      'date',
        'priority':       239,
    },
    'payroll_salary_component': {
        'description':    'Payroll Salary Component',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       240,
    },
    'payroll_salary_history': {
        'description':    'Payroll Salary History',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       241,
    },
    'payroll_salary_structure': {
        'description':    'Payroll Salary Structure',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       242,
    },
    'payroll_validation_log': {
        'description':    'Payroll Validation Log',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       243,
    },
    'payroll_workflow_log': {
        'description':    'Payroll Workflow Log',
        'timestamp_col':  None,
        'pk_col':         'id',
        'order_col':      'id',
        'priority':       244,
    },
    'pfd_conversion_feedback': {
        'description':    'Pfd Conversion Feedback',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       245,
    },
    'pfd_documents': {
        'description':    'Pfd Documents',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       246,
    },
    'pfd_issues': {
        'description':    'Pfd Issues',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       247,
    },
    'pfd_projects': {
        'description':    'Pfd Projects',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       248,
    },
    'pfd_uploads': {
        'description':    'Pfd Uploads',
        'timestamp_col':  None,
        'pk_col':         'id',
        'order_col':      'id',
        'priority':       249,
    },
    'pfd_verification_reports': {
        'description':    'Pfd Verification Reports',
        'timestamp_col':  'updated_at',
        'pk_col':         'id',
        'order_col':      'updated_at',
        'priority':       250,
    },
    'pfdq_documents': {
        'description':    'Pfdq Documents',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       251,
    },
    'pfdq_drawings': {
        'description':    'Pfdq Drawings',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       252,
    },
    'pfdq_findings': {
        'description':    'Pfdq Findings',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       253,
    },
    'pfdq_projects': {
        'description':    'Pfdq Projects',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       254,
    },
    'pid_analysis_pidanalysisreport': {
        'description':    'Pid Analysis Pidanalysisreport',
        'timestamp_col':  'updated_at',
        'pk_col':         'id',
        'order_col':      'updated_at',
        'priority':       255,
    },
    'pid_analysis_piddrawing': {
        'description':    'Pid Analysis Piddrawing',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       256,
    },
    'pid_analysis_pidissue': {
        'description':    'Pid Analysis Pidissue',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       257,
    },
    'pid_analysis_referencedocument': {
        'description':    'Pid Analysis Referencedocument',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       258,
    },
    'pid_checker_v2_equipment_list_row': {
        'description':    'Pid Checker V2 Equipment List Row',
        'timestamp_col':  None,
        'pk_col':         'id',
        'order_col':      'id',
        'priority':       259,
    },
    'pid_checker_v2_equipment_list_upload': {
        'description':    'Pid Checker V2 Equipment List Upload',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       260,
    },
    'pid_checker_v2_extraction': {
        'description':    'Pid Checker V2 Extraction',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       261,
    },
    'pid_checker_v2_instrument_index_row': {
        'description':    'Pid Checker V2 Instrument Index Row',
        'timestamp_col':  None,
        'pk_col':         'id',
        'order_col':      'id',
        'priority':       262,
    },
    'pid_checker_v2_instrument_index_upload': {
        'description':    'Pid Checker V2 Instrument Index Upload',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       263,
    },
    'pid_checker_v2_legend_sheet': {
        'description':    'Pid Checker V2 Legend Sheet',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       264,
    },
    'pid_checker_v2_line_list_row': {
        'description':    'Pid Checker V2 Line List Row',
        'timestamp_col':  None,
        'pk_col':         'id',
        'order_col':      'id',
        'priority':       265,
    },
    'pid_checker_v2_line_list_upload': {
        'description':    'Pid Checker V2 Line List Upload',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       266,
    },
    'pid_checker_v2_line_tag': {
        'description':    'Pid Checker V2 Line Tag',
        'timestamp_col':  None,
        'pk_col':         'id',
        'order_col':      'id',
        'priority':       267,
    },
    'pid_checker_v2_project': {
        'description':    'Pid Checker V2 Project',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       268,
    },
    'pid_checker_v2_usage_log': {
        'description':    'Pid Checker V2 Usage Log',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       269,
    },
    'pid_conversions': {
        'description':    'Pid Conversions',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       270,
    },
    'pid_equipment_items': {
        'description':    'Pid Equipment Items',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       271,
    },
    'pid_equipment_types': {
        'description':    'Pid Equipment Types',
        'timestamp_col':  'created_at',
        'pk_col':         'code',
        'order_col':      'created_at',
        'priority':       272,
    },
    'pid_projects': {
        'description':    'Pid Projects',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       273,
    },
    'pidv2_ai_check_runs': {
        'description':    'Pidv2 Ai Check Runs',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       274,
    },
    'pidv2_comparison_findings': {
        'description':    'Pidv2 Comparison Findings',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       275,
    },
    'pidv2_comparison_findings_source_extractions': {
        'description':    'Pidv2 Comparison Findings Source Extractions',
        'timestamp_col':  None,
        'pk_col':         'id',
        'order_col':      'id',
        'priority':       276,
    },
    'pidv2_documents': {
        'description':    'Pidv2 Documents',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       277,
    },
    'pidv2_drawings': {
        'description':    'Pidv2 Drawings',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       278,
    },
    'pidv2_extraction_pages': {
        'description':    'Pidv2 Extraction Pages',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       279,
    },
    'pidv2_extraction_results': {
        'description':    'Pidv2 Extraction Results',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       280,
    },
    'pidv2_findings': {
        'description':    'Pidv2 Findings',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       281,
    },
    'pidv2_instrument_symbols': {
        'description':    'Pidv2 Instrument Symbols',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       282,
    },
    'pidv2_legend_sheets': {
        'description':    'Pidv2 Legend Sheets',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       283,
    },
    'pidv2_projects': {
        'description':    'Pidv2 Projects',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       284,
    },
    'pidv2_reference_data': {
        'description':    'Pidv2 Reference Data',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       285,
    },
    'pidv_ai_check_runs': {
        'description':    'Pidv Ai Check Runs',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       286,
    },
    'pidv_documents': {
        'description':    'Pidv Documents',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       287,
    },
    'pidv_drawings': {
        'description':    'Pidv Drawings',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       288,
    },
    'pidv_findings': {
        'description':    'Pidv Findings',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       289,
    },
    'pidv_instrument_symbols': {
        'description':    'Pidv Instrument Symbols',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       290,
    },
    'pidv_legend_sheets': {
        'description':    'Pidv Legend Sheets',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       291,
    },
    'pidv_projects': {
        'description':    'Pidv Projects',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       292,
    },
    'pidv_reference_data': {
        'description':    'Pidv Reference Data',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       293,
    },
    'planning_intelligence_planningfile': {
        'description':    'Planning Intelligence Planningfile',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       294,
    },
    'planning_intelligence_planninggeneration': {
        'description':    'Planning Intelligence Planninggeneration',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       295,
    },
    'planning_intelligence_planningproject': {
        'description':    'Planning Intelligence Planningproject',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       296,
    },
    'process_datasheet_extraction_jobs': {
        'description':    'Process Datasheet Extraction Jobs',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       297,
    },
    'process_datasheet_pumphydraulicsnapshot': {
        'description':    'Process Datasheet Pumphydraulicsnapshot',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       298,
    },
    'process_datasheet_revisions': {
        'description':    'Process Datasheet Revisions',
        'timestamp_col':  None,
        'pk_col':         'id',
        'order_col':      'id',
        'priority':       299,
    },
    'process_datasheet_templates': {
        'description':    'Process Datasheet Templates',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       300,
    },
    'process_datasheet_validation_rules': {
        'description':    'Process Datasheet Validation Rules',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       301,
    },
    'process_datasheets': {
        'description':    'Process Datasheets',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       302,
    },
    'process_equipment_types': {
        'description':    'Process Equipment Types',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       303,
    },
    'procurement_budget': {
        'description':    'Procurement Budget',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       304,
    },
    'procurement_costcenter': {
        'description':    'Procurement Costcenter',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       305,
    },
    'procurement_number_sequences': {
        'description':    'Procurement Number Sequences',
        'timestamp_col':  'updated_at',
        'pk_col':         'id',
        'order_col':      'updated_at',
        'priority':       306,
    },
    'procurement_order_lines': {
        'description':    'Procurement Order Lines',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       307,
    },
    'procurement_orders': {
        'description':    'Procurement Orders',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       308,
    },
    'procurement_orders_related_invoices': {
        'description':    'Procurement Orders Related Invoices',
        'timestamp_col':  None,
        'pk_col':         'id',
        'order_col':      'id',
        'priority':       309,
    },
    'procurement_po_documents': {
        'description':    'Procurement Po Documents',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       310,
    },
    'procurement_project': {
        'description':    'Procurement Project',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       311,
    },
    'procurement_project_team_members': {
        'description':    'Procurement Project Team Members',
        'timestamp_col':  None,
        'pk_col':         'id',
        'order_col':      'id',
        'priority':       312,
    },
    'procurement_receipt_lines': {
        'description':    'Procurement Receipt Lines',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       313,
    },
    'procurement_receipts': {
        'description':    'Procurement Receipts',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       314,
    },
    'procurement_requisitions': {
        'description':    'Procurement Requisitions',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       315,
    },
    'procurement_vendors': {
        'description':    'Procurement Vendors',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       316,
    },
    'project_control_changeevent': {
        'description':    'Project Control Changeevent',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       317,
    },
    'project_control_costsnapshot': {
        'description':    'Project Control Costsnapshot',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       318,
    },
    'project_control_estimate': {
        'description':    'Project Control Estimate',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       319,
    },
    'project_control_estimatelineitem': {
        'description':    'Project Control Estimatelineitem',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       320,
    },
    'project_control_planningpackage': {
        'description':    'Project Control Planningpackage',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       321,
    },
    'project_control_projectdocument': {
        'description':    'Project Control Projectdocument',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       322,
    },
    'project_control_wbsnode': {
        'description':    'Project Control Wbsnode',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       323,
    },
    'pump_calculation_data': {
        'description':    'Pump Calculation Data',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       324,
    },
    'qhse_audits': {
        'description':    'Qhse Audits',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       325,
    },
    'qhse_running_projects': {
        'description':    'Qhse Running Projects',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       326,
    },
    'qhse_spot_check_register': {
        'description':    'Qhse Spot Check Register',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       327,
    },
    'rbac_access_requests': {
        'description':    'Rbac Access Requests',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       328,
    },
    'rbac_audit_logs': {
        'description':    'Rbac Audit Logs',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       329,
    },
    'rbac_engineer_profiles': {
        'description':    'Rbac Engineer Profiles',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       330,
    },
    'rbac_modules': {
        'description':    'Rbac Modules',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       8,  # Parent: referenced by rbac_role_modules
    },
    'rbac_organizations': {
        'description':    'Rbac Organizations',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       5,  # Parent: might be referenced by users
    },
    'rbac_permissions': {
        'description':    'Rbac Permissions',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       7,  # Parent: referenced by rbac_role_permissions
    },
    'rbac_profile_documents': {
        'description':    'Rbac Profile Documents',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       334,
    },
    'rbac_role_modules': {
        'description':    'Rbac Role Modules',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       53,  # Child: references rbac_roles and rbac_modules
    },
    'rbac_role_permissions': {
        'description':    'Rbac Role Permissions',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       52,  # Child: references rbac_roles and rbac_permissions
    },
    'rbac_roles': {
        'description':    'Rbac Roles',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       6,  # Parent: referenced by rbac_user_roles, rbac_role_permissions
    },
    'rbac_social_media_links': {
        'description':    'Rbac Social Media Links',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       338,
    },
    'rbac_subscription_features': {
        'description':    'Rbac Subscription Features',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       339,
    },
    'rbac_subscription_history': {
        'description':    'Rbac Subscription History',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       340,
    },
    'rbac_subscription_invoices': {
        'description':    'Rbac Subscription Invoices',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       341,
    },
    'rbac_subscription_plans': {
        'description':    'Rbac Subscription Plans',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       9,  # Parent: referenced by rbac_user_subscriptions
    },
    'rbac_usage_tracking': {
        'description':    'Rbac Usage Tracking',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       343,
    },
    'rbac_user_achievements': {
        'description':    'Rbac User Achievements',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       344,
    },
    'rbac_user_profiles': {
        'description':    'Rbac User Profiles',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       50,  # Child: references users (must sync AFTER users)
    },
    'rbac_user_roles': {
        'description':    'Rbac User Roles',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       51,  # Child: references users and rbac_roles
    },
    'rbac_user_storage': {
        'description':    'Rbac User Storage',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       347,
    },
    'rbac_user_subscriptions': {
        'description':    'Rbac User Subscriptions',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       57,  # Child: references users and rbac_subscription_plans
    },
    'rbac_work_experience': {
        'description':    'Rbac Work Experience',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       349,
    },
    'sales_activities': {
        'description':    'Sales Activities',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       350,
    },
    'sales_activities_participants': {
        'description':    'Sales Activities Participants',
        'timestamp_col':  None,
        'pk_col':         'id',
        'order_col':      'id',
        'priority':       351,
    },
    'sales_approval_routes': {
        'description':    'Sales Approval Routes',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       352,
    },
    'sales_ariba_integration_logs': {
        'description':    'Sales Ariba Integration Logs',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       353,
    },
    'sales_clients': {
        'description':    'Sales Clients',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       354,
    },
    'sales_contacts': {
        'description':    'Sales Contacts',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       355,
    },
    'sales_deals': {
        'description':    'Sales Deals',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       356,
    },
    'sales_deals_team_members': {
        'description':    'Sales Deals Team Members',
        'timestamp_col':  None,
        'pk_col':         'id',
        'order_col':      'id',
        'priority':       357,
    },
    'sales_document_approvals': {
        'description':    'Sales Document Approvals',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       358,
    },
    'sales_document_comments': {
        'description':    'Sales Document Comments',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       359,
    },
    'sales_documents': {
        'description':    'Sales Documents',
        'timestamp_col':  'updated_at',
        'pk_col':         'id',
        'order_col':      'updated_at',
        'priority':       360,
    },
    'sales_forecasts': {
        'description':    'Sales Forecasts',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       361,
    },
    'sales_quotes': {
        'description':    'Sales Quotes',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       362,
    },
    'security_events': {
        'description':    'Security Events',
        'timestamp_col':  'timestamp',
        'pk_col':         'id',
        'order_col':      'timestamp',
        'priority':       363,
    },
    'site_visit_check_in': {
        'description':    'Site Visit Check In',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       364,
    },
    'site_visit_client_site': {
        'description':    'Site Visit Client Site',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       365,
    },
    'site_visit_request': {
        'description':    'Site Visit Request',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       366,
    },
    'sld_documents': {
        'description':    'Sld Documents',
        'timestamp_col':  None,
        'pk_col':         'id',
        'order_col':      'id',
        'priority':       367,
    },
    'sld_drawings': {
        'description':    'Sld Drawings',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       368,
    },
    'sld_findings': {
        'description':    'Sld Findings',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       369,
    },
    'sld_projects': {
        'description':    'Sld Projects',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       370,
    },
    'spec_customization_componentmatchingresult': {
        'description':    'Spec Customization Componentmatchingresult',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       371,
    },
    'spec_customization_matchingrule': {
        'description':    'Spec Customization Matchingrule',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       372,
    },
    'spec_customization_matchingworkbookset': {
        'description':    'Spec Customization Matchingworkbookset',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       373,
    },
    'spec_customization_paperspecdocument': {
        'description':    'Spec Customization Paperspecdocument',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       374,
    },
    'spec_customization_paperspecextractionjob': {
        'description':    'Spec Customization Paperspecextractionjob',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       375,
    },
    'spec_customization_pipingclass': {
        'description':    'Spec Customization Pipingclass',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       376,
    },
    'spec_customization_pipingclasscomponent': {
        'description':    'Spec Customization Pipingclasscomponent',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       377,
    },
    'spec_customization_specproject': {
        'description':    'Spec Customization Specproject',
        'timestamp_col':  'created_at',
        'pk_col':         'project_id',
        'order_col':      'created_at',
        'priority':       378,
    },
    'spec_customization_workbookcelloverride': {
        'description':    'Spec Customization Workbookcelloverride',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       379,
    },
    'system_activity': {
        'description':    'System Activity',
        'timestamp_col':  'timestamp',
        'pk_col':         'id',
        'order_col':      'timestamp',
        'priority':       380,
    },
    'timesheet_biometricusermaster': {
        'description':    'Timesheet Biometricusermaster',
        'timestamp_col':  None,
        'pk_col':         'id',
        'order_col':      'id',
        'priority':       381,
    },
    'timesheet_dailyattendancesummary': {
        'description':    'Timesheet Dailyattendancesummary',
        'timestamp_col':  'date',
        'pk_col':         'id',
        'order_col':      'date',
        'priority':       382,
    },
    'timesheet_timesheetevent': {
        'description':    'Timesheet Timesheetevent',
        'timestamp_col':  'event_time',
        'pk_col':         'id',
        'order_col':      'event_time',
        'priority':       383,
    },
    'transformation_pipelines': {
        'description':    'Transformation Pipelines',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       384,
    },
    'transformation_steps': {
        'description':    'Transformation Steps',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       385,
    },
    'usage_log': {
        'description':    'Usage Log',
        'timestamp_col':  'timestamp',
        'pk_col':         'id',
        'order_col':      'timestamp',
        'priority':       386,
    },
    'user_profiles': {
        'description':    'User Profiles',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       387,
    },
    'user_session': {
        'description':    'User Session',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       388,
    },
    'users': {
        'description':    'Users',
        'timestamp_col':  None,
        'pk_col':         'id',
        'order_col':      'id',
        'priority':       1,  # CRITICAL: Must sync FIRST (parent of many tables)
    },
    'users_groups': {
        'description':    'Users Groups',
        'timestamp_col':  None,
        'pk_col':         'id',
        'order_col':      'id',
        'priority':       55,  # Child: references users and auth_group
    },
    'users_user_permissions': {
        'description':    'Users User Permissions',
        'timestamp_col':  None,
        'pk_col':         'id',
        'order_col':      'id',
        'priority':       56,  # Child: references users and auth_permission
    },
    'version_comparisons': {
        'description':    'Version Comparisons',
        'timestamp_col':  None,
        'pk_col':         'id',
        'order_col':      'id',
        'priority':       392,
    },
    'wrench_integration_wrenchconfig': {
        'description':    'Wrench Integration Wrenchconfig',
        'timestamp_col':  'created_at',
        'pk_col':         'id',
        'order_col':      'created_at',
        'priority':       393,
    },
    'wrench_integration_wrenchs3syncjob': {
        'description':    'Wrench Integration Wrenchs3Syncjob',
        'timestamp_col':  'updated_at',
        'pk_col':         'id',
        'order_col':      'updated_at',
        'priority':       394,
    },
    'wrench_integration_wrenchsynclog': {
        'description':    'Wrench Integration Wrenchsynclog',
        'timestamp_col':  None,
        'pk_col':         'id',
        'order_col':      'id',
        'priority':       395,
    },
}
