# Generated by Django 4.2.16 on 2026-07-10 17:04
# FIXED: Changed RenameIndex to conditional SQL to handle missing indexes

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0018_leave_encashment'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""DO $$ BEGIN IF EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'payroll_enc_yr_mo') THEN ALTER INDEX payroll_enc_yr_mo RENAME TO payroll_lea_year_ed3552_idx; END IF; END $$;""",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='leaveencashmentrun',
            name='missing_salaries',
            field=models.JSONField(blank=True, default=list, help_text='employee_codes with no salary on record (encashment_pay=0)'),
        ),
    ]
