# Generated by Django 4.2.16 on 2026-07-10 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0018_leave_encashment'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='leaveencashmentrun',
            new_name='payroll_lea_year_ed3552_idx',
            old_name='payroll_enc_yr_mo',
        ),
        migrations.AlterField(
            model_name='leaveencashmentrun',
            name='missing_salaries',
            field=models.JSONField(blank=True, default=list, help_text='employee_codes with no salary on record (encashment_pay=0)'),
        ),
    ]
