# Generated by Django 5.0 on 2026-07-22 11:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0019_rename_payroll_enc_yr_mo_payroll_lea_year_ed3552_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='leaveencashmentrun',
            new_name='payroll_lea_year_ed3552_idx',
            old_name='payroll_enc_yr_mo',
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='attachment',
            field=models.FileField(blank=True, help_text='Supporting documents (medical certificate, travel docs, etc.)', null=True, upload_to='leave_attachments/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='contact_number',
            field=models.CharField(blank=True, help_text='Contact number while on leave/travelling', max_length=20),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='substitute_employee',
            field=models.ForeignKey(blank=True, help_text='Employee who will substitute during leave', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='substituted_leave_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='substitute_name',
            field=models.CharField(blank=True, help_text='Substitute employee name (for non-system users)', max_length=255),
        ),
    ]
