# Generated by Django 5.0 on 2026-08-05 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0020_add_leave_additional_fields'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
        migrations.RenameIndex(
            model_name='leaveencashmentrun',
            new_name='payroll_lea_year_ed3552_idx',
            old_name='payroll_enc_yr_mo',
        ),
            ],
        ),
    ]
