# Generated by Django 5.0 on 2026-09-03 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_core', '0003_hrworkflowdefinition_hrworkflowinstance_and_more'),
        ('payroll', '0021_rename_payroll_enc_yr_mo_payroll_lea_year_ed3552_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='canonical_employee',
            field=models.ForeignKey(blank=True, help_text='Authoritative employee identity for this request.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_requests', to='hr_core.employeemaster'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='workflow_instance',
            field=models.OneToOneField(blank=True, help_text='Shared approval workflow runtime for this request.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_request', to='hr_core.hrworkflowinstance'),
        ),
    ]
