# Generated by Django 5.0 on 2026-01-20 09:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignProject',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=300)),
                ('design_type', models.CharField(choices=[('process_flow', 'Process Flow Design'), ('equipment', 'Equipment Design'), ('piping', 'Piping & Instrumentation'), ('heat_exchanger', 'Heat Exchanger Design'), ('vessel', 'Pressure Vessel Design'), ('pump', 'Pump Selection & Design'), ('valve', 'Valve Sizing & Selection'), ('safety', 'Safety System Design'), ('other', 'Other Design Type')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('analyzing', 'Analyzing'), ('completed', 'Completed'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('organization', models.CharField(blank=True, max_length=300)),
                ('design_parameters', models.JSONField(blank=True, default=dict)),
                ('ai_analysis_results', models.JSONField(blank=True, default=dict)),
                ('ai_confidence_score', models.FloatField(default=0.0, help_text='AI confidence score (0-100)')),
                ('ai_recommendations', models.JSONField(blank=True, default=list)),
                ('input_file', models.FileField(blank=True, null=True, upload_to='designiq/inputs/%Y/%m/%d/')),
                ('output_file', models.FileField(blank=True, null=True, upload_to='designiq/outputs/%Y/%m/%d/')),
                ('processing_time', models.FloatField(blank=True, help_text='Processing time in seconds', null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='designiq_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'DesignIQ Project',
                'verbose_name_plural': 'DesignIQ Projects',
                'db_table': 'designiq_projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DesignOptimization',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('impact', models.CharField(choices=[('high', 'High Impact'), ('medium', 'Medium Impact'), ('low', 'Low Impact')], default='medium', max_length=20)),
                ('estimated_cost_savings', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('estimated_efficiency_gain', models.FloatField(blank=True, help_text='Percentage improvement', null=True)),
                ('implementation_effort', models.CharField(blank=True, max_length=100)),
                ('implementation_notes', models.TextField(blank=True)),
                ('is_implemented', models.BooleanField(default=False)),
                ('implemented_at', models.DateTimeField(blank=True, null=True)),
                ('implemented_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='optimizations', to='designiq.designproject')),
            ],
            options={
                'verbose_name': 'Design Optimization',
                'verbose_name_plural': 'Design Optimizations',
                'db_table': 'designiq_optimizations',
                'ordering': ['impact', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DesignAnalysis',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('analysis_type', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('info', 'Informational')], default='info', max_length=20)),
                ('ai_finding', models.TextField(blank=True)),
                ('ai_recommendation', models.TextField(blank=True)),
                ('ai_confidence', models.FloatField(default=0.0)),
                ('standard_reference', models.CharField(blank=True, help_text='e.g., ASME, API, ISO', max_length=200)),
                ('code_section', models.CharField(blank=True, max_length=200)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_analyses', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='designiq.designproject')),
            ],
            options={
                'verbose_name': 'Design Analysis',
                'verbose_name_plural': 'Design Analyses',
                'db_table': 'designiq_analyses',
                'ordering': ['severity', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DesignTemplate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('design_type', models.CharField(choices=[('process_flow', 'Process Flow Design'), ('equipment', 'Equipment Design'), ('piping', 'Piping & Instrumentation'), ('heat_exchanger', 'Heat Exchanger Design'), ('vessel', 'Pressure Vessel Design'), ('pump', 'Pump Selection & Design'), ('valve', 'Valve Sizing & Selection'), ('safety', 'Safety System Design'), ('other', 'Other Design Type')], max_length=50)),
                ('description', models.TextField()),
                ('template_data', models.JSONField(default=dict)),
                ('parameters_schema', models.JSONField(default=dict, help_text='JSON schema for parameters')),
                ('is_public', models.BooleanField(default=False)),
                ('usage_count', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Design Template',
                'verbose_name_plural': 'Design Templates',
                'db_table': 'designiq_templates',
                'ordering': ['-usage_count', 'name'],
            },
        ),
        migrations.AddIndex(
            model_name='designproject',
            index=models.Index(fields=['created_by', 'status'], name='designiq_pr_created_018c62_idx'),
        ),
        migrations.AddIndex(
            model_name='designproject',
            index=models.Index(fields=['design_type'], name='designiq_pr_design__fdac53_idx'),
        ),
        migrations.AddIndex(
            model_name='designproject',
            index=models.Index(fields=['-created_at'], name='designiq_pr_created_9d7386_idx'),
        ),
        migrations.AddIndex(
            model_name='designanalysis',
            index=models.Index(fields=['project', 'severity'], name='designiq_an_project_2f2579_idx'),
        ),
        migrations.AddIndex(
            model_name='designanalysis',
            index=models.Index(fields=['is_resolved'], name='designiq_an_is_reso_309c03_idx'),
        ),
    ]
