# Generated by Django 5.0 on 2026-01-20 10:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designiq', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EngineeringListItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('list_type', models.CharField(db_index=True, max_length=50)),
                ('item_tag', models.CharField(db_index=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='active', max_length=20)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('is_validated', models.BooleanField(default=False)),
                ('validation_notes', models.TextField(blank=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.IntegerField(default=1)),
                ('revision_history', models.JSONField(blank=True, default=list)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='list_items_created', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='list_items', to='designiq.designproject')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='list_items_updated', to=settings.AUTH_USER_MODEL)),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='list_items_validated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'designiq_engineering_list_items',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['list_type', 'status'], name='designiq_en_list_ty_309a3d_idx'), models.Index(fields=['project', 'list_type'], name='designiq_en_project_2b33fc_idx'), models.Index(fields=['item_tag'], name='designiq_en_item_ta_63a2d5_idx'), models.Index(fields=['-created_at'], name='designiq_en_created_e505ba_idx')],
                'unique_together': {('project', 'list_type', 'item_tag')},
            },
        ),
    ]
