# Generated by Django 5.0 on 2026-07-28 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designiq', '0003_processedpidoutput'),
    ]

    operations = [
        migrations.AddField(
            model_name='processedpidoutput',
            name='edited_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_versions', to='designiq.processedpidoutput'),
        ),
    ]
