# Generated by Django 5.0 on 2026-07-28 08:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designiq', '0004_processedpidoutput_edited_from'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PIDSourceDrawing',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_file', models.FileField(upload_to='designiq/source_drawings/%Y/%m/')),
                ('original_filename', models.CharField(max_length=500)),
                ('page_count', models.PositiveIntegerField(default=1)),
                ('sequence', models.PositiveIntegerField(default=0)),
                ('output', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_drawings', to='designiq.processedpidoutput')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'designiq_pid_source_drawings',
                'ordering': ['sequence', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='PIDLineAnnotation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('line_number', models.CharField(db_index=True, max_length=200)),
                ('from_page_index', models.PositiveIntegerField(default=0)),
                ('from_point', models.JSONField(blank=True, default=dict)),
                ('to_page_index', models.PositiveIntegerField(default=0)),
                ('to_point', models.JSONField(blank=True, default=dict)),
                ('path_points', models.JSONField(blank=True, default=list)),
                ('color', models.CharField(blank=True, max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('output', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_annotations', to='designiq.processedpidoutput')),
                ('from_drawing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_annotations', to='designiq.pidsourcedrawing')),
                ('to_drawing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_annotations', to='designiq.pidsourcedrawing')),
            ],
            options={
                'db_table': 'designiq_pid_line_annotations',
                'ordering': ['line_number'],
                'unique_together': {('output', 'line_number')},
            },
        ),
    ]
