# Generated by Django 5.0 on 2026-07-28 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designiq', '0005_pidsourcedrawing_pidlineannotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='processedpidoutput',
            name='tag_positions',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
