# Generated by Django 5.0 on 2026-09-23 05:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sha256', models.CharField(max_length=64)),
                ('parser_version', models.CharField(max_length=32)),
                ('file_name', models.CharField(max_length=255)),
                ('reporting_date', models.DateField()),
                ('imported_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('row_count', models.PositiveIntegerField()),
                ('warnings', models.JSONField(default=list)),
                ('reconciliation', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['-reporting_date', '-imported_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_code', models.CharField(db_index=True, max_length=128)),
                ('subproject_code', models.CharField(max_length=128)),
                ('title', models.TextField()),
                ('pm', models.CharField(blank=True, max_length=128)),
                ('pc', models.CharField(blank=True, max_length=128)),
                ('business_unit', models.CharField(blank=True, max_length=128)),
                ('client', models.CharField(blank=True, max_length=255)),
                ('scope_type', models.CharField(blank=True, max_length=128)),
                ('currency', models.CharField(blank=True, max_length=16)),
                ('source_row', models.PositiveIntegerField()),
                ('include_without_pt', models.BooleanField(null=True)),
                ('include_with_pt', models.BooleanField(null=True)),
                ('contract_value_aed', models.DecimalField(decimal_places=8, max_digits=28, null=True)),
                ('recognized_revenue_aed', models.DecimalField(decimal_places=8, max_digits=28, null=True)),
                ('period_revenue_aed', models.DecimalField(decimal_places=8, max_digits=28, null=True)),
                ('backlog_without_pt_aed', models.DecimalField(decimal_places=8, max_digits=28, null=True)),
                ('backlog_with_pt_aed', models.DecimalField(decimal_places=8, max_digits=28, null=True)),
                ('poc_pct', models.DecimalField(decimal_places=8, max_digits=20, null=True)),
                ('eddr_pct', models.DecimalField(decimal_places=8, max_digits=20, null=True)),
                ('target_margin_pct', models.DecimalField(decimal_places=8, max_digits=20, null=True)),
                ('forecast_margin_pct', models.DecimalField(decimal_places=8, max_digits=20, null=True)),
                ('overclaim_aed', models.DecimalField(decimal_places=8, max_digits=28, null=True)),
                ('ld_exposure_aed', models.DecimalField(decimal_places=8, max_digits=28, null=True)),
                ('prolongation_cost_aed', models.DecimalField(decimal_places=8, max_digits=28, null=True)),
                ('start_date', models.DateField(null=True)),
                ('contractual_finish', models.DateField(null=True)),
                ('forecast_finish', models.DateField(null=True)),
                ('extra', models.JSONField(default=dict)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='portfolio.portfoliosnapshot')),
            ],
            options={
                'ordering': ['source_row', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='poc', max_length=80, unique=True)),
                ('etag', models.CharField(blank=True, max_length=512)),
                ('remote_identity', models.CharField(blank=True, max_length=1000)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('sync_token', models.UUIDField(blank=True, null=True)),
                ('sync_expires_at', models.DateTimeField(blank=True, null=True)),
                ('active_snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='portfolio.portfoliosnapshot')),
            ],
        ),
        migrations.AddField(
            model_name='portfoliosnapshot',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='portfolio.portfoliosource'),
        ),
        migrations.AddConstraint(
            model_name='portfoliorow',
            constraint=models.UniqueConstraint(fields=('snapshot', 'project_code', 'subproject_code'), name='portfolio_row_identity_unique'),
        ),
        migrations.AddConstraint(
            model_name='portfoliosnapshot',
            constraint=models.UniqueConstraint(fields=('source', 'sha256', 'parser_version'), name='portfolio_source_version_unique'),
        ),
    ]
