# Generated by Django 5.0 on 2026-09-15 05:09

import apps.file_replica.storage
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0011_enquiryattachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReplicaSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('root_path', models.CharField(max_length=1024)),
                ('included_paths', models.JSONField(blank=True, default=list)),
                ('excluded_paths', models.JSONField(blank=True, default=list)),
                ('mode', models.CharField(choices=[('catalogue', 'Catalogue'), ('mirror', 'Mirror')], default='catalogue', max_length=16)),
                ('enabled', models.BooleanField(default=True)),
                ('max_file_size_mb', models.PositiveIntegerField(default=100)),
                ('interval_seconds', models.PositiveIntegerField(default=300)),
                ('token_hash', models.CharField(blank=True, editable=False, max_length=64)),
                ('active_run', models.UUIDField(blank=True, editable=False, null=True)),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ReplicaScope',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relative_path', models.CharField(max_length=1024)),
                ('path_key', models.CharField(max_length=64)),
                ('access_enabled', models.BooleanField(default=False)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replica_scopes', to='core.project')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scopes', to='file_replica.replicasource')),
            ],
            options={
                'ordering': ['relative_path', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ReplicaScan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(default='running', max_length=16)),
                ('config_hash', models.CharField(max_length=64)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='file_replica.replicasource')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ReplicaEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relative_path', models.CharField(max_length=2048)),
                ('normalized_path', models.CharField(max_length=4096)),
                ('path_key', models.CharField(max_length=64)),
                ('parent_path', models.CharField(blank=True, max_length=2048)),
                ('name', models.CharField(max_length=512)),
                ('is_directory', models.BooleanField(default=False)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('modified_at', models.DateTimeField(blank=True, null=True)),
                ('checksum', models.CharField(blank=True, max_length=64)),
                ('content_type', models.CharField(blank=True, max_length=128)),
                ('status', models.CharField(default='indexed', max_length=16)),
                ('error', models.TextField(blank=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_scan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='file_replica.replicascan')),
                ('scope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='file_replica.replicascope')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='file_replica.replicasource')),
            ],
            options={
                'ordering': ['-is_directory', 'name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ReplicaVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.PositiveIntegerField()),
                ('file', models.FileField(max_length=512, storage=apps.file_replica.storage.replica_storage, upload_to=apps.file_replica.storage.version_path)),
                ('checksum', models.CharField(max_length=64)),
                ('size_bytes', models.PositiveBigIntegerField()),
                ('modified_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='file_replica.replicaentry')),
            ],
            options={
                'ordering': ['-number'],
            },
        ),
        migrations.CreateModel(
            name='ReplicaExtraction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(default='pending_review', max_length=24)),
                ('sections', models.JSONField(default=list)),
                ('suggestions', models.JSONField(default=list)),
                ('warnings', models.JSONField(default=list)),
                ('error', models.TextField(blank=True)),
                ('review_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extractions', to='file_replica.replicaentry')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='extractions', to='file_replica.replicaversion')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='replicaentry',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='file_replica.replicaversion'),
        ),
        migrations.AddConstraint(
            model_name='replicascope',
            constraint=models.UniqueConstraint(fields=('source', 'path_key'), name='replica_scope_path_unique'),
        ),
        migrations.AddConstraint(
            model_name='replicaversion',
            constraint=models.UniqueConstraint(fields=('entry', 'number'), name='replica_version_number_unique'),
        ),
        migrations.AddIndex(
            model_name='replicaentry',
            index=models.Index(fields=['source', 'scope'], name='file_replic_source__a391c3_idx'),
        ),
        migrations.AddIndex(
            model_name='replicaentry',
            index=models.Index(fields=['source', 'status'], name='file_replic_source__46e5c1_idx'),
        ),
        migrations.AddConstraint(
            model_name='replicaentry',
            constraint=models.UniqueConstraint(fields=('source', 'path_key'), name='replica_entry_path_unique'),
        ),
    ]
