# Generated by Django 5.0 on 2026-01-27 05:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MLDetectionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('model_type', models.CharField(choices=[('isolation_forest', 'Isolation Forest'), ('autoencoder', 'Autoencoder'), ('lstm', 'LSTM Network'), ('random_forest', 'Random Forest'), ('gradient_boost', 'Gradient Boosting'), ('svm', 'Support Vector Machine')], max_length=50)),
                ('version', models.CharField(max_length=50)),
                ('model_file', models.FileField(blank=True, null=True, upload_to='ml_models/')),
                ('model_params', models.JSONField(default=dict)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('precision', models.FloatField(blank=True, null=True)),
                ('recall', models.FloatField(blank=True, null=True)),
                ('f1_score', models.FloatField(blank=True, null=True)),
                ('training_samples', models.IntegerField(default=0)),
                ('training_date', models.DateTimeField(blank=True, null=True)),
                ('feature_importance', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ml_detection_model',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DetectionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('detection_type', models.CharField(choices=[('anomaly', 'Anomaly Detection'), ('threshold', 'Threshold Alert'), ('pattern', 'Pattern Recognition'), ('prediction', 'Predictive Alert'), ('security', 'Security Threat'), ('performance', 'Performance Degradation')], max_length=50)),
                ('description', models.TextField()),
                ('ml_config', models.JSONField(default=dict, help_text='ML model parameters')),
                ('threshold_config', models.JSONField(default=dict, help_text='Threshold settings')),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('info', 'Info')], default='medium', max_length=20)),
                ('auto_notify', models.BooleanField(default=True)),
                ('notification_channels', models.JSONField(default=list, help_text="['email', 'dashboard', 'webhook']")),
                ('is_active', models.BooleanField(default=True)),
                ('is_ml_enabled', models.BooleanField(default=True)),
                ('cooldown_period_seconds', models.IntegerField(default=300, help_text='Time between alerts')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ml_detection_config',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DetectionMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_detections', models.IntegerField(default=0)),
                ('true_positives', models.IntegerField(default=0)),
                ('false_positives', models.IntegerField(default=0)),
                ('true_negatives', models.IntegerField(default=0)),
                ('false_negatives', models.IntegerField(default=0)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('precision', models.FloatField(blank=True, null=True)),
                ('recall', models.FloatField(blank=True, null=True)),
                ('f1_score', models.FloatField(blank=True, null=True)),
                ('avg_detection_time_ms', models.FloatField(blank=True, null=True)),
                ('total_processing_time_ms', models.FloatField(blank=True, null=True)),
                ('detection_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ml_detection.detectionconfig')),
            ],
            options={
                'db_table': 'ml_detection_metrics',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='RealTimeAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('anomaly_detected', 'Anomaly Detected'), ('threshold_exceeded', 'Threshold Exceeded'), ('security_threat', 'Security Threat'), ('performance_issue', 'Performance Issue'), ('pattern_match', 'Pattern Match'), ('prediction_warning', 'Prediction Warning')], max_length=50)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('info', 'Info')], max_length=20)),
                ('confidence_score', models.FloatField(help_text='ML confidence 0-1')),
                ('detected_data', models.JSONField(default=dict, help_text='Raw data that triggered alert')),
                ('context', models.JSONField(default=dict, help_text='Additional context')),
                ('affected_resources', models.JSONField(default=list, help_text='Resources affected')),
                ('status', models.CharField(choices=[('new', 'New'), ('acknowledged', 'Acknowledged'), ('investigating', 'Investigating'), ('resolved', 'Resolved'), ('false_positive', 'False Positive')], default='new', max_length=20)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('detected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ml_acknowledged_alerts', to=settings.AUTH_USER_MODEL)),
                ('detection_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ml_detection.detectionconfig')),
                ('ml_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ml_detection.mldetectionmodel')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ml_resolved_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ml_realtime_alert',
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='AnomalyDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('feature_name', models.CharField(max_length=200)),
                ('observed_value', models.FloatField()),
                ('expected_value', models.FloatField()),
                ('deviation', models.FloatField()),
                ('anomaly_score', models.FloatField(help_text='ML anomaly score')),
                ('threshold', models.FloatField()),
                ('is_anomaly', models.BooleanField()),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('detection_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ml_detection.mldetectionmodel')),
                ('related_alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ml_detection.realtimealert')),
            ],
            options={
                'db_table': 'ml_anomaly_detection',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='RealTimeDataStream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stream_type', models.CharField(choices=[('user_activity', 'User Activity'), ('system_metrics', 'System Metrics'), ('api_requests', 'API Requests'), ('security_events', 'Security Events'), ('performance', 'Performance Data')], max_length=50)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('data', models.JSONField(help_text='Streaming data point')),
                ('features', models.JSONField(default=dict, help_text='Extracted features for ML')),
                ('analyzed', models.BooleanField(default=False)),
                ('anomaly_detected', models.BooleanField(default=False)),
                ('ml_score', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ml_realtime_data_stream',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['stream_type', '-timestamp'], name='ml_realtime_stream__af9831_idx'), models.Index(fields=['analyzed', 'anomaly_detected'], name='ml_realtime_analyze_62ab0b_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='realtimealert',
            index=models.Index(fields=['-detected_at', 'severity'], name='ml_realtime_detecte_df872f_idx'),
        ),
        migrations.AddIndex(
            model_name='realtimealert',
            index=models.Index(fields=['status', '-created_at'], name='ml_realtime_status_abf7fc_idx'),
        ),
        migrations.AddIndex(
            model_name='anomalydetection',
            index=models.Index(fields=['-timestamp', 'is_anomaly'], name='ml_anomaly__timesta_e4958a_idx'),
        ),
        migrations.AddIndex(
            model_name='anomalydetection',
            index=models.Index(fields=['feature_name', '-timestamp'], name='ml_anomaly__feature_47b563_idx'),
        ),
    ]
